import { CarrierCode, MarketplaceFulfillmentStatus, PriceCurrency, ShipmentStatus, ShippingError, type Shipment } from "@noctella/shared";
import { BadRequestError, NotFoundError } from "../errors";

export type ShipmentCoreContext = { uow: { run: <T>(fn: (ctx: any) => T) => T | Promise<T> }; orders: { getOrder: (id:string)=>any; listOrderItems:(orderId:string)=>any[]; getMarketplaceOrder:(orderId:string)=>any }; clock:{ now:()=>string }; ids:{ newId:()=>string }; fulfillment:{ enqueueSubmitShipment:(shipment:any)=>void|Promise<void> } };
const terminal = [ShipmentStatus.Cancelled, ShipmentStatus.Returned];
const allowed: Record<string, string[]> = { [ShipmentStatus.Draft]: [ShipmentStatus.Ready, ShipmentStatus.Cancelled], [ShipmentStatus.Ready]: [ShipmentStatus.LabelPending, ShipmentStatus.LabelCreated, ShipmentStatus.InTransit, ShipmentStatus.Cancelled], [ShipmentStatus.LabelPending]: [ShipmentStatus.LabelCreated, ShipmentStatus.Cancelled], [ShipmentStatus.LabelCreated]: [ShipmentStatus.InTransit, ShipmentStatus.Cancelled], [ShipmentStatus.InTransit]: [ShipmentStatus.Delivered, ShipmentStatus.DeliveryFailed, ShipmentStatus.Returned], [ShipmentStatus.DeliveryFailed]: [ShipmentStatus.InTransit, ShipmentStatus.Returned], [ShipmentStatus.Delivered]: [ShipmentStatus.Returned] };
const clean = (v: unknown) => String(v instanceof Error ? v.message : v ?? "").replace(/Bearer\s+\S+|access_token\S*|refresh_token\S*/gi, "[redacted]").slice(0, 500);
function hydrate(row:any, items:any[] = []): Shipment { if (!row) throw new NotFoundError("Shipment not found"); return { id: row.id, orderId: row.orderId, marketplaceOrderId: row.marketplaceOrderId ?? undefined, channel: row.channel ?? undefined, carrierCode: row.carrierCode, customCarrierName: row.customCarrierName ?? undefined, trackingNumber: row.trackingNumber ?? undefined, trackingUrl: row.trackingUrl ?? undefined, status: row.status, shippingCost: Number(row.shippingCost ?? 0), currency: "EUR", shippedAt: row.shippedAt ?? undefined, deliveredAt: row.deliveredAt ?? undefined, cancelledAt: row.cancelledAt ?? undefined, returnedAt: row.returnedAt ?? undefined, externalFulfillmentId: row.externalFulfillmentId ?? undefined, marketplaceFulfillmentStatus: row.marketplaceFulfillmentStatus ?? undefined, lastError: row.lastError ?? undefined, createdAt: row.createdAt, updatedAt: row.updatedAt, items } as Shipment; }
function event(ctx: ShipmentCoreContext, repos:any, shipmentId:string, type:string, prev?:string|null, next?:string|null, payload?:unknown, error?:unknown) { repos.events.append({ id: ctx.ids.newId(), shipmentId, eventType: type, previousStatus: prev, newStatus: next, payloadSnapshot: JSON.stringify(payload ?? {}), errorCode: error ? ShippingError.Unknown : undefined, errorMessage: error ? clean(error) : undefined, createdAt: ctx.clock.now() }); }
function detail(repos:any, id:string) { const row = repos.shipments.getById(id); return hydrate(row, repos.items.listByShipment(id)); }
export const getShipmentDetailUseCase = (ctx: ShipmentCoreContext, id: string) => ctx.uow.run(({repositories}:any)=>detail(repositories,id));
export const listShipmentsUseCase = (ctx: ShipmentCoreContext, q:any={}) => ctx.uow.run(({repositories}:any)=>repositories.shipments.list(q).filter((r:any)=> (!q.orderId||r.orderId===q.orderId)&&(!q.status||r.status===q.status)&&(!q.channel||r.channel===q.channel)&&(!q.carrier||r.carrierCode===q.carrier)&&(!q.trackingNumber||r.trackingNumber===q.trackingNumber)).map((r:any)=>hydrate(r, repositories.items.listByShipment(r.id))));
export const getShipmentEventsUseCase = (ctx: ShipmentCoreContext, id:string) => ctx.uow.run(({repositories}:any)=>repositories.events.listByShipment(id));
export const addShipmentEventUseCase = (ctx: ShipmentCoreContext, shipmentId:string, input:any) => ctx.uow.run(({repositories}:any)=>{ const s=repositories.shipments.getById(shipmentId); if(!s) throw new NotFoundError("Shipment not found"); event(ctx,repositories,shipmentId,input.eventType ?? "manual", input.previousStatus, input.newStatus, input.payload, input.error); return repositories.events.getLatestByShipment(shipmentId); });
export function createShipmentUseCase(ctx: ShipmentCoreContext, input:any) { return ctx.uow.run(({repositories}:any)=>{ const order=ctx.orders.getOrder(input.orderId); if(!order) throw new NotFoundError("Order not found"); if (input.currency && input.currency !== PriceCurrency.Eur) throw new BadRequestError("Shipping currency must be EUR"); if (input.carrierCode === CarrierCode.Other && !input.customCarrierName) throw new BadRequestError("Custom carrier name is required"); const existing = repositories.shipments.findByOrderId(input.orderId); if (existing && existing.status === ShipmentStatus.Draft) return hydrate(existing, repositories.items.listByShipment(existing.id)); const allItems = ctx.orders.listOrderItems(input.orderId); const wanted = input.items?.length ? input.items : allItems.map((i:any)=>({ orderItemId:i.id, quantity:i.quantity })); for (const wi of wanted) { const item = allItems.find((i:any)=>i.id===wi.orderItemId); if(!item) throw new BadRequestError("Shipment item must belong to order"); if(wi.quantity<1 || wi.quantity>item.quantity) throw new BadRequestError("Shipment quantity exceeds order item quantity"); } const mo=ctx.orders.getMarketplaceOrder(input.orderId); const now=ctx.clock.now(); const id=ctx.ids.newId(); repositories.shipments.create({ id, orderId:input.orderId, marketplaceOrderId: input.marketplaceOrderId ?? mo?.id, channel: input.channel ?? mo?.channel, carrierCode: input.carrierCode, customCarrierName: input.customCarrierName, trackingNumber: input.trackingNumber, trackingUrl: input.trackingUrl, status: ShipmentStatus.Draft, shippingCost: input.shippingCost ?? 0, currency:"EUR", marketplaceFulfillmentStatus: mo ? MarketplaceFulfillmentStatus.Pending : undefined, customsSnapshot: JSON.stringify(input.customs ?? {}), createdAt: now, updatedAt: now }); for (const wi of wanted) repositories.items.create({ id:ctx.ids.newId(), shipmentId:id, orderItemId:wi.orderItemId, quantity:wi.quantity, createdAt:now }); event(ctx,repositories,id,"created",null,ShipmentStatus.Draft,input); return detail(repositories,id); }); }
export function updateShipmentUseCase(ctx: ShipmentCoreContext, id:string, input:any) { return ctx.uow.run(({repositories}:any)=>{ repositories.shipments.getById(id); repositories.shipments.update(id,{ customCarrierName:input.customCarrierName, trackingUrl:input.trackingUrl, shippingCost:input.shippingCost, updatedAt:ctx.clock.now() }); event(ctx,repositories,id,"updated",undefined,undefined,input); return detail(repositories,id); }); }
export function updateShipmentTrackingUseCase(ctx: ShipmentCoreContext, id:string, input:any) { return ctx.uow.run(({repositories}:any)=>{ const s=detail(repositories,id); repositories.shipments.updateTracking(id,{ trackingNumber:input.trackingNumber, trackingUrl:input.trackingUrl, carrierCode:input.carrierCode ?? s.carrierCode, customCarrierName:input.customCarrierName, updatedAt:ctx.clock.now() }); event(ctx,repositories,id,"tracking_assigned",s.status,s.status,input); return detail(repositories,id); }); }
export function updateShipmentStatusUseCase(ctx: ShipmentCoreContext, id:string, status:ShipmentStatus, payload:any={}) { return ctx.uow.run(({repositories, afterCommit}:any)=>{ const row=repositories.shipments.getById(id); if(!row) throw new NotFoundError("Shipment not found"); if(row.status===status) return detail(repositories,id); if(terminal.includes(row.status as ShipmentStatus)) throw new BadRequestError("Shipment is terminal"); if(!allowed[row.status]?.includes(status)) throw new BadRequestError(`Invalid shipment status transition ${row.status} -> ${status}`); if(status===ShipmentStatus.InTransit && row.carrierCode!==CarrierCode.LocalPickup && !row.trackingNumber) throw new BadRequestError("Tracking number is required before shipping"); const now=ctx.clock.now(); const patch:any={ status, updatedAt:now }; if(status===ShipmentStatus.InTransit) patch.shippedAt=payload.shippedAt ?? now; if(status===ShipmentStatus.Delivered) patch.deliveredAt=payload.deliveredAt ?? now; if(status===ShipmentStatus.Cancelled) patch.cancelledAt=payload.cancelledAt ?? now; if(status===ShipmentStatus.Returned) patch.returnedAt=payload.returnedAt ?? now; repositories.shipments.updateStatus(id, patch); event(ctx,repositories,id,"status_changed",row.status,status,payload); const s=detail(repositories,id); if(status===ShipmentStatus.InTransit && s.channel && !s.externalFulfillmentId) afterCommit(()=>ctx.fulfillment.enqueueSubmitShipment(s)); return s; }); }
export const markShipmentDeliveredUseCase = (ctx:ShipmentCoreContext,id:string,p?:any)=>updateShipmentStatusUseCase(ctx,id,ShipmentStatus.Delivered,p);
export const markShipmentFailedUseCase = (ctx:ShipmentCoreContext,id:string,p?:any)=>updateShipmentStatusUseCase(ctx,id,ShipmentStatus.DeliveryFailed,p);
export const cancelShipmentUseCase = (ctx:ShipmentCoreContext,id:string,p?:any)=>updateShipmentStatusUseCase(ctx,id,ShipmentStatus.Cancelled,p);
export const markShipmentReturnedUseCase = (ctx:ShipmentCoreContext,id:string,p?:any)=>updateShipmentStatusUseCase(ctx,id,ShipmentStatus.Returned,p);
