import type { SaleChannel, SaleSource, SaleStatus } from "../../repositories/sales/types";

export interface SalesCustomerInput { readonly customerId?: string | null; readonly email?: string | null; readonly billingAddress?: string | null; readonly shippingAddress?: string | null }
export interface SalesMarketplaceInput { readonly channel?: SaleChannel | null; readonly marketplaceOrderId?: string | null; readonly externalOrderId?: string | null; readonly externalOrderNumber?: string | null; readonly externalTransactionId?: string | null; readonly connectionId?: string | null }
export interface SalesShippingInput { readonly status?: string | null; readonly shippingStatus?: string | null; readonly trackingNumber?: string | null }
export interface CreateSaleLineInput { readonly title: string; readonly quantity: number; readonly unitPrice: number; readonly productId?: string | null; readonly sku?: string | null; readonly slug?: string | null; readonly productType?: string | null; readonly imageUrl?: string | null }
export interface CreateSaleInput { readonly reference: string; readonly source: SaleSource; readonly status: SaleStatus; readonly paymentStatus: string; readonly paymentProvider?: string | null; readonly paymentReference?: string | null; readonly orderDraftId?: string | null; readonly idempotencyKey?: string | null; readonly customer?: SalesCustomerInput; readonly marketplace?: SalesMarketplaceInput; readonly shipping?: SalesShippingInput; readonly notes?: string | null; readonly shippingAmount: number; readonly taxAmount: number; readonly currency: "EUR"; readonly lines: readonly CreateSaleLineInput[] }
export interface UpdateSaleInput { readonly saleId: string; readonly expectedVersion: string; readonly reference?: string; readonly status?: SaleStatus; readonly customer?: SalesCustomerInput; readonly notes?: string | null; readonly currency: "EUR" }
export interface CancelSaleInput { readonly saleId: string; readonly expectedVersion: string }
export interface GetSaleInput { readonly saleId: string }
export interface ListSalesInput { readonly status?: SaleStatus; readonly source?: SaleSource; readonly channel?: SaleChannel; readonly productId?: string | null; readonly customerId?: string | null; readonly reference?: string; readonly externalOrderId?: string; readonly paymentStatus?: string; readonly dateFrom?: string; readonly dateTo?: string; readonly limit?: number; readonly offset?: number }
export interface SaleLineOutput { readonly id: string; readonly saleId: string; readonly productId: string | null; readonly sku: string | null; readonly title: string; readonly slug: string | null; readonly productType: string | null; readonly imageUrl: string | null; readonly quantity: number; readonly unitPrice: number; readonly totalPrice: number; readonly currency: "EUR"; readonly stockMovementId: string | null; readonly createdAt: string; readonly updatedAt: string }
export interface SaleOutput { readonly id: string; readonly reference: string; readonly orderDraftId: string | null; readonly source: SaleSource; readonly status: SaleStatus; readonly paymentStatus: string; readonly customer: Readonly<{ customerId: string | null; email: string | null; billingAddress: string | null; shippingAddress: string | null }>; readonly payment: Readonly<{ status: string; provider: string | null; reference: string | null }>; readonly fulfillment: Readonly<{ status: string | null; shippingStatus: string | null; trackingNumber: string | null }>; readonly marketplace: Readonly<{ channel: SaleChannel | null; marketplaceOrderId: string | null; externalOrderId: string | null; externalOrderNumber: string | null; externalTransactionId: string | null; connectionId: string | null }>; readonly financials: Readonly<{ subtotalAmount: number; shippingAmount: number; taxAmount: number; totalAmount: number; grossRevenue: number | null; shippingCharged: number | null; shippingCost: number | null; marketplaceFee: number | null; promotedFee: number | null; paymentFee: number | null; itemCost: number | null; netRevenue: number | null; profit: number | null; currency: "EUR" }>; readonly receipt: Readonly<{ invoiceId: string | null; invoiceNumber: string | null }>; readonly notes: string | null; readonly idempotencyKey: string | null; readonly createdAt: string; readonly updatedAt: string; readonly completedAt: string | null; readonly lines: readonly SaleLineOutput[] }
export interface SaleListOutput { readonly rows: readonly SaleOutput[]; readonly total: number; readonly limit: number; readonly offset: number }
