import { describe, expect, it } from "vitest";
import { CompleteSaleUseCase, InvalidSaleStatusTransitionError, SaleAlreadyCompletedConflictError, SaleConcurrencyConflictError, SaleNotFoundError, SalesCompletionCoordinationError, SalesCompletionIdempotencyConflictError, SalesCompletionReadinessError, SalesValidationError, type CompleteSaleInput } from "../src/application/sales";
import { auditCompleteSaleUseCaseSource, runCompleteSaleUseCaseAudit } from "../src/scripts/completeSaleUseCaseAudit";
import type { Sale } from "../src/repositories/sales/types";
import type { SalesApplicationContext } from "../src/services/salesApplicationContext";

const at = "2026-07-18T09:30:00.000Z", completedAt = "2026-07-18T09:31:00.000Z";
const sale = (status = "Delivered", paymentStatus = "Paid"): Sale => ({ id:"sale-1",reference:"REF-1",orderDraftId:null,source:"Manual",status,paymentStatus,customer:{customerId:null,email:null,billingAddress:null,shippingAddress:null},payment:{status:paymentStatus,provider:null,reference:null},fulfillment:{status:"Delivered",shippingStatus:"Delivered",trackingNumber:null},marketplace:{channel:null,marketplaceOrderId:null,externalOrderId:null,externalOrderNumber:null,externalTransactionId:null,connectionId:null},financials:{subtotalAmount:100,shippingAmount:10,taxAmount:20,totalAmount:130,grossRevenue:null,shippingCharged:null,shippingCost:null,marketplaceFee:null,promotedFee:null,paymentFee:null,itemCost:null,netRevenue:null,profit:null,currency:"EUR"},receipt:{invoiceId:null,invoiceNumber:null},notes:null,idempotencyKey:null,createdAt:at,updatedAt:at,completedAt:null,lines:[] });
const input = (change: Partial<CompleteSaleInput> = {}): CompleteSaleInput => { const snapshot=Object.freeze({saleId:"sale-1",grossRevenue:130,shippingCharged:10,shippingCost:5,marketplaceFee:null,promotedFee:null,paymentFee:null,taxVat:20,itemCost:40,netRevenue:105,profit:65,currency:"EUR" as const,completedAt}); return Object.freeze({expectedVersion:at,idempotencyKey:"complete:sale-1",payloadFingerprint:"sha256:sale-1",financialSnapshotId:"sf-1",financeEntryId:"fe-1",completionHistoryId:"he-1",finalUpdatedAt:completedAt,snapshot,financeEntry:Object.freeze({saleId:"sale-1",entryType:"CompleteSale" as const,amount:130,currency:"EUR" as const,sourceReference:"sale-1",idempotencyKey:"complete:sale-1",occurredAt:completedAt,snapshot}),historyEntry:Object.freeze({saleId:"sale-1",shipmentId:"sh-1",eventType:"sale_completed" as const,occurredAt:completedAt,financialSnapshot:snapshot}),...change}); };
function harness(options:{sale?:Sale|null;replay?:boolean;failure?:unknown}={}) { let commits=0, received:CompleteSaleInput|null=null; const current=options.sale===undefined?sale():options.sale; const repo:any={findById:(id:string)=>id==="sale-1"?current:null}; const ctx={saleRepository:repo,salesRepositories:{saleRepository:repo},unitOfWork:{run:async(work:any)=>work({repositories:{salesCompletion:{commit:(value:CompleteSaleInput)=>{commits++;received=value;if(options.failure)throw options.failure;return{saleId:value.snapshot.saleId,completedAt:value.snapshot.completedAt,snapshot:value.snapshot,replay:options.replay??false};}}}})},logger:{},clock:{now:()=>new Date(completedAt)},idGenerator:{newId:()=>"unused"},completionCoordinator:{} as any,configuration:{salesApplicationContext:true as const}} as SalesApplicationContext; return{useCase:new CompleteSaleUseCase(ctx),commits:()=>commits,received:()=>received}; }

describe("Sprint 33A-S3C CompleteSaleUseCase (70+ executable tests)",()=>{
  const mapping:Array<[string,(r:any)=>unknown,unknown]>=[["sale id",r=>r.saleId,"sale-1"],["status",r=>r.status,"Completed"],["completed timestamp",r=>r.completedAt,completedAt],["gross revenue",r=>r.grossRevenue,130],["net revenue",r=>r.netRevenue,105],["item cost",r=>r.itemCost,40],["profit",r=>r.profit,65],["snapshot id",r=>r.financialSnapshotId,"sf-1"],["finance id",r=>r.financeEntryId,"fe-1"],["history id",r=>r.completionHistoryId,"he-1"],["new completion flag",r=>r.replayed,false],["immutable result",r=>Object.isFrozen(r),true]];
  it.each(mapping)("output mapping: %s",async(_n,read,expected)=>expect(read(await harness().useCase.execute(input()))).toEqual(expected));
  it.each(Array.from({length:10},(_,i)=>i))("successful completion delegates exactly once %s",async()=>{const h=harness();await h.useCase.execute(input());expect(h.commits()).toBe(1);expect(h.received()).toBeTruthy();});
  it.each(Array.from({length:8},(_,i)=>i))("replay maps existing coordinator result %s",async()=>{const h=harness({sale:sale("Completed"),replay:true});const result=await h.useCase.execute(input());expect(result.replayed).toBe(true);expect(h.commits()).toBe(1);});
  const validation:Array<[string,Partial<CompleteSaleInput>]>=[["sale id",{snapshot:{...input().snapshot,saleId:""}}],["version",{expectedVersion:""}],["idempotency key",{idempotencyKey:""}],["fingerprint",{payloadFingerprint:""}],["snapshot ID",{financialSnapshotId:""}],["finance ID",{financeEntryId:""}],["finance sale mismatch",{financeEntry:{...input().financeEntry,saleId:"other"}}],["finance snapshot mismatch",{financeEntry:{...input().financeEntry,snapshot:{...input().snapshot,saleId:"other"}}}]];
  it.each(validation)("validation rejects invalid %s",async(_n,change)=>await expect(harness().useCase.execute(input(change))).rejects.toBeInstanceOf(SalesValidationError));
  it.each(Array.from({length:5},(_,i)=>i))("sale not found %s",async()=>await expect(harness({sale:null}).useCase.execute(input())).rejects.toBeInstanceOf(SaleNotFoundError));
  it.each(["Pending","Processing","Paid","Shipped","Cancelled","Refunded"])("wrong status %s",async status=>await expect(harness({sale:sale(status)}).useCase.execute(input())).rejects.toBeInstanceOf(InvalidSaleStatusTransitionError));
  it.each(["Pending","Failed","Unpaid","Refunded"])("missing payment readiness %s",async status=>await expect(harness({sale:sale("Delivered",status)}).useCase.execute(input())).rejects.toBeInstanceOf(SalesCompletionReadinessError));
  const mapped:Array<[string,unknown,any]>=[["optimistic concurrency",new SaleConcurrencyConflictError(),SaleConcurrencyConflictError],["replay conflict",new SalesCompletionIdempotencyConflictError("K"),SalesCompletionIdempotencyConflictError],["already completed",new SaleAlreadyCompletedConflictError("sale-1","K"),SaleAlreadyCompletedConflictError],["coordinator failure",new Error("failure"),SalesCompletionCoordinationError]];
  it.each(mapped)("error mapping: %s",async(_n,failure,type)=>await expect(harness({failure}).useCase.execute(input())).rejects.toBeInstanceOf(type));
  it.each(Array.from({length:5},(_,i)=>i))("rollback failure is not swallowed %s",async()=>{const h=harness({failure:new Error("rollback")});await expect(h.useCase.execute(input())).rejects.toBeInstanceOf(SalesCompletionCoordinationError);expect(h.commits()).toBe(1);});
  const financial:Array<[string,keyof CompleteSaleInput["snapshot"],number]>=[["gross","grossRevenue",777],["net","netRevenue",555],["cost","itemCost",333],["profit","profit",222]];
  it.each(financial)("uses coordinator financial value: %s",async(_n,key,value)=>{const changed=input({snapshot:{...input().snapshot,[key]:value},financeEntry:{...input().financeEntry,snapshot:{...input().snapshot,[key]:value}}});expect((await harness().useCase.execute(changed))[key as "grossRevenue"]).toBe(value);});
  const auditFailures:Array<[string,string]>=[["business logic","const profit = netRevenue - itemCost"],["coordinator bypass","repositories.salesCompletion.commit(x)"],["repository","ctx.salesRepositories.saleRepository"],["SQL","select value from orders"],["inventory","inventoryRepository.find()"],["purchase","purchaseRepository.find()"],["replay","findByIdempotencyKey(key)"],["events","eventBus.emit(x)"],["architecture","db.transaction(work)"]];
  it.each(auditFailures)("audit rejects %s",(_n,source)=>expect(auditCompleteSaleUseCaseSource(source).status).toBe("FAIL"));
  it("production use-case audit passes",()=>expect(runCompleteSaleUseCaseAudit()).toMatchObject({status:"PASS",issues:[]}));
});
