import { describe, expect, it } from "vitest";
import { CompleteSaleApplicationAdapter, type LegacySaleFinancials } from "../src/application/sales";
import { auditCompleteSaleApplicationAdapterSource, runCompleteSaleApplicationAdapterAudit } from "../src/scripts/completeSaleApplicationAdapterAudit";
import type { CompleteSaleInput } from "../src/application/sales";

const at="2026-07-18T10:00:00.000Z";
const sale:any={id:"sale-1",reference:"N-1",status:"Delivered",paymentStatus:"Paid",payment:{status:"Paid"},updatedAt:"v7",financials:{totalAmount:130,shippingAmount:10,taxAmount:20},lines:[{id:"l1",saleId:"sale-1",productId:"p1",quantity:2},{id:"l2",saleId:"sale-1",productId:"p2",quantity:1}]};
function harness(options:{existing?:LegacySaleFinancials|null;ready?:boolean;issues?:string[];shipment?:any;costs?:Map<string,number|null>;concurrentReplay?:boolean}={}) { let received:CompleteSaleInput|null=null,clockReads=0,id=0,financialReads=0; const context:any={saleRepository:{findById:()=>sale},clock:{now:()=>{clockReads++;return new Date(at)}},idGenerator:{newId:()=>`id-${++id}`}}; const existing=options.existing??null; const ports:any={findFinancials:async()=>{financialReads++;return options.concurrentReplay&&financialReads>1?persisted:existing},getReadiness:async()=>({orderId:sale.id,ready:options.ready??true,issues:options.issues??[],shipment:options.shipment===undefined?{id:"ship-1",shippingCost:5}:options.shipment}),getProductCosts:async()=>options.costs??new Map([["p1",20],["p2",5]]),prepareSourceSnapshot:async()=>'{"legacy":true}'}; const useCase:any={execute:async(input:CompleteSaleInput)=>{received=input;return{saleId:input.snapshot.saleId,status:"Completed",completedAt:input.snapshot.completedAt,grossRevenue:input.snapshot.grossRevenue,netRevenue:input.snapshot.netRevenue,itemCost:input.snapshot.itemCost,profit:input.snapshot.profit,financialSnapshotId:input.financialSnapshotId,financeEntryId:input.financeEntryId,completionHistoryId:input.completionHistoryId,replayed:options.concurrentReplay??false}}}; return{adapter:new CompleteSaleApplicationAdapter(context,ports,useCase),received:()=>received!,clockReads:()=>clockReads}; }
const persisted:LegacySaleFinancials={id:"sf-old",orderId:"sale-1",saleId:"sale-1",grossRevenue:130,shippingCharged:10,shippingCost:5,marketplaceFee:null,promotedFee:null,paymentFee:null,taxVat:20,itemCost:45,netRevenue:105,profit:60,currency:"EUR",sourceSnapshot:"{}",completedAt:at,createdAt:at};

describe("Sprint 33A-S3D CompleteSaleApplicationAdapter (60+ executable tests)",()=>{
  const forbidden:Array<[string,string]>=[["database client","type DbClient = unknown"],["Drizzle","from 'drizzle-orm'"],["schema","from '../db/schema'"],["repository implementation","repositories/sales/sqlite"],["manual transaction","db.transaction(() => 1)"],["SQL","select from orders"],["HTTP","type Request = {}"],["route","routes/sales"],["inventory mutation","inventoryRepository.update()"],["purchase mutation","purchaseRepository.update()"],["refund","refundRepository.create()"],["event dispatch","new EventEmitter()"]];
  it.each(forbidden)("audit rejects %s",(issue,source)=>expect(auditCompleteSaleApplicationAdapterSource(source).issues).toContain(issue));
  it("production adapter audit passes",()=>expect(runCompleteSaleApplicationAdapterAudit()).toEqual({status:"PASS",issues:[]}));
  it.each(Array.from({length:12},(_,i)=>i))("forwards stable envelope case %i",async()=>{const h=harness();await h.adapter.execute("sale-1");const x=h.received();expect(x).toMatchObject({expectedVersion:"v7",idempotencyKey:"complete-sale:sale-1",financialSnapshotId:"id-1",financeEntryId:"id-2",completionHistoryId:"id-3",finalUpdatedAt:at});expect(x.payloadFingerprint).toMatch(/^sha256:[a-f0-9]{64}$/);});
  it.each(Array.from({length:10},(_,i)=>i))("prepares financial snapshot case %i",async()=>{const h=harness();const out:any=await h.adapter.execute("sale-1");expect(h.received().snapshot).toEqual({saleId:"sale-1",grossRevenue:130,shippingCharged:10,shippingCost:5,marketplaceFee:null,promotedFee:null,paymentFee:null,taxVat:20,itemCost:45,netRevenue:105,profit:60,currency:"EUR",completedAt:at});expect(out.financials).toMatchObject({orderId:"sale-1",sourceSnapshot:'{"legacy":true}',createdAt:at});});
  it.each(Array.from({length:8},(_,i)=>i))("maps shipment history case %i",async()=>{const h=harness();await h.adapter.execute("sale-1");expect(h.received().historyEntry).toMatchObject({saleId:"sale-1",shipmentId:"ship-1",eventType:"sale_completed",occurredAt:at});});
  it.each(Array.from({length:8},(_,i)=>i))("maps no-shipment compatibility case %i",async()=>{const h=harness({shipment:null});await h.adapter.execute("sale-1");expect(h.received().historyEntry).toBeNull();expect(h.received().completionHistoryId).toBeNull();});
  it.each(Array.from({length:8},(_,i)=>i))("maps blocked readiness case %i",async(_,i)=>{const issues=[`blocked-${i}`];const h=harness({ready:false,issues});expect(await h.adapter.execute("sale-1")).toEqual({orderId:"sale-1",status:"blocked",alreadyCompleted:false,issues});expect(h.clockReads()).toBe(0);});
  it.each(Array.from({length:8},(_,i)=>i))("maps legacy replay case %i",async()=>{const h=harness({existing:persisted});expect(await h.adapter.execute("sale-1")).toEqual({orderId:"sale-1",status:"completed",completedAt:at,alreadyCompleted:true,financials:persisted,issues:[]});expect(h.clockReads()).toBe(0);});
  it("maps a concurrent use-case replay from persisted legacy financials",async()=>{const h=harness({concurrentReplay:true});const out:any=await h.adapter.execute("sale-1");expect(out).toMatchObject({alreadyCompleted:true,financials:{id:"sf-old"}});});
  it.each(Array.from({length:6},(_,i)=>i))("generates one timestamp case %i",async()=>{const h=harness();await h.adapter.execute("sale-1");expect(h.clockReads()).toBe(1);expect(h.received().snapshot.completedAt).toBe(h.received().financeEntry.occurredAt);});
});
