import { describe, expect, it, vi } from "vitest";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import Database from "better-sqlite3";
import { getDatabaseConfig, redactSecrets } from "../src/db/config";
import { checkBackupReadiness, checkSqliteIntegrity, compareSchemaModels, createMigrationPlan, createMigrationPreview, executeMigrationBatch, requiredSprint24Tables, rollbackMigrationBatch, runSchemaParity, validateCutoverState, validateMigrationPlan, validatePostgresMigrationSql, verifyMigrationBatch } from "../src/services/databaseMigrationFoundation";
import { migrationTransformations, postgresTypeMappings } from "../src/db/schema.postgres";
import { createDatabaseRuntime } from "../src/db/runtime";
import { requireDatabaseAdmin } from "../src/routes/databaseAdmin";

describe("Sprint 24 database migration foundation", () => {
  it("keeps sqlite as default driver",()=>expect(getDatabaseConfig({}).driver).toBe("sqlite"));
  it("fails safely when postgres has no config",()=>expect(()=>getDatabaseConfig({DATABASE_DRIVER:"postgres"})).toThrow(/requires/));
  it("blocks SupabasePrimary without verification",()=>expect(()=>getDatabaseConfig({DATABASE_CUTOVER_STATE:"SupabasePrimary"})).toThrow(/blocked/));
  it("rejects dual-write mode",()=>expect(()=>getDatabaseConfig({DATABASE_DUAL_WRITE:"true"})).toThrow(/Dual-write/));
  it("recognizes rollback mode",()=>expect(validateCutoverState("RollbackMode")).toBe(true));
  it("redacts secrets",()=>{ vi.stubEnv("DATABASE_URL","postgres://u:p@h/db"); expect(redactSecrets("postgres://u:p@h/db failed")).not.toContain("u:p"); vi.unstubAllEnvs(); });
  it("represents all required tables",()=>expect(runSchemaParity().tables.length).toBe(requiredSprint24Tables.length));
  it("passes static schema parity",()=>expect(runSchemaParity().status).toBe("PASS"));
  it("reports column parity summary",()=>expect(runSchemaParity().tables.every(t=>t.columns>0)).toBe(true));
  it("reports expected warning differences",()=>expect(runSchemaParity().warnings.length).toBeGreaterThan(0));
  it("detects deterministic parity",()=>expect(runSchemaParity().checksum).toBe(runSchemaParity().checksum));
  it("has idempotency tables",()=>expect(requiredSprint24Tables).toContain("background_jobs"));
  it("maps timestamps",()=>expect(postgresTypeMappings.timestamp).toBe("timestamptz"));
  it("maps jsonb",()=>expect(postgresTypeMappings.json).toBe("jsonb"));
  it("maps decimal money safely",()=>expect(postgresTypeMappings.money).toContain("numeric"));
  it("defines boolean transformation",()=>expect(migrationTransformations.join(" ")).toContain("boolean"));
  it("defines invoice uniqueness review",()=>expect(migrationTransformations.join(" ")).toContain("invoice"));
  it("creates row counts in preview",()=>expect(createMigrationPreview(":memory:").sourceRowCounts).toBeDefined());
  it("creates table dependency order",()=>expect(createMigrationPreview(":memory:").tableOrder[0]).toBe("categories"));
  it("flags missing source tables as preview warnings for memory db",()=>expect(createMigrationPreview(":memory:").warnings.length).toBeGreaterThan(0));
  it("includes deterministic table checksums",()=>{ const a=createMigrationPreview(":memory:"), b=createMigrationPreview(":memory:"); expect(a.tableChecksums).toEqual(b.tableChecksums); });
  it("keeps manifest dry-run",()=>expect(createMigrationPreview(":memory:").dryRun).toBe(true));
  it("does not target-write in preview",()=>expect(createMigrationPreview(":memory:").targetDriver).toBe("supabase-postgres"));
  it("creates execution plan",()=>expect(createMigrationPlan().batches.length).toBe(requiredSprint24Tables.length));
  it("validates execution disabled by default",()=>expect(validateMigrationPlan().executionEnabled).toBe(false));
  it("requires feature flag for batch execution",()=>expect(()=>executeMigrationBatch()).toThrow(/disabled/));
  it("prepares checkpoint verification metadata",()=>expect(verifyMigrationBatch().dryRun).toBe(true));
  it("prepares rollback metadata",()=>expect(rollbackMigrationBatch().metadataPrepared).toBe(true));
  it("keeps backup prerequisites safe",()=>expect(checkBackupReadiness(":memory:").rollbackManifestPrerequisite).toBe("required"));
  it("does not expose secrets in parity",()=>expect(JSON.stringify(runSchemaParity())).not.toMatch(/SUPABASE|postgres:\/\//));

  it("detects deliberate missing column, unique, index and foreign key",()=>{ const sqlite={orders:{columns:["id","order_number"],unique:["order_number"],indexes:["id"],foreignKeys:["customer_id"]}}; const pg={orders:{columns:["id"],unique:[],indexes:[],foreignKeys:[]}}; const r=compareSchemaModels(sqlite,pg); expect(r.status).toBe("FAIL"); expect(r.blocking.map(b=>b.kind)).toEqual(expect.arrayContaining(["missing-column","missing-unique","missing-index","missing-foreign-key"])); });
  it("validates complete postgres migration SQL statically",()=>{ const r=validatePostgresMigrationSql(); expect(r.status).toBe("PASS"); expect(r.tableCount).toBe(requiredSprint24Tables.length); expect(r.indexCount).toBeGreaterThan(10); });
  it("has postgres runtime dependency in package manifest",()=>{ const pkg=JSON.parse(fs.readFileSync(path.join(__dirname,"../package.json"),"utf8")); expect(pkg.dependencies.pg).toBeTruthy(); });
  it("does not create postgres pool for sqlite runtime",async()=>{ const rt=createDatabaseRuntime({DATABASE_DRIVER:"sqlite",DATABASE_URL:":memory:"}); expect(rt.driver).toBe("sqlite"); await rt.shutdown(); });
  it("fails unsupported driver safely",()=>expect(()=>createDatabaseRuntime({DATABASE_DRIVER:"mysql"})).toThrow(/Unsupported/));
  it("fails postgres runtime safely without url",()=>expect(()=>createDatabaseRuntime({DATABASE_DRIVER:"postgres"})).toThrow(/requires/));
  it("previews populated sqlite counts and stable fingerprint",()=>{ const f=path.join(os.tmpdir(),`s24-${Date.now()}.sqlite`); const db=new Database(f); db.exec("CREATE TABLE categories(id TEXT PRIMARY KEY); INSERT INTO categories VALUES ('cat1'); CREATE TABLE products(id TEXT PRIMARY KEY, category_id TEXT); INSERT INTO products VALUES ('p1','missing');"); db.close(); const a=createMigrationPreview(f), b=createMigrationPreview(f); expect(a.sourceRowCounts.categories).toBe(1); expect(a.sourceRowCounts.products).toBe(1); expect(a.sourceDatabaseFingerprint).toBe(b.sourceDatabaseFingerprint); fs.unlinkSync(f); });
  it("passes integrity for a valid temporary sqlite database",()=>{ const f=path.join(os.tmpdir(),`s24-ok-${Date.now()}.sqlite`); const db=new Database(f); db.exec("CREATE TABLE t(id TEXT PRIMARY KEY)"); db.close(); expect(checkSqliteIntegrity(f).status).toBe("PASS"); fs.unlinkSync(f); });
  it("fails integrity for corrupt temporary file",()=>{ const f=path.join(os.tmpdir(),`s24-bad-${Date.now()}.sqlite`); fs.writeFileSync(f,"not a sqlite db"); expect(checkSqliteIntegrity(f).status).toBe("FAIL"); fs.unlinkSync(f); });
  it("reports missing integrity file as warning",()=>expect(checkSqliteIntegrity(path.join(os.tmpdir(),"missing-s24.sqlite")).status).toBe("WARN"));
  it("reports backup readiness for valid backup",()=>{ const f=path.join(os.tmpdir(),`s24-bak-${Date.now()}.sqlite`); const db=new Database(f); db.exec("CREATE TABLE t(id TEXT PRIMARY KEY)"); db.close(); fs.copyFileSync(f,`${f}.bak`); expect(checkBackupReadiness(f).sqliteBackupPresent).toBe(true); fs.unlinkSync(f); fs.unlinkSync(`${f}.bak`); });
  it("rejects unauthenticated admin database route",()=>{ let code=0; requireDatabaseAdmin({header:()=>undefined},{status:(c:number)=>{code=c; return {json:()=>undefined};}},()=>{code=200}); expect(code).toBe(403); });
  it("rejects unauthorized admin role",()=>{ let code=0; requireDatabaseAdmin({header:(h:string)=>h==="x-admin-role"?"staff":undefined},{status:(c:number)=>{code=c; return {json:()=>undefined};}},()=>{code=200}); expect(code).toBe(403); });
  it("accepts authorized admin role",()=>{ let code=0; requireDatabaseAdmin({header:(h:string)=>h==="x-admin-role"?"admin":undefined},{status:(c:number)=>{code=c; return {json:()=>undefined};}},()=>{code=200}); expect(code).toBe(200); });
});
