import { ProductStatus, ProductType } from "@noctella/shared";
import { describe, expect, it, beforeEach } from "vitest";
import { createCategory } from "../src/services/categories";
import { createProduct } from "../src/services/products";
import { createTestDb } from "./testDb";
import { acknowledge, authenticateErp, capabilities, checkpoint, constantTimeEqual, hashErpKey, health, identityCheck, isVersionSupported, listProductProjections, PRODUCT_FIELD_MAPPING, validateCommandEnvelope, versionInfo } from "../src/services/erpIntegration";
import { eq } from "drizzle-orm";
import { erpIntegrationAudit, erpIntegrationClients, products, stockMovements, orders, backgroundJobs } from "../src/db/schema";

const key = "test-erp-key";
describe("ERP integration foundation", () => {
  let db: ReturnType<typeof createTestDb>; let productId = "";
  beforeEach(async () => { db=createTestDb(); process.env.ERP_INTEGRATION_KEY=key; const cat=await createCategory(db,{ name:"Watches", displayOrder:0, isActive:true }); const p=await createProduct(db,{ sku:"ERP-SKU-1", title:"ERP Clock", type:ProductType.LotItem, status:ProductStatus.Approved, categoryId:cat.id, erpReferenceId:"erp-1", priceEur:10, stockQuantity:3, customsWarning:false, isFeatured:false, allowMakeOffer:false, allowCashOnDelivery:false, showInArchiveAfterSale:false }); productId=p.id; await db.update(products).set({ erpReferenceId:"erp-1" }).where(eq(products.id, productId)); });
  it("authenticates valid key and rejects invalid or missing without returning raw key", async () => { expect((await authenticateErp(db,key,"0.1.0","r1")).ok).toBe(true); expect((await authenticateErp(db,"bad","0.1.0","r2")).ok).toBe(false); expect((await authenticateErp(db,undefined,"0.1.0","r3")).ok).toBe(false); expect(constantTimeEqual(hashErpKey(key), hashErpKey(key))).toBe(true); const audit=await db.select().from(erpIntegrationAudit); expect(JSON.stringify(audit)).not.toContain(key); });
  it("rejects inactive persisted clients", async () => { await db.insert(erpIntegrationClients).values({ id:"c1", name:"ERP", keyHash:hashErpKey("persisted"), keyVersion:"v1", isActive:false }); expect((await authenticateErp(db,"persisted","0.1.0","r4")).ok).toBe(false); });
  it("returns version, health and capabilities without secrets", async () => { expect(versionInfo("0.1.0").compatible).toBe(true); expect(isVersionSupported("0.0.1")).toBe(false); expect(isVersionSupported("9.0.0")).toBe(false); expect((await health(db)).database).toBe("Healthy"); expect(capabilities().writesEnabled).toBe(true); expect(JSON.stringify(capabilities())).not.toContain(key); });
  it("supports read-only product projections, filters and no leakage", async () => { const list=await listProductProjections(db,{ search:"Clock", limit:10, updatedSince:"2000" }); expect(list.items[0].centralProductId).toBe(productId); expect(list.items[0].availableStock).toBe(3); expect(JSON.stringify(list)).not.toMatch(/token|buyer|customer/i); });
  it("checks identity without mutation", async () => { const before=(await db.select().from(products)).length; expect((await identityCheck(db,{ erpReferenceId:"erp-1" })).result).toBe("Match"); expect((await identityCheck(db,{ sku:"ERP-SKU-1" })).result).toBe("Match"); expect((await identityCheck(db,{ noctellaId:"legacy" })).result).toBe("CreateCandidate"); expect((await identityCheck(db,{ sku:" " })).result).toBe("Invalid"); expect((await db.select().from(products)).length).toBe(before); });
  it("contains required mapping including deferred/loss-risk fields", () => { const names=PRODUCT_FIELD_MAPPING.map(f=>f.erpField); for (const f of ["depth","diameter","provenance","productWorkflowStatus","availableQuantity","updatedAt"]) expect(names).toContain(f); expect(PRODUCT_FIELD_MAPPING.find(f=>f.erpField==="availableQuantity")?.owner).toBe("Derived"); expect(PRODUCT_FIELD_MAPPING.find(f=>f.erpField==="depth")?.dataLossRisk).not.toBe("None"); expect(names).not.toContain("imageDataUrl"); });
  it("generates and idempotently acknowledges checkpoints without business mutation", async () => { const before=(await db.select().from(products)).length; const cp=await checkpoint(db); expect(cp.checkpointToken).toBeTruthy(); const a1=await acknowledge(db,"env","req-ack",cp.checkpointToken,{ ok:true }); const a2=await acknowledge(db,"env","req-ack",cp.checkpointToken,{ ok:true }); expect(a2.id).toBe(a1.id); expect((await db.select().from(products)).length).toBe(before); });
  it("validates command envelopes and enables Sprint 18 commands without side effects", async () => { const before=[(await db.select().from(stockMovements)).length,(await db.select().from(orders)).length,(await db.select().from(backgroundJobs)).length]; const base={ commandId:"c", requestId:"r", clientId:"env", clientVersion:"0.1.0", entityType:"Product", idempotencyKey:"i", payload:{}, createdAt:new Date().toISOString() }; expect(validateCommandEnvelope({ ...base, commandType:"CreateProduct" }).status).toBe("Valid"); expect(validateCommandEnvelope({ ...base, commandType:"Unknown" }).status).toBe("Invalid"); expect(validateCommandEnvelope({}).status).toBe("Invalid"); expect([(await db.select().from(stockMovements)).length,(await db.select().from(orders)).length,(await db.select().from(backgroundJobs)).length]).toEqual(before); });
});
