import { ProductStatus, ProductType, ErpMigrationAction, ErpMigrationSeverity } from "@noctella/shared";
import { describe, expect, it, beforeEach } from "vitest";
import { createCategory } from "../src/services/categories";
import { createProduct } from "../src/services/products";
import { buildErpMigrationPreview, fingerprintErpMigrationSource, validateErpMigrationSource } from "../src/services/erpMigration";
import { products, stockMovements, orders, shipments, refunds, backgroundJobs } from "../src/db/schema";
import { eq } from "drizzle-orm";
import { createTestDb } from "./testDb";

describe("ERP migration preview", () => {
  let db: ReturnType<typeof createTestDb>;
  beforeEach(async () => { db=createTestDb(); const cat=await createCategory(db,{ name:"Watches", displayOrder:0, isActive:true }); const p=await createProduct(db,{ sku:"SKU-1", title:"Clock", type:ProductType.LotItem, status:ProductStatus.Approved, categoryId:cat.id, erpReferenceId:"erp-1", priceEur:10, stockQuantity:5, customsWarning:false, isFeatured:false, allowMakeOffer:false, allowCashOnDelivery:false, showInArchiveAfterSale:false }); await db.update(products).set({ erpReferenceId:"erp-1" }).where(eq(products.id,p.id)); });
  const source = { sourceVersion:"noctella-erp-1", inventoryProducts:[{ id:"erp-2", noctellaId:"N-1", sku:"SKU-2", name:"Vase", category:"Unknown", collection:"Missing", provenance:"Estate", previousOwner:"Jane Owner", depth:2, diameter:3, buyPrice:5, expectedSalePrice:20, availableQuantity:9, imageDataUrl:"data:image/png;base64,aaa", productWorkflowStatus:"done", createdAt:"2025-01-01" }], suppliers:[{ id:"s1", name:"Supplier", country:"FR" }], purchases:[{ id:"p1", productId:"erp-2" }], sales:[{ id:"sale1", productId:"missing", buyerEmail:"karen@example.com" }], invoices:[{ id:"i1", invoiceNumber:"INV-1" }], financeRecords:[{ id:"f1", amount:1 }], shippingRecords:[{ id:"sh1", address:"1 Street Paris FR" }] };
  it("validates source security and optional domains", () => { expect(validateErpMigrationSource(source).ok).toBe(true); expect(validateErpMigrationSource({ inventoryProducts:[{ id:"1", sku:"A" },{ id:"2", sku:"A" }] }).ok).toBe(false); expect(validateErpMigrationSource({ inventoryProducts:[{ id:"1", availableQuantity:-1 }] }).issues.some(i=>i.type==="InvalidQuantity")).toBe(true); expect(validateErpMigrationSource({ inventoryProducts:[], constructor:{ polluted:true } }).ok).toBe(false); expect(validateErpMigrationSource({ inventoryProducts:[], accessToken:"secret" }).issues.some(i=>i.severity===ErpMigrationSeverity.Blocking)).toBe(true); expect(validateErpMigrationSource({ inventoryProducts:[{ id:"1", createdAt:"bad" }] }).issues.some(i=>i.type==="InvalidDate")).toBe(true); expect(validateErpMigrationSource({ inventoryProducts:[{ id:"1", buyPrice:"bad" }] }).issues.some(i=>i.type==="InvalidValue")).toBe(true); expect(validateErpMigrationSource({ sourceVersion:"mystery", inventoryProducts:[] }).issues.some(i=>i.message.includes("Unknown ERP source version"))).toBe(true); });
  it("maps products, masks PII and does not mutate", async () => { const before={ products:(await db.select().from(products)).length, stock:(await db.select().from(stockMovements)).length, orders:(await db.select().from(orders)).length, shipments:(await db.select().from(shipments)).length, refunds:(await db.select().from(refunds)).length, jobs:(await db.select().from(backgroundJobs)).length }; const result=await buildErpMigrationPreview(db, source); expect(result.dryRun).toBe(true); const product=result.entityPreviews.find(e=>e.sourceId==="erp-2")!; expect(product.action).toBe(ErpMigrationAction.Create); expect(product.mappedFields.find(f=>f.sourceField==="id")?.targetField).toBe("erpReferenceId"); expect(product.mappedFields.find(f=>f.sourceField==="name")?.targetField).toBe("title"); expect(product.mappedFields.find(f=>f.sourceField==="availableQuantity")?.classification).toBe("derived"); expect(product.mappedFields.find(f=>f.sourceField==="imageDataUrl")?.classification).toBe("deferred"); expect(result.summary.fieldLossCount).toBeGreaterThan(0); expect(JSON.stringify(result)).not.toContain("karen@example.com"); expect((await db.select().from(products)).length).toBe(before.products); expect((await db.select().from(stockMovements)).length).toBe(before.stock); expect((await db.select().from(orders)).length).toBe(before.orders); expect((await db.select().from(shipments)).length).toBe(before.shipments); expect((await db.select().from(refunds)).length).toBe(before.refunds); expect((await db.select().from(backgroundJobs)).length).toBe(before.jobs); });
  it("matches ERP reference and SKU, keeps manifest deterministic", async () => { const match=await buildErpMigrationPreview(db,{ inventoryProducts:[{ id:"erp-1", sku:"OTHER", name:"Clock" },{ id:"new", sku:"SKU-1", name:"Clock" },{ id:"blank", sku:" ", name:"New" }] }); expect(match.entityPreviews.find(e=>e.sourceId==="erp-1")?.action).toBe(ErpMigrationAction.Match); expect(match.entityPreviews.find(e=>e.sourceId==="new")?.action).toBe(ErpMigrationAction.Match); expect(match.entityPreviews.find(e=>e.sourceId==="blank")?.action).toBe(ErpMigrationAction.Create); const a=await buildErpMigrationPreview(db,source); const b=await buildErpMigrationPreview(db,source); expect(a.manifestPreview).toEqual(b.manifestPreview); expect(a.manifestPreview.entries[0].idempotencyKey).toBeTruthy(); expect(fingerprintErpMigrationSource(source).value).not.toBe(fingerprintErpMigrationSource({...source, extra:true}).value); });
});
