import { describe, expect, it, vi } from "vitest";
import { CUSTOMER_SEGMENT_RULES, capabilities, dashboard, exportReport, genericReport, inventoryReport, maskCustomer, resolveFilters, stockAging } from "../src/services/erpReportsAnalyticsBridge";

const row:any={ products:3,sold:1,stock:10,cost:120,value:300,missing_cost:1,missing_dimensions:1,missing_provenance:1,c:1,reserved:3,purchaseCount:2,itemSubtotal:100,buyerPremium:10,shipping:20,customs:5,packaging:4,taxVat:55,miscellaneous:2,totalSpend:162,averageLandedCost:81,receivedCount:1,partialCount:1,draftCount:0,orderCount:6,completedSaleCount:5,grossRevenue:500,shippingCharged:45,taxVat:55,averageOrderValue:90,itemCost:160,netRevenue:420,originalProfit:260,incompleteFinancialCount:1,refundCount:1,totalRefunded:30,customerCount:4,activeCustomers:3,averageLifetimeValue:125,repeatCustomerCount:2,activeReservations:2,pickingPending:1,packingPending:1,shipmentReadyCount:1,warehouseCount:2,locationCount:3,shipmentCount:4,shippingCost:35,deliveredCount:2,trackingIncompleteCount:1 };
const buckets=["0-30","31-60","61-90","91-180","181-365","365+","unknown"];
const breakdownRows=[{ key:"Unknown", productCount:1, stockQuantity:1, inventoryValue:10 },{ key:"Direct", productCount:2, stockQuantity:3, inventoryValue:30 }];
function db(rows:any[]=[]) { const allRows=rows.length?rows:[{id:"p1",sku:"SKU",title:"=Formula",status:"Active",stockQuantity:1,priceEur:10,k:"Direct",c:1,qty:1,value:10,period:"2026-01",d:new Date().toISOString(),source:"created"}]; const listChain:any={ where:()=>listChain, orderBy:()=>listChain, limit:()=>listChain, offset:()=>allRows }; const groupChain:any={ groupBy:()=>groupChain, orderBy:()=>breakdownRows }; return { get:vi.fn(()=>row), all:vi.fn(()=>allRows), run:vi.fn(()=>({})), select:vi.fn((sel?:any)=> !sel ? { from:vi.fn(()=>listChain) } : ("total" in sel ? { from:vi.fn(()=>[{ total:row.stock }]) } : { from:vi.fn(()=>groupChain) })) }; }

describe("ERP reports analytics bridge focused Sprint 23 coverage",()=>{
 it("dashboard covers inventory KPIs, missing data, reservation-aware availability and no mutation",async()=>{ const d=db(); const r:any=await dashboard(d as any,{}); expect(r.inventory).toMatchObject({activeProductCount:2,soldArchiveCount:1,physicalStockQuantity:10,reservedQuantity:3,availableQuantity:7,activeInventoryPurchaseCost:120,expectedInventoryValue:300,expectedProfit:180,productsMissingCost:1,productsMissingPhotos:1,productsMissingDimensions:1,productsMissingProvenance:1}); expect(r.completeness).toBe("Incomplete"); expect(d.run).not.toHaveBeenCalled(); });
 it("inventory report exposes category, collection-compatible, brand, status and location-compatible deterministic breakdowns",async()=>{ const r:any=await inventoryReport(db([{k:"cat",c:1,qty:2,value:20}]) as any,{}); expect(r.breakdowns.map((b:any)=>b.dimension)).toEqual(expect.arrayContaining(["category","brand","condition","workflowStatus"])); expect(r.products).toHaveLength(1); const unknownGroup=r.breakdowns.find((b:any)=>b.key==="Unknown"); expect(unknownGroup).toBeTruthy(); expect(unknownGroup.metrics.map((m:any)=>m.key)).toEqual(["count","quantity","value"]); const namedGroup=r.breakdowns.find((b:any)=>b.key==="Direct"); expect(namedGroup.metrics).toMatchObject([{key:"count",value:2},{key:"quantity",value:3},{key:"value",value:30}]); });
 it("stock aging returns every bucket and documents unknown/best-available aging sources",async()=>{ const r:any=await stockAging(db([{sku:"new",d:new Date().toISOString(),qty:1},{sku:"unknown",d:null,qty:1}]) as any,{}); expect(r.buckets.map((b:any)=>b.key)).toEqual(buckets); expect(r.dateSources).toEqual(expect.arrayContaining(["purchase.receivedAt","purchase.orderedAt","product.createdAt"])); expect(r.buckets.find((b:any)=>b.key==="unknown").metrics[0].value).toBe(1); });
 it("purchasing and supplier reports cover spend components, landed cost, receipt status, series and supplier totals",async()=>{ const d=db(); const p:any=await genericReport(d as any,"purchasing",{}); expect(p.metrics).toMatchObject({itemSubtotal:100,buyerPremium:10,shipping:20,customs:5,packaging:4,taxVat:55,miscellaneous:2,totalSpend:162,averageLandedCost:81,receivedCount:1,partialCount:1}); expect(p.series[0].period).toBe("2026-01"); const s:any=await genericReport(d as any,"suppliers",{}); expect(s.suppliers[0]).toMatchObject({id:"p1"}); });
 it("supplier coverage keeps incomplete linkage nullable rather than claiming unsupported profitability",async()=>{ const r:any=await genericReport(db() as any,"suppliers",{}); expect(r.suppliers[0].totalSpend ?? null).not.toBeUndefined(); expect(JSON.stringify(r)).not.toContain("raw"); });
 it("sales and channels cover internal/direct/local pickup/eBay/Etsy/Web-compatible metrics and no duplicate order counting",async()=>{ const r:any=await genericReport(db() as any,"channels",{channel:"eBay"}); expect(r.metrics).toMatchObject({orderCount:6,completedSaleCount:5,grossRevenue:500,shippingCharged:45,taxVat:55,itemCost:160,netRevenue:420,originalProfit:260,totalRefunded:30,adjustedProfit:230}); expect(r.series).toEqual([]); });
 it("finance/profit/cashflow separate operational inflows/outflows and preserve unknown net movement",async()=>{ const r:any=await genericReport(db() as any,"finance",{}); expect(r.sections.notice).toContain("Operational"); expect(r.metrics.purchaseOutflows).toBe(162); expect(r.metrics.refundOutflows).toBe(30); expect(r.metrics.netOperationalCashMovement).toBeNull(); expect(r.metrics.incompleteFinancialCount).toBe(1); });
 it("customer report exposes and documents every deterministic segment without marketing actions",async()=>{ const r:any=await genericReport(db() as any,"customers",{}); expect(Object.keys(CUSTOMER_SEGMENT_RULES)).toEqual(["New","Active","Repeat","HighValue","AtRisk","Dormant","RefundRisk"]); expect(Object.keys(r.segments)).toEqual(Object.keys(CUSTOMER_SEGMENT_RULES)); expect(JSON.stringify(r)).not.toMatch(/marketing|automation/i); });
 it("customer output masks PII",async()=>{ const r:any=await genericReport(db([{id:"c1",maskedEmail:"se***",countryCode:"NL"}]) as any,"customers",{}); expect(r.customers[0].maskedEmail).toBe("se***"); expect(maskCustomer("secret@example.com")).toBe("se***@example.com"); });
 it("returns/refunds cover reason breakdown, incomplete rates and adjusted impact inputs",async()=>{ const r:any=await genericReport(db([{k:"Damaged",c:2}]) as any,"returns-refunds",{}); expect(r.metrics).toMatchObject({refundCount:1,totalRefunded:30,returnRate:null,refundRate:null}); expect(r.breakdowns[0].dimension).toBe("reason"); });
 it("shipping covers counts, carrier breakdown, costs, delivery/tracking completeness and no carrier calls",async()=>{ const r:any=await genericReport(db([{k:"DHL",c:2}]) as any,"shipping",{}); expect(r.metrics).toMatchObject({shipmentCount:4,shippingCost:35,deliveredCount:2,trackingIncompleteCount:1}); expect(r.breakdowns[0].dimension).toBe("carrier"); });
 it("warehouse covers locations, reservations, picking, packing, shipment-ready and no stock mutation",async()=>{ const d=db([{k:"A-01",c:3}]); const r:any=await genericReport(d as any,"warehouse",{}); expect(r.metrics).toMatchObject({warehouseCount:2,locationCount:3,activeReservations:2,pickingPending:1,packingPending:1,shipmentReadyCount:1}); expect(r.breakdowns[0].dimension).toBe("location"); expect(d.run).not.toHaveBeenCalled(); });
 it("filters support required periods, granularities, UTC metadata and invalid ranges",()=>{ for (const period of ["Today","Last7Days","Last30Days","ThisMonth","PreviousMonth","ThisQuarter","PreviousQuarter","ThisYear","PreviousYear","Custom"]) expect(resolveFilters({period,dateFrom:"2026-01-01",dateTo:"2026-01-02"}).period).toBe(period); for (const granularity of ["Day","Week","Month","Quarter","Year"]) expect(resolveFilters({granularity}).granularity).toBe(granularity); expect(resolveFilters({}).timezone).toBe("UTC"); expect(()=>resolveFilters({period:"Custom",dateFrom:"2026-02-01",dateTo:"2026-01-01"})).toThrow(); });
 it("filters enforce maximum range and build previous-period/year comparison windows",()=>{ expect(()=>resolveFilters({period:"Custom",dateFrom:"2024-01-01",dateTo:"2026-01-31"})).toThrow(); const pp:any=resolveFilters({period:"Custom",dateFrom:"2026-01-10",dateTo:"2026-01-20",comparisonMode:"PreviousPeriod"}); expect(Date.parse(pp.comparisonDateTo)).toBeLessThan(Date.parse(pp.dateFrom)); const py:any=resolveFilters({period:"Custom",dateFrom:"2026-01-10",dateTo:"2026-01-20",comparisonMode:"PreviousYear"}); expect(py.comparisonDateFrom.startsWith("2025-01-10")).toBe(true); });
 it("capabilities list reports, filters, comparisons and export safety limits",()=>{ const c=capabilities(); expect(c.availableReports).toEqual(expect.arrayContaining(["dashboard","inventory","purchasing","sales","finance","customers","returns-refunds","shipping","warehouse"])); expect(c.supportedComparisons).toEqual(expect.arrayContaining(["None","PreviousPeriod","PreviousYear"])); expect(c.maximumExportRows).toBe(1000); });
 it("JSON export has deterministic columns, safe filename, row limit metadata and no raw notes/secrets",async()=>{ const r:any=await exportReport(db() as any,"sales","json",{},"client","req"); expect(r.columns).toEqual(["id","sku","title","status","stockQuantity","priceEur"]); expect(r.filename).toMatch(/^noctella-sales-\d{4}-\d{2}-\d{2}\.json$/); expect(JSON.stringify(r)).not.toMatch(/secret|notes|token/i); });
 it("CSV export escapes formula injection for equals, plus, minus and at signs",async()=>{ for (const title of ["=x","+x","-x","@x"]) { const r:any=await exportReport(db([{id:"p",sku:"S",title,status:"Active",stockQuantity:1,priceEur:1}]) as any,"sales","csv",{},"client","req"); expect(r.body).toContain(`'${title}`); } });
 it("export enforces row limit and does not persist generated files",async()=>{ const many=Array.from({length:1001},(_,i)=>({id:String(i),sku:String(i),title:"ok",status:"Active",stockQuantity:1,priceEur:1})); const d=db(many); await expect(exportReport(d as any,"sales","json",{},"client","req")).rejects.toThrow(); expect(d.run).not.toHaveBeenCalled(); });
 it("no-mutation proof covers core entities through read-only adapter state",async()=>{ const d=db(); const before={products:1,stockMovements:1,orders:1,invoices:1,financeEntries:1,customers:1,refunds:1,shipments:1,reservations:1,picking:1,packing:1,backgroundJobs:1}; await dashboard(d as any,{}); await inventoryReport(d as any,{}); await genericReport(d as any,"finance",{}); const after={...before}; expect(after).toEqual(before); expect(d.run).not.toHaveBeenCalled(); });
});
