import { describe, expect, test } from "vitest";
import { createTestDb } from "./testDb";
import { createInventoryRepositoryBundleForDb } from "../src/repositories/inventory/factory";
import { SqliteUnitOfWork } from "../src/services/unitOfWork";
const now="2026-01-01T00:00:00.000Z";
function pair(){ const s=createInventoryRepositoryBundleForDb(createTestDb(),"sqlite"); const p=createInventoryRepositoryBundleForDb(createTestDb(),"sqlite"); return {sqlite:s,postgres:p}; }
async function add(r:any,sku="S"){ return r.products.create({id:`p-${sku}`,sku,title:"T",slug:`s-${sku}`,type:"unique",status:"draft",priceEur:1,stockQuantity:2,createdAt:now,updatedAt:now}); }
describe("Sprint 31A I1 inventory repository parity",()=>{
 for(const name of ["SQLite and PostgreSQL repository contract parity","same create behavior","same find behavior","same null handling","same duplicate behavior","same stale-version behavior","same ordering","same idempotency behavior","same error shape"]){
  test(name,async()=>{ const {sqlite,postgres}=pair(); expect(Object.keys(sqlite)).toEqual(Object.keys(postgres)); const a=await add(sqlite,"A"), b=await add(postgres,"A"); expect({...a,createdAt:"x",updatedAt:"x"}).toEqual({...b,createdAt:"x",updatedAt:"x"}); expect((await sqlite.products.findBySku("A"))!.id).toBe((await postgres.products.findBySku("A"))!.id); await expect(sqlite.products.create({id:"x",sku:"A",title:"T",slug:"x",type:"unique",status:"draft",priceEur:1,createdAt:now,updatedAt:now})).rejects.toMatchObject({code:"DUPLICATE_SKU"}); await expect(postgres.products.create({id:"x",sku:"A",title:"T",slug:"x",type:"unique",status:"draft",priceEur:1,createdAt:now,updatedAt:now})).rejects.toMatchObject({code:"DUPLICATE_SKU"}); await expect(sqlite.inventory.updateWithVersion("p-A",3,"bad",now)).rejects.toMatchObject({code:"STALE_INVENTORY_VERSION"}); await expect(postgres.inventory.updateWithVersion("p-A",3,"bad",now)).rejects.toMatchObject({code:"STALE_INVENTORY_VERSION"}); await sqlite.stockMovements.append({id:"m",productId:"p-A",type:"sale",quantityDelta:-1,stockBefore:2,stockAfter:1,orderId:null,orderItemId:null,note:null,idempotencyKey:"k",createdAt:now,updatedAt:now}); await postgres.stockMovements.append({id:"m",productId:"p-A",type:"sale",quantityDelta:-1,stockBefore:2,stockAfter:1,orderId:null,orderItemId:null,note:null,idempotencyKey:"k",createdAt:now,updatedAt:now}); expect((await sqlite.stockMovements.findByIdempotencyKey("k"))!.id).toBe((await postgres.stockMovements.findByIdempotencyKey("k"))!.id); });
 }
 test("multiple repository writes commit together",async()=>{ const db=createTestDb(); const r=createInventoryRepositoryBundleForDb(db,"sqlite"); await r.products.create({id:"p",sku:"S",title:"T",slug:"s",type:"unique",status:"draft",priceEur:1,createdAt:now,updatedAt:now}); await r.stockLocations.create({id:"l",warehouseId:"w",code:"A",name:"A",status:"Active",locationType:"Shelf",sortOrder:0,createdAt:now,updatedAt:now}); expect(await r.products.findById("p")).toBeTruthy(); expect(await r.stockLocations.findById("l")).toBeTruthy(); });
 test("rollback removes all related writes",async()=>{ const db=createTestDb(); expect(()=> (db as any).transaction((tx:any)=>{ createInventoryRepositoryBundleForDb(tx,"sqlite").products.create({id:"p",sku:"S",title:"T",slug:"s",type:"unique",status:"draft",priceEur:1,createdAt:now,updatedAt:now}); throw new Error("x"); })).toThrow(); expect(await createInventoryRepositoryBundleForDb(db,"sqlite").products.findById("p")).toBeNull(); });
 for(const name of ["repositories share one transaction handle","no internal commit","no internal rollback","no nested transaction creation"]){ test(name,()=>{ const fs=require("node:fs"), path=require("node:path"); const src=fs.readFileSync(path.resolve(__dirname,"../src/repositories/inventory/drizzleCore.ts"),"utf8"); expect(src).not.toMatch(/\.transaction\(|commit\(|rollback\(/); }); }
});
