import { describe, expect, test, vi } from "vitest";
import { ProductStatus, ProductType } from "@noctella/shared";
import { buildInventoryApplicationContext } from "../src/services/inventoryApplicationContext";
import { createGetInventoryUseCase, createIncreaseInventoryUseCase } from "../src/application/inventory";
const product={id:"p1",sku:"SKU",title:"T",slug:"t",type:ProductType.UniqueItem,status:ProductStatus.Draft,stockQuantity:1,priceEur:1,purchaseCost:null,purchaseCurrency:"EUR",categoryId:null,collectionId:null,createdAt:"v1",updatedAt:"v1",marketplace:{}};
function harness(fail=false){ const calls:string[]=[]; let p={...product}; const repos:any={products:{},inventory:{findByProduct:vi.fn(async()=>({productId:"p1",locationId:null,quantity:p.stockQuantity,updatedAt:p.updatedAt})),updateWithVersion:vi.fn(async(_:string,q:number)=>{calls.push("stock"); p={...p,stockQuantity:q,updatedAt:"v2"}; return {productId:"p1",locationId:null,quantity:q,updatedAt:"v2"};})},stockMovements:{findByIdempotencyKey:vi.fn(async()=>null),append:vi.fn(async()=>{calls.push("movement"); if(fail) throw new Error("append");})},stockLocations:{}}; const uow={run:vi.fn(async(fn:any)=>{calls.push("begin"); const snap={...p}; try{const r=await fn({repositories:{inventoryRepositories:repos}}); calls.push("commit"); return r;}catch(e){p=snap; calls.push("rollback"); throw e;}})}; const c=buildInventoryApplicationContext({repositories:repos,unitOfWork:uow,clock:{now:()=>new Date("2026-01-01T00:00:00.000Z")},idGenerator:{newId:()=>"m"},logger:{}}); return {c,uow,calls,get:()=>p};}
describe("Sprint 31A-I3 inventory use case transactions",()=>{
 test("mutating use case uses one transaction",async()=>{const h=harness(); await createIncreaseInventoryUseCase(h.c).execute({productId:"p1",quantity:1,expectedVersion:"v1"}); expect(h.uow.run).toHaveBeenCalledTimes(1);});
 test("query avoids transaction",async()=>{const h=harness(); await createGetInventoryUseCase(h.c).execute({productId:"p1"}); expect(h.uow.run).not.toHaveBeenCalled();});
 test("stock and movement commit together",async()=>{const h=harness(); await createIncreaseInventoryUseCase(h.c).execute({productId:"p1",quantity:1,expectedVersion:"v1"}); expect(h.calls).toEqual(["begin","stock","movement","commit"]);});
 test("stock rollback when movement append fails",async()=>{const h=harness(true); await expect(createIncreaseInventoryUseCase(h.c).execute({productId:"p1",quantity:1,expectedVersion:"v1"})).rejects.toThrow("append"); expect(h.get().stockQuantity).toBe(1);});
 test("no nested transaction",async()=>{const h=harness(); await createIncreaseInventoryUseCase(h.c).execute({productId:"p1",quantity:1,expectedVersion:"v1"}); expect(h.calls.filter(c=>c==="begin")).toHaveLength(1);});
 test("no mutation before transaction",async()=>{const h=harness(); await createIncreaseInventoryUseCase(h.c).execute({productId:"p1",quantity:1,expectedVersion:"v1"}); expect(h.calls[0]).toBe("begin");});
 test("no mutation after transaction",async()=>{const h=harness(); await createIncreaseInventoryUseCase(h.c).execute({productId:"p1",quantity:1,expectedVersion:"v1"}); expect(h.calls.at(-1)).toBe("commit");});
});
