import crypto from "node:crypto";
import Database from "better-sqlite3";
import { drizzle } from "drizzle-orm/better-sqlite3";
import { eq } from "drizzle-orm";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { MarketplaceOrderStatus, MarketplaceWebhookEventStatus, MarketplaceWebhookEventType, ProductStatus, ProductType, PublishChannel, StockMovementType } from "@noctella/shared";
import * as schema from "../src/db/schema";
import { ensureSchema } from "../src/db/migrate";
import { encryptCredential } from "../src/services/credentialEncryption";
import { getProductById } from "../src/services/products";
import { listStockMovements } from "../src/services/stockMovements";
import { getMarketplaceOrder, importMarketplaceOrder, listSyncRuns, listWebhookEvents, persistOrder, processWebhook, retryMarketplaceOrder, syncExternalListing } from "../src/services/marketplaceSync";
import type { MarketplaceAdapter, NormalizedMarketplaceOrder } from "../src/services/marketplaceAdapters";

const key = Buffer.alloc(32, 9).toString("base64");
type TestDb = ReturnType<typeof db>;
function db() { const sqlite = new Database(":memory:"); ensureSchema(sqlite); return drizzle(sqlite, { schema }); }
function sign(channel: PublishChannel, body: Buffer) { const secret = channel === PublishChannel.Ebay ? "ebay-secret" : "etsy-secret"; return crypto.createHmac("sha256", secret).update(body).digest("hex"); }
function order(overrides: Partial<NormalizedMarketplaceOrder> = {}): NormalizedMarketplaceOrder { return { externalOrderId: "ext-order-1", externalOrderNumber: "1001", status: "paid", currency: "EUR", subtotal: 10, shipping: 0, tax: 0, total: 10, buyerEmail: "buyer@example.com", buyerName: "Buyer", orderedAt: new Date().toISOString(), items: [{ externalOrderItemId:"i1", externalListingId:"listing-1", sku:"SKU-1", title:"Original title", quantity:1, unitPrice:10, lineTotal:10 }], raw: { ok:true }, ...overrides }; }
function fakeAdapter(overrides: Partial<MarketplaceAdapter> = {}) { let calls = 0; const adapter: MarketplaceAdapter & { calls: () => number; order: NormalizedMarketplaceOrder } = { order: order(), calls: () => calls, getAuthorizationUrl: () => "", exchangeAuthorizationCode: async () => ({ accessToken:"" }), refreshAccessToken: async () => ({ accessToken:"" }), verifyConnection: async () => ({}), createListing: async () => ({ externalListingId:"", externalStatus:"" }), updateListing: async () => ({ externalListingId:"", externalStatus:"" }), endListing: async () => ({ externalListingId:"", externalStatus:"" }), normalizeError: () => ({ type:"Temporary", message:"temporary", retryable:true }), verifyWebhookSignature: (raw, headers) => String(headers["x-marketplace-signature"]) === sign((headers["x-channel"] as PublishChannel) ?? PublishChannel.Ebay, raw), parseWebhookEvent: (raw) => { const p = JSON.parse(raw.toString()); return { externalEventId:p.eventId, eventType:p.eventType, externalOrderId:p.externalOrderId, externalListingId:p.externalListingId, payload:p }; }, fetchOrderById: async (_token, id) => { calls += 1; return { ...adapter.order, externalOrderId:id }; }, fetchListingStatus: async () => ({ externalListingId:"listing-1", externalStatus:"ended" }), ...overrides }; return adapter; }
async function connect(database: TestDb, channel: PublishChannel) { const now = new Date().toISOString(); await database.insert(schema.marketplaceConnections).values({ id:`conn-${channel}`, channel, accountLabel:"Default", encryptedAccessToken: encryptCredential(`token-${channel}`), scopes:"[]", status:"connected", createdAt:now, updatedAt:now }); return `conn-${channel}`; }
async function product(database: TestDb, id="p1", sku="SKU-1", stock=1) { const now = new Date().toISOString(); await database.insert(schema.products).values({ id, sku, title:"Backend title", slug:id, type:ProductType.UniqueItem, status:ProductStatus.Published, stockQuantity:stock, priceEur:10, createdAt:now, updatedAt:now }); return id; }
async function listing(database: TestDb, productId="p1", channel=PublishChannel.Ebay) { const now = new Date().toISOString(); await database.insert(schema.externalListings).values({ id:`listing-row-${channel}`, productId, channel, connectionId:`conn-${channel}`, externalListingId:"listing-1", externalStatus:"active", payloadSnapshot:"{}", publishedAt:now, updatedAt:now }); }

beforeEach(() => { process.env.MARKETPLACE_CREDENTIAL_ENCRYPTION_KEY = key; process.env.EBAY_WEBHOOK_SECRET = "ebay-secret"; process.env.ETSY_WEBHOOK_SECRET = "etsy-secret"; process.env.MARKETPLACE_IMPORT_MAX_RETRIES = "3"; vi.restoreAllMocks(); vi.spyOn(global, "fetch").mockRejectedValue(new Error("live network disabled")); });

describe("marketplace sync database consistency", () => {
  it("creates equivalent marketplace tables and unique indexes for clean and upgraded databases", () => {
    const clean = new Database(":memory:"); ensureSchema(clean); const upgraded = new Database(":memory:"); ensureSchema(upgraded); upgraded.exec("DROP TABLE marketplace_webhook_events; DROP TABLE marketplace_order_items; DROP TABLE marketplace_orders; DROP TABLE marketplace_sync_runs; DROP TABLE marketplace_import_attempts;"); ensureSchema(upgraded);
    for (const table of ["marketplace_webhook_events","marketplace_orders","marketplace_order_items","marketplace_sync_runs"]) { expect(clean.prepare(`PRAGMA table_info(${table})`).all().length).toBeGreaterThan(0); expect(upgraded.prepare(`PRAGMA table_info(${table})`).all().length).toBe(clean.prepare(`PRAGMA table_info(${table})`).all().length); }
    expect(clean.prepare("PRAGMA index_list(marketplace_webhook_events)").all()).toEqual(expect.arrayContaining([expect.objectContaining({ name:"idx_webhook_channel_external", unique:1 })]));
    expect(clean.prepare("PRAGMA index_list(marketplace_orders)").all()).toEqual(expect.arrayContaining([expect.objectContaining({ name:"idx_marketplace_orders_channel_external", unique:1 })]));
  });
});

describe("webhook security", () => {
  it("accepts valid eBay and Etsy signatures and rejects invalid signatures without orders or stock movements", async () => { for (const ch of [PublishChannel.Ebay, PublishChannel.Etsy]) { const database=db(); await connect(database,ch); await product(database); await listing(database,"p1",ch); const adapter=fakeAdapter(); const body=Buffer.from(JSON.stringify({ eventId:`evt-${ch}`, eventType:MarketplaceWebhookEventType.OrderPaid, externalOrderId:"ext-order-1" })); await expect(processWebhook(database,ch,body,{ "x-marketplace-signature":sign(ch,body), "x-channel":ch },adapter)).resolves.toBeDefined(); expect((await database.select().from(schema.marketplaceOrders))).toHaveLength(1); const invalidDb=db(); await expect(processWebhook(invalidDb,ch,body,{ "x-marketplace-signature":"bad", "x-channel":ch },adapter)).rejects.toThrow(/signature/i); expect(await invalidDb.select().from(schema.marketplaceOrders)).toHaveLength(0); expect(await invalidDb.select().from(schema.stockMovements)).toHaveLength(0); } });
  it("replays are idempotent and unsupported events are Ignored", async () => { const database=db(); await connect(database,PublishChannel.Ebay); await product(database); await listing(database); const adapter=fakeAdapter(); const body=Buffer.from(JSON.stringify({ eventId:"evt-replay", eventType:MarketplaceWebhookEventType.OrderPaid, externalOrderId:"ext-order-1" })); await processWebhook(database,PublishChannel.Ebay,body,{ "x-marketplace-signature":sign(PublishChannel.Ebay,body), "x-channel":PublishChannel.Ebay },adapter); await processWebhook(database,PublishChannel.Ebay,body,{ "x-marketplace-signature":sign(PublishChannel.Ebay,body), "x-channel":PublishChannel.Ebay },adapter); expect(adapter.calls()).toBe(1); expect(await database.select().from(schema.marketplaceWebhookEvents)).toHaveLength(1); const unsupported=Buffer.from(JSON.stringify({ eventId:"evt-ignore", eventType:"unknown" })); await processWebhook(database,PublishChannel.Ebay,unsupported,{ "x-marketplace-signature":sign(PublishChannel.Ebay,unsupported), "x-channel":PublishChannel.Ebay },adapter); const events=await listWebhookEvents(database,{ status:MarketplaceWebhookEventStatus.Ignored }); expect(events.items).toHaveLength(1); });
});

describe("marketplace order import, stock, idempotency, and retry", () => {
  it("imports paid eBay and Etsy orders, matches by listing then SKU, persists unmatched items, and creates stock movements once", async () => { for (const ch of [PublishChannel.Ebay, PublishChannel.Etsy]) { const database=db(); await connect(database,ch); await product(database,"p1","SKU-1",1); await product(database,"p2","SKU-2",1); await listing(database,"p1",ch); const adapter=fakeAdapter(); adapter.order=order({ externalOrderId:`order-${ch}`, subtotal:20, total:20, items:[{ externalListingId:"listing-1", title:"Listing", quantity:1, unitPrice:10, lineTotal:10 }, { sku:"SKU-2", title:"Sku", quantity:1, unitPrice:10, lineTotal:10 }, { sku:"NOPE", title:"Unmatched", quantity:1, unitPrice:0, lineTotal:0 }] }); const imported=await importMarketplaceOrder(database,ch,`order-${ch}`,adapter); expect(imported.items.map((i:any)=>i.productId).sort()).toEqual([null,"p1","p2"].sort()); expect(imported.internalOrderId).toBeTruthy(); const again=await importMarketplaceOrder(database,ch,`order-${ch}`,adapter); expect(again.internalOrderId).toBe(imported.internalOrderId); expect((await listStockMovements(database,{ page:1, pageSize:20 })).items.filter((m)=>m.type===StockMovementType.Sale)).toHaveLength(2); expect((await getProductById(database,"p1")).title).toBe("Backend title"); } });
  it("unpaid orders persist without internal orders and listing sync does not change stock", async () => { const database=db(); await connect(database,PublishChannel.Ebay); await product(database); await listing(database); const adapter=fakeAdapter(); adapter.order=order({ status:"pending" }); const imported=await importMarketplaceOrder(database,PublishChannel.Ebay,"unpaid",adapter); expect(imported.internalOrderId).toBeNull(); const before=(await getProductById(database,"p1")).stockQuantity; await syncExternalListing(database,"listing-row-ebay",adapter); expect((await getProductById(database,"p1")).stockQuantity).toBe(before); expect((await database.select().from(schema.externalListings).where(eq(schema.externalListings.id,"listing-row-ebay")))[0].externalStatus).toBe("ended"); });
  it("rejects unsupported currency and quantity > 1 safely without silent wrong stock", async () => { const database=db(); await connect(database,PublishChannel.Ebay); await product(database,"p1","SKU-1",5); await listing(database); await expect(persistOrder(database,PublishChannel.Ebay,"conn-ebay",order({ externalOrderId:"usd", currency:"USD" }))).rejects.toThrow(/currency/i); await expect(persistOrder(database,PublishChannel.Ebay,"conn-ebay",order({ externalOrderId:"qty", subtotal:20, total:20, items:[{ sku:"SKU-1", title:"Two", quantity:2, unitPrice:10, lineTotal:20 }] }))).rejects.toThrow(/quantities greater than 1/i); expect((await getProductById(database,"p1")).stockQuantity).toBe(5); expect((await getMarketplaceOrder(database,(await database.select().from(schema.marketplaceOrders).where(eq(schema.marketplaceOrders.externalOrderId,"qty")))[0].id)).attempts).toHaveLength(1); });
  it("rolls back insufficient stock and preserves retryable audit, then retry succeeds with prior attempt visible and retry limit/permanent failures enforced", async () => { const database=db(); await connect(database,PublishChannel.Ebay); await product(database,"p1","SKU-1",0); await listing(database); const adapter=fakeAdapter(); await expect(importMarketplaceOrder(database,PublishChannel.Ebay,"stock-fail",adapter)).rejects.toThrow(/stock|published/i); expect(await database.select().from(schema.orders)).toHaveLength(0); expect(await database.select().from(schema.stockMovements)).toHaveLength(0); const [failed]=await database.select().from(schema.marketplaceOrders); expect(failed.retryable).toBe(true); await database.update(schema.products).set({ stockQuantity:1, status:ProductStatus.Published }).where(eq(schema.products.id,"p1")); const retried=await retryMarketplaceOrder(database,failed.id,adapter); expect(retried.internalOrderId).toBeTruthy(); expect(retried.attempts).toHaveLength(2); const permanentDb=db(); await connect(permanentDb,PublishChannel.Ebay); await product(permanentDb); await listing(permanentDb); await expect(persistOrder(permanentDb,PublishChannel.Ebay,"conn-ebay",order({ externalOrderId:"perm", currency:"USD" }))).rejects.toThrow(); const [perm]=await permanentDb.select().from(schema.marketplaceOrders); await expect(retryMarketplaceOrder(permanentDb,perm.id,adapter)).rejects.toThrow(/not retryable/); process.env.MARKETPLACE_IMPORT_MAX_RETRIES="1"; await expect(retryMarketplaceOrder(database,failed.id,adapter)).rejects.toThrow(/not retryable/); expect((await listSyncRuns(database,{})).items.some((r)=>r.failureCount===1)).toBe(true); });
  it("does not call live network", async () => { const database=db(); await connect(database,PublishChannel.Ebay); await product(database); await listing(database); await importMarketplaceOrder(database,PublishChannel.Ebay,"no-network",fakeAdapter()); expect(global.fetch).not.toHaveBeenCalled(); });
});
