import crypto from "node:crypto";
import { and, asc, eq } from "drizzle-orm";
import { beforeAll, describe, expect, it } from "vitest";
import { MarketplaceOrderStatus, MarketplaceWebhookEventType, ProductStatus, ProductType, PublishChannel, StockMovementType } from "@noctella/shared";
import * as schema from "../src/db/schema.postgres";
import { createPostgresTestDb, postgresTestConfigured, type PostgresTestDb } from "./postgresTestDb";

if (postgresTestConfigured) {
  process.env.DATABASE_DRIVER = "postgres";
  process.env.DATABASE_URL = process.env.POSTGRES_TEST_DATABASE_URL;
  process.env.MARKETPLACE_CREDENTIAL_ENCRYPTION_KEY = Buffer.alloc(32, 11).toString("base64");
  process.env.MARKETPLACE_IMPORT_MAX_RETRIES = "3";
}

let sync: typeof import("../src/services/marketplaceSync");
let lifecycle: typeof import("../src/services/productLifecycle");
let productsService: typeof import("../src/services/products");
let encryption: typeof import("../src/services/credentialEncryption");

beforeAll(async () => {
  if (!postgresTestConfigured) return;
  sync = await import("../src/services/marketplaceSync");
  lifecycle = await import("../src/services/productLifecycle");
  productsService = await import("../src/services/products");
  encryption = await import("../src/services/credentialEncryption");
});

const suite = describe.skipIf(!postgresTestConfigured);
const now = () => new Date();
async function product(h: PostgresTestDb, id="p1", sku="SKU-1", stock=1) {
  const t=now(); await h.db.insert(schema.products).values({id,sku,title:`Product ${id}`,slug:id,type:ProductType.UniqueItem,status:ProductStatus.Published,stockQuantity:stock,priceEur:"10",wooProductName:`Web ${id}`,wooShortDescription:"Short",wooLongDescription:"Long",ebayTitle:`eBay ${id}`,ebayDescription:"Description",ebayCategory:"123",ebayListingPriceEur:"10",createdAt:t,updatedAt:t});
}
async function connection(h:PostgresTestDb,id="conn",channel=PublishChannel.Ebay){const t=now();await h.db.insert(schema.marketplaceConnections).values({id,channel,accountLabel:id,status:"connected",encryptedAccessToken:encryption.encryptCredential(`token-${id}`),scopes:"[]",createdAt:t,updatedAt:t});}
async function listing(h:PostgresTestDb,id="listing-row",productId="p1",connectionId="conn",externalListingId="listing-1"){const t=now();await h.db.insert(schema.externalListings).values({id,productId,channel:PublishChannel.Ebay,connectionId,externalListingId,externalStatus:"active",payloadSnapshot:{title:"snapshot"},publishedAt:t,updatedAt:t});}
async function photo(h:PostgresTestDb,productId="p1"){const t=now();await h.db.insert(schema.productPhotos).values({id:`photo-${productId}`,productId,url:"/photo.jpg",thumbnailUrl:"/thumb.jpg",filename:"photo.jpg",mimeType:"image/jpeg",sizeBytes:1,width:1,height:1,sortOrder:0,isPrimary:true,processingStatus:"Ready",createdAt:t,updatedAt:t});}
const order=(overrides:Record<string,unknown>={})=>({externalOrderId:"external-1",externalOrderNumber:"1001",status:"pending",currency:"EUR",subtotal:10,shipping:0,tax:0,total:10,buyerEmail:"buyer@example.test",buyerName:"Buyer",orderedAt:new Date().toISOString(),items:[{externalOrderItemId:"item-1",externalListingId:"listing-1",sku:"SKU-1",title:"Marketplace title",quantity:1,unitPrice:10,lineTotal:10}],raw:{native:true},...overrides} as any);

suite("Sprint 151 real PostgreSQL runtime", () => {
  it("applies the migration chain through 0023 twice and enforces all four marketplace unique indexes", async()=>{const h=await createPostgresTestDb();try{const again=await h.migrateAgain();expect(again.at(-1)).toBe("0023_sprint151_orders_shipping_snapshot_parity.sql");const indexes=await h.pool.query("SELECT indexname FROM pg_indexes WHERE schemaname=current_schema() AND indexname = ANY($1)",[["idx_marketplace_connections_channel_account","idx_external_listings_channel_external","idx_webhook_channel_external","idx_marketplace_orders_channel_external"]]);expect(indexes.rows.map(r=>r.indexname).sort()).toEqual(["idx_external_listings_channel_external","idx_marketplace_connections_channel_account","idx_marketplace_orders_channel_external","idx_webhook_channel_external"].sort());}finally{await h.close();}});

  it("atomically pauses, round-trips lifecycle JSONB/timestamptz, and reuses the idempotency key",async()=>{const h=await createPostgresTestDb();try{await product(h);await connection(h);await listing(h);const first=await lifecycle.pauseProduct(h.db as any,{productId:"p1",actorAdminUserId:"admin",idempotencyKey:"pause-idem"},()=>({endListing:async()=>({externalListingId:"listing-1",externalStatus:"ended"}),normalizeError:()=>({type:"Temporary",message:"temporary",retryable:true})} as any));expect(first.operation.status).toBe("succeeded");const replay=await lifecycle.pauseProduct(h.db as any,{productId:"p1",actorAdminUserId:"admin",idempotencyKey:"pause-idem"},()=>({} as any));expect(replay.operation.id).toBe(first.operation.id);expect((await h.db.select().from(schema.productLifecycleOperations))).toHaveLength(1);const raw=(await h.pool.query("SELECT target_snapshot,created_at FROM product_lifecycle_operations")).rows[0];expect(Array.isArray(raw.target_snapshot)).toBe(true);expect(raw.created_at).toBeInstanceOf(Date);expect(first.operation.createdAt).toMatch(/Z$/);}finally{await h.close();}});

  it("rolls back the Product pause when lifecycle-operation persistence fails",async()=>{const h=await createPostgresTestDb();try{await product(h);await h.pool.query("CREATE FUNCTION reject_lifecycle() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'forced lifecycle failure'; END $$; CREATE TRIGGER reject_lifecycle BEFORE INSERT ON product_lifecycle_operations FOR EACH ROW EXECUTE FUNCTION reject_lifecycle()");await expect(lifecycle.pauseProduct(h.db as any,{productId:"p1",actorAdminUserId:"admin",idempotencyKey:"rollback"},()=>({} as any))).rejects.toThrow();const [p]=await h.db.select().from(schema.products).where(eq(schema.products.id,"p1"));expect(p.salePausedAt).toBeNull();expect(await h.db.select().from(schema.productLifecycleOperations)).toHaveLength(0);}finally{await h.close();}});

  it("persists partial Pause state and Retry processes only the retryable failed target",async()=>{const h=await createPostgresTestDb();try{await product(h);await connection(h,"c1");await connection(h,"c2");await listing(h,"l1","p1","c1","remote-1");await listing(h,"l2","p1","c2","remote-2");let fail=true;const calls:string[]=[];const adapter=()=>({endListing:async(_t:string,id:string)=>{calls.push(id);if(id==="remote-1"&&fail)throw new Error("temporary");return{externalListingId:id,externalStatus:"ended"};},fetchListingStatus:async(_t:string,id:string)=>({externalListingId:id,externalStatus:"active"}),normalizeError:()=>({type:"Temporary",message:"temporary",retryable:true})} as any);const first=await lifecycle.pauseProduct(h.db as any,{productId:"p1",actorAdminUserId:"admin",idempotencyKey:"partial"},adapter);expect(first.operation.status).toBe("partially_failed");fail=false;calls.length=0;const retried=await lifecycle.retryPauseOperation(h.db as any,"p1",first.operation.id,adapter);expect(retried.status).toBe("succeeded");expect(calls).toEqual(["remote-1"]);}finally{await h.close();}});

  it("persists unpaid orders with native JSONB, numeric/boolean/ISO normalization, matching precedence, and reconciliation",async()=>{const h=await createPostgresTestDb();try{await product(h,"p1","SKU-1");await product(h,"p2","SKU-2");await connection(h);await listing(h);const saved=await sync.persistOrder(h.db as any,PublishChannel.Ebay,"conn",order({items:[{externalListingId:"listing-1",sku:"SKU-2",title:"listing wins",quantity:1,unitPrice:4.25,lineTotal:4.25},{sku:"SKU-2",title:"sku",quantity:1,unitPrice:5.75,lineTotal:5.75},{sku:"missing",title:"unmatched",quantity:1,unitPrice:0,lineTotal:0}]}));expect(saved.internalOrderId).toBeNull();expect(saved.items.map((x:any)=>x.productId)).toEqual(["p1","p2",null]);expect(saved.subtotal).toBe(10);expect(saved.retryable).toBe(false);expect(saved.orderedAt).toMatch(/Z$/);const raw=(await h.pool.query("SELECT raw_payload_snapshot,subtotal,retryable FROM marketplace_orders")).rows[0];expect(raw.raw_payload_snapshot).toEqual({native:true});expect(typeof raw.subtotal).toBe("string");expect(raw.retryable).toBe(0);const result=await sync.syncExternalListing(h.db as any,"listing-row",{fetchListingStatus:async()=>({externalListingId:"listing-1",externalStatus:"ended"})} as any);expect(result.changed).toBe(true);expect(await h.db.select().from(schema.stockMovements)).toHaveLength(0);}finally{await h.close();}});

  it("rolls back the initial marketplace order when any item insert fails",async()=>{const h=await createPostgresTestDb();try{await product(h);await connection(h);await listing(h);await h.pool.query("CREATE FUNCTION reject_marketplace_item() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'forced item failure'; END $$; CREATE TRIGGER reject_marketplace_item BEFORE INSERT ON marketplace_order_items FOR EACH ROW EXECUTE FUNCTION reject_marketplace_item()");await expect(sync.persistOrder(h.db as any,PublishChannel.Ebay,"conn",order())).rejects.toThrow();expect(await h.db.select().from(schema.marketplaceOrders)).toHaveLength(0);expect(await h.db.select().from(schema.marketplaceOrderItems)).toHaveLength(0);}finally{await h.close();}});

  it("enforces webhook replay and concurrent webhook/order uniqueness",async()=>{const h=await createPostgresTestDb();try{await product(h);await connection(h);await listing(h);const body=Buffer.from("{}");const adapter={verifyWebhookSignature:async()=>true,parseWebhookEvent:async()=>({externalEventId:"event-1",eventType:MarketplaceWebhookEventType.Unsupported,payload:{ok:true}})} as any;await sync.processWebhook(h.db as any,PublishChannel.Ebay,body,{},adapter);const replay=await sync.processWebhook(h.db as any,PublishChannel.Ebay,body,{},adapter);expect(replay.duplicate).toBe(true);expect(await h.db.select().from(schema.marketplaceWebhookEvents)).toHaveLength(1);const t=now(),base={channel:PublishChannel.Ebay,marketplaceConnectionId:"conn",status:MarketplaceOrderStatus.Pending,importStatus:"pending",retryable:1,currency:"EUR",subtotal:"1",shipping:"0",tax:"0",total:"1",rawPayloadSnapshot:{},orderedAt:t,importedAt:t,updatedAt:t};const outcomes=await Promise.allSettled([h.db.insert(schema.marketplaceOrders).values({id:"race-1",externalOrderId:"race",...base}),h.db.insert(schema.marketplaceOrders).values({id:"race-2",externalOrderId:"race",...base})]);expect(outcomes.filter(x=>x.status==="fulfilled")).toHaveLength(1);expect(await h.db.select().from(schema.marketplaceOrders).where(and(eq(schema.marketplaceOrders.channel,PublishChannel.Ebay),eq(schema.marketplaceOrders.externalOrderId,"race")))).toHaveLength(1);}finally{await h.close();}});

  it("imports a paid order through createOrder with one Sale movement and deferred invoicing",async()=>{const h=await createPostgresTestDb();try{await product(h);await connection(h);await listing(h);const logicalOrder=order({status:"paid"});const paid=await sync.persistOrder(h.db as any,PublishChannel.Ebay,"conn",logicalOrder);expect(paid.internalOrderId).toBeTruthy();expect(await h.db.select().from(schema.orders)).toHaveLength(1);expect((await h.db.select().from(schema.stockMovements)).filter((m:any)=>m.type===StockMovementType.Sale&&m.productId==="p1")).toHaveLength(1);const replay=await sync.persistOrder(h.db as any,PublishChannel.Ebay,"conn",logicalOrder);expect(replay.internalOrderId).toBe(paid.internalOrderId);expect(await h.db.select().from(schema.orders)).toHaveLength(1);expect((await h.db.select().from(schema.stockMovements)).filter((m:any)=>m.type===StockMovementType.Sale&&m.productId==="p1")).toHaveLength(1);expect(await h.db.select().from(schema.invoices)).toHaveLength(0);}finally{await h.close();}});

  it("preserves successful Relist target history across partial failure and clears salePausedAt only after Retry succeeds",async()=>{const h=await createPostgresTestDb();try{await product(h);await photo(h);await connection(h);await listing(h);const paused=await lifecycle.pauseProduct(h.db as any,{productId:"p1",actorAdminUserId:"admin",idempotencyKey:"relist-pause"},()=>({endListing:async()=>({externalListingId:"listing-1",externalStatus:"ended"}),normalizeError:()=>({type:"Temporary",message:"temporary",retryable:true})} as any));expect(paused.operation.status).toBe("succeeded");let fail=true;const createCalls:string[]=[];const adapter=()=>({createListing:async()=>{createCalls.push("ebay");if(fail)throw new Error("temporary relist failure");return{externalListingId:"replacement-1",externalStatus:"active"};},normalizeError:()=>({type:"Temporary",message:"temporary",retryable:true})} as any);const first=await lifecycle.relistProduct(h.db as any,{productId:"p1",actorAdminUserId:"admin",idempotencyKey:"relist-operation"},adapter);expect(first.operation.status).toBe("partially_failed");expect(first.operation.targetResults.find((t:any)=>t.channel===PublishChannel.NoctellaWeb)?.status).toBe("succeeded");expect(first.operation.targetResults.find((t:any)=>t.channel===PublishChannel.Ebay)?.status).toBe("failed");expect((await productsService.getProductById(h.db as any,"p1")).salePausedAt).toBeTruthy();const webJobsBefore=(await h.db.select().from(schema.publishJobs)).filter((j:any)=>j.channel===PublishChannel.NoctellaWeb);fail=false;const retried=await lifecycle.retryLifecycleOperation(h.db as any,"p1",first.operation.id,adapter);expect(retried.operation.status).toBe("succeeded");expect(retried.operation.targetResults.find((t:any)=>t.channel===PublishChannel.NoctellaWeb)?.status).toBe("succeeded");expect((await productsService.getProductById(h.db as any,"p1")).salePausedAt).toBeUndefined();expect((await h.db.select().from(schema.publishJobs)).filter((j:any)=>j.channel===PublishChannel.NoctellaWeb)).toHaveLength(webJobsBefore.length);expect((await h.db.select().from(schema.productLifecycleOperations))).toHaveLength(2);expect((await h.db.select().from(schema.externalListings)).some((l:any)=>l.externalListingId==="replacement-1")).toBe(true);expect(createCalls.length).toBeGreaterThanOrEqual(2);}finally{await h.close();}});

  it("blocks unsafe Archive states, then archives safely without deleting lifecycle or publishing history",async()=>{const h=await createPostgresTestDb();try{await product(h);await connection(h);await listing(h);await expect(productsService.archiveProduct(h.db as any,"p1")).rejects.toThrow();await h.db.update(schema.externalListings).set({externalStatus:"ended",updatedAt:now()}).where(eq(schema.externalListings.id,"listing-row"));const t=now();await h.db.insert(schema.productLifecycleOperations).values({id:"archive-operation",productId:"p1",action:"pause",status:"processing",previousProductStatus:ProductStatus.Published,targetSnapshot:[],targetResults:[],actorAdminUserId:"admin",idempotencyKey:"archive-operation",createdAt:t,updatedAt:t});await expect(productsService.archiveProduct(h.db as any,"p1")).rejects.toThrow();await h.db.update(schema.productLifecycleOperations).set({status:"succeeded",completedAt:now(),updatedAt:now()}).where(eq(schema.productLifecycleOperations.id,"archive-operation"));await h.db.insert(schema.publishJobs).values({id:"archive-job",productId:"p1",channel:PublishChannel.NoctellaWeb,status:"succeeded",idempotencyKey:"archive-job",payloadSnapshot:{title:"history"},attemptCount:1,createdAt:t,updatedAt:t,completedAt:t});const counts={operations:(await h.db.select().from(schema.productLifecycleOperations)).length,listings:(await h.db.select().from(schema.externalListings)).length,jobs:(await h.db.select().from(schema.publishJobs)).length};const archived=await productsService.archiveProduct(h.db as any,"p1");expect(archived.status).toBe(ProductStatus.Archived);expect(await h.db.select().from(schema.productLifecycleOperations)).toHaveLength(counts.operations);expect(await h.db.select().from(schema.externalListings)).toHaveLength(counts.listings);expect(await h.db.select().from(schema.publishJobs)).toHaveLength(counts.jobs);}finally{await h.close();}});

  it("enforces the migration 0019 partial unique index for one processing lifecycle operation per Product",async()=>{const h=await createPostgresTestDb();try{await product(h);const t=now(),base={productId:"p1",action:"pause",status:"processing",previousProductStatus:ProductStatus.Published,targetSnapshot:[],targetResults:[],actorAdminUserId:"admin",createdAt:t,updatedAt:t};const outcomes=await Promise.allSettled([h.db.insert(schema.productLifecycleOperations).values({id:"processing-1",idempotencyKey:"processing-1",...base}),h.db.insert(schema.productLifecycleOperations).values({id:"processing-2",idempotencyKey:"processing-2",...base})]);expect(outcomes.filter((x)=>x.status==="fulfilled")).toHaveLength(1);expect(await h.db.select().from(schema.productLifecycleOperations).where(and(eq(schema.productLifecycleOperations.productId,"p1"),eq(schema.productLifecycleOperations.status,"processing")))).toHaveLength(1);}finally{await h.close();}});

  it("keeps marketplace retry attempts durably ordered, preserves failure-to-success history, and enforces retry limits",async()=>{const h=await createPostgresTestDb();try{await product(h,"p1","SKU-1",0);await connection(h);await listing(h);const adapter={fetchOrderById:async()=>order({externalOrderId:"retry-order",status:"paid"})} as any;await expect(sync.importMarketplaceOrder(h.db as any,PublishChannel.Ebay,"retry-order",adapter)).rejects.toThrow();const [failed]=await h.db.select().from(schema.marketplaceOrders).where(eq(schema.marketplaceOrders.externalOrderId,"retry-order"));expect(failed.retryable).toBe(1);expect((await h.db.select().from(schema.marketplaceImportAttempts).where(eq(schema.marketplaceImportAttempts.marketplaceOrderId,failed.id))).map((a:any)=>a.attemptNumber)).toEqual([1]);await h.db.update(schema.products).set({stockQuantity:1,updatedAt:now()}).where(eq(schema.products.id,"p1"));const succeeded=await sync.retryMarketplaceOrder(h.db as any,failed.id,adapter);expect(succeeded.internalOrderId).toBeTruthy();const history=await h.db.select().from(schema.marketplaceImportAttempts).where(eq(schema.marketplaceImportAttempts.marketplaceOrderId,failed.id)).orderBy(asc(schema.marketplaceImportAttempts.attemptNumber));expect(history.map((a:any)=>a.attemptNumber)).toEqual([1,2]);expect(history.map((a:any)=>a.status)).toEqual(["failed","succeeded"]);expect(new Set(history.map((a:any)=>a.attemptNumber)).size).toBe(2);await product(h,"p2","SKU-2",0);await listing(h,"listing-2","p2","conn","listing-2");const limitedAdapter={fetchOrderById:async()=>order({externalOrderId:"limited-order",status:"paid",items:[{externalOrderItemId:"limited-item",externalListingId:"listing-2",sku:"SKU-2",title:"limited",quantity:1,unitPrice:10,lineTotal:10}]})} as any;await expect(sync.importMarketplaceOrder(h.db as any,PublishChannel.Ebay,"limited-order",limitedAdapter)).rejects.toThrow();const [limited]=await h.db.select().from(schema.marketplaceOrders).where(eq(schema.marketplaceOrders.externalOrderId,"limited-order"));process.env.MARKETPLACE_IMPORT_MAX_RETRIES="1";await expect(sync.retryMarketplaceOrder(h.db as any,limited.id,limitedAdapter)).rejects.toThrow(/not retryable/i);expect(await h.db.select().from(schema.marketplaceImportAttempts).where(eq(schema.marketplaceImportAttempts.marketplaceOrderId,limited.id))).toHaveLength(1);}finally{process.env.MARKETPLACE_IMPORT_MAX_RETRIES="3";await h.close();}});

  it("rejects concurrent duplicate webhook persistence with exactly one durable logical event",async()=>{const h=await createPostgresTestDb();try{const t=now(),base={channel:PublishChannel.Ebay,externalEventId:"concurrent-event",eventType:MarketplaceWebhookEventType.Unsupported,status:"received",signatureValid:1,payloadSnapshot:{concurrent:true},attemptCount:0,receivedAt:t,createdAt:t,updatedAt:t};const outcomes=await Promise.allSettled([h.db.insert(schema.marketplaceWebhookEvents).values({id:"webhook-race-1",...base}),h.db.insert(schema.marketplaceWebhookEvents).values({id:"webhook-race-2",...base})]);expect(outcomes.filter((x)=>x.status==="fulfilled")).toHaveLength(1);expect(outcomes.filter((x)=>x.status==="rejected")).toHaveLength(1);expect(await h.db.select().from(schema.marketplaceWebhookEvents).where(and(eq(schema.marketplaceWebhookEvents.channel,PublishChannel.Ebay),eq(schema.marketplaceWebhookEvents.externalEventId,"concurrent-event")))).toHaveLength(1);}finally{await h.close();}});
});
