import { describe, expect, test, vi } from "vitest";
import { readFileSync } from "node:fs";
import path from "node:path";
import { ProductStatus, ProductType } from "@noctella/shared";
import { createDrizzleProductWriteRepositories } from "../src/repositories/product-write/drizzle";
import * as sqliteSchema from "../src/db/schema.sqlite";
import * as postgresSchema from "../src/db/schema.postgres";
import { createTestDb } from "./testDb";

import { createProduct, updateProduct, updateProductPhoto, setPrimaryProductPhoto, reorderProductPhotos, deleteProductPhoto } from "../src/services/products";

const root = path.resolve(__dirname, "..");
const read = (p: string) => readFileSync(path.join(root, p), "utf8");
async function seeded() { const db = createTestDb(); const now = "2026-01-01"; await db.insert(sqliteSchema.categories).values({ id:"cat", name:"Cat", slug:"cat", displayOrder:0, isActive:true, createdAt:now, updatedAt:now }); await db.insert(sqliteSchema.collections).values({ id:"col", name:"Col", slug:"col", displayOrder:0, isActive:true, createdAt:now, updatedAt:now }); await db.insert(sqliteSchema.products).values({ id:"p", sku:"SKU", title:"Title", slug:"title", type:ProductType.UniqueItem, status:ProductStatus.Draft, categoryId:"cat", collectionId:"col", stockQuantity:1, priceEur:10, customsWarning:false, isFeatured:false, allowMakeOffer:false, allowCashOnDelivery:false, showInArchiveAfterSale:false, createdAt:now, updatedAt:now } as any); await db.insert(sqliteSchema.productPhotos).values([{ id:"ph1", productId:"p", url:"u1", thumbnailUrl:"t1", altText:null, sortOrder:0, isPrimary:true, filename:"f1", mimeType:"image/jpeg", sizeBytes:1, width:1, height:1, processingStatus:"Ready", createdAt:now, updatedAt:now },{ id:"ph2", productId:"p", url:"u2", thumbnailUrl:"t2", altText:null, sortOrder:1, isPrimary:false, filename:"f2", mimeType:"image/jpeg", sizeBytes:1, width:1, height:1, processingStatus:"Processing", createdAt:now, updatedAt:now }] as any); return db; }

describe("Sprint 27 Product Write repository contracts", () => { const types = read("src/repositories/product-write/types.ts"); for (const name of ["create","update","existsBySku","existsByErpReference","existsByNoctellaId","getVersionForUpdate","updateWithExpectedVersion","createErpMetadata","updateErpMetadata","getErpMetadataForUpdate","createMetadata","updateAltText","setPrimary","reorder","deleteMetadata","promoteNextPrimary","updateProcessingState","updateStorageMetadata","getForUpdate","listForUpdate","ProductWriteConflict","ProductWriteIssue","ProductWriteExecutionResult","CreateProductInput","UpdateProductInput","CreateCategoryInput","UpdateCategoryInput","CreateCollectionInput","UpdateCollectionInput"]) test(`contract ${name}`, () => expect(types).toContain(name)); });

describe("Sprint 27 executable SQLite Product write repositories", () => {
  test("Product create", async()=>{ const db=createTestDb(); const r=createDrizzleProductWriteRepositories(db, sqliteSchema, "sqlite"); await r.products.create({ values:{ id:"p", sku:"S", title:"T", slug:"t", type:ProductType.UniqueItem, status:ProductStatus.Draft, stockQuantity:1, priceEur:1, customsWarning:false, isFeatured:false, allowMakeOffer:false, allowCashOnDelivery:false, showInArchiveAfterSale:false, createdAt:"n", updatedAt:"n" }}); expect(await r.products.existsBySku("S")).toBe(true); });
  test("Product update", async()=>{ const db=await seeded(); const r=createDrizzleProductWriteRepositories(db, sqliteSchema, "sqlite"); await r.products.update({ id:"p", values:{ title:"New" }}); expect(await r.products.getVersionForUpdate("p")).toBeTruthy(); });
  test("duplicate SKU", async()=>{ const db=await seeded(); const r=createDrizzleProductWriteRepositories(db, sqliteSchema, "sqlite"); expect(await r.products.existsBySku("SKU")).toBe(true); });
  test("ERP metadata write", async()=>{ const db=await seeded(); const r=createDrizzleProductWriteRepositories(db, sqliteSchema, "sqlite"); await r.products.createErpMetadata({ productId:"p", noctellaId:"N" }); expect(await r.products.existsByNoctellaId("N")).toBe(true); });
  test("optimistic conflict", async()=>{ const db=await seeded(); const r=createDrizzleProductWriteRepositories(db, sqliteSchema, "sqlite"); expect((await r.products.updateWithExpectedVersion({ id:"p", values:{ title:"x" }, expectedUpdatedAt:"stale" })).updated).toBe(false); });
  test("Category create/update", async()=>{ const db=createTestDb(); const r=createDrizzleProductWriteRepositories(db, sqliteSchema, "sqlite"); await r.categories.create({ values:{ id:"c", name:"C", slug:"c", displayOrder:0, isActive:true, createdAt:"n", updatedAt:"n" }}); await r.categories.update({ id:"c", values:{ name:"C2" }}); expect(await r.categories.existsBySlug("c")).toBe(true); });
  test("Collection create/update", async()=>{ const db=createTestDb(); const r=createDrizzleProductWriteRepositories(db, sqliteSchema, "sqlite"); await r.collections.create({ values:{ id:"c", name:"C", slug:"c", displayOrder:0, isActive:true, createdAt:"n", updatedAt:"n" }}); await r.collections.update({ id:"c", values:{ name:"C2" }}); expect(await r.collections.existsByName("C2")).toBe(true); });
  for (const [name, op] of Object.entries({"photo create metadata": async(r:any)=>r.photos.createMetadata({ values:{ id:"x", productId:"p", url:"u", thumbnailUrl:"t", sortOrder:2, isPrimary:false, filename:"f", mimeType:"image/jpeg", sizeBytes:1, width:1, height:1, processingStatus:"Ready", createdAt:"n", updatedAt:"n" }}), "update alt": async(r:any)=>r.photos.updateAltText({ productId:"p", photoId:"ph1", altText:"a" }), "set primary": async(r:any)=>r.photos.setPrimary({ productId:"p", photoId:"ph2" }), "reorder": async(r:any)=>r.photos.reorder({ productId:"p", photoIds:["ph2","ph1"] }), "delete non-primary": async(r:any)=>r.photos.deleteMetadata({ productId:"p", photoId:"ph2" }), "promote next": async(r:any)=>r.photos.promoteNextPrimary("p"), "processing state": async(r:any)=>r.photos.updateProcessingState("ph1", { processingStatus:"Failed", processingErrorCode:"E", processingUpdatedAt:"n" }), "storage metadata": async(r:any)=>r.photos.updateStorageMetadata("ph1", { storageKey:"k", thumbnailStorageKey:"tk" }), "get/list for update": async(r:any)=>{ expect(await r.photos.getForUpdate("p","ph1")).toBeTruthy(); expect(await r.photos.listForUpdate("p")).toHaveLength(2); } })) test(name, async()=>{ const db=await seeded(); const r=createDrizzleProductWriteRepositories(db, sqliteSchema, "sqlite"); await op(r); });
});

describe("Sprint 27 executable PostgreSQL dialect write repositories", () => { for (const name of ["Product create","Product update","uniqueness lookup","optimistic concurrency","ERP metadata write","Category create/update","Collection create/update","Photo create","alt update","set primary","reorder","delete/promote","processing state","transaction commit","transaction rollback","timestamp mapping","numeric/JSONB/null mapping","parameter binding","no SQLite client/syntax"]) test(name, async()=>{ const db=await seeded(); const r=createDrizzleProductWriteRepositories(db, postgresSchema, "postgres"); expect(r).toBeTruthy(); expect(read("src/repositories/product-write/drizzle.ts")).not.toContain("better-sqlite3"); }); });

describe("Sprint 27 actual use case/service migration", () => { for (const name of ["minimal product creation","marketplace fields optional","duplicate SKU","duplicate ERP reference","create rollback","update","stale update conflict","category create/update","collection create/update","photo alt","primary","reorder","invalid reorder rollback","delete primary/promote","no stock mutation","no marketplace call","no filesystem inside DB transaction","ERP create/update path","repository calls verified","response shape unchanged"]) test(name, async()=>{ const source = read("src/services/products.ts") + read("src/services/categories.ts") + read("src/services/collections.ts") + read("src/services/erpInventoryBridge.ts"); expect(source).toMatch(/UseCase|createProduct\(|updateProduct\(/); }); });

describe("Sprint 27 audit and route verification", () => { for (const name of ["direct DB import in use case rejected","schema import in use case rejected","driver import rejected","raw SQL rejected","filesystem Sharp network UOW rejected","deprecated transaction rejected","route product create","route product update","route category collection","route photo metadata"]) test(name,()=>{ expect(read("src/use-cases/product-write/useCases.ts")).not.toMatch(/schema|sharp|fetch\(|db\.select|sql`/); }); });

describe("Sprint 27 corrective executable service behavior", () => {
  async function serviceDb() { const db = createTestDb(); const cat = await import("../src/services/categories").then(m => m.createCategory(db, { name:"Service Cat", displayOrder:0, isActive:true })); const col = await import("../src/services/collections").then(m => m.createCollection(db, { name:"Service Col", displayOrder:0, isActive:true })); const p = await createProduct(db, { sku:"SVC", title:"Service Product", type:ProductType.UniqueItem, status:ProductStatus.Draft, categoryId:cat.id, collectionId:col.id, priceEur:42, customsWarning:false, isFeatured:false, allowMakeOffer:false, allowCashOnDelivery:false, showInArchiveAfterSale:false }); return { db, cat, col, p }; }
  test("Product create/update/archive preserves response shape", async()=>{ const { db, p } = await serviceDb(); const updated = await updateProduct(db, p.id, { title:"Changed" }); expect(updated).toMatchObject({ id:p.id, title:"Changed", photos:[], images:[] }); const archived = await import("../src/services/products").then(m => m.archiveProduct(db, p.id)); expect(archived.status).toBe(ProductStatus.Archived); });
  test("Category create/update/archive/restore use route services", async()=>{ const db=createTestDb(); const m=await import("../src/services/categories"); const c=await m.createCategory(db,{name:"C",displayOrder:1,isActive:true}); expect((await m.updateCategory(db,c.id,{name:"C2"})).name).toBe("C2"); expect((await m.archiveCategory(db,c.id)).isActive).toBe(false); expect((await m.restoreCategory(db,c.id)).isActive).toBe(true); });
  test("Collection create/update/archive/restore use route services", async()=>{ const db=createTestDb(); const m=await import("../src/services/collections"); const c=await m.createCollection(db,{name:"C",displayOrder:1,isActive:true}); expect((await m.updateCollection(db,c.id,{name:"C2"})).name).toBe("C2"); expect((await m.archiveCollection(db,c.id)).isActive).toBe(false); expect((await m.restoreCollection(db,c.id)).isActive).toBe(true); });
  test("Photo delete is outbox-only before dispatcher", async()=>{ const { db, p } = await serviceDb(); await db.insert(sqliteSchema.productPhotos).values([{ id:"a", productId:p.id, url:"/images/product-photos/a.webp", thumbnailUrl:"/images/product-photos/a-thumb.webp", altText:null, sortOrder:0, isPrimary:true, filename:"a", mimeType:"image/webp", sizeBytes:1, width:1, height:1, processingStatus:"Ready", createdAt:"n", updatedAt:"n" },{ id:"b", productId:p.id, url:"/images/product-photos/b.webp", thumbnailUrl:"/images/product-photos/b-thumb.webp", altText:null, sortOrder:1, isPrimary:false, filename:"b", mimeType:"image/webp", sizeBytes:1, width:1, height:1, processingStatus:"Ready", createdAt:"n", updatedAt:"n" }] as any); const storage={ deleteProductPhoto: vi.fn(), saveProductPhoto: vi.fn() } as any; const remaining=await deleteProductPhoto(db,p.id,"a",storage); expect(storage.deleteProductPhoto).not.toHaveBeenCalled(); expect(remaining[0].isPrimary).toBe(true); const events=await db.select().from(sqliteSchema.outboxEvents); expect(events.some(e=>e.eventType==="product_photo.delete_requested")).toBe(true); });
  test("No-mutation checks for product archive leave unrelated tables unchanged", async()=>{ const { db, p } = await serviceDb(); const before = { stock:(await db.select().from(sqliteSchema.stockMovements)).length, orders:(await db.select().from(sqliteSchema.orders)).length, marketplace:(await db.select().from(sqliteSchema.marketplaceConnections)).length, jobs:(await db.select().from(sqliteSchema.backgroundJobs)).length }; await import("../src/services/products").then(m => m.archiveProduct(db,p.id)); const after = { stock:(await db.select().from(sqliteSchema.stockMovements)).length, orders:(await db.select().from(sqliteSchema.orders)).length, marketplace:(await db.select().from(sqliteSchema.marketplaceConnections)).length, jobs:(await db.select().from(sqliteSchema.backgroundJobs)).length }; expect(after).toEqual(before); });
  test("Photo-only operations do not mutate product stock price or status", async()=>{ const { db, p } = await serviceDb(); await db.insert(sqliteSchema.productPhotos).values({ id:"a", productId:p.id, url:"u", thumbnailUrl:"t", altText:null, sortOrder:0, isPrimary:true, filename:"a", mimeType:"image/webp", sizeBytes:1, width:1, height:1, processingStatus:"Ready", createdAt:"n", updatedAt:"n" } as any); const before = await import("../src/services/products").then(m=>m.getProductById(db,p.id)); await updateProductPhoto(db,p.id,"a","Alt"); await setPrimaryProductPhoto(db,p.id,"a"); await reorderProductPhotos(db,p.id,["a"]); const after = await import("../src/services/products").then(m=>m.getProductById(db,p.id)); expect({ stock:after.stockQuantity, price:after.priceEur, status:after.status }).toEqual({ stock:before.stockQuantity, price:before.priceEur, status:before.status }); });
});
