import {describe,it,expect} from "vitest";
import {auditPurchaseUseCaseSource,runPurchaseUseCaseAudit} from "../src/scripts/purchaseUseCaseAudit";
describe("Purchase use case audit Sprint 32A-P3",()=>{
it("production audit passes",()=>expect(runPurchaseUseCaseAudit().status).toBe("PASS"));
it("SQL fixture fails",()=>expect(auditPurchaseUseCaseSource("sql`select 1`").issues).toContain("SQL"));
it("schema fixture fails",()=>expect(auditPurchaseUseCaseSource("from '../../db/schema'").issues).toContain("schema"));
it("DbClient fixture fails",()=>expect(auditPurchaseUseCaseSource("type X=DbClient").issues).toContain("DbClient"));
it("Drizzle fixture fails",()=>expect(auditPurchaseUseCaseSource("drizzle-orm").issues).toContain("Drizzle"));
it("implementation import fixture fails",()=>expect(auditPurchaseUseCaseSource("repositories/purchase/sqlite").issues).toContain("repository implementation"));
it("route fixture fails",()=>expect(auditPurchaseUseCaseSource("routes/erp").issues).toContain("routes"));
it("controller fixture fails",()=>expect(auditPurchaseUseCaseSource("controllers/purchase").issues).toContain("controllers"));
it("HTTP fixture fails",()=>expect(auditPurchaseUseCaseSource("fetch('/x')").issues).toContain("HTTP"));
it("axios fixture fails",()=>expect(auditPurchaseUseCaseSource("axios.get('/x')").issues).toContain("HTTP"));
it("provider SDK fixture fails",()=>expect(auditPurchaseUseCaseSource("stripe").issues).toContain("provider SDK"));
it("marketplace SDK fixture fails",()=>expect(auditPurchaseUseCaseSource("ebay sdk").issues).toContain("marketplace SDK"));
it("AI SDK fixture fails",()=>expect(auditPurchaseUseCaseSource("openai").issues).toContain("AI SDK"));
it("environment loading fixture fails",()=>expect(auditPurchaseUseCaseSource("process.env.X").issues).toContain("environment loading"));
it("direct Inventory repository fixture fails",()=>expect(auditPurchaseUseCaseSource("repositories/inventory").issues).toContain("direct Inventory repository"));
it("direct stock update fixture fails",()=>expect(auditPurchaseUseCaseSource("stock table").issues).toContain("direct stock update"));
it("manual transaction fixture fails",()=>expect(auditPurchaseUseCaseSource("db.transaction(() => {})").issues).toContain("manual transaction"));
it("commit fixture fails",()=>expect(auditPurchaseUseCaseSource("commit()").issues).toContain("manual transaction"));
it("rollback fixture fails",()=>expect(auditPurchaseUseCaseSource("rollback()").issues).toContain("manual transaction"));
it("Date.now fixture fails",()=>expect(auditPurchaseUseCaseSource("Date.now()").issues).toContain("Date.now"));
it("randomUUID fixture fails",()=>expect(auditPurchaseUseCaseSource("randomUUID()").issues).toContain("randomUUID"));
it("Math.random fixture fails",()=>expect(auditPurchaseUseCaseSource("Math.random()").issues).toContain("Math.random"));
it("EventEmitter fixture fails",()=>expect(auditPurchaseUseCaseSource("new EventEmitter()").issues).toContain("EventEmitter"));
it("queue fixture fails",()=>expect(auditPurchaseUseCaseSource("queue.add(x)").issues).toContain("queue"));
it("worker fixture fails",()=>expect(auditPurchaseUseCaseSource("worker process").issues).toContain("queue"));
it("webhook fixture fails",()=>expect(auditPurchaseUseCaseSource("webhook").issues).toContain("webhook"));
it("generic patch fixture fails",()=>expect(auditPurchaseUseCaseSource("Record<string, unknown>").issues).toContain("generic patch"));
it("allowed context passes",()=>expect(auditPurchaseUseCaseSource("PurchaseApplicationContext unitOfWork repository contracts clock idGenerator").status).toBe("PASS"));
it("event publication fixture fails",()=>expect(auditPurchaseUseCaseSource("publish(event)").issues).toContain("event publication"));
it("stock movement table fixture fails",()=>expect(auditPurchaseUseCaseSource("insert into stock_movements").issues).toContain("SQL"));
it("repository factory fixture fails",()=>expect(auditPurchaseUseCaseSource("createPurchaseRepositories()").issues).toContain("repository implementation"));
it("response fixture fails",()=>expect(auditPurchaseUseCaseSource("Response").issues).toContain("HTTP"));
it("request fixture fails",()=>expect(auditPurchaseUseCaseSource("Request").issues).toContain("HTTP"));
});
