import { describe,it,expect } from "vitest"; import Database from "better-sqlite3"; import { drizzle } from "drizzle-orm/better-sqlite3"; import { ensureSchema } from "../src/db/migrate"; import { createPurchaseRepositoriesForDb } from "../src/repositories/purchase/factory";
function repo(){const raw=new Database(":memory:"); ensureSchema(raw); return {raw,r:createPurchaseRepositoriesForDb(drizzle(raw),"sqlite")};} const now="2026-01-01T00:00:00.000Z";
function purchase(id="p1"){return{id,erpReferenceId:`erp-${id}`,supplierId:null,sourceType:"Other",externalReference:`ext-${id}`,invoiceReferenceNumber:null,auctionHouse:null,auctionDate:null,currency:"EUR" as const,itemSubtotal:20,buyerPremium:null,shippingCost:null,customsCost:null,packagingCost:null,taxVat:null,miscellaneousCost:null,totalCost:20,status:"Draft",orderedAt:null,receivedAt:null,notes:null,createdAt:now,updatedAt:now,lines:[{id:`l-${id}`,productId:null,sourceLineReference:null,titleSnapshot:"Free text",quantity:2,receivedQuantity:0,unitPurchaseCost:10,weight:null,manualAllocatedCost:null,createdAt:now,updatedAt:now}]};}
function supplier(id="s1"){return{id,erpReferenceId:`code-${id}`,name:"Supplier",normalizedName:"supplier",supplierType:"Other",countryCode:null,city:null,email:null,phone:null,website:null,taxNumber:null,notes:null,status:"Active",createdAt:now,updatedAt:now};}
const cases=[
["create minimum valid purchase",(r:any)=>expect(r.purchases.create(purchase()).id).toBe("p1")],
["find by ID",(r:any)=>{r.purchases.create(purchase());expect(r.purchases.findById("p1")?.id).toBe("p1")}],
["find by reference",(r:any)=>{r.purchases.create(purchase());expect(r.purchases.findByReference("erp-p1")?.id).toBe("p1")}],
["not found null",(r:any)=>expect(r.purchases.findById("missing")).toBeNull()],
["exists by reference",(r:any)=>{r.purchases.create(purchase());expect(r.purchases.existsByReference("ext-p1")).toBe(true)}],
["optional supplier",(r:any)=>expect(r.purchases.create(purchase()).supplierId).toBeNull()],
["optional product reference",(r:any)=>expect(r.purchases.create(purchase()).lines[0].productId).toBeNull()],
["EUR persistence",(r:any)=>expect(r.purchases.create(purchase()).currency).toBe("EUR")],
["money mapping",(r:any)=>expect(r.purchases.create(purchase()).itemSubtotal).toBe(20)],
["list ordering",(r:any)=>{r.purchases.create(purchase("a"));r.purchases.create({...purchase("b"),createdAt:"2026-01-02",updatedAt:"2026-01-02"});expect(r.purchases.list().rows[0].id).toBe("b")}],
["optional dates",(r:any)=>expect(r.purchases.create(purchase()).orderedAt).toBeNull()],
["notes mapping",(r:any)=>expect(r.purchases.create({...purchase(),notes:"n"}).notes).toBe("n")],
["line order",(r:any)=>{const p=purchase();p.lines=[p.lines[0],{...p.lines[0],id:"l2",titleSnapshot:"Second"}];expect(r.purchases.create(p).lines.map((l:any)=>l.id)).toEqual(["l-p1","l2"])}],
["quantity mapping",(r:any)=>expect(r.purchases.create(purchase()).lines[0].quantity).toBe(2)],
["unit cost mapping",(r:any)=>expect(r.purchases.create(purchase()).lines[0].unitPurchaseCost).toBe(10)],
["received quantity mapping",(r:any)=>expect(r.purchases.create(purchase()).lines[0].receivedQuantity).toBe(0)],
["free text line",(r:any)=>expect(r.purchases.create(purchase()).lines[0].titleSnapshot).toBe("Free text")],
["add line",(r:any)=>{r.purchases.create(purchase());expect(r.purchases.addLine({...(purchase().lines[0] as any),id:"l2",purchaseId:"p1"}).id).toBe("l2")}],
["update line",(r:any)=>{r.purchases.create(purchase());expect(r.purchases.updateLine("l-p1",{receivedQuantity:1})?.receivedQuantity).toBe(1)}],
["remove line",(r:any)=>{r.purchases.create(purchase());expect(r.purchases.removeLine("l-p1")).toBe(true)}],
["status persists",(r:any)=>expect(r.purchases.create({...purchase(),status:"Received"}).status).toBe("Received")],
["no transition validation",(r:any)=>expect(r.purchases.create({...purchase(),status:"Cancelled"}).status).toBe("Cancelled")],
["update purchase",(r:any)=>{r.purchases.create(purchase());expect(r.purchases.update("p1",{notes:"u",updatedAt:"v2"})?.notes).toBe("u")}],
["valid version update",(r:any)=>{r.purchases.create(purchase());expect(r.purchases.updateWithVersion("p1",now,{notes:"v",updatedAt:"v2"}).ok).toBe(true)}],
["stale version failure",(r:any)=>{r.purchases.create(purchase());expect(r.purchases.updateWithVersion("p1","old",{notes:"v",updatedAt:"v2"}).ok).toBe(false)}],
["supplier create",(r:any)=>expect(r.suppliers.create(supplier()).id).toBe("s1")],
["supplier find",(r:any)=>{r.suppliers.create(supplier());expect(r.suppliers.findById("s1")?.id).toBe("s1")}],
["supplier code",(r:any)=>{r.suppliers.create(supplier());expect(r.suppliers.findByCode("code-s1")?.id).toBe("s1")}],
["supplier name",(r:any)=>{r.suppliers.create(supplier());expect(r.suppliers.findByName("supplier")).toHaveLength(1)}],
["supplier list",(r:any)=>{r.suppliers.create(supplier());expect(r.suppliers.list()[0].id).toBe("s1")}],
["supplier optional fields",(r:any)=>expect(r.suppliers.create(supplier()).email).toBeNull()],
["supplier update",(r:any)=>{r.suppliers.create(supplier());expect(r.suppliers.update("s1",{notes:"n",updatedAt:"v2"})?.notes).toBe("n")}],
["supplier stale",(r:any)=>{r.suppliers.create(supplier());expect(r.suppliers.updateWithVersion("s1","bad",{notes:"n",updatedAt:"v2"}).ok).toBe(false)}],
["supplier not found",(r:any)=>expect(r.suppliers.findById("x")).toBeNull()],
["append receipt",(r:any)=>{r.purchases.create(purchase());expect(r.receipts.append({id:"rec1",purchaseId:"p1",idempotencyKey:"k1",receivedAt:now,note:null,createdAt:now,lines:[{id:"rl1",receiptId:"rec1",purchaseLineId:"l-p1",quantityReceived:1,stockMovementId:null,createdAt:now}]}).id).toBe("rec1")}],
["find receipt",(r:any)=>{r.purchases.create(purchase());r.receipts.append({id:"rec1",purchaseId:"p1",idempotencyKey:"k1",receivedAt:now,note:null,createdAt:now,lines:[]});expect(r.receipts.findById("rec1")?.id).toBe("rec1")}],
["receipt by purchase",(r:any)=>{r.purchases.create(purchase());r.receipts.append({id:"rec1",purchaseId:"p1",idempotencyKey:"k1",receivedAt:now,note:null,createdAt:now,lines:[]});expect(r.receipts.listByPurchase("p1")).toHaveLength(1)}],
["receipt by line",(r:any)=>{r.purchases.create(purchase());r.receipts.append({id:"rec1",purchaseId:"p1",idempotencyKey:"k1",receivedAt:now,note:null,createdAt:now,lines:[{id:"rl1",receiptId:"rec1",purchaseLineId:"l-p1",quantityReceived:1,stockMovementId:null,createdAt:now}]});expect(r.receipts.listByPurchaseLine("l-p1")).toHaveLength(1)}],
["receipt idempotency",(r:any)=>{r.receipts.append({id:"rec1",purchaseId:"p1",idempotencyKey:"k1",receivedAt:now,note:null,createdAt:now,lines:[]});expect(r.receipts.findByIdempotencyKey("k1")?.id).toBe("rec1")}],
["receipt reference",(r:any)=>{r.purchases.create(purchase());r.receipts.append({id:"rec1",purchaseId:"p1",idempotencyKey:"k1",receivedAt:now,note:null,createdAt:now,lines:[]});expect(r.receipts.listByReference("erp-p1")).toHaveLength(1)}],
["receipt no update API",(r:any)=>expect("update" in r.receipts).toBe(false)],
["receipt no delete API",(r:any)=>expect("delete" in r.receipts).toBe(false)],
["no inventory API",(r:any)=>expect("stock" in r.purchases).toBe(false)],
["no event API",(r:any)=>expect("events" in r.purchases).toBe(false)],
["no raw query",(r:any)=>expect("rawQuery" in r.purchases).toBe(false)],
["no transaction",(r:any)=>expect("transaction" in r.purchases).toBe(false)],
["factory unsupported",()=>expect(()=>createPurchaseRepositoriesForDb({},"bad" as any)).toThrow(/UNSUPPORTED/)],
["factory requires db",()=>expect(()=>createPurchaseRepositoriesForDb(null as any,"sqlite")).toThrow(/REQUIRED/)],
["line missing update null",(r:any)=>expect(r.purchases.updateLine("x",{updatedAt:"z"})).toBeNull()],
["line missing remove false",(r:any)=>expect(r.purchases.removeLine("x")).toBe(false)],
["purchase missing update null",(r:any)=>expect(r.purchases.update("x",{updatedAt:"z"})).toBeNull()],
["supplier missing update null",(r:any)=>expect(r.suppliers.update("x",{updatedAt:"z"})).toBeNull()],
["same behavior postgres factory",()=>{const {raw}=repo();expect(createPurchaseRepositoriesForDb(drizzle(raw),"postgres").purchases.findById("x")).toBeNull()}]
];
describe("purchase repository Sprint 32A-P1",()=>{ for(const [name,fn] of cases) it(name,()=>{const x=repo(); try{(fn as any)(x.r)} finally{x.raw.close();}}); });
