import { describe, expect, it } from "vitest";
import { auditRefundProviderBoundary } from "../src/scripts/refundProviderBoundaryAudit";
import { normalizeRefundProviderError, toProviderResult, unsupportedRefundCapability, type RefundExecutionRequest, type RefundProviderRetryableFailureResult, type RefundProviderTerminalFailureResult, type RefundProviderSuccessResult } from "../src/providers/refund";
import { FakeMarketplaceRefundProvider, FakePaymentRefundProvider } from "../src/providers/refund/testing/fakes";

describe("refund provider boundary Sprint 30B-R5", () => {
 const req: RefundExecutionRequest = Object.freeze({refundId:"r1",orderId:"o1",amount:12.34,currency:"EUR",idempotencyKey:"idem",reason:"return",items:Object.freeze([{id:"i1",amount:12.34,quantity:1}]),metadata:Object.freeze({safe:true})});
 it("success result shape",()=>{const r:RefundProviderSuccessResult={outcome:"success",externalRefundId:"ext",providerStatus:"succeeded",processedAt:"now",metadata:{a:"b"}};expect(r.externalRefundId).toBe("ext")});
 it("retryable result shape",()=>{const r:RefundProviderRetryableFailureResult={outcome:"retryable_failure",code:"RATE",message:"later",retryAfter:5,providerStatus:"429"};expect(r.retryAfter).toBe(5)});
 it("terminal result shape",()=>{const r:RefundProviderTerminalFailureResult={outcome:"terminal_failure",code:"DECLINED",message:"no"};expect(r.code).toBe("DECLINED")});
 it("request contains no credentials",()=>expect(JSON.stringify(req)).not.toMatch(/secret|token|credential|card/i));
 it("readonly-safe metadata",()=>expect(Object.isFrozen(req.metadata)).toBe(true));
 it("currency and amount preserved",()=>expect([req.currency,req.amount]).toEqual(["EUR",12.34]));
 it("idempotency key preserved",()=>expect(req.idempotencyKey).toBe("idem"));
 it("legacy success normalizes",()=>expect(toProviderResult({providerRefundId:"x",status:"ok"})).toMatchObject({outcome:"success",externalRefundId:"x"}));
 it("marketplace execute success",async()=>expect(await new FakeMarketplaceRefundProvider().executeRefund(req)).toMatchObject({outcome:"success"}));
 it("marketplace execute retryable failure",async()=>expect(await new FakeMarketplaceRefundProvider({executeResult:{outcome:"retryable_failure",code:"R",message:"retry"}}).executeRefund(req)).toMatchObject({outcome:"retryable_failure"}));
 it("marketplace execute terminal failure",async()=>expect(await new FakeMarketplaceRefundProvider({executeResult:{outcome:"terminal_failure",code:"T",message:"term"}}).executeRefund(req)).toMatchObject({outcome:"terminal_failure"}));
 it("marketplace cancel supported",async()=>expect(await new FakeMarketplaceRefundProvider({capabilities:{supportsCancelRefund:true}}).cancelRefund({refundId:"r"})).toMatchObject({providerStatus:"cancelled"}));
 it("marketplace cancel unsupported",async()=>await expect(new FakeMarketplaceRefundProvider().cancelRefund({refundId:"r"})).rejects.toMatchObject({code:"UNSUPPORTED_PROVIDER_CAPABILITY"}));
 it("marketplace status supported",async()=>expect(await new FakeMarketplaceRefundProvider({capabilities:{supportsRefundStatus:true}}).getRefundStatus({refundId:"r"})).toMatchObject({providerStatus:"unknown"}));
 it("marketplace status unsupported",async()=>await expect(new FakeMarketplaceRefundProvider().getRefundStatus({refundId:"r"})).rejects.toThrow(/does not support/));
 it("marketplace call recording",async()=>{const p=new FakeMarketplaceRefundProvider();await p.executeRefund(req);expect(p.calls[0]).toMatchObject({operation:"execute"});});
 it("no raw marketplace error leakage",()=>expect(normalizeRefundProviderError(Object.assign(Error("Bearer abc"),{retryable:false}))).not.toHaveProperty("stack"));
 it("payment execute success",async()=>expect(await new FakePaymentRefundProvider().executeRefund(req)).toMatchObject({outcome:"success"}));
 it("payment execute retryable failure",async()=>expect(await new FakePaymentRefundProvider({executeResult:{outcome:"retryable_failure",code:"R",message:"retry"}}).executeRefund(req)).toMatchObject({outcome:"retryable_failure"}));
 it("payment execute terminal failure",async()=>expect(await new FakePaymentRefundProvider({executeResult:{outcome:"terminal_failure",code:"T",message:"term"}}).executeRefund(req)).toMatchObject({outcome:"terminal_failure"}));
 it("payment cancel supported",async()=>expect(await new FakePaymentRefundProvider({capabilities:{supportsCancelRefund:true}}).cancelRefund({refundId:"r"})).toMatchObject({providerStatus:"cancelled"}));
 it("payment status supported",async()=>expect(await new FakePaymentRefundProvider({capabilities:{supportsRefundStatus:true}}).getRefundStatus({refundId:"r"})).toMatchObject({providerStatus:"unknown"}));
 it("payment idempotency preserved",async()=>{const p=new FakePaymentRefundProvider();await p.executeRefund(req);expect((p.calls[0].request as any).idempotencyKey).toBe("idem")});
 it("no raw payment error leakage",()=>expect(normalizeRefundProviderError({message:"access_token abc",retryable:true})).toMatchObject({outcome:"retryable_failure"}));
 it("unsupported capability helper",()=>expect(unsupportedRefundCapability("executeRefund","x")).toMatchObject({code:"UNSUPPORTED_PROVIDER_CAPABILITY"}));
 it("production provider boundary passes",()=>expect(auditRefundProviderBoundary()).toBe(true));
 it("DB import fixture fails",()=>expect(()=>auditRefundProviderBoundary({bad:"import '../db/schema'"})).toThrow(/DB/));
 it("SDK import fixture fails",()=>expect(()=>auditRefundProviderBoundary({bad:"import Stripe from 'stripe'"})).toThrow(/SDK/));
 it("HTTP fixture fails",()=>expect(()=>auditRefundProviderBoundary({bad:"fetch('https://x')"})).toThrow(/HTTP/));
 it("credential env fixture fails",()=>expect(()=>auditRefundProviderBoundary({bad:"process.env.SECRET"})).toThrow(/credential/));
 it("UnitOfWork fixture fails",()=>expect(()=>auditRefundProviderBoundary({bad:"UnitOfWork"})).toThrow(/UnitOfWork/));
});
