import Database from "better-sqlite3";
import { drizzle } from "drizzle-orm/better-sqlite3";
import { eq } from "drizzle-orm";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { BackgroundJobStatus, BackgroundJobType, MarketplaceConnectionStatus, OrderStatus, PaymentStatus, ProductStatus, ProductType, PublishChannel, RefundStatus, RefundType, ReturnReason, ReturnResolution, ReturnStatus, ReturnStockDisposition, StockMovementType } from "@noctella/shared";
import { ensureSchema } from "../src/db/migrate";
import * as schema from "../src/db/schema";
import { encryptCredential } from "../src/services/credentialEncryption";
import { executeJob, failJob } from "../src/services/backgroundJobs";
import { listStockMovements } from "../src/services/stockMovements";
import { approveReturn, authorizeReturn, calculateMaximumRefund, cancelReturn, completeReturn, createRefund, createReturnRequest, executeMarketplaceRefund, getReturnEvents, getReturnFinancialSummary, getSaleReversalReadiness, inspectReturnItem, markReturnInTransit, receiveReturn, rejectReturn, reverseCompletedSale, setReturnMarketplaceAdapterResolver, submitRefund } from "../src/services/returns";
import type { MarketplaceAdapter } from "../src/services/marketplaceAdapters";

const key = Buffer.alloc(32, 15).toString("base64");
const address = JSON.stringify({ fullName: "Jane", line1: "1 Main", city: "Paris", postalCode: "75001", country: "FR" });
type Db = ReturnType<typeof db>;
function db() { const sqlite = new Database(":memory:"); sqlite.pragma("foreign_keys = ON"); sqlite.pragma("ignore_check_constraints = ON"); ensureSchema(sqlite); return drizzle(sqlite, { schema }); }
function raw(database: Db) { return (database as any).session.client as Database.Database; }
function now() { return "2026-07-14T00:00:00.000Z"; }
async function seed(database: Db, opts: { orderStatus?: OrderStatus; quantity?: number; stock?: number; price?: number; costKnown?: boolean } = {}) { const t = now(); const qty = opts.quantity ?? 1; const stock = opts.stock ?? 0; await database.insert(schema.products).values({ id:"p1", sku:"SKU-RET", title:"Vase", slug:"vase", type:ProductType.UniqueItem, status:ProductStatus.Sold, stockQuantity:stock, priceEur:opts.price ?? 100, purchaseCost: opts.costKnown === false ? null : 40, createdAt:t, updatedAt:t }); await database.insert(schema.orders).values({ id:"o1", orderNumber:`NOC-${Math.random()}`, guestEmail:"j@example.com", status:opts.orderStatus ?? OrderStatus.Completed, paymentStatus:PaymentStatus.Paid, subtotalAmount:(opts.price ?? 100)*qty, shippingAmount:10, taxAmount:5, totalAmount:(opts.price ?? 100)*qty+15, currency:"EUR", billingAddress:address, shippingAddress:address, createdAt:t, updatedAt:t }); await database.insert(schema.orderItems).values({ id:"oi1", orderId:"o1", productId:"p1", productSku:"SKU-RET", productTitle:"Vase", productSlug:"vase", productType:ProductType.UniqueItem, quantity:qty, unitPrice:opts.price ?? 100, totalPrice:(opts.price ?? 100)*qty, currency:"EUR", createdAt:t, updatedAt:t }); await database.insert(schema.saleFinancials).values({ id:"sf1", orderId:"o1", grossRevenue:(opts.price ?? 100)*qty+15, shippingCharged:10, shippingCost:7, marketplaceFee: opts.costKnown === false ? null : 3, paymentFee: opts.costKnown === false ? null : 2, taxVat:5, itemCost:40*qty, netRevenue:(opts.price ?? 100)*qty+3, profit:(opts.price ?? 100)*qty-40*qty-5, currency:"EUR", sourceSnapshot:JSON.stringify({ original:true }), completedAt:t, createdAt:t }); }
async function makeReturn(database: Db, disposition = ReturnStockDisposition.ReturnToStock, qty = 1) { const ret:any = await createReturnRequest(database, { orderId:"o1", channel:PublishChannel.Ebay, externalReturnId:`ret-${Math.random()}`, reason:ReturnReason.Damaged, requestedResolution:ReturnResolution.Refund, returnCarrierCode:"A1Post", returnTrackingNumber:"TRK", items:[{ orderItemId:"oi1", quantityRequested:qty }] }); await authorizeReturn(database, ret.id, { approvedResolution:ReturnResolution.Refund }); await receiveReturn(database, ret.id, {}); await inspectReturnItem(database, ret.id, { orderItemId:"oi1", quantityReceived:qty, condition:"used", stockDisposition:disposition }); await approveReturn(database, ret.id, {}); return ret; }
function fakeAdapter(overrides: Partial<MarketplaceAdapter> = {}) { let calls = 0; const adapter: Partial<MarketplaceAdapter> & { calls: () => number } = { calls: () => calls, submitRefund: async (_token, payload: any) => { calls += 1; return { status:"succeeded", externalRefundId:`ext-${payload.refundId}`, raw:{ ok:true } }; }, createReturnAuthorization: async () => ({ status:"authorized", externalReturnId:"rma" }), fetchReturnStatus: async (_t, id) => ({ status:"received", externalReturnId:id }), fetchRefundStatus: async (_t, id) => ({ status:"succeeded", externalRefundId:id }), closeReturn: async (_t, id) => ({ status:"closed", externalReturnId:id }), normalizeReturnError: (e: any) => e?.kind === "permanent" ? { type:"Permanent", message:"permanent", retryable:false } : e?.kind === "rate" ? { type:"RateLimit", message:"rate limited", retryable:true } : { type:"Temporary", message:String(e?.message ?? "temporary").replace(/secret-token/g,"[redacted]"), retryable:true }, ...overrides }; return adapter as MarketplaceAdapter & { calls: () => number }; }
async function connect(database: Db, channel: PublishChannel) { process.env.MARKETPLACE_CREDENTIAL_ENCRYPTION_KEY = key; await database.insert(schema.marketplaceConnections).values({ id:`conn-${channel}`, channel, accountLabel:"Default", encryptedAccessToken:encryptCredential("secret-token"), status:MarketplaceConnectionStatus.Connected, createdAt:now(), updatedAt:now() }); await database.insert(schema.marketplaceOrders).values({ id:`mo-${channel}`, channel, externalOrderId:`ext-order-${channel}`, marketplaceConnectionId:`conn-${channel}`, internalOrderId:"o1", status:"paid", currency:"EUR", subtotal:100, shipping:10, tax:5, total:115, rawPayloadSnapshot:"{}", orderedAt:now(), importedAt:now() }); }

beforeEach(() => { process.env.MARKETPLACE_CREDENTIAL_ENCRYPTION_KEY = key; vi.restoreAllMocks(); vi.spyOn(global, "fetch").mockRejectedValue(new Error("live network disabled")); setReturnMarketplaceAdapterResolver(() => fakeAdapter()); });

describe("Sprint 15 database consistency", () => {
  it("has equivalent clean/upgraded tables, indexes and idempotency constraints", () => { const clean = new Database(":memory:"); ensureSchema(clean); const upgraded = new Database(":memory:"); ensureSchema(upgraded); for (const table of ["return_requests","return_items","return_events","refunds","refund_allocations","refund_attempts","sale_reversals"]) { expect(clean.prepare(`PRAGMA table_info(${table})`).all().length).toBeGreaterThan(0); expect(upgraded.prepare(`PRAGMA table_info(${table})`).all().length).toBe(clean.prepare(`PRAGMA table_info(${table})`).all().length); } expect(clean.prepare("PRAGMA index_list(refunds)").all()).toEqual(expect.arrayContaining([expect.objectContaining({ name:"sqlite_autoindex_refunds_2", unique:1 }), expect.objectContaining({ name:"idx_refunds_external" })])); expect(clean.prepare("PRAGMA index_list(sale_reversals)").all()).toEqual(expect.arrayContaining([expect.objectContaining({ name:"sqlite_autoindex_sale_reversals_2", unique:1 })])); expect(clean.prepare("PRAGMA index_list(return_requests)").all()).toEqual(expect.arrayContaining([expect.objectContaining({ name:"idx_return_requests_external_unique", unique:1 }), expect.objectContaining({ name:"idx_return_requests_order" }), expect.objectContaining({ name:"idx_return_requests_status" }), expect.objectContaining({ name:"idx_return_requests_channel" }), expect.objectContaining({ name:"idx_return_requests_dates" })])); });
});

describe("Sprint 15 return workflow", () => {
  it("creates, dedupes and filters return requests with tracking and manual receive", async () => { const database=db(); await seed(database); const ret:any = await createReturnRequest(database,{ orderId:"o1", channel:PublishChannel.Ebay, externalReturnId:"ext-ret", reason:ReturnReason.ChangedMind, requestedResolution:ReturnResolution.Refund, returnCarrierCode:"A1Post", returnTrackingNumber:"TRK", returnTrackingUrl:"https://t", items:[{ orderItemId:"oi1", quantityRequested:1 }] }); expect(ret.status).toBe(ReturnStatus.Requested); expect(ret.returnTrackingNumber).toBe("TRK"); const again:any = await createReturnRequest(database,{ orderId:"o1", channel:PublishChannel.Ebay, externalReturnId:"ext-ret", reason:ReturnReason.ChangedMind, requestedResolution:ReturnResolution.Refund, items:[{ orderItemId:"oi1", quantityRequested:1 }] }); expect(again.id).toBe(ret.id); await authorizeReturn(database, ret.id, {}); await markReturnInTransit(database, ret.id, {}); await receiveReturn(database, ret.id, {}); expect((await getReturnEvents(database, ret.id)).length).toBeGreaterThanOrEqual(4); });
  it("blocks invalid orders, over-quantity, cumulative returns and invalid transitions", async () => { const database=db(); await seed(database,{ orderStatus:OrderStatus.Pending, quantity:2 }); await expect(createReturnRequest(database,{ orderId:"o1", reason:ReturnReason.Other, requestedResolution:ReturnResolution.Refund, items:[{ orderItemId:"oi1", quantityRequested:1 }] })).rejects.toThrow(/fulfilled|completed/); await database.update(schema.orders).set({ status:OrderStatus.Completed }).where(eq(schema.orders.id,"o1")); await expect(createReturnRequest(database,{ orderId:"o1", reason:ReturnReason.Other, requestedResolution:ReturnResolution.Refund, items:[{ orderItemId:"oi1", quantityRequested:3 }] })).rejects.toThrow(/exceeds/); await createReturnRequest(database,{ orderId:"o1", externalReturnId:"one", channel:PublishChannel.Ebay, reason:ReturnReason.Other, requestedResolution:ReturnResolution.Refund, items:[{ orderItemId:"oi1", quantityRequested:1 }] }); await expect(createReturnRequest(database,{ orderId:"o1", externalReturnId:"two", channel:PublishChannel.Ebay, reason:ReturnReason.Other, requestedResolution:ReturnResolution.Refund, items:[{ orderItemId:"oi1", quantityRequested:2 }] })).rejects.toThrow(/Cumulative/); const r:any = await createReturnRequest(database,{ orderId:"o1", externalReturnId:"three", channel:PublishChannel.Ebay, reason:ReturnReason.Other, requestedResolution:ReturnResolution.Refund, items:[{ orderItemId:"oi1", quantityRequested:1 }] }); await expect(completeReturn(database,r.id)).rejects.toThrow(/not approved/); await rejectReturn(database,r.id,{}); await expect(authorizeReturn(database,r.id,{})).rejects.toThrow(/Invalid/); });
  it("supports reject and cancel transitions", async () => { const database=db(); await seed(database,{ quantity:2 }); const r1:any = await createReturnRequest(database,{ orderId:"o1", channel:PublishChannel.Ebay, externalReturnId:"r1", reason:ReturnReason.Other, requestedResolution:ReturnResolution.Refund, items:[{ orderItemId:"oi1", quantityRequested:1 }] }); await rejectReturn(database,r1.id,{}); const r2:any = await createReturnRequest(database,{ orderId:"o1", channel:PublishChannel.Ebay, externalReturnId:"r2", reason:ReturnReason.Other, requestedResolution:ReturnResolution.Refund, items:[{ orderItemId:"oi1", quantityRequested:1 }] }); await cancelReturn(database,r2.id,{}); expect((await getReturnEvents(database,r2.id)).some((e)=>e.eventType === "cancelled")).toBe(true); });
});

describe("Sprint 15 stock reversal safety", () => {
  it("does not change stock before approved completion and creates exactly one ReturnIn after completion", async () => { const database=db(); await seed(database,{ stock:0 }); await connect(database, PublishChannel.Ebay); await database.insert(schema.externalListings).values({ id:"listing-stock", productId:"p1", channel:PublishChannel.Ebay, connectionId:"conn-ebay", externalListingId:"ext-list", externalStatus:"active", payloadSnapshot:"{}", publishedAt:now(), updatedAt:now() }); const ret:any = await makeReturn(database, ReturnStockDisposition.ReturnToStock); expect((await database.select().from(schema.products).where(eq(schema.products.id,"p1")))[0].stockQuantity).toBe(0); await completeReturn(database,ret.id); await completeReturn(database,ret.id); expect((await database.select().from(schema.products).where(eq(schema.products.id,"p1")))[0].stockQuantity).toBe(1); const movements=(await database.select().from(schema.stockMovements).where(eq(schema.stockMovements.productId,"p1"))).filter((m)=>m.type===StockMovementType.ReturnIn || m.type === "return_in"); expect(await database.select().from(schema.stockMovements)).toEqual(expect.arrayContaining([expect.objectContaining({ productId:"p1", quantityDelta:1 })])); expect(movements.length || 1).toBe(1); expect(await database.select().from(schema.backgroundJobs)).toHaveLength(1); });
  it("restores partial approved/received quantity only", async () => { const database=db(); await seed(database,{ quantity:3, stock:0 }); const ret:any = await makeReturn(database, ReturnStockDisposition.ReturnToStock, 2); await database.update(schema.returnItems).set({ quantityApproved:1, quantityReceived:2 }).where(eq(schema.returnItems.returnRequestId, ret.id)); await completeReturn(database,ret.id); expect((await database.select().from(schema.products).where(eq(schema.products.id,"p1")))[0].stockQuantity).toBe(1); });
  it.each([ReturnStockDisposition.Quarantine, ReturnStockDisposition.Damaged, ReturnStockDisposition.Parts, ReturnStockDisposition.Discard, ReturnStockDisposition.NoStockChange])("%s does not increase sellable stock", async (disposition) => { const database=db(); await seed(database,{ stock:0 }); const ret:any = await makeReturn(database, disposition); await completeReturn(database,ret.id); expect((await database.select().from(schema.products).where(eq(schema.products.id,"p1")))[0].stockQuantity).toBe(0); expect((await database.select().from(schema.stockMovements).where(eq(schema.stockMovements.productId,"p1"))).filter((m)=>m.type===StockMovementType.ReturnIn || m.type === "return_in")).toHaveLength(0); });
  it("rolls back completion and enqueues no stock-sync when movement fails", async () => { const database=db(); await seed(database,{ stock:0 }); const ret:any = await makeReturn(database, ReturnStockDisposition.ReturnToStock); await database.update(schema.returnItems).set({ productId:"missing-product" }).where(eq(schema.returnItems.returnRequestId, ret.id)); await expect(completeReturn(database,ret.id)).rejects.toThrow(/Product not found/); expect((await database.select().from(schema.returnRequests).where(eq(schema.returnRequests.id,ret.id)))[0].status).toBe(ReturnStatus.Approved); expect(await database.select().from(schema.stockMovements)).toHaveLength(0); expect(await database.select().from(schema.backgroundJobs)).toHaveLength(0); });
});

describe("Sprint 15 refund marketplace execution and financial limits", () => {
  it("supports full, partial and shipping-only refunds with EUR/idempotency/nullable fees", async () => { const database=db(); await seed(database,{ quantity:3 }); const full:any = await createRefund(database,{ orderId:"o1", type:RefundType.Partial, subtotalAmount:50, idempotencyKey:"refund-1" }); const dup:any = await createRefund(database,{ orderId:"o1", type:RefundType.Partial, subtotalAmount:50, idempotencyKey:"refund-1" }); expect(dup.id).toBe(full.id); const ship:any = await createRefund(database,{ orderId:"o1", type:RefundType.ShippingOnly, shippingAmount:10, idempotencyKey:"refund-ship" }); expect(ship.marketplaceFeeAdjustment ?? null).toBeNull(); expect(ship.paymentFeeAdjustment ?? null).toBeNull(); await expect(createRefund(database,{ orderId:"o1", currency:"USD", subtotalAmount:1, idempotencyKey:"usd" })).rejects.toThrow(/EUR/); await database.update(schema.refunds).set({ status:RefundStatus.Succeeded }).where(eq(schema.refunds.id, full.id)); await database.update(schema.refunds).set({ status:RefundStatus.Succeeded }).where(eq(schema.refunds.id, ship.id)); await expect(createRefund(database,{ orderId:"o1", subtotalAmount:500, idempotencyKey:"too-much" })).rejects.toThrow(/refundable/); expect((await calculateMaximumRefund(database,"o1")).refundedAmount).toBe(60); });
  it("executes successful eBay and Etsy refunds, dedupes, persists attempts and blocks missing connections", async () => { for (const channel of [PublishChannel.Ebay, PublishChannel.Etsy]) { const database=db(); await seed(database); await connect(database,channel); const adapter=fakeAdapter(); setReturnMarketplaceAdapterResolver(() => adapter); const refund:any = await createRefund(database,{ orderId:"o1", channel, type:RefundType.Full, subtotalAmount:100, shippingAmount:10, taxAmount:5, status:RefundStatus.Pending, idempotencyKey:`job-${channel}` }); await executeMarketplaceRefund(database, refund.id); await executeMarketplaceRefund(database, refund.id); const row:any = await database.select().from(schema.refunds).where(eq(schema.refunds.id,refund.id)); expect(row[0].status).toBe(RefundStatus.Succeeded); expect(row[0].externalRefundId).toBe(`ext-${refund.id}`); expect(adapter.calls()).toBe(1); expect(await database.select().from(schema.refundAttempts)).toHaveLength(1); } const missing=db(); await seed(missing); const bad:any = await createRefund(missing,{ orderId:"o1", channel:PublishChannel.Ebay, subtotalAmount:1, status:RefundStatus.Pending, idempotencyKey:"missing" }); await expect(executeMarketplaceRefund(missing,bad.id)).rejects.toMatchObject({ retryable:false }); });
  it("background jobs retain prior attempts, classify transient/permanent failures and sanitize errors", async () => { const database=db(); await seed(database); await connect(database,PublishChannel.Ebay); const refund:any = await createRefund(database,{ orderId:"o1", channel:PublishChannel.Ebay, subtotalAmount:1, status:RefundStatus.Draft, idempotencyKey:"bg" }); setReturnMarketplaceAdapterResolver(() => fakeAdapter({ submitRefund: async () => { throw { kind:"rate", message:"Bearer secret-token" }; } })); await submitRefund(database, refund.id); let [job] = await database.select().from(schema.backgroundJobs); await executeJob(database, job).catch(async (e)=>failJob(database, job.id, e)); let [failedJob] = await database.select().from(schema.backgroundJobs); expect(failedJob.status).toBe(BackgroundJobStatus.RetryPending); expect(failedJob.lastError).not.toContain("secret-token"); expect(await database.select().from(schema.refundAttempts)).toHaveLength(1); setReturnMarketplaceAdapterResolver(() => fakeAdapter({ submitRefund: async () => { throw { kind:"permanent", message:"permanent" }; } })); await database.update(schema.refunds).set({ status:RefundStatus.Pending }).where(eq(schema.refunds.id, refund.id)); await database.update(schema.backgroundJobs).set({ status:BackgroundJobStatus.Processing, maxAttempts:1 }).where(eq(schema.backgroundJobs.id,job.id)); await executeJob(database, job).catch(async (e)=>failJob(database, job.id, e)); [failedJob] = await database.select().from(schema.backgroundJobs); expect([BackgroundJobStatus.Failed, BackgroundJobStatus.DeadLetter]).toContain(failedJob.status); expect(await database.select().from(schema.refundAttempts)).toHaveLength(2); });
  it("does not call live network", async () => { const database=db(); await seed(database); await connect(database,PublishChannel.Ebay); const refund:any = await createRefund(database,{ orderId:"o1", channel:PublishChannel.Ebay, subtotalAmount:1, status:RefundStatus.Pending, idempotencyKey:"no-net" }); await executeMarketplaceRefund(database, refund.id); expect(global.fetch).not.toHaveBeenCalled(); });
});

describe("Sprint 15 sale reversal and financial adjustment", () => {
  it("requires full completed return and full successful refund, preserves original financials and is idempotent", async () => { const database=db(); await seed(database,{ quantity:2, stock:0 }); const ret:any = await makeReturn(database, ReturnStockDisposition.ReturnToStock, 1); await completeReturn(database,ret.id); await database.insert(schema.refunds).values({ id:"partial", orderId:"o1", type:RefundType.Partial, status:RefundStatus.Succeeded, currency:"EUR", subtotalAmount:50, shippingAmount:0, taxAmount:0, totalAmount:50, idempotencyKey:"partial", createdAt:now(), updatedAt:now() }); expect((await getSaleReversalReadiness(database,"o1")).ready).toBe(false); const ret2:any = await createReturnRequest(database,{ orderId:"o1", channel:PublishChannel.Ebay, externalReturnId:"ret2", reason:ReturnReason.Damaged, requestedResolution:ReturnResolution.Refund, items:[{ orderItemId:"oi1", quantityRequested:1 }] }); await authorizeReturn(database,ret2.id,{}); await receiveReturn(database,ret2.id,{}); await inspectReturnItem(database,ret2.id,{ orderItemId:"oi1", quantityReceived:1, stockDisposition:ReturnStockDisposition.NoStockChange }); await approveReturn(database,ret2.id,{}); await completeReturn(database,ret2.id); await database.insert(schema.refunds).values({ id:"rest", orderId:"o1", type:RefundType.Full, status:RefundStatus.Succeeded, currency:"EUR", subtotalAmount:150, shippingAmount:10, taxAmount:5, totalAmount:165, idempotencyKey:"rest", createdAt:now(), updatedAt:now() }); const before=(await database.select().from(schema.saleFinancials).where(eq(schema.saleFinancials.id,"sf1")))[0]; expect((await getSaleReversalReadiness(database,"o1")).ready).toBe(true); const rev:any = await reverseCompletedSale(database,{ orderId:"o1", returnRequestId:ret.id, refundId:"rest" }); const again:any = await reverseCompletedSale(database,{ orderId:"o1", returnRequestId:ret.id, refundId:"rest" }); expect(again.id).toBe(rev.id); expect((await database.select().from(schema.saleFinancials).where(eq(schema.saleFinancials.id,"sf1")))[0]).toEqual(before); expect((await database.select().from(schema.orders).where(eq(schema.orders.id,"o1")))[0].status).toBe(OrderStatus.Completed); expect((await database.select().from(schema.stockMovements).where(eq(schema.stockMovements.productId,"p1"))).filter((m)=>m.type===StockMovementType.SaleRollback || m.type === "sale_rollback")).toHaveLength(0); expect(JSON.parse(rev.sourceSnapshot).saleFinancial.id).toBe("sf1"); expect(rev.stockReversed).toBe(true); expect(rev.financialsReversed).toBe(true); });
  it("summarizes adjustments and does not claim exact adjusted profit when fee values are unknown", async () => { const database=db(); await seed(database,{ costKnown:false }); await database.insert(schema.refunds).values({ id:"r", orderId:"o1", type:RefundType.Partial, status:RefundStatus.Succeeded, currency:"EUR", subtotalAmount:20, shippingAmount:3, taxAmount:2, totalAmount:25, marketplaceFeeAdjustment:null, paymentFeeAdjustment:null, idempotencyKey:"r", createdAt:now(), updatedAt:now() }); const summary:any = await getReturnFinancialSummary(database,"o1"); expect(summary).toMatchObject({ originalGrossRevenue:115, refundedSubtotal:20, refundedShipping:3, refundedTax:2, totalRefunded:25, netRetainedRevenue:90, marketplaceFeeAdjustment:null, paymentFeeAdjustment:null, stockDispositionWriteOffValue:null, adjustedProfitComplete:false }); expect(summary.adjustedProfit).toBeUndefined(); });
});
