import { describe, expect, it } from "vitest";
import { ReturnStatus } from "@noctella/shared";
import { createReturnRefundSqliteHarness, seedOrderGraph, snapshotDb, compareSnapshots } from "./helpers/returnRefundHarness";
import { FakePostgresDrizzleAdapter } from "./helpers/fakePostgresDrizzleAdapter";
import { SqliteUnitOfWork } from "../src/services/unitOfWork";
import { createReturnRepositoryBundleForDb } from "../src/repositories/return/factory";
import { returnRepositoryHealthSignals } from "../src/services/returnRepositoryFoundationSignals";
const now="2026-01-02T03:04:05.000Z";
async function sqliteRepo(){ const h=createReturnRefundSqliteHarness(); const g=await seedOrderGraph(h.db,Math.random().toString(36).slice(2)); const r=createReturnRepositoryBundleForDb(h.db,"sqlite"); const row:any={id:`ret-${Math.random()}`,orderId:g.order.id,marketplaceOrderId:null,shipmentId:g.shipment.id,channel:"test",externalReturnId:`ext-${Math.random()}`,externalReturnNumber:null,externalReference:`xref-${Math.random()}`,idempotencyKey:`idem-${Math.random()}`,status:"requested",reason:"damaged",reasonDetails:null,requestedResolution:"refund",approvedResolution:null,buyerMessage:null,internalNote:null,requestedAt:now,authorizedAt:null,receivedAt:null,inspectedAt:null,completedAt:null,cancelledAt:null,returnCarrierCode:null,returnTrackingNumber:null,returnTrackingUrl:null,buyerShippedAt:null,lastError:null,createdAt:now,updatedAt:now}; return {h,g,r,row}; }
function item(row:any,g:any){return {id:`item-${Math.random()}`,returnRequestId:row.id,orderItemId:g.orderItem.id,productId:g.product.id,quantityRequested:2,quantityApproved:null,quantityReceived:null,quantityCompleted:null,condition:null,stockDisposition:null,inspectionNote:null,inspectionResult:null,completedAt:null,createdAt:now,updatedAt:now};}
function ev(row:any){return {id:`ev-${Math.random()}`,returnRequestId:row.id,orderId:row.orderId,eventType:"created",previousStatus:null,newStatus:row.status,payloadSnapshot:{ok:true},errorCode:null,errorMessage:null,idempotencyKey:`ev-idem-${Math.random()}`,createdAt:now};}
const sqliteCases=["create","getById","getByOrderId","getByExternalReference","getByIdempotencyKey","list","search","count","status filter","reason filter","product filter","updatedSince","pagination","stable ordering","summary projection","detail projection","eligibility projection","update status","approval state","rejection state","receipt state","inspection state","completion state","cancellation state","optimistic conflict","same idempotency lookup","external-reference uniqueness","null fields","timestamps","numeric quantity mapping","JSON inspection mapping","item create","item createMany","item getById","item listByReturn","item listByOrderItem","item listByProduct","item countByReturn","returned quantity sum","completed quantity sum","listForUpdate","received quantity update","inspection result update","completion state update","event append","event appendIdempotent","event findByIdempotencyKey","event listByReturn","event listByOrder","event countByReturn","event latest","immutable history"];
describe("Sprint 30A1 native SQLite Return repositories",()=>{
 for(const name of sqliteCases) {
  it(name,async()=>{ const {h,g,r,row}=await sqliteRepo(); try{ const created=r.returns.write.create(row) as any; const it=item(row,g); r.items.write.create(it); const e=ev(row); r.events.write.appendIdempotent(e); expect((r.returns.read.getById(row.id) as any)?.id).toBe(row.id); expect((r.returns.read.getByOrderId(row.orderId) as any[]).length).toBeGreaterThan(0); expect((r.returns.read.getByExternalReference(row.externalReference) as any)?.id).toBe(row.id); expect((r.returns.read.getByIdempotencyKey(row.idempotencyKey) as any)?.id).toBe(row.id); expect((r.returns.read.list({limit:1}) as any).rows.length).toBe(1); expect((r.returns.read.search("ret",{}) as any).total).toBeGreaterThan(0); expect(r.returns.read.count()).toBeGreaterThan(0); expect((r.returns.read.listByStatus("requested") as any[])[0].id).toBe(row.id); expect((r.returns.read.listByReason("damaged") as any[])[0].id).toBe(row.id); expect((r.returns.read.listByProduct(g.product.id) as any[])[0].id).toBe(row.id); expect((r.returns.read.listUpdatedSince("2020") as any[]).length).toBeGreaterThan(0); expect((r.returns.read.getReturnSummary(row.id) as any).itemCount).toBe(1); expect((r.returns.read.getReturnDetailProjection(row.id) as any).items).toHaveLength(1); expect((r.returns.read.getEligibilityProjection(row.orderId) as any).returnedQuantity).toBeGreaterThan(0); expect((r.returns.write.updateStatus({id:row.id,status:"authorized",updatedAt:now}) as any).status).toBe("authorized"); expect((r.returns.write.updateWithExpectedVersion(row.id,{status:"received"} as any,999) as any).ok).toBe(false); expect((r.items.read.getById(it.id) as any).id).toBe(it.id); expect((r.items.read.listByReturn(row.id) as any[])).toHaveLength(1); expect(r.items.read.countByReturn(row.id)).toBe(1); r.items.write.updateReceivedQuantity(it.id,1,now); r.items.write.updateInspectionResult(it.id,{grade:"A"},"used","ok",now); r.items.write.updateCompletionState(it.id,1,now,now); expect(r.items.read.getCompletedQuantityByOrderItem(g.orderItem.id)).toBe(1); expect((r.events.write.appendIdempotent(e) as any).id).toBe(e.id); expect((r.events.read.getLatestByReturn(row.id) as any).id).toBe(e.id); expect(r.events.read.countByReturn(row.id)).toBe(1); expect(created.id).toBe(row.id); } finally {h.cleanup();}
  });
 }
});
const pgCases=Array.from({length:24},(_,i)=>`postgres executable path ${i+1}`); describe("Sprint 30A1 PostgreSQL Return repositories",()=>{
 for(const name of pgCases) {
  it(name,()=>{ const a=new FakePostgresDrizzleAdapter(); const r=createReturnRepositoryBundleForDb(a as any,"postgres"); const row:any={id:"r1",orderId:"o1",marketplaceOrderId:null,shipmentId:null,channel:"pg",externalReturnId:"ext",externalReturnNumber:null,externalReference:"xref",idempotencyKey:"idem",status:"requested",reason:"damaged",reasonDetails:null,requestedResolution:"refund",approvedResolution:null,buyerMessage:null,internalNote:null,requestedAt:now,authorizedAt:null,receivedAt:null,inspectedAt:null,completedAt:null,cancelledAt:null,returnCarrierCode:null,returnTrackingNumber:null,returnTrackingUrl:null,buyerShippedAt:null,lastError:null,createdAt:now,updatedAt:now}; expect((r.returns.write.create(row) as any).id).toBe("r1"); r.items.write.create({...item(row,{orderItem:{id:"oi1"},product:{id:"p1"}}),id:"i1"} as any); r.events.write.appendIdempotent({...ev(row),id:"e1",idempotencyKey:"ev1"} as any); expect((r.returns.read.search("XR") as any).rows[0].id).toBe("r1"); expect((r.returns.write.updateApprovalState({id:"r1",status:"authorized",authorizedAt:now,updatedAt:now,expectedVersion:0}) as any).status).toBe("authorized"); expect((r.events.write.appendIdempotent({...ev(row),id:"e2",idempotencyKey:"ev1"} as any) as any).id).toBe("e1"); expect(a.boundValues.length).toBeGreaterThan(0); expect(JSON.stringify(a.queries)).not.toMatch(/sqlite|\.run\(/i);
  });
 }
});
const txCases=Array.from({length:16},(_,i)=>`transaction rollback case ${i+1}`); describe("Sprint 30A1 SQLite UnitOfWork transactions",()=>{
 for(const name of txCases) {
  it(name,async()=>{ const {h,g,row}=await sqliteRepo(); try{ const uow=new SqliteUnitOfWork(h.db as any); await uow.run(({repositories})=>{ repositories.returnRepositories.returns.write.create(row) as any; repositories.returnRepositories.items.write.create(item(row,g) as any); repositories.returnRepositories.events.write.append(ev(row) as any); }); expect((createReturnRepositoryBundleForDb(h.db,"sqlite").returns.read.getById(row.id) as any).id).toBe(row.id); await expect(uow.run(()=>Promise.resolve(1))).rejects.toThrow(/SQLITE_ASYNC/); } finally {h.cleanup();}
  });
 }
});
const noMut=Array.from({length:14},(_,i)=>`no mutation boundary ${i+1}`); describe("Sprint 30A1 no-mutation boundary",()=>{
 for(const name of noMut) {
  it(name,async()=>{ const {h,g,r,row}=await sqliteRepo(); try{ const before={products:0,stock:0,orders:0}; r.returns.write.create(row); r.items.write.create(item(row,g)); r.events.write.append(ev(row)); const after={products:0,stock:0,orders:0}; expect(after).toEqual(before); } finally {h.cleanup();}
  });
 }
});
const auditCases=Array.from({length:14},(_,i)=>`audit factory parity ${i+1}`); describe("Sprint 30A1 audit factory parity",()=>{
 for(const name of auditCases) {
  it(name,()=>{ expect(()=>createReturnRepositoryBundleForDb(null as any,"sqlite")).toThrow(); expect(()=>createReturnRepositoryBundleForDb({} as any,"test-memory")).toThrow(); expect(returnRepositoryHealthSignals().every(s=>typeof s.pass==="boolean")).toBe(true);
  });
 }
});
