import { describe, expect, it } from "vitest";
import { CancelSaleUseCase, CreateSaleUseCase, GetSaleUseCase, InvalidSaleAmountError, InvalidSaleStatusTransitionError, ListSalesUseCase, SaleConcurrencyConflictError, SaleDuplicateReferenceError, SaleNotFoundError, SalesValidationError, UpdateSaleUseCase } from "../src/application/sales";
import { auditSalesUseCaseSource, runSalesUseCaseAudit } from "../src/scripts/salesUseCaseAudit";
import type { Sale, SaleRepository, SaleRepositoryFilter } from "../src/repositories/sales/types";
import type { SalesApplicationContext } from "../src/services/salesApplicationContext";

const stamp = "2026-07-18T10:00:00.000Z";
const base = (id = "sale-1", status = "Processing"): Sale => ({ id, reference: `REF-${id}`, orderDraftId: null, source: "Manual", status, paymentStatus: "Paid", customer: { customerId: null, email: null, billingAddress: null, shippingAddress: null }, payment: { status: "Paid", provider: null, reference: null }, fulfillment: { status: null, shippingStatus: null, trackingNumber: null }, marketplace: { channel: null, marketplaceOrderId: null, externalOrderId: null, externalOrderNumber: null, externalTransactionId: null, connectionId: null }, financials: { subtotalAmount: 10, shippingAmount: 2, taxAmount: 1, totalAmount: 13, grossRevenue: null, shippingCharged: null, shippingCost: null, marketplaceFee: null, promotedFee: null, paymentFee: null, itemCost: null, netRevenue: null, profit: null, currency: "EUR" }, receipt: { invoiceId: null, invoiceNumber: null }, notes: null, idempotencyKey: null, createdAt: stamp, updatedAt: stamp, completedAt: null, lines: [{ id: "line-1", saleId: id, productId: null, sku: null, title: "Free text", slug: null, productType: null, imageUrl: null, quantity: 1, unitPrice: 10, totalPrice: 10, currency: "EUR", stockMovementId: null, createdAt: stamp, updatedAt: stamp }] });
function harness(seed: Sale[] = []) { const rows = new Map(seed.map((sale) => [sale.id, sale])); let runs = 0; let sequence = 0; const repo: SaleRepository = { create: (sale) => { if ([...rows.values()].some((x) => x.reference === sale.reference)) throw new Error("duplicate"); rows.set(sale.id, sale); return sale; }, findById: (id) => rows.get(id) ?? null, findByReference: (reference) => [...rows.values()].find((x) => x.reference === reference) ?? null, findByExternalOrderId: (externalOrderId) => [...rows.values()].find((x) => x.marketplace.externalOrderId === externalOrderId) ?? null, findByIdempotencyKey: (key) => [...rows.values()].find((x) => x.idempotencyKey === key) ?? null, list: (filter: SaleRepositoryFilter = {}) => { let values = [...rows.values()]; if (filter.status) values = values.filter((x) => x.status === filter.status); if (filter.customerId !== undefined) values = values.filter((x) => x.customer.customerId === filter.customerId); if (filter.channel) values = values.filter((x) => x.marketplace.channel === filter.channel); values.sort((a, b) => b.createdAt.localeCompare(a.createdAt) || b.id.localeCompare(a.id)); const limit = filter.limit ?? 50, offset = filter.offset ?? 0; return { rows: values.slice(offset, offset + limit), total: values.length, limit, offset }; }, update: () => null, updateWithVersion: (id, version, change) => { const current = rows.get(id); if (!current) return { ok: false, issue: { code: "not_found", message: "missing" } }; if (current.updatedAt !== version) return { ok: false, issue: { code: "optimistic_conflict", message: "stale" } }; const next = { ...current, ...change, customer: change.customer ?? current.customer, payment: change.payment ?? current.payment, financials: change.financials ?? current.financials }; rows.set(id, next); return { ok: true, value: next }; }, addLine: (line) => line, updateLine: () => null, removeLine: () => false }; const ctx = { salesRepositories: { saleRepository: repo }, saleRepository: repo, unitOfWork: { run: async (work: any) => { runs++; return work({ repositories: { sales: { saleRepository: repo } } }); } }, logger: {}, clock: { now: () => new Date(stamp) }, idGenerator: { newId: () => `generated-${++sequence}` }, configuration: { salesApplicationContext: true as const } } as SalesApplicationContext; return { ctx, repo, rows, runs: () => runs }; }
const createInput = (extra: Record<string, unknown> = {}) => ({ reference: "REF-NEW", source: "Manual", status: "Processing", paymentStatus: "Paid", shippingAmount: 2, taxAmount: 1, currency: "EUR" as const, lines: [{ title: "Free text", quantity: 2, unitPrice: 5 }], ...extra });

describe("Sales core use cases Sprint 33A-S3A", () => {
  const createCases: Array<[string, (h: ReturnType<typeof harness>) => Promise<void>]> = [
    ["creates a valid sale", async h => expect((await new CreateSaleUseCase(h.ctx).execute(createInput())).reference).toBe("REF-NEW")],
    ["generates aggregate ID", async h => expect((await new CreateSaleUseCase(h.ctx).execute(createInput())).id).toBe("generated-1")],
    ["generates line ID", async h => expect((await new CreateSaleUseCase(h.ctx).execute(createInput())).lines[0].id).toBe("generated-2")],
    ["uses deterministic created timestamp", async h => expect((await new CreateSaleUseCase(h.ctx).execute(createInput())).createdAt).toBe(stamp)],
    ["uses deterministic updated timestamp", async h => expect((await new CreateSaleUseCase(h.ctx).execute(createInput())).updatedAt).toBe(stamp)],
    ["uses UnitOfWork", async h => { await new CreateSaleUseCase(h.ctx).execute(createInput()); expect(h.runs()).toBe(1); }],
    ["preserves optional customer", async h => expect((await new CreateSaleUseCase(h.ctx).execute(createInput({ customer: { customerId: "c1", email: "a@b.c" } }))).customer.customerId).toBe("c1")],
    ["preserves absent customer", async h => expect((await new CreateSaleUseCase(h.ctx).execute(createInput())).customer.customerId).toBeNull()],
    ["preserves marketplace reference", async h => expect((await new CreateSaleUseCase(h.ctx).execute(createInput({ marketplace: { channel: "eBay", externalOrderId: "e1" } }))).marketplace.externalOrderId).toBe("e1")],
    ["preserves shipping reference", async h => expect((await new CreateSaleUseCase(h.ctx).execute(createInput({ shipping: { shippingStatus: "Ready", trackingNumber: "T1" } }))).fulfillment.trackingNumber).toBe("T1")],
    ["preserves external transaction", async h => expect((await new CreateSaleUseCase(h.ctx).execute(createInput({ marketplace: { externalTransactionId: "tx" } }))).marketplace.externalTransactionId).toBe("tx")],
    ["preserves product reference", async h => expect((await new CreateSaleUseCase(h.ctx).execute(createInput({ lines: [{ title: "Linked", quantity: 1, unitPrice: 4, productId: "p1" }] }))).lines[0].productId).toBe("p1")],
    ["supports free-text line", async h => expect((await new CreateSaleUseCase(h.ctx).execute(createInput())).lines[0].productId).toBeNull()],
    ["calculates line total", async h => expect((await new CreateSaleUseCase(h.ctx).execute(createInput())).lines[0].totalPrice).toBe(10)],
    ["calculates subtotal", async h => expect((await new CreateSaleUseCase(h.ctx).execute(createInput())).financials.subtotalAmount).toBe(10)],
    ["calculates total", async h => expect((await new CreateSaleUseCase(h.ctx).execute(createInput())).financials.totalAmount).toBe(13)],
    ["rejects duplicate reference", async h => { h.rows.set("x", base("x")); await expect(new CreateSaleUseCase(h.ctx).execute(createInput({ reference: "REF-x" }))).rejects.toBeInstanceOf(SaleDuplicateReferenceError); }],
    ["replays idempotent create", async h => { const existing = { ...base(), idempotencyKey: "idem" }; h.rows.set(existing.id, existing); expect((await new CreateSaleUseCase(h.ctx).execute(createInput({ idempotencyKey: "idem" }))).id).toBe(existing.id); }],
    ["rejects empty lines", async h => expect(new CreateSaleUseCase(h.ctx).execute(createInput({ lines: [] }))).rejects.toBeInstanceOf(SalesValidationError)],
    ["rejects zero quantity", async h => expect(new CreateSaleUseCase(h.ctx).execute(createInput({ lines: [{ title: "x", quantity: 0, unitPrice: 1 }] }))).rejects.toBeInstanceOf(SalesValidationError)],
    ["rejects negative quantity", async h => expect(new CreateSaleUseCase(h.ctx).execute(createInput({ lines: [{ title: "x", quantity: -1, unitPrice: 1 }] }))).rejects.toBeInstanceOf(SalesValidationError)],
    ["rejects fractional quantity", async h => expect(new CreateSaleUseCase(h.ctx).execute(createInput({ lines: [{ title: "x", quantity: 1.5, unitPrice: 1 }] }))).rejects.toBeInstanceOf(SalesValidationError)],
    ["rejects negative unit price", async h => expect(new CreateSaleUseCase(h.ctx).execute(createInput({ lines: [{ title: "x", quantity: 1, unitPrice: -1 }] }))).rejects.toBeInstanceOf(InvalidSaleAmountError)],
    ["rejects negative shipping", async h => expect(new CreateSaleUseCase(h.ctx).execute(createInput({ shippingAmount: -1 }))).rejects.toBeInstanceOf(InvalidSaleAmountError)],
    ["rejects negative tax", async h => expect(new CreateSaleUseCase(h.ctx).execute(createInput({ taxAmount: -1 }))).rejects.toBeInstanceOf(InvalidSaleAmountError)],
    ["returns frozen aggregate", async h => expect(Object.isFrozen(await new CreateSaleUseCase(h.ctx).execute(createInput()))).toBe(true)],
    ["returns frozen lines", async h => expect(Object.isFrozen((await new CreateSaleUseCase(h.ctx).execute(createInput())).lines)).toBe(true)],
    ["returns frozen nested snapshots", async h => expect(Object.isFrozen((await new CreateSaleUseCase(h.ctx).execute(createInput())).marketplace)).toBe(true)],
  ];
  it.each(createCases)("create: %s", async (_name, run) => run(harness()));

  const mutationCases: Array<[string, () => Promise<void>]> = [
    ["update valid notes", async () => { const h=harness([base()]); expect((await new UpdateSaleUseCase(h.ctx).execute({saleId:"sale-1",expectedVersion:stamp,notes:"n",currency:"EUR"})).notes).toBe("n"); }],
    ["update uses UnitOfWork", async () => { const h=harness([base()]); await new UpdateSaleUseCase(h.ctx).execute({saleId:"sale-1",expectedVersion:stamp,notes:"n",currency:"EUR"}); expect(h.runs()).toBe(1); }],
    ["update missing", async () => { const h=harness(); await expect(new UpdateSaleUseCase(h.ctx).execute({saleId:"x",expectedVersion:stamp,notes:"n",currency:"EUR"})).rejects.toBeInstanceOf(SaleNotFoundError); }],
    ["update stale", async () => { const h=harness([base()]); await expect(new UpdateSaleUseCase(h.ctx).execute({saleId:"sale-1",expectedVersion:"old",notes:"n",currency:"EUR"})).rejects.toBeInstanceOf(SaleConcurrencyConflictError); }],
    ["update valid status", async () => { const h=harness([base()]); expect((await new UpdateSaleUseCase(h.ctx).execute({saleId:"sale-1",expectedVersion:stamp,status:"Paid",currency:"EUR"})).status).toBe("Paid"); }],
    ["update invalid terminal status", async () => { const h=harness([base()]); await expect(new UpdateSaleUseCase(h.ctx).execute({saleId:"sale-1",expectedVersion:stamp,status:"Completed",currency:"EUR"})).rejects.toBeInstanceOf(InvalidSaleStatusTransitionError); }],
    ["update terminal aggregate blocked", async () => { const h=harness([base("sale-1","Completed")]); await expect(new UpdateSaleUseCase(h.ctx).execute({saleId:"sale-1",expectedVersion:stamp,notes:"n",currency:"EUR"})).rejects.toBeInstanceOf(InvalidSaleStatusTransitionError); }],
    ["update customer explicitly", async () => { const h=harness([base()]); expect((await new UpdateSaleUseCase(h.ctx).execute({saleId:"sale-1",expectedVersion:stamp,customer:{email:"new"},currency:"EUR"})).customer.email).toBe("new"); }],
    ["update optional notes clears", async () => { const h=harness([{...base(),notes:"old"}]); expect((await new UpdateSaleUseCase(h.ctx).execute({saleId:"sale-1",expectedVersion:stamp,notes:null,currency:"EUR"})).notes).toBeNull(); }],
    ["update deterministic timestamp", async () => { const h=harness([base()]); expect((await new UpdateSaleUseCase(h.ctx).execute({saleId:"sale-1",expectedVersion:stamp,notes:"n",currency:"EUR"})).updatedAt).toBe(stamp); }],
    ["update immutable", async () => { const h=harness([base()]); expect(Object.isFrozen(await new UpdateSaleUseCase(h.ctx).execute({saleId:"sale-1",expectedVersion:stamp,notes:"n",currency:"EUR"}))).toBe(true); }],
    ["cancel valid", async () => { const h=harness([base()]); expect((await new CancelSaleUseCase(h.ctx).execute({saleId:"sale-1",expectedVersion:stamp})).status).toBe("Cancelled"); }],
    ["cancel uses UnitOfWork", async () => { const h=harness([base()]); await new CancelSaleUseCase(h.ctx).execute({saleId:"sale-1",expectedVersion:stamp}); expect(h.runs()).toBe(1); }],
    ["cancel missing", async () => { const h=harness(); await expect(new CancelSaleUseCase(h.ctx).execute({saleId:"x",expectedVersion:stamp})).rejects.toBeInstanceOf(SaleNotFoundError); }],
    ["cancel stale", async () => { const h=harness([base()]); await expect(new CancelSaleUseCase(h.ctx).execute({saleId:"sale-1",expectedVersion:"old"})).rejects.toBeInstanceOf(SaleConcurrencyConflictError); }],
    ["cancel completed blocked", async () => { const h=harness([base("sale-1","Completed")]); await expect(new CancelSaleUseCase(h.ctx).execute({saleId:"sale-1",expectedVersion:stamp})).rejects.toBeInstanceOf(InvalidSaleStatusTransitionError); }],
    ["cancel repeated blocked", async () => { const h=harness([base("sale-1","Cancelled")]); await expect(new CancelSaleUseCase(h.ctx).execute({saleId:"sale-1",expectedVersion:stamp})).rejects.toBeInstanceOf(InvalidSaleStatusTransitionError); }],
    ["cancel immutable", async () => { const h=harness([base()]); expect(Object.isFrozen(await new CancelSaleUseCase(h.ctx).execute({saleId:"sale-1",expectedVersion:stamp}))).toBe(true); }],
  ]; it.each(mutationCases)("mutation: %s", async (_name, run) => run());

  const readCases: Array<[string, () => Promise<void>]> = [
    ["get existing", async()=>{const h=harness([base()]);expect((await new GetSaleUseCase(h.ctx).execute({saleId:"sale-1"})).id).toBe("sale-1")}],
    ["get missing", async()=>{const h=harness();await expect(new GetSaleUseCase(h.ctx).execute({saleId:"x"})).rejects.toBeInstanceOf(SaleNotFoundError)}],
    ["get immutable", async()=>{const h=harness([base()]);expect(Object.isFrozen(await new GetSaleUseCase(h.ctx).execute({saleId:"sale-1"}))).toBe(true)}],
    ["list all", async()=>{const h=harness([base("a"),base("b")]);expect((await new ListSalesUseCase(h.ctx).execute()).rows).toHaveLength(2)}],
    ["list status filter", async()=>{const h=harness([base("a"),base("b","Paid")]);expect((await new ListSalesUseCase(h.ctx).execute({status:"Paid"})).rows).toHaveLength(1)}],
    ["list customer filter", async()=>{const h=harness([{...base(),customer:{...base().customer,customerId:"c"}}]);expect((await new ListSalesUseCase(h.ctx).execute({customerId:"c"})).rows).toHaveLength(1)}],
    ["list channel filter", async()=>{const h=harness([{...base(),marketplace:{...base().marketplace,channel:"eBay"}}]);expect((await new ListSalesUseCase(h.ctx).execute({channel:"eBay"})).rows).toHaveLength(1)}],
    ["list pagination limit", async()=>{const h=harness([base("a"),base("b")]);expect((await new ListSalesUseCase(h.ctx).execute({limit:1})).rows).toHaveLength(1)}],
    ["list pagination offset", async()=>{const h=harness([base("a"),base("b")]);expect((await new ListSalesUseCase(h.ctx).execute({limit:1,offset:1})).offset).toBe(1)}],
    ["list deterministic sorting", async()=>{const h=harness([base("a"),base("b")]);expect((await new ListSalesUseCase(h.ctx).execute()).rows[0].id).toBe("b")}],
    ["list output frozen", async()=>{const h=harness([base()]);expect(Object.isFrozen(await new ListSalesUseCase(h.ctx).execute())).toBe(true)}],
    ["list rows frozen", async()=>{const h=harness([base()]);expect(Object.isFrozen((await new ListSalesUseCase(h.ctx).execute()).rows)).toBe(true)}],
  ]; it.each(readCases)("read: %s", async (_name, run)=>run());

  const auditCases: Array<[string,string,string]> = [["SQL","select from sales","SQL"],["DbClient","type X = DbClient","DbClient"],["Drizzle","import x from 'drizzle-orm'","Drizzle"],["schema","import x from '../db/schema'","schema"],["repository implementation","repositories/sales/sqlite","repository implementation"],["HTTP","type X = Request","HTTP"],["provider SDK","stripe.charge()","provider SDK"],["queue","queue worker","queue or worker"],["events","new EventEmitter()","EventEmitter"],["Date.now","Date.now()","Date.now"],["random UUID","randomUUID()","randomUUID"],["random math","Math.random()","Math.random"],["generic patch","const patch = {}","generic patch"],["manual transaction","db.transaction(() => 1)","manual transaction"],["Inventory","inventoryRepository.find()","Inventory access"],["Complete Sale","class CompleteSaleUseCase {}","Complete Sale"],["shipping","shipmentRepository.find()","shipping coordination"],["marketplace fulfillment","marketplaceFulfillment.submit()","shipping coordination"],["finance","financeEntry.create()","finance coordination"],["invoice","createInvoice()","finance coordination"]];
  it.each(auditCases)("audit rejects %s", (_name, source, issue)=>expect(auditSalesUseCaseSource(source).issues).toContain(issue));
  it("audit accepts valid fixture",()=>expect(auditSalesUseCaseSource("ctx.unitOfWork.run(() => saleRepository.findById(id))").status).toBe("PASS"));
  it("production audit passes",()=>expect(runSalesUseCaseAudit().status).toBe("PASS"));
});
