import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import Database from "better-sqlite3";
import { drizzle } from "drizzle-orm/better-sqlite3";
import { describe, expect, it } from "vitest";
import { ensureSchema } from "../src/db/migrate";
import * as schema from "../src/db/schema";
import { createTransactionalSalesCompletionCoordinator, type SalesCompletionCommitInput } from "../src/application/sales/completionCoordination";
import { SaleAlreadyCompletedConflictError, SalesCompletionIdempotencyConflictError } from "../src/application/sales/errors";
import { auditCompletedSaleReplayGuardSource } from "../src/scripts/salesCompletionCoordinationAudit";
import { createPostgresSalesCompletionTransactionRepository } from "../src/repositories/sales-completion/postgres";
import { SqliteUnitOfWork } from "../src/services/unitOfWork";

const at="2026-07-18T09:30:00.000Z", next="2026-07-18T09:31:00.000Z";
const order=(id:string)=>({id,orderNumber:`N-${id}`,guestEmail:"buyer@example.test",status:"Delivered",paymentStatus:"Paid",subtotalAmount:100,shippingAmount:10,taxAmount:20,totalAmount:130,currency:"EUR",billingAddress:"{}",shippingAddress:"{}",createdAt:at,updatedAt:at});
const shipment=(id:string)=>({id:`sh:${id}`,orderId:id,carrierCode:"LocalPickup",status:"Delivered",shippingCost:5,currency:"EUR",createdAt:at,updatedAt:at});
const input=(saleId:string,key=`complete:${saleId}`,fingerprint=`sha256:${saleId}`):SalesCompletionCommitInput=>{const snapshot=Object.freeze({saleId,grossRevenue:130,shippingCharged:10,shippingCost:5,marketplaceFee:null,promotedFee:null,paymentFee:null,taxVat:20,itemCost:40,netRevenue:105,profit:65,currency:"EUR" as const,completedAt:next});return Object.freeze({expectedVersion:at,idempotencyKey:key,payloadFingerprint:fingerprint,financialSnapshotId:`sf:${key}`,financeEntryId:`fe:${key}`,completionHistoryId:`he:${key}`,finalUpdatedAt:next,snapshot,financeEntry:Object.freeze({saleId,entryType:"CompleteSale" as const,amount:130,currency:"EUR" as const,sourceReference:saleId,idempotencyKey:key,occurredAt:next,snapshot}),historyEntry:Object.freeze({saleId,shipmentId:`sh:${saleId}`,eventType:"sale_completed" as const,occurredAt:next,financialSnapshot:snapshot})});};
function fixture(id:string){const raw=new Database(":memory:");ensureSchema(raw);const db=drizzle(raw,{schema});db.insert(schema.orders).values(order(id)).run();db.insert(schema.shipments).values(shipment(id)).run();return{raw,coordinator:createTransactionalSalesCompletionCoordinator(new SqliteUnitOfWork(db as any))};}
const count=(raw:Database.Database,table:string)=>Number((raw.prepare(`SELECT count(*) value FROM ${table}`).get() as any).value);
const source=(file:string)=>readFileSync(resolve(__dirname,`../src/${file}`),"utf8");
class PgCompletionDb {
  execution:any=null; writes:any[]=[]; updateRows=1; selects=0;
  async transaction<T>(work:(tx:this)=>Promise<T>){const before={execution:this.execution,writes:[...this.writes]};try{return await work(this);}catch(error){this.execution=before.execution;this.writes=before.writes;throw error;}}
  insert(_table:any){return{values:(value:any)=>{const write=()=>{this.writes.push(value);return[value];};return{then:(ok:any,bad:any)=>Promise.resolve(write()).then(ok,bad),onConflictDoNothing:()=>({returning:async()=>{if(this.execution)return[];this.execution=value;return[value];}})}}};}
  select(){return{from:(_table:any)=>({where:async()=>{this.selects++;if(!this.execution)return[];return this.selects%2===1?[this.execution]:[];}})};}
  update(_table:any){return{set:(_value:any)=>({where:(_predicate:any)=>({returning:async()=>this.updateRows?[{id:"sale"}]:[]})})};}
}

describe("Sprint 33A-S3BR3 completed sale replay guard (65 executable tests)",()=>{
  const firstChecks:Array<[string,(f:ReturnType<typeof fixture>,r:any)=>unknown]>=[
    ["returns non-replay",(_f,r)=>r.replay===false],["returns sale identity",(_f,r)=>r.saleId==="first"],["writes one snapshot",f=>count(f.raw,"sale_financials")===1],["writes one finance entry",f=>count(f.raw,"finance_entries")===1],["writes one history",f=>count(f.raw,"shipment_events")===1],["writes one final state",f=>(f.raw.prepare("SELECT status FROM orders WHERE id='first'").get() as any).status==="Completed"],["persists completion identity",f=>count(f.raw,"sale_completion_executions")===1],["persists sale id",f=>(f.raw.prepare("SELECT sale_id FROM sale_completion_executions").get() as any).sale_id==="first"]];
  it.each(firstChecks)("first completion: %s",async(_n,check)=>{const f=fixture("first");try{expect(check(f,await f.coordinator.commit(input("first")))).toBe(true);}finally{f.raw.close();}});

  const replayChecks:Array<[string,(f:ReturnType<typeof fixture>,a:any,b:any)=>unknown]>=[
    ["is recognized",(_f,_a,b)=>b.replay===true],["is deterministic",(_f,a,b)=>JSON.stringify({...b,replay:false})===JSON.stringify(a)],["keeps one snapshot",f=>count(f.raw,"sale_financials")===1],["keeps one finance entry",f=>count(f.raw,"finance_entries")===1],["keeps one history",f=>count(f.raw,"shipment_events")===1],["keeps one final update",f=>(f.raw.prepare("SELECT updated_at FROM orders").get() as any).updated_at===next],["keeps one identity",f=>count(f.raw,"sale_completion_executions")===1],["ignores alternate effect ids",f=>!(f.raw.prepare("SELECT id FROM sale_financials").get() as any).id.startsWith("other")]];
  it.each(replayChecks)("exact replay: %s",async(_n,check)=>{const f=fixture("replay");try{const a=await f.coordinator.commit(input("replay"));const b=await f.coordinator.commit({...input("replay"),financialSnapshotId:"other-sf",financeEntryId:"other-fe",completionHistoryId:"other-he"});expect(check(f,a,b)).toBe(true);}finally{f.raw.close();}});

  const conflictChecks:Array<[string,string]>=[["explicit error","error"],["zero snapshot mutations","sale_financials"],["zero finance mutations","finance_entries"],["zero history mutations","shipment_events"],["zero identity mutations","sale_completion_executions"]];
  it.each(conflictChecks)("conflicting replay: %s",async(_n,kind)=>{const f=fixture("conflict");try{await f.coordinator.commit(input("conflict"));const p=f.coordinator.commit(input("conflict","complete:conflict","changed"));if(kind==="error")await expect(p).rejects.toBeInstanceOf(SalesCompletionIdempotencyConflictError);else{await expect(p).rejects.toThrow();expect(count(f.raw,kind)).toBe(1);}}finally{f.raw.close();}});

  const duplicateChecks:Array<[string,string,string]>=[["same fingerprint explicit error","sha256:duplicate","error"],["different fingerprint explicit error","different","error"],["same fingerprint snapshot unchanged","sha256:duplicate","sale_financials"],["different fingerprint finance unchanged","different","finance_entries"],["same fingerprint history unchanged","sha256:duplicate","shipment_events"],["different fingerprint identity unchanged","different","sale_completion_executions"],["same fingerprint final state unchanged","sha256:duplicate","orders"],["different fingerprint final state unchanged","different","orders"]];
  it.each(duplicateChecks)("new-key duplicate: %s",async(_n,fp,kind)=>{const f=fixture("duplicate");try{await f.coordinator.commit(input("duplicate","K1","sha256:duplicate"));const p=f.coordinator.commit(input("duplicate","K2",fp));if(kind==="error")await expect(p).rejects.toBeInstanceOf(SaleAlreadyCompletedConflictError);else{await expect(p).rejects.toThrow();expect(kind==="orders"?(f.raw.prepare("SELECT count(*) value FROM orders WHERE status='Completed'").get() as any).value:count(f.raw,kind)).toBe(1);}}finally{f.raw.close();}});

  const raceChecks:Array<[string,string]>=[["one completion identity","sale_completion_executions"],["one snapshot","sale_financials"],["one finance entry","finance_entries"],["one history","shipment_events"],["one final state","orders"]];
  it.each(raceChecks)("different-key race: %s",async(_n,kind)=>{const f=fixture("race");try{await f.coordinator.commit(input("race","K1","F1"));await expect(f.coordinator.commit(input("race","K2","F2"))).rejects.toBeInstanceOf(SaleAlreadyCompletedConflictError);expect(kind==="orders"?(f.raw.prepare("SELECT count(*) value FROM orders WHERE status='Completed'").get() as any).value:count(f.raw,kind)).toBe(1);}finally{f.raw.close();}});

  const errorChecks:Array<[string,(e:SaleAlreadyCompletedConflictError)=>unknown]>=[["has explicit code",e=>e.code==="sale_already_completed_conflict"],["identifies sale",e=>e.metadata.saleId==="s1"],["identifies winning key",e=>e.metadata.completedWithIdempotencyKey==="K1"],["has immutable metadata",e=>Object.isFrozen(e.metadata)]];
  it.each(errorChecks)("error contract: %s",(_n,check)=>expect(check(new SaleAlreadyCompletedConflictError("s1","K1"))).toBe(true));

  const parityChecks:Array<[string,(s:{sqlite:string;postgres:string;sqliteSchema:string;postgresSchema:string;migration:string})=>unknown]>=[
    ["SQLite unique sale identity",s=>s.sqliteSchema.includes("idx_sale_completion_executions_sale_unique")],["PostgreSQL unique sale identity",s=>s.postgresSchema.includes("idx_sale_completion_executions_sale_unique")],["migration is additive",s=>s.migration.includes("CREATE UNIQUE INDEX IF NOT EXISTS")],["migration is non-destructive",s=>!/(DROP|DELETE|TRUNCATE)/.test(s.migration)],["SQLite persisted sale lookup",s=>s.sqlite.includes("saleCompletionExecutions.saleId")],["PostgreSQL persisted sale lookup",s=>s.postgres.includes("saleCompletionExecutions.saleId")],["SQLite explicit conflict",s=>s.sqlite.includes("SaleAlreadyCompletedConflictError")],["PostgreSQL explicit conflict",s=>s.postgres.includes("SaleAlreadyCompletedConflictError")]];
  it.each(parityChecks)("persistence/parity: %s",(_n,check)=>expect(check({sqlite:source("repositories/sales-completion/sqlite.ts"),postgres:source("repositories/sales-completion/postgres.ts"),sqliteSchema:source("db/schema.sqlite.ts"),postgresSchema:source("db/schema.postgres.ts"),migration:source("db/postgres-migrations/0005_sprint33a_s3br3_completed_sale_guard.sql")})).toBe(true));

  const auditChecks:Array<[string,(a:ReturnType<typeof auditCompletedSaleReplayGuardSource>,s:{sqlite:string;postgres:string;sqliteSchema:string;postgresSchema:string})=>unknown]>=[
    ["accepts valid persisted guard",a=>a.status==="PASS"],["rejects missing SQLite lookup",(_a,s)=>auditCompletedSaleReplayGuardSource(s.sqlite.replace(/const existingSale[\s\S]*?throw new SaleConcurrencyConflictError\(\);/,"throw new SaleConcurrencyConflictError();"),s.postgres,s.sqliteSchema,s.postgresSchema).status==="FAIL"],["rejects missing PostgreSQL lookup",(_a,s)=>auditCompletedSaleReplayGuardSource(s.sqlite,s.postgres.replace(/const \[existingSale\][\s\S]*?throw new SaleConcurrencyConflictError\(\);/,"throw new SaleConcurrencyConflictError();"),s.sqliteSchema,s.postgresSchema).status==="FAIL"],["rejects non-unique SQLite sale id",(_a,s)=>auditCompletedSaleReplayGuardSource(s.sqlite,s.postgres,s.sqliteSchema.replace("uniqueIndex(\"idx_sale_completion_executions_sale_unique\")","index(\"idx_sale_completion_executions_sale\")"),s.postgresSchema).status==="FAIL"],["rejects non-unique PostgreSQL sale id",(_a,s)=>auditCompletedSaleReplayGuardSource(s.sqlite,s.postgres,s.sqliteSchema,s.postgresSchema.replace("uniqueIndex(\"idx_sale_completion_executions_sale_unique\")","index(\"idx_sale_completion_executions_sale\")")).status==="FAIL"],["rejects silent SQLite duplicate",(_a,s)=>auditCompletedSaleReplayGuardSource(s.sqlite.replace("throw new SaleAlreadyCompletedConflictError(input.snapshot.saleId, existingSale.idempotencyKey);","return replayResult(existingSale.resultPayload);"),s.postgres,s.sqliteSchema,s.postgresSchema).status==="FAIL"],["rejects silent PostgreSQL duplicate",(_a,s)=>auditCompletedSaleReplayGuardSource(s.sqlite,s.postgres.replace("throw new SaleAlreadyCompletedConflictError(input.snapshot.saleId, existingSale.idempotencyKey);","return replayResult(JSON.stringify(existingSale.resultPayload));"),s.sqliteSchema,s.postgresSchema).status==="FAIL"],["rejects SQLite precheck-only guard",(_a,s)=>auditCompletedSaleReplayGuardSource(s.sqlite.replace("onConflictDoNothing","precheckOnly"),s.postgres,s.sqliteSchema,s.postgresSchema).status==="FAIL"],["rejects PostgreSQL precheck-only guard",(_a,s)=>auditCompletedSaleReplayGuardSource(s.sqlite,s.postgres.replace("onConflictDoNothing","precheckOnly"),s.sqliteSchema,s.postgresSchema).status==="FAIL"],["reports immutable issues",a=>Object.isFrozen(a.issues)]];
  it.each(auditChecks)("audit: %s",(_n,check)=>{const s={sqlite:source("repositories/sales-completion/sqlite.ts"),postgres:source("repositories/sales-completion/postgres.ts"),sqliteSchema:source("db/schema.sqlite.ts"),postgresSchema:source("db/schema.postgres.ts")};expect(check(auditCompletedSaleReplayGuardSource(s.sqlite,s.postgres,s.sqliteSchema,s.postgresSchema),s)).toBe(true);});

  const scopeChecks:Array<[string,RegExp]>=[["no CompleteSaleUseCase",/class\s+CompleteSaleUseCase|function\s+CompleteSaleUseCase/],["no route changes",/routes?\//],["no controller changes",/controllers?\//],["no service guard",/services\/.*completed/i]];
  it.each(scopeChecks)("scope: %s",(_n,pattern)=>expect(pattern.test([source("repositories/sales-completion/sqlite.ts"),source("repositories/sales-completion/postgres.ts")].join("\n"))).toBe(false));

  it("PostgreSQL exact replay is deterministic and mutation-free",async()=>{const db=new PgCompletionDb();const repo=createPostgresSalesCompletionTransactionRepository(db as any);const first=await repo.commit(input("pg-replay"));db.selects=0;const replay=await repo.commit(input("pg-replay"));expect({...replay,replay:false}).toEqual(first);expect(db.writes).toHaveLength(3);});
  it("PostgreSQL same-key changed payload is an idempotency conflict",async()=>{const db=new PgCompletionDb();const repo=createPostgresSalesCompletionTransactionRepository(db as any);await repo.commit(input("pg-conflict"));db.selects=0;await expect(repo.commit(input("pg-conflict","complete:pg-conflict","changed"))).rejects.toBeInstanceOf(SalesCompletionIdempotencyConflictError);expect(db.writes).toHaveLength(3);});
  it("PostgreSQL different key is an already-completed conflict",async()=>{const db=new PgCompletionDb();const repo=createPostgresSalesCompletionTransactionRepository(db as any);await repo.commit(input("pg-duplicate","K1","F1"));db.selects=1;await expect(repo.commit(input("pg-duplicate","K2","F2"))).rejects.toBeInstanceOf(SaleAlreadyCompletedConflictError);expect(db.writes).toHaveLength(3);});
  it("PostgreSQL different-key race persists exactly one completion",async()=>{const db=new PgCompletionDb();const repo=createPostgresSalesCompletionTransactionRepository(db as any);await repo.commit(input("pg-race","K1","F1"));db.selects=1;await expect(repo.commit(input("pg-race","K2","F2"))).rejects.toThrow();expect([db.execution,...db.writes]).toHaveLength(4);});
  it("PostgreSQL loser rollback removes the reserved completion identity",async()=>{const db=new PgCompletionDb();db.updateRows=0;await expect(db.transaction(tx=>createPostgresSalesCompletionTransactionRepository(tx as any).commit(input("pg-rollback")))).rejects.toThrow();expect(db.execution).toBeNull();expect(db.writes).toHaveLength(0);});
});
