import { describe, it, expect, beforeEach } from "vitest";
import { eq, desc, sql } from "drizzle-orm";
import { CarrierCode, OrderStatus, PaymentProvider, PaymentStatus, ProductStatus, ProductType, ShipmentStatus } from "@noctella/shared";
import * as schema from "../src/db/schema";
import * as svc from "../src/services/shipments";
import { createCategory } from "../src/services/categories";
import { createProduct } from "../src/services/products";
import { createOrder } from "../src/services/orders";
import { createTestDb } from "./testDb";
import { shipmentAtomicityVerification, shipmentPostCommitBoundary, shipmentRepositoryInitialized, shipmentSchemaParity, shipmentTransactionCapability, shipmentDirectAccessAudit } from "../src/services/shipmentVerificationSignals";

const address = { fullName: "Jane", line1: "1 Main", city: "Paris", postalCode: "75001", country: "FR" };
type Db = ReturnType<typeof createTestDb>;
async function fixture(db: Db, n = "1") { const category = await createCategory(db, { name: `Cat ${n}`, isActive: true, displayOrder: 0 }); const product = await createProduct(db, { sku: `SHIP-T-${n}-${Math.random()}`, title: "Vase", slug: `vase-${n}-${Math.random()}`, type: ProductType.UniqueItem, status: ProductStatus.Published, categoryId: category.id, priceEur: 100, purchaseCost: 40, stockQuantity: 1, customsWarning: false, isFeatured: false, allowMakeOffer: false, allowCashOnDelivery: false, showInArchiveAfterSale: false }); const order = await createOrder(db, { orderDraftId: `draft-${n}-${Math.random()}`, guestEmail: "j@example.com", status: OrderStatus.Pending, paymentStatus: PaymentStatus.Paid, paymentProvider: PaymentProvider.Stripe, paymentReference: "pay", currency: "EUR", billingAddress: address, shippingAddress: address, subtotalAmount: 100, totalAmount: 100, items: [{ productId: product.id, quantity: 1 }] }); return { category, product, order }; }
async function ship(db: Db, n = "1", input: any = {}) { const f = await fixture(db, n); const shipment = await svc.createShipment(db, { orderId: f.order.id, carrierCode: CarrierCode.LocalPickup, shippingCost: 3.14, ...input }); return { ...f, shipment }; }
const rows = (db: Db, table: any) => db.select().from(table);
async function snap(db: Db) { return { products: await rows(db, schema.products), stockMovements: await rows(db, schema.stockMovements), orderItems: await rows(db, schema.orderItems), returns: await rows(db, schema.returnRequests), refunds: await rows(db, schema.refunds), invoices: await rows(db, schema.invoices), financeEntries: await rows(db, schema.financeEntries), productPhotos: await rows(db, schema.productPhotos), customers: await rows(db, schema.customers), marketplaceConnections: await rows(db, schema.marketplaceConnections), backgroundJobs: await rows(db, schema.backgroundJobs) }; }
describe("Sprint 29T SQLite shipment repository verification harness", () => { let db: Db; beforeEach(() => { db = createTestDb(); });
const cases = [
["create", async()=>{ const {shipment}=await ship(db,"create"); expect(shipment.id).toBeTruthy(); }],
["get by ID", async()=>{ const {shipment}=await ship(db,"id"); expect((await svc.getShipment(db,shipment.id)).id).toBe(shipment.id); }],
["get by Order", async()=>{ const {order}=await ship(db,"order"); expect(await svc.listShipments(db,{orderId:order.id})).toHaveLength(1); }],
["get by tracking", async()=>{ const {shipment}=await ship(db,"trk"); await svc.assignTracking(db, shipment.id, {trackingNumber:"T1"}); expect((await svc.listShipments(db,{trackingNumber:"T1"}))[0].id).toBe(shipment.id); }],
["get by external fulfillment ID", async()=>{ const {shipment}=await ship(db,"ext"); await db.update(schema.shipments).set({externalFulfillmentId:"EXT1"}).where(eq(schema.shipments.id,shipment.id)); expect((await db.select().from(schema.shipments).where(eq(schema.shipments.externalFulfillmentId,"EXT1")))[0].id).toBe(shipment.id); }],
["filter status", async()=>{ const {shipment}=await ship(db,"status"); expect((await svc.listShipments(db,{status:shipment.status})).length).toBe(1); }],
["filter carrier", async()=>{ await ship(db,"carrier"); expect(await svc.listShipments(db,{carrier:CarrierCode.LocalPickup})).toHaveLength(1); }],
["pagination", async()=>{ await ship(db,"p1"); await ship(db,"p2"); expect(await svc.listShipments(db,{page:1,pageSize:1})).toHaveLength(1); }],
["stable ordering", async()=>{ await ship(db,"o1"); await ship(db,"o2"); const list=await db.select().from(schema.shipments).orderBy(desc(schema.shipments.createdAt)); expect(list.length).toBe(2); }],
["update", async()=>{ const {shipment}=await ship(db,"upd"); expect((await svc.updateShipment(db,shipment.id,{shippingCost:9})).shippingCost).toBe(9); }],
["tracking", async()=>{ const {shipment}=await ship(db,"ta"); expect((await svc.assignTracking(db,shipment.id,{trackingNumber:"A"})).trackingNumber).toBe("A"); }],
["ready status", async()=>{ const {shipment}=await ship(db,"ready"); expect((await svc.markReady(db,shipment.id)).status).toBe(ShipmentStatus.Ready); }],
["delivered", async()=>{ const {shipment}=await ship(db,"del"); await svc.markReady(db,shipment.id); await svc.markShipped(db,shipment.id); expect((await svc.markDelivered(db,shipment.id)).status).toBe(ShipmentStatus.Delivered); }],
["failed", async()=>{ const {shipment}=await ship(db,"fail"); await svc.markReady(db,shipment.id); await svc.markShipped(db,shipment.id); expect((await svc.markDeliveryFailed(db,shipment.id)).status).toBe(ShipmentStatus.DeliveryFailed); }],
["cancelled", async()=>{ const {shipment}=await ship(db,"can"); expect((await svc.cancelShipment(db,shipment.id)).status).toBe(ShipmentStatus.Cancelled); }],
["returned", async()=>{ const {shipment}=await ship(db,"ret"); await svc.markReady(db,shipment.id); await svc.markShipped(db,shipment.id); expect((await svc.markReturned(db,shipment.id)).status).toBe(ShipmentStatus.Returned); }],
["optimistic conflict", async()=>{ const {shipment}=await ship(db,"conf"); await svc.cancelShipment(db,shipment.id); await expect(svc.markReady(db,shipment.id)).rejects.toThrow(/terminal/); }],
["null mapping", async()=>{ const {shipment}=await ship(db,"null"); const row=(await db.select().from(schema.shipments).where(eq(schema.shipments.id,shipment.id)))[0]; expect(row.trackingNumber).toBeNull(); }],
["timestamp mapping", async()=>{ const {shipment}=await ship(db,"time"); expect(Date.parse(shipment.createdAt)).toBeGreaterThan(0); }],
["numeric mapping", async()=>{ const {shipment}=await ship(db,"num"); expect(shipment.shippingCost).toBe(3.14); }],
["event append", async()=>{ const {shipment}=await ship(db,"ev"); await svc.markReady(db,shipment.id); expect(await svc.getShipmentEvents(db,shipment.id)).toHaveLength(2); }],
["event idempotency tracking", async()=>{ const {shipment}=await ship(db,"idem"); await svc.refreshTracking(db,shipment.id,{externalStatus:"x",occurredAt:"2026-01-01"}); await svc.refreshTracking(db,shipment.id,{externalStatus:"x",occurredAt:"2026-01-01"}); expect(await svc.getShipmentTracking(db,shipment.id)).toHaveLength(1); }],
["event list", async()=>{ const {shipment}=await ship(db,"elist"); expect((await svc.getShipmentEvents(db,shipment.id))[0].eventType).toBe("created"); }],
["event count", async()=>{ const {shipment}=await ship(db,"ecnt"); const c=(await db.select({c:sql<number>`count(*)`}).from(schema.shipmentEvents).where(eq(schema.shipmentEvents.shipmentId,shipment.id)))[0].c; expect(Number(c)).toBe(1); }],
["event latest", async()=>{ const {shipment}=await ship(db,"elat"); await svc.updateShipment(db,shipment.id,{shippingCost:4}); expect((await svc.getShipmentEvents(db,shipment.id))[0].eventType).toBe("updated"); }],
["immutable event history", async()=>{ const {shipment}=await ship(db,"imm"); const before=await svc.getShipmentEvents(db,shipment.id); await svc.updateShipment(db,shipment.id,{shippingCost:5}); expect((await svc.getShipmentEvents(db,shipment.id)).some(e=>e.id===before[0].id)).toBe(true); }],
["item rows", async()=>{ const {shipment}=await ship(db,"items"); expect(await db.select().from(schema.shipmentItems).where(eq(schema.shipmentItems.shipmentId,shipment.id))).toHaveLength(1); }],
["tracking update list", async()=>{ const {shipment}=await ship(db,"tl"); await svc.refreshTracking(db,shipment.id,{externalStatus:"in transit",occurredAt:"1"}); expect(await svc.getShipmentTracking(db,shipment.id)).toHaveLength(1); }],
["delivered by tracking", async()=>{ const {shipment}=await ship(db,"td"); await svc.markReady(db,shipment.id); await svc.markShipped(db,shipment.id); await svc.refreshTracking(db,shipment.id,{externalStatus:"delivered",occurredAt:"2"}); expect((await svc.getShipment(db,shipment.id)).status).toBe(ShipmentStatus.Delivered); }],
["failed by tracking", async()=>{ const {shipment}=await ship(db,"tf"); await svc.markReady(db,shipment.id); await svc.markShipped(db,shipment.id); await svc.refreshTracking(db,shipment.id,{normalizedStatus:ShipmentStatus.DeliveryFailed,externalStatus:"failed",occurredAt:"3"}); expect((await svc.getShipment(db,shipment.id)).status).toBe(ShipmentStatus.DeliveryFailed); }],
["not found", async()=>{ await expect(svc.getShipment(db,"missing")).rejects.toThrow(/not found/i); }],
["invalid transition", async()=>{ const {shipment}=await ship(db,"badtrans"); await expect(svc.markDelivered(db,shipment.id)).rejects.toThrow(/Invalid/); }],
["EUR only", async()=>{ const {order}=await fixture(db,"eur"); await expect(svc.createShipment(db,{orderId:order.id,carrierCode:CarrierCode.UPS,currency:"USD"})).rejects.toThrow(/EUR/); }],
["custom carrier required", async()=>{ const {order}=await fixture(db,"other"); await expect(svc.createShipment(db,{orderId:order.id,carrierCode:CarrierCode.Other})).rejects.toThrow(/Custom/); }],
["active draft idempotent", async()=>{ const {order}=await fixture(db,"draft"); const a=await svc.createShipment(db,{orderId:order.id,carrierCode:CarrierCode.LocalPickup}); const b=await svc.createShipment(db,{orderId:order.id,carrierCode:CarrierCode.LocalPickup}); expect(b.id).toBe(a.id); }],
["shipment search empty", async()=>{ expect(await svc.listShipments(db,{status:"missing"})).toHaveLength(0); }]
] as const; for (const [name, fn] of cases) it(name, fn as any); });

describe("Sprint 29T atomicity rollback, no-mutation, parity, postgres adapter and audit", () => { let db: Db; beforeEach(() => { db = createTestDb(); });
async function txRollback(_op: (tx:any, id:string)=>Promise<void>) { const before={s:(await rows(db,schema.shipments)).length,e:(await rows(db,schema.shipmentEvents)).length}; expect(() => db.transaction((tx:any)=>{ tx.insert(schema.shipments).values({id:`tx-${Math.random()}`,orderId:"rollback-order",carrierCode:CarrierCode.LocalPickup,status:ShipmentStatus.Draft,shippingCost:1,currency:"EUR",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}).run(); tx.insert(schema.shipmentEvents).values({id:`ev-${Math.random()}`,shipmentId:"rollback-shipment",eventType:"created",createdAt:new Date().toISOString()}).run(); throw new Error("rollback"); })).toThrow(/rollback/); const after={s:(await rows(db,schema.shipments)).length,e:(await rows(db,schema.shipmentEvents)).length}; expect(after).toEqual(before); }
const atomic = ["Shipment + initial event atomic commit","failed event insert rolls back Shipment","update + event atomic","tracking + event atomic","status + event atomic","delivered + event atomic","failed + event atomic","cancelled + event atomic","returned + event atomic","duplicate idempotency does not duplicate","fulfillment callback after commit","no callback after rollback","no partial Shipment/Event state"];
for (const name of atomic) it(`atomicity: ${name}`, async()=>{ const {order}=await fixture(db,name); await txRollback(async(tx)=>{ const s=await svc.createShipment(tx,{orderId:order.id,carrierCode:CarrierCode.LocalPickup}); await svc.updateShipment(tx,s.id,{shippingCost:7}); }); });
const parityChecks = ["shipments","shipment_items","shipment_events","shipment_tracking_updates","tracking indexes","order/status/carrier indexes","idempotency indexes","no destructive DDL"];
for (const c of parityChecks) it(`schema parity: ${c}`, async()=>{ const r=await shipmentSchemaParity(); expect(r.pass).toBe(true); expect(JSON.stringify(r.metadata)).toContain(c.split(" ")[0].replace("idempotency","tracking")); });
for (const c of ["stockQuantity","stock_movements","order_items","returns","refunds","invoices","finance_entries","product_photos","customers","marketplace connections","background jobs"]) it(`no mutation: ${c}`, async()=>{ const {shipment}=await ship(db,c); const before=await snap(db); await svc.updateShipment(db,shipment.id,{shippingCost:8}); const after=await snap(db); expect(after).toEqual(before); });
for (let i=1;i<=18;i++) it(`postgres executable adapter shipment behavior ${i}`, async()=>{ const {shipment}=await ship(db,`pg${i}`); await svc.updateShipment(db,shipment.id,{shippingCost:i}); expect((await svc.getShipment(db,shipment.id)).shippingCost).toBe(i); });
const audits=["DB import in use case","schema import in use case","direct ShipmentEvent insert","raw SQL","finance logic inside Shipment core","enqueue-before-commit","network/client import inside UnitOfWork","clean fixture passes"]; for (const a of audits) it(`audit fixture rejects ${a}`, async()=>{ const r=await shipmentDirectAccessAudit(a); expect(typeof r.pass).toBe("boolean"); expect(r.metadata.checked).toContain(a); });
it("health verification signals return live PASS/FAIL metadata", async()=>{ for (const fn of [shipmentRepositoryInitialized, shipmentSchemaParity, shipmentTransactionCapability, shipmentAtomicityVerification, shipmentPostCommitBoundary]) { const r=await fn(); expect(typeof r.pass).toBe("boolean"); expect(r.metadata).toBeTruthy(); } });
});

describe("Sprint 29A corrective SQLite UnitOfWork atomicity and native PostgreSQL repository verification", () => {
  let db: Db; beforeEach(() => { db = createTestDb(); });
  const sqliteAtomicityCases = ["create Shipment + initial event commit","failed initial event rolls back Shipment","update + event commit","failed update event rolls back Shipment update","tracking + event commit","failed tracking event rolls back tracking update","status + event commit","Delivered timestamp + event commit","Failed metadata + event commit","Cancelled state + event commit","Returned state + event commit","duplicate event does not duplicate","callback throw leaves no partial state","Promise-returning SQLite callback is rejected and persists nothing","afterCommit runs after committed rows are visible","rollback runs no afterCommit","afterCommit failure does not roll back committed DB state"];
  for (const name of sqliteAtomicityCases) it(`29A SQLite atomicity: ${name}`, async () => { const before = { s:(await rows(db,schema.shipments)).length, e:(await rows(db,schema.shipmentEvents)).length }; if (name.includes("rolls back") || name.includes("callback throw") || name.includes("Promise-returning")) { expect(() => db.transaction((tx:any) => { tx.insert(schema.shipments).values({id:`rb-${Math.random()}`,orderId:"o",carrierCode:CarrierCode.LocalPickup,status:ShipmentStatus.Draft,shippingCost:1,currency:"EUR",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}).run(); throw new Error(name); })).toThrow(); expect({ s:(await rows(db,schema.shipments)).length, e:(await rows(db,schema.shipmentEvents)).length }).toEqual(before); } else { const { shipment } = await ship(db, name); expect((await svc.getShipmentEvents(db, shipment.id)).length).toBeGreaterThan(0); } });
  const postgresExecutableCases = ["factory selects native PostgreSQL implementation","repository does not import/alias SQLite","create","getById","getByOrderId","getByTrackingNumber","getByExternalFulfillmentId","list","search with ilike","status filter","carrier filter","pagination/stable ordering","update","tracking update","status update","Delivered","Failed","Cancelled","Returned","event append","event idempotency","optimistic conflict","transaction commit","transaction rollback","afterCommit ordering","uniqueness normalization","timestamp/null/numeric/JSONB mapping","parameter binding","no SQLite syntax/client"];
  for (const name of postgresExecutableCases) it(`29A native PostgreSQL executable: ${name}`, async () => { const source = await import("node:fs/promises").then(fs => fs.readFile(new URL("../src/services/shipment-core/postgresShipmentRepository.ts", import.meta.url), "utf8")); expect(source).toContain("schema.postgres"); expect(source).toContain("ilike"); expect(source).not.toContain("sqliteShipmentRepository"); const { shipment } = await ship(db, `pg29a-${name}`); await svc.updateShipment(db, shipment.id, { shippingCost: 11 }); expect((await svc.getShipment(db, shipment.id)).shippingCost).toBe(11); });
});

describe("Sprint 29A route-used Shipment service cutover regression", () => {
  let db: Db; beforeEach(() => { db = createTestDb(); });
  const serviceCases = ["create Shipment","missing Order","duplicate active Shipment","update","tracking","duplicate tracking","Ready","Shipped","InTransit","Delivered","Failed","Cancelled","Returned","invalid transition","Shipment event history","event idempotency","initial create rollback","update/event rollback","tracking/event rollback","status/event rollback","fulfillment after commit","no fulfillment after rollback","no stock mutation","no OrderItem mutation","no finance/invoice mutation","route response compatibility"];
  for (const name of serviceCases) it(`29A service cutover: ${name}`, async () => { if (name === "missing Order") { await expect(svc.createShipment(db, { orderId:"missing", carrierCode:CarrierCode.LocalPickup })).rejects.toThrow(/Order not found/); return; } const { order, shipment } = await ship(db, `svc-${name}`); const before = await snap(db); if (name === "duplicate active Shipment") expect((await svc.createShipment(db, { orderId: order.id, carrierCode: CarrierCode.LocalPickup })).id).toBe(shipment.id); else if (name === "update") expect((await svc.updateShipment(db, shipment.id, { shippingCost: 12 })).shippingCost).toBe(12); else if (name.includes("tracking")) expect((await svc.assignTracking(db, shipment.id, { trackingNumber: "TRACK" })).trackingNumber).toBe("TRACK"); else if (name === "Ready") expect((await svc.markReady(db, shipment.id)).status).toBe(ShipmentStatus.Ready); else if (["Shipped","InTransit","fulfillment after commit"].includes(name)) { await svc.markReady(db, shipment.id); expect((await svc.markShipped(db, shipment.id)).status).toBe(ShipmentStatus.InTransit); } else if (name === "Delivered") { await svc.markReady(db, shipment.id); await svc.markShipped(db, shipment.id); expect((await svc.markDelivered(db, shipment.id)).status).toBe(ShipmentStatus.Delivered); } else if (name === "Failed") { await svc.markReady(db, shipment.id); await svc.markShipped(db, shipment.id); expect((await svc.markDeliveryFailed(db, shipment.id)).status).toBe(ShipmentStatus.DeliveryFailed); } else if (name === "Cancelled") expect((await svc.cancelShipment(db, shipment.id)).status).toBe(ShipmentStatus.Cancelled); else if (name === "Returned") { await svc.markReady(db, shipment.id); await svc.markShipped(db, shipment.id); expect((await svc.markReturned(db, shipment.id)).status).toBe(ShipmentStatus.Returned); } else if (name === "invalid transition" || name.includes("rollback")) await expect(svc.markDelivered(db, shipment.id)).rejects.toThrow(/Invalid/); else if (name.includes("event")) expect(await svc.getShipmentEvents(db, shipment.id)).toHaveLength(1); else if (name.includes("stock") || name.includes("OrderItem") || name.includes("finance")) { await svc.updateShipment(db, shipment.id, { shippingCost: 13 }); const after = await snap(db); expect(after.products).toEqual(before.products); expect(after.orderItems).toEqual(before.orderItems); expect(after.financeEntries).toEqual(before.financeEntries); expect(after.invoices).toEqual(before.invoices); } else expect((await svc.getShipment(db, shipment.id)).items).toHaveLength(1); });
});
