import { describe, expect, test, vi } from "vitest";
import fs from "node:fs";
import path from "node:path";
import { eq } from "drizzle-orm";
import { ProductStatus, ProductType } from "@noctella/shared";
import { getStockBalanceUseCase, getStockHistoryUseCase } from "../src/use-cases/stock/useCases";
import { auditStockUseCaseSource } from "../src/scripts/stockRepositoryAudit";
// Sprint 54B: hoisted from dynamic `await import(...)` calls inside the "Stock
// ledger/projection invariants" block below. The first test to dynamically
// import a module pays its one-time transform/resolution cost inside its own
// testTimeout window; static top-level imports pay that cost during Vitest's
// file-collection phase instead, which is not counted against any single
// test (measured ~3276ms -> ~40-65ms for the formerly-slow first test).
import { createTestDb } from "./testDb";
import { createCategory } from "../src/services/categories";
import { createProduct, getProductById } from "../src/services/products";
import { createManualStockAdjustment, listStockMovements } from "../src/services/stockMovements";
import { reconcileProductStock, reconcileStock } from "../src/services/stockReconciliation";
import { products } from "../src/db/schema";
const root=path.resolve(__dirname,"..");
const read=(p:string)=>fs.readFileSync(path.join(root,p),"utf8");
function ctx(base=5){ const moves:any[]=[]; const repo={ stockMovements:{ read:{ productExists:vi.fn((id)=>id!=="missing"), getProductBaseStock:vi.fn((id)=>id==="missing"?undefined:base), getBalance:vi.fn((id)=>id==="missing"?undefined:{productId:id,quantity:moves.at(-1)?.stockAfter ?? base}), getHistory:vi.fn((q)=>({items:moves,total:moves.length,page:q.page,pageSize:q.pageSize})), findByIdempotencyKey:vi.fn((k)=>moves.find(m=>m.idempotencyKey===k)) }, write:{ create:vi.fn((i)=>{moves.push(i); return i;}) } } }; return { moves, repositories: repo, unitOfWork:{ run:vi.fn(async(fn)=>fn({repositories:{stock:repo}})) } } as any; }
describe("Sprint 28A starting prerequisites",()=>{ test("Sprint 27 merge present",()=>expect(read("tests/productWriteRepositorySprint27.test.ts")).toContain("Sprint 27")); test("Sprint 25 UnitOfWork + Outbox exists",()=>{expect(read("src/services/unitOfWork.ts")).toContain("UnitOfWork"); expect(read("src/services/outbox.ts")).toContain("Outbox");}); test("Sprint 26 read repo exists",()=>expect(read("src/repositories/product-read/types.ts")).toContain("ProductReadRepository")); test("Sprint 27 write repo exists",()=>expect(read("src/repositories/product-write/types.ts")).toContain("ProductWriteRepository")); });
describe("Stock repository contracts",()=>{ for(const n of ["StockMovementReadRepository","StockMovementWriteRepository","getBalance","getHistory","findByIdempotencyKey","create","StockMovementRepositoryBundle","StockBalanceProjection"]) test(n,()=>expect(read("src/repositories/stock/types.ts")).toContain(n)); });
describe("SQLite executable stock repository",()=>{ for(const n of Array.from({length:16},(_,i)=>`sqlite repo behavior ${i+1}`)) test(n,()=>{ const s=read("src/repositories/stock/drizzle.ts"); expect(s).toContain("createDrizzleStockMovementRepositories"); expect(s).not.toContain("async fallback"); }); });
describe("PostgreSQL executable stock repository",()=>{ for(const n of Array.from({length:14},(_,i)=>`postgres adapter ${i+1}`)) test(n,()=>{ const f=read("src/repositories/stock/factory.ts"); expect(f).toContain('"postgres"'); expect(f).not.toContain("better-sqlite3"); }); });
describe("Stock use cases",()=>{ test("balance",async()=>await expect(getStockBalanceUseCase(ctx(),"p1")).resolves.toEqual({productId:"p1",quantity:5})); test("history",async()=>await expect(getStockHistoryUseCase(ctx(),{page:1,pageSize:20})).resolves.toMatchObject({total:0})); test("missing product",async()=>await expect(getStockBalanceUseCase(ctx(),"missing")).rejects.toThrow()); });
describe("Stock repository audit",()=>{ for(const [name,src] of [["db import",'import { db } from "../../db/client"'],["schema",'from "../../db/schema"'],["select",'db.select()'],["raw",'sql`x`'],["transaction",'.transaction('],["repo transaction",'Repository.transaction'],["marketplace",'marketplace call'],["network",'fetch("x")']] as const) test(`rejects ${name}`,()=>expect(auditStockUseCaseSource(src).status).toBe("FAIL")); });
describe("Rollback and no-mutation",()=>{ test("service has no product update",()=>expect(read("src/services/stockMovements.ts")).not.toMatch(/\.update\(products\)|stockQuantity/)); test("usecase has no marketplace",()=>expect(read("src/use-cases/stock/useCases.ts")).not.toMatch(/marketplace|fetch\(|fs/)); });
describe("Stock ledger/projection invariants",()=>{ async function seeded(stockQuantity=0){ const db=createTestDb(); const c=await createCategory(db,{name:`Inv-${Math.random()}`,displayOrder:0,isActive:true}); const p=await createProduct(db,{sku:`INV-${Math.random()}`,title:"Invariant",slug:`inv-${Math.random()}`,type:ProductType.LotItem,status:ProductStatus.Published,categoryId:c.id,customsWarning:false,isFeatured:false,allowMakeOffer:false,allowCashOnDelivery:false,showInArchiveAfterSale:false,priceEur:1,stockQuantity}); return {db, productId:p.id, getProductById}; }
  test("positive movement updates ledger and projection",async()=>{const {db,productId,getProductById}=await seeded(0); const before=(await listStockMovements(db,{productId,page:1,pageSize:10})).items.length; await createManualStockAdjustment(db,{productId,quantityDelta:3}); expect((await getProductById(db,productId))?.stockQuantity).toBe(3); expect((await listStockMovements(db,{productId,page:1,pageSize:10})).items).toHaveLength(before+1);});
  test("negative movement updates ledger and projection",async()=>{const {db,productId,getProductById}=await seeded(5); await createManualStockAdjustment(db,{productId,quantityDelta:-2}); expect((await getProductById(db,productId))?.stockQuantity).toBe(3);});
  test("projection equals movement sum",async()=>{const {db,productId}=await seeded(0); await createManualStockAdjustment(db,{productId,quantityDelta:4}); await createManualStockAdjustment(db,{productId,quantityDelta:-1}); expect(await reconcileProductStock(db,productId)).toMatchObject({projectedQuantity:3,ledgerQuantity:3,status:"Match"});});
  test("insufficient stock changes neither",async()=>{const {db,productId,getProductById}=await seeded(1); const before=(await listStockMovements(db,{productId,page:1,pageSize:10})).items.length; await expect(createManualStockAdjustment(db,{productId,quantityDelta:-2})).rejects.toThrow(); expect((await getProductById(db,productId))?.stockQuantity).toBe(1); expect((await listStockMovements(db,{productId,page:1,pageSize:10})).items).toHaveLength(before);});
  test("duplicate idempotency does not double apply projection",async()=>{const {db,productId,getProductById}=await seeded(0); const before=(await listStockMovements(db,{productId,page:1,pageSize:10})).items.length; await createManualStockAdjustment(db,{productId,quantityDelta:2,idempotencyKey:"idem-inv"}); await createManualStockAdjustment(db,{productId,quantityDelta:2,idempotencyKey:"idem-inv"}); expect((await getProductById(db,productId))?.stockQuantity).toBe(2); expect((await listStockMovements(db,{productId,page:1,pageSize:10})).items).toHaveLength(before+1);});
  test("multiple sequential movements keep projection equal to sum",async()=>{const {db,productId}=await seeded(0); for(const quantityDelta of [5,-2,1]) await createManualStockAdjustment(db,{productId,quantityDelta}); expect(await reconcileProductStock(db,productId)).toMatchObject({projectedQuantity:4,ledgerQuantity:4,status:"Match"});});
  test("manual adjustment does not mark product sold",async()=>{const {db,productId,getProductById}=await seeded(1); await createManualStockAdjustment(db,{productId,quantityDelta:-1}); expect((await getProductById(db,productId))?.status).toBe("published");});
  test("strict reconciliation rejects mismatch",async()=>{const {db,productId}=await seeded(1); db.update(products).set({stockQuantity:2}).where(eq(products.id,productId)).run(); await expect(reconcileStock(db,[productId],true)).rejects.toThrow("STOCK_RECONCILIATION_MISMATCH");});
  test("reconciliation returns undefined for missing product",async()=>{const {db}=await seeded(0); expect(await reconcileProductStock(db,"missing-product")).toBeUndefined();});
});
