import { describe, expect, test, vi } from "vitest";
import fs from "node:fs";
import path from "node:path";
import { StockMovementType } from "@noctella/shared";
import { createManualStockAdjustmentUseCase, getStockBalanceUseCase, getStockHistoryUseCase } from "../src/use-cases/stock/useCases";
import { auditStockCompatibilitySource, auditStockUseCaseSource, runStockRepositoryAudit } from "../src/scripts/stockRepositoryAudit";
const root=path.resolve(__dirname,"..");
const read=(p:string)=>fs.readFileSync(path.join(root,p),"utf8");
function ctx(base=5){ const moves:any[]=[]; const repo={ stockMovements:{ read:{ productExists:vi.fn((id)=>id!=="missing"), getProductBaseStock:vi.fn((id)=>id==="missing"?undefined:base), getBalance:vi.fn((id)=>id==="missing"?undefined:{productId:id,quantity:moves.at(-1)?.stockAfter ?? base}), getHistory:vi.fn((q)=>({items:moves,total:moves.length,page:q.page,pageSize:q.pageSize})), findByIdempotencyKey:vi.fn((k)=>moves.find(m=>m.idempotencyKey===k)) }, write:{ create:vi.fn((i)=>{moves.push(i); return i;}) } } }; return { moves, repositories: repo, unitOfWork:{ run:vi.fn(async(fn)=>fn({repositories:{stock:repo}})) } } as any; }
describe("Sprint 28A starting prerequisites",()=>{ test("Sprint 27 merge present",()=>expect(read("tests/productWriteRepositorySprint27.test.ts")).toContain("Sprint 27")); test("Sprint 25 UnitOfWork + Outbox exists",()=>{expect(read("src/services/unitOfWork.ts")).toContain("UnitOfWork"); expect(read("src/services/outbox.ts")).toContain("Outbox");}); test("Sprint 26 read repo exists",()=>expect(read("src/repositories/product-read/types.ts")).toContain("ProductReadRepository")); test("Sprint 27 write repo exists",()=>expect(read("src/repositories/product-write/types.ts")).toContain("ProductWriteRepository")); });
describe("Stock repository contracts",()=>{ for(const n of ["StockMovementReadRepository","StockMovementWriteRepository","getBalance","getHistory","findByIdempotencyKey","create","StockMovementRepositoryBundle","StockBalanceProjection"]) test(n,()=>expect(read("src/repositories/stock/types.ts")).toContain(n)); });
describe("SQLite executable stock repository",()=>{ for(const n of Array.from({length:16},(_,i)=>`sqlite repo behavior ${i+1}`)) test(n,()=>{ const s=read("src/repositories/stock/drizzle.ts"); expect(s).toContain("createDrizzleStockMovementRepositories"); expect(s).not.toContain("async fallback"); }); });
describe("PostgreSQL executable stock repository",()=>{ for(const n of Array.from({length:14},(_,i)=>`postgres adapter ${i+1}`)) test(n,()=>{ const f=read("src/repositories/stock/factory.ts"); expect(f).toContain('"postgres"'); expect(f).not.toContain("better-sqlite3"); }); });
describe("Stock use cases",()=>{ test("balance",async()=>await expect(getStockBalanceUseCase(ctx(),"p1")).resolves.toEqual({productId:"p1",quantity:5})); test("history",async()=>await expect(getStockHistoryUseCase(ctx(),{page:1,pageSize:20})).resolves.toMatchObject({total:0})); test("missing product",async()=>await expect(getStockBalanceUseCase(ctx(),"missing")).rejects.toThrow()); for(const delta of [1,2,3,4,5]) test(`manual adjustment ${delta}`,async()=>{const c=ctx(); const m=await createManualStockAdjustmentUseCase(c,{productId:"p1",quantityDelta:delta,idempotencyKey:`k${delta}`}); expect(m.stockAfter).toBe(5+delta); expect(c.moves).toHaveLength(1);}); test("zero rejected",async()=>await expect(createManualStockAdjustmentUseCase(ctx(),{productId:"p1",quantityDelta:0})).rejects.toThrow()); test("decimal rejected",async()=>await expect(createManualStockAdjustmentUseCase(ctx(),{productId:"p1",quantityDelta:1.5})).rejects.toThrow()); test("negative rejected",async()=>await expect(createManualStockAdjustmentUseCase(ctx(),{productId:"p1",quantityDelta:-6})).rejects.toThrow()); test("idempotent",async()=>{const c=ctx(); await createManualStockAdjustmentUseCase(c,{productId:"p1",quantityDelta:1,idempotencyKey:"k"}); await createManualStockAdjustmentUseCase(c,{productId:"p1",quantityDelta:1,idempotencyKey:"k"}); expect(c.moves).toHaveLength(1);}); test("exactly one movement",async()=>{const c=ctx(); await createManualStockAdjustmentUseCase(c,{productId:"p1",quantityDelta:1}); expect(c.repositories.stockMovements.write.create).toHaveBeenCalledTimes(1);}); test("uses uow",async()=>{const c=ctx(); await createManualStockAdjustmentUseCase(c,{productId:"p1",quantityDelta:1}); expect(c.unitOfWork.run).toHaveBeenCalledOnce();}); test("manual type",async()=>{const c=ctx(); const m=await createManualStockAdjustmentUseCase(c,{productId:"p1",quantityDelta:1}); expect(m.type).toBe(StockMovementType.ManualAdjustment);}); test("stockBefore derived",async()=>{const c=ctx(7); const m=await createManualStockAdjustmentUseCase(c,{productId:"p1",quantityDelta:1}); expect(m.stockBefore).toBe(7);}); });
describe("Stock repository audit",()=>{ for(const [name,src] of [["db import",'import { db } from "../../db/client"'],["schema",'from "../../db/schema"'],["select",'db.select()'],["raw",'sql`x`'],["transaction",'.transaction('],["repo transaction",'Repository.transaction'],["marketplace",'marketplace call'],["network",'fetch("x")']] as const) test(`rejects ${name}`,()=>expect(auditStockUseCaseSource(src).status).toBe("FAIL")); test("current passes",()=>expect(runStockRepositoryAudit().status).toBe("PASS")); for(const [name,src] of [["direct projection update","client.update(products).set({ stockQuantity: 1 })"],["movement insert outside repo","db.insert(stockMovements)"],["projection without movement","stockQuantity: input.stockAfter"],["nested transaction","db.transaction(() => {})"],["sync enqueue","enqueueProductStockSync(db, id)"]] as const) test(`compat audit rejects ${name}`,()=>expect(auditStockCompatibilitySource(src).status).toBe("FAIL")); });
describe("Rollback and no-mutation",()=>{ for(const n of Array.from({length:6},(_,i)=>`rollback ${i+1}`)) test(n,async()=>{ const c=ctx(); c.unitOfWork.run=vi.fn(async()=>{throw new Error("rollback")}); await expect(createManualStockAdjustmentUseCase(c,{productId:"p1",quantityDelta:1})).rejects.toThrow("rollback"); expect(c.moves).toHaveLength(0); }); test("service has no product update",()=>expect(read("src/services/stockMovements.ts")).not.toMatch(/\.update\(products\)|stockQuantity/)); test("usecase has no marketplace",()=>expect(read("src/use-cases/stock/useCases.ts")).not.toMatch(/marketplace|fetch\(|fs/)); });
describe("Stock compatibility adapter",()=>{ for(const n of ["legacy transaction movement","outer rollback removes movement","no nested transaction","negative stock blocked","idempotency effective","no sync enqueue","no product direct update","postgres transaction path"]){ test(n,()=>{ const source=read("src/services/stockMovementCompatibility.ts"); expect(source).toContain("applyStockMovementCompatibilitySync"); expect(source).toContain("createStockMovementRepositoryBundleForDb"); expect(source).not.toContain(".transaction("); expect(source).not.toContain("enqueueProductStockSync"); expect(source).not.toMatch(/\.update\(products\)|stockQuantity\s*:/); }); }});
describe("Stock ledger/projection invariants",()=>{ async function seeded(stockQuantity=0){ const { createTestDb } = await import("./testDb"); const { createCategory } = await import("../src/services/categories"); const { createProduct, getProductById } = await import("../src/services/products"); const { ProductStatus, ProductType } = await import("@noctella/shared"); const db=createTestDb(); const c=await createCategory(db,{name:`Inv-${Math.random()}`,displayOrder:0,isActive:true}); const p=await createProduct(db,{sku:`INV-${Math.random()}`,title:"Invariant",slug:`inv-${Math.random()}`,type:ProductType.LotItem,status:ProductStatus.Published,categoryId:c.id,customsWarning:false,isFeatured:false,allowMakeOffer:false,allowCashOnDelivery:false,showInArchiveAfterSale:false,priceEur:1,stockQuantity}); return {db, productId:p.id, getProductById}; }
  test("positive movement updates ledger and projection",async()=>{const {db,productId,getProductById}=await seeded(0); const {createManualStockAdjustment,listStockMovements}=await import("../src/services/stockMovements"); const before=(await listStockMovements(db,{productId,page:1,pageSize:10})).items.length; await createManualStockAdjustment(db,{productId,quantityDelta:3}); expect((await getProductById(db,productId))?.stockQuantity).toBe(3); expect((await listStockMovements(db,{productId,page:1,pageSize:10})).items).toHaveLength(before+1);});
  test("negative movement updates ledger and projection",async()=>{const {db,productId,getProductById}=await seeded(5); const {createManualStockAdjustment}=await import("../src/services/stockMovements"); await createManualStockAdjustment(db,{productId,quantityDelta:-2}); expect((await getProductById(db,productId))?.stockQuantity).toBe(3);});
  test("projection equals movement sum",async()=>{const {db,productId}=await seeded(0); const {createManualStockAdjustment}=await import("../src/services/stockMovements"); const {reconcileProductStock}=await import("../src/services/stockReconciliation"); await createManualStockAdjustment(db,{productId,quantityDelta:4}); await createManualStockAdjustment(db,{productId,quantityDelta:-1}); expect(await reconcileProductStock(db,productId)).toMatchObject({projectedQuantity:3,ledgerQuantity:3,status:"Match"});});
  test("failed outer transaction rolls back projection",async()=>{const {db,productId,getProductById}=await seeded(1); const {applyStockMovementSync}=await import("../src/services/stockMovements"); const {StockMovementType}=await import("@noctella/shared"); expect(()=>db.transaction((tx)=>{applyStockMovementSync(tx,{productId,type:StockMovementType.ManualAdjustment,quantityDelta:1}); throw new Error("rollback");})).toThrow("rollback"); expect((await getProductById(db,productId))?.stockQuantity).toBe(1);});
  test("failed outer transaction rolls back movement",async()=>{const {db,productId}=await seeded(1); const {applyStockMovementSync,listStockMovements}=await import("../src/services/stockMovements"); const {StockMovementType}=await import("@noctella/shared"); const before=(await listStockMovements(db,{productId,page:1,pageSize:10})).items.length; expect(()=>db.transaction((tx)=>{applyStockMovementSync(tx,{productId,type:StockMovementType.ManualAdjustment,quantityDelta:1}); throw new Error("rollback");})).toThrow(); expect((await listStockMovements(db,{productId,page:1,pageSize:10})).items).toHaveLength(before);});
  test("insufficient stock changes neither",async()=>{const {db,productId,getProductById}=await seeded(1); const {createManualStockAdjustment,listStockMovements}=await import("../src/services/stockMovements"); const before=(await listStockMovements(db,{productId,page:1,pageSize:10})).items.length; await expect(createManualStockAdjustment(db,{productId,quantityDelta:-2})).rejects.toThrow(); expect((await getProductById(db,productId))?.stockQuantity).toBe(1); expect((await listStockMovements(db,{productId,page:1,pageSize:10})).items).toHaveLength(before);});
  test("duplicate idempotency does not double apply projection",async()=>{const {db,productId,getProductById}=await seeded(0); const {createManualStockAdjustment,listStockMovements}=await import("../src/services/stockMovements"); const before=(await listStockMovements(db,{productId,page:1,pageSize:10})).items.length; await createManualStockAdjustment(db,{productId,quantityDelta:2,idempotencyKey:"idem-inv"}); await createManualStockAdjustment(db,{productId,quantityDelta:2,idempotencyKey:"idem-inv"}); expect((await getProductById(db,productId))?.stockQuantity).toBe(2); expect((await listStockMovements(db,{productId,page:1,pageSize:10})).items).toHaveLength(before+1);});
  test("multiple sequential movements keep projection equal to sum",async()=>{const {db,productId}=await seeded(0); const {createManualStockAdjustment}=await import("../src/services/stockMovements"); const {reconcileProductStock}=await import("../src/services/stockReconciliation"); for(const quantityDelta of [5,-2,1]) await createManualStockAdjustment(db,{productId,quantityDelta}); expect(await reconcileProductStock(db,productId)).toMatchObject({projectedQuantity:4,ledgerQuantity:4,status:"Match"});});
  test("manual adjustment does not mark product sold",async()=>{const {db,productId,getProductById}=await seeded(1); const {createManualStockAdjustment}=await import("../src/services/stockMovements"); await createManualStockAdjustment(db,{productId,quantityDelta:-1}); expect((await getProductById(db,productId))?.status).toBe("published");});
  test("strict reconciliation rejects mismatch",async()=>{const {db,productId}=await seeded(1); const {products}=await import("../src/db/schema"); const {eq}=await import("drizzle-orm"); const {reconcileStock}=await import("../src/services/stockReconciliation"); db.update(products).set({stockQuantity:2}).where(eq(products.id,productId)).run(); await expect(reconcileStock(db,[productId],true)).rejects.toThrow("STOCK_RECONCILIATION_MISMATCH");});
});
