import Stripe from "stripe"; import request from "supertest"; import { afterEach,describe,expect,it,vi } from "vitest"; import { StripeCheckoutAdapter } from "../src/payments/stripe"; import { processStripeWebhook } from "../src/services/stripePayments"; import app from "../src/app";
vi.hoisted(()=>{process.env.DATABASE_DRIVER="sqlite";process.env.DATABASE_URL=":memory:";});
const secret="whsec_sprint127_test"; const payload=JSON.stringify({id:"evt_test",type:"checkout.session.completed",livemode:false,data:{object:{id:"cs_test",payment_status:"paid",currency:"eur",amount_total:100,payment_intent:"pi_test",metadata:{paymentId:"payment-1"},client_reference_id:"payment-1"}}});
describe("Sprint 127 Stripe webhook security",()=>{
 afterEach(()=>vi.unstubAllEnvs());
 it("rejects live Stripe keys",()=>expect(()=>new StripeCheckoutAdapter("sk_live_forbidden")).toThrow("STRIPE_TEST_MODE_REQUIRED"));
 it("verifies exact raw bytes and normalizes required facts",()=>{const stripe=new Stripe("sk_test_placeholder"),header=stripe.webhooks.generateTestHeaderString({payload,secret});const event=new StripeCheckoutAdapter("sk_test_placeholder").constructWebhookEvent(Buffer.from(payload),header,secret);expect(event).toMatchObject({eventId:"evt_test",eventType:"checkout.session.completed",livemode:false,sessionId:"cs_test",paymentStatus:"paid",currency:"eur",amountTotal:100,paymentIntentId:"pi_test",metadataPaymentId:"payment-1",clientReferenceId:"payment-1"});});
 it("rejects a validly signed live-mode event before database processing",async()=>{vi.stubEnv("STRIPE_WEBHOOK_SECRET",secret);const livePayload=JSON.stringify({...JSON.parse(payload),livemode:true});const stripe=new Stripe("sk_test_placeholder"),header=stripe.webhooks.generateTestHeaderString({payload:livePayload,secret});const database=new Proxy({}, {get(){throw new Error("DATABASE_TOUCHED")}}) as any;await expect(processStripeWebhook(database,Buffer.from(livePayload),header,new StripeCheckoutAdapter("sk_test_placeholder"))).rejects.toThrow("STRIPE_LIVE_EVENT_REJECTED");});
 it("does not touch the database when signature verification fails",async()=>{vi.stubEnv("STRIPE_WEBHOOK_SECRET",secret);const database=new Proxy({}, {get(){throw new Error("DATABASE_TOUCHED")}}) as any;await expect(processStripeWebhook(database,Buffer.from(payload),"t=1,v1=bad",new StripeCheckoutAdapter("sk_test_placeholder"))).rejects.not.toThrow("DATABASE_TOUCHED");});
 it("rejects an invalid signature",()=>expect(()=>new StripeCheckoutAdapter("sk_test_placeholder").constructWebhookEvent(Buffer.from(payload),"t=1,v1=bad",secret)).toThrow());
 it("rejects the wrong webhook secret",()=>{const stripe=new Stripe("sk_test_placeholder"),header=stripe.webhooks.generateTestHeaderString({payload,secret});expect(()=>new StripeCheckoutAdapter("sk_test_placeholder").constructWebhookEvent(Buffer.from(payload),header,"whsec_wrong")).toThrow();});
 it("rejects body mutation or reserialization after signing",()=>{const stripe=new Stripe("sk_test_placeholder"),header=stripe.webhooks.generateTestHeaderString({payload,secret});expect(()=>new StripeCheckoutAdapter("sk_test_placeholder").constructWebhookEvent(Buffer.from(`${payload} `),header,secret)).toThrow();});
 it("rejects a missing signature at the raw webhook route",async()=>{expect((await request(app).post("/api/webhooks/stripe").set("content-type","application/json").send(payload)).status).toBe(400);});
 it("fails closed with 503 when Stripe configuration is missing",async()=>{vi.stubEnv("STRIPE_SECRET_KEY","");expect((await request(app).post("/api/webhooks/stripe").set("content-type","application/json").set("stripe-signature","invalid").send(payload)).status).toBe(503);});
 it("rejects an invalid route signature before domain processing",async()=>{vi.stubEnv("STRIPE_SECRET_KEY","sk_test_placeholder");vi.stubEnv("STRIPE_WEBHOOK_SECRET",secret);expect((await request(app).post("/api/webhooks/stripe").set("content-type","application/json").set("stripe-signature","t=1,v1=bad").send(payload)).status).toBe(400);});
});
