import Database from "better-sqlite3";
import { drizzle } from "drizzle-orm/better-sqlite3";
import { describe,expect,it } from "vitest";
import { ensureSchema } from "../src/db/migrate";
import * as schema from "../src/db/schema";
import { createTransactionPaymentRepositories } from "../src/repositories/payment/drizzle";

function fixture(){const sqlite=new Database(":memory:");ensureSchema(sqlite);const db=drizzle(sqlite,{schema}) as any,repositories=createTransactionPaymentRepositories(db,"sqlite");const insertPayment=(id:string,status="pending",extra:Record<string,unknown>={})=>db.insert(schema.payments).values({id,provider:"stripe",status,amount:1,currency:"EUR",idempotencyKey:`key-${id}`,createdAt:"now",updatedAt:"now",...extra}).run();return{sqlite,db,...repositories,insertPayment};}

describe("Sprint 127 transaction payment repository guards",()=>{
  it("fails closed for missing, wrong-state and conflicting Session updates while matching replay is safe",()=>{const f=fixture();expect(()=>f.payments.setProviderReference("missing","cs_1")).toThrow("PAYMENT_SESSION_UPDATE_REJECTED");f.insertPayment("pending");f.payments.setProviderReference("pending","cs_1");expect(()=>f.payments.setProviderReference("pending","cs_1")).not.toThrow();expect(()=>f.payments.setProviderReference("pending","cs_2")).toThrow("PAYMENT_SESSION_IDENTITY_CONFLICT");f.insertPayment("terminal","manual_refund_required");expect(()=>f.payments.setProviderReference("terminal","cs_3")).toThrow("PAYMENT_SESSION_IDENTITY_CONFLICT");});
  it("fails closed for paid/link zero-row, wrong-state, order and PaymentIntent conflicts",()=>{const f=fixture();expect(()=>f.payments.markPaidAndLinkOrder("missing","order-1","pi_1","later")).toThrow("PAYMENT_PAID_UPDATE_REJECTED");f.insertPayment("manual","manual_refund_required");expect(()=>f.payments.markPaidAndLinkOrder("manual","order-1","pi_1","later")).toThrow("PAYMENT_PAID_IDENTITY_CONFLICT");f.insertPayment("paid-source");f.payments.markPaidAndLinkOrder("paid-source","order-1","pi_1","later");expect(()=>f.payments.markPaidAndLinkOrder("paid-source","order-1","pi_1","later")).not.toThrow();expect(()=>f.payments.markPaidAndLinkOrder("paid-source","order-2","pi_1","later")).toThrow("PAYMENT_PAID_IDENTITY_CONFLICT");expect(()=>f.payments.markPaidAndLinkOrder("paid-source","order-1","pi_2","later")).toThrow("PAYMENT_PAID_IDENTITY_CONFLICT");const row=f.db.select().from(schema.payments).all().find((x:any)=>x.id==="paid-source");expect(row).toMatchObject({orderId:"order-1",providerTransactionReference:"pi_1",status:"paid"});});
  it("preserves PaymentIntent identity for manual-refund matching replay and conflict",()=>{const f=fixture();f.insertPayment("manual-source");f.payments.markManualRefundRequired("manual-source","pi_1","later");expect(()=>f.payments.markManualRefundRequired("manual-source","pi_1","later")).not.toThrow();expect(()=>f.payments.markManualRefundRequired("manual-source","pi_2","later")).toThrow("PAYMENT_MANUAL_REFUND_IDENTITY_CONFLICT");expect(f.db.select().from(schema.payments).all().find((x:any)=>x.id==="manual-source")).toMatchObject({providerTransactionReference:"pi_1",status:"manual_refund_required",orderId:null});});
});

describe("Sprint 127 transaction payment-event repository guards",()=>{
  const processing=(id:string,paymentId:string|null="payment-1")=>({id,provider:"stripe",providerEventId:`evt-${id}`,eventType:"checkout.session.completed",paymentId,status:"processing",resultClassification:null,errorCode:null,createdAt:"now",updatedAt:"now"});
  it("fails closed for missing event and conflicting payment binding",()=>{const f=fixture();expect(()=>f.paymentEvents.complete("stripe","missing",null,"completed","rejected",null,"later")).toThrow("PAYMENT_EVENT_COMPLETION_REJECTED");f.paymentEvents.claim(processing("binding"));expect(()=>f.paymentEvents.complete("stripe","evt-binding","payment-2","completed","fulfilled",null,"later")).toThrow("PAYMENT_EVENT_STATE_CONFLICT");});
  it("allows exact terminal replay and rejects conflicting terminal state/result",()=>{const f=fixture();f.paymentEvents.claim(processing("terminal"));f.paymentEvents.complete("stripe","evt-terminal","payment-1","completed","fulfilled",null,"later");expect(()=>f.paymentEvents.complete("stripe","evt-terminal","payment-1","completed","fulfilled",null,"later")).not.toThrow();expect(()=>f.paymentEvents.complete("stripe","evt-terminal","payment-1","manual_refund_required","insufficient_stock","INSUFFICIENT_STOCK","later")).toThrow("PAYMENT_EVENT_STATE_CONFLICT");expect(()=>f.paymentEvents.complete("stripe","evt-terminal","payment-1","completed","different",null,"later")).toThrow("PAYMENT_EVENT_STATE_CONFLICT");expect(f.db.select().from(schema.paymentEvents).all()).toHaveLength(1);});
});
