// @vitest-environment jsdom
import"@testing-library/jest-dom/vitest";import{render,screen,waitFor}from"@testing-library/react";import userEvent from"@testing-library/user-event";import{useState}from"react";import{ProductStatus,PublishChannel,type ProductLifecycleOperation}from"@noctella/shared";import{beforeEach,describe,expect,it,vi}from"vitest";import{ProductLifecycleActions}from"./ProductLifecycleActions";import{productLifecycleApi}from"@/lib/productLifecycle";import{ApiError}from"@/lib/api";
const op=(action:"pause"|"relist",status:any,target:any=status==="succeeded"?"succeeded":"failed"):ProductLifecycleOperation=>({id:"op",productId:"p",action,status,previousProductStatus:ProductStatus.Draft,targetSnapshot:[],targetResults:[{key:"t",kind:"external",channel:PublishChannel.Ebay,status:target,retryable:true,error:target==="failed"?"temporary":undefined}],actorAdminUserId:"a",idempotencyKey:"k",createdAt:"t",updatedAt:"t"});const props=(x:any={})=>({productId:"p",isDirty:false,salePaused:false,persistedStatus:"draft",onPausedChange:vi.fn(),onVersionResult:vi.fn(),onCanonicalProduct:vi.fn(),...x});beforeEach(()=>{vi.restoreAllMocks();vi.spyOn(productLifecycleApi,"archiveSafety").mockResolvedValue({canArchive:true});vi.spyOn(productLifecycleApi,"state").mockResolvedValue({productId:"p",productStatus:ProductStatus.Draft,productUpdatedAt:"v",hasActiveExternalListings:false})});
describe("final CP5B corrections",()=>{
 it.each(["succeeded","partially_failed","failed"])("Pause %s establishes paused UI even when refresh fails",async status=>{const state=vi.spyOn(productLifecycleApi,"state");state.mockResolvedValueOnce({productId:"p",productStatus:ProductStatus.Draft,productUpdatedAt:"v1",hasActiveExternalListings:false}).mockRejectedValueOnce(new Error("refresh failed"));vi.spyOn(productLifecycleApi,"pause").mockResolvedValue({operation:op("pause",status),productUpdatedAtBefore:"v1",productUpdatedAtAfter:"v2"});const version=vi.fn();function Harness(){const[paused,setPaused]=useState(false);return <ProductLifecycleActions {...props({salePaused:paused,onPausedChange:setPaused,onVersionResult:version})}/>}render(<Harness/>);await userEvent.click(await screen.findByRole("button",{name:"Pause"}));await userEvent.click(screen.getByRole("button",{name:"Pause Now"}));expect(await screen.findByRole("button",{name:"Paused"})).toBeDisabled();expect(screen.getByRole("alert")).toHaveTextContent("refresh failed");expect(version).toHaveBeenCalledWith("v1","v2")});
 it("does not show a false Relist warning for historical success",async()=>{vi.spyOn(productLifecycleApi,"state").mockResolvedValue({productId:"p",productStatus:ProductStatus.Draft,productUpdatedAt:"v",operation:op("relist","succeeded"),hasActiveExternalListings:false});render(<ProductLifecycleActions {...props({isDirty:true})}/>);await screen.findByRole("button",{name:"Pause"});expect(screen.queryByText("Save changes before relisting")).not.toBeInTheDocument();expect(screen.queryByRole("button",{name:"Retry"})).not.toBeInTheDocument()});
 it("shows Relist warning only for paused or retryable failed Relist",async()=>{vi.spyOn(productLifecycleApi,"state").mockResolvedValue({productId:"p",salePausedAt:"x",productStatus:ProductStatus.Draft,productUpdatedAt:"v",operation:op("relist","failed"),hasActiveExternalListings:true});const retry=vi.spyOn(productLifecycleApi,"retry");render(<ProductLifecycleActions {...props({isDirty:true,salePaused:true})}/>);expect(await screen.findByText("Save changes before relisting")).toBeInTheDocument();expect(screen.getByRole("button",{name:"Relist"})).toBeDisabled();expect(screen.getByRole("button",{name:"Retry"})).toBeDisabled();expect(retry).not.toHaveBeenCalled()});
 it("directly blocks dirty Archive",async()=>{const archive=vi.spyOn(productLifecycleApi,"archive");render(<ProductLifecycleActions {...props({isDirty:true})}/>);expect(await screen.findByText("Save changes before archiving")).toBeInTheDocument();expect(screen.getByRole("button",{name:"Archive"})).toBeDisabled();expect(archive).not.toHaveBeenCalled()});
 it("fails lifecycle access closed while Archive remains independent",async()=>{vi.spyOn(productLifecycleApi,"state").mockRejectedValue(new ApiError("Forbidden",403));render(<ProductLifecycleActions {...props()}/>);expect(await screen.findByRole("button",{name:"Pause unavailable"})).toBeDisabled();expect(screen.getByRole("button",{name:"Archive"})).toBeEnabled()});
 it("prevents duplicate Pause calls while pending",async()=>{let resolve!:(v:any)=>void;const pause=vi.spyOn(productLifecycleApi,"pause").mockReturnValue(new Promise(r=>resolve=r));render(<ProductLifecycleActions {...props()}/>);await userEvent.click(await screen.findByRole("button",{name:"Pause"}));const b=screen.getByRole("button",{name:"Pause Now"});await userEvent.click(b);await userEvent.click(b);expect(pause).toHaveBeenCalledTimes(1);resolve({operation:op("pause","succeeded"),productUpdatedAtBefore:"v",productUpdatedAtAfter:"v2"})});
});
