export const dynamic = "force-dynamic";

import { fetchErpIntegrationOverview, mapCapabilities, mapClientMetadata, mapFieldOwnership, mapReadOnlyLabel, mapVersionStatus } from "../../lib/erpIntegration";
import { mapCommandStatus, mapRecentCommands } from "../../lib/erpInventoryBridge";

export default async function ErpIntegrationPage() {
  const overview = await fetchErpIntegrationOverview();
  const clients = overview.clients.map(mapClientMetadata); const commands = mapRecentCommands(overview.recentCommandExecutions ?? []);
  return <main><h1>ERP Integration</h1><p>{mapReadOnlyLabel(overview.capabilities)}</p><section><h2>Status</h2><p>API {overview.version.apiVersion}: {mapVersionStatus(overview.version)}</p><p>Health: {overview.health.status} / DB {overview.health.database}</p><p>Client versions: min {overview.version.minimumSupportedErpClientVersion}, latest {overview.version.latestSupportedErpClientVersion}</p></section><section><h2>Configured clients</h2>{clients.length ? clients.map((c) => <p key={c.id}>{c.name} — key version {c.keyVersion} — last seen {c.lastSeenAt}</p>) : <p>Environment-key metadata only. Managed key issuance is deferred; raw secrets are never displayed.</p>}</section><section><h2>Capabilities</h2><ul>{mapCapabilities(overview.capabilities).map((m: { name: string; mode: string }) => <li key={m.name}>{m.name}: {m.mode}</li>)}</ul></section><section><h2>Checkpoint status</h2><p>{overview.checkpoints.length} recent acknowledgements</p></section><section><h2>Write capabilities</h2><p>CreateProduct / UpdateProduct / AdjustStock enabled through ERP command bridge.</p></section><section><h2>Recent command executions</h2><p>{commands.length} recent executions; raw payloads and secrets are never displayed.</p>{commands.slice(0,5).map((c:any) => <p key={c.id}>{c.commandType}: {mapCommandStatus(c.status)}</p>)}</section><section><h2>Failed/conflicted command summary</h2><p>{commands.filter((c:any) => ["Failed","Conflict","Rejected"].includes(c.status)).length} need attention.</p></section><section><h2>Recent safe audit events</h2><p>{overview.audit.length} events; safe metadata only, no keys or customer payloads.</p></section><section><h2>Field ownership mapping</h2><p>{mapFieldOwnership(overview.mappingSummary).length} ERP fields mapped or explicitly deferred.</p></section></main>;
}
