import Database from "better-sqlite3";
import { drizzle } from "drizzle-orm/better-sqlite3";
import { eq, sql } from "drizzle-orm";
import { createHash } from "node:crypto";
import { CarrierCode, OrderStatus, PaymentProvider, PaymentStatus, ProductStatus, ProductType } from "@noctella/shared";
import { ensureSchema } from "../../src/db/migrate";
import * as schema from "../../src/db/schema";
import { createCategory } from "../../src/services/categories";
import { createProduct } from "../../src/services/products";
import { createOrder } from "../../src/services/orders";
import { createShipment } from "../../src/services/shipments";
import { createPaymentSession } from "../../src/payments/paymentRepository";

const address = { fullName:"Harness Buyer", line1:"PII REDACTED", city:"Paris", postalCode:"75001", country:"FR" };
export const deterministicClock = { now: () => new Date("2026-01-02T03:04:05.000Z") };
export function deterministicIds(prefix="rr") { let n=0; return { id: () => `${prefix}-${String(++n).padStart(4,"0")}` }; }
export type HarnessDb = ReturnType<typeof drizzle<typeof schema>>;
/**
 * Sprint 53B: uses an in-memory SQLite database instead of a real temp file.
 * Nothing in this codebase reopens the database by filename (confirmed by
 * inspecting every consumer), so the only observable differences are that
 * cleanup no longer needs to remove a temp directory and `path` reports
 * ":memory:" instead of a real file path - neither is read by any consumer.
 */
export function createReturnRefundSqliteHarness() { const sqlite=new Database(":memory:"); sqlite.pragma("foreign_keys = ON"); ensureSchema(sqlite); const db=drizzle(sqlite,{schema}); return { db, sqlite, path:":memory:", cleanup(){ sqlite.close(); } }; }
export async function seedOrderGraph(db:any, suffix="ok", status:any=OrderStatus.Completed) { const cat=await createCategory(db,{name:`RR ${suffix}`,isActive:true,displayOrder:0}); const product=await createProduct(db,{sku:`RR-${suffix}`,title:"Harness Item",slug:`rr-${suffix}`,type:ProductType.UniqueItem,status:ProductStatus.Published,categoryId:cat.id,priceEur:120,purchaseCost:50,stockQuantity:1,customsWarning:false,isFeatured:false,allowMakeOffer:false,allowCashOnDelivery:false,showInArchiveAfterSale:false}); const payRef=`pay-${suffix}`; await createPaymentSession(db,{provider:PaymentProvider.Stripe,providerReference:payRef,status:PaymentStatus.Paid,amount:120,currency:"EUR",idempotencyKey:`test:${payRef}`}); const order=await createOrder(db,{orderDraftId:`rr-draft-${suffix}`,guestEmail:"redacted@example.invalid",status,paymentStatus:PaymentStatus.Paid,paymentProvider:PaymentProvider.Stripe,paymentReference:payRef,currency:"EUR",billingAddress:address,shippingAddress:address,subtotalAmount:120,totalAmount:120,items:[{productId:product.id,quantity:1}]}); const shipment=await createShipment(db,{orderId:order.id,carrierCode:CarrierCode.LocalPickup}); const [orderItem]=await db.select().from(schema.orderItems).where(eq(schema.orderItems.orderId,order.id)); return { cat, product, order, orderItem, shipment }; }
export const returnInput = (g:any, overrides:any={}) => ({ id:g.id(), status:"requested", reason:"damaged", requestedResolution:"refund", requestedAt:deterministicClock.now().toISOString(), createdAt:deterministicClock.now().toISOString(), updatedAt:deterministicClock.now().toISOString(), ...overrides });
export async function seedReturn(db:any, graph:any, overrides:any={}) { const g=deterministicIds(`ret-${overrides.status??"requested"}`); const row={...returnInput(g,{orderId:graph.order.id,shipmentId:graph.shipment.id,channel:"test",externalReturnId:`ext-${g.id()}`,...overrides})}; await db.insert(schema.returnRequests).values(row).run(); const item={id:g.id(),returnRequestId:row.id,orderItemId:graph.orderItem.id,productId:graph.product.id,quantityRequested:overrides.quantityRequested??1,quantityApproved:overrides.quantityApproved??null,quantityReceived:overrides.quantityReceived??null,condition:overrides.condition??null,stockDisposition:overrides.stockDisposition??null,inspectionNote:null,createdAt:row.createdAt,updatedAt:row.updatedAt}; await db.insert(schema.returnItems).values(item).run(); await db.insert(schema.returnEvents).values({id:g.id(),returnRequestId:row.id,eventType:"created",previousStatus:null,newStatus:row.status,payloadSnapshot:JSON.stringify({safe:true}),createdAt:row.createdAt}).run(); return { returnRequest: row, returnItem: item }; }
export async function seedRefund(db:any, graph:any, ret:any, overrides:any={}) { const g=deterministicIds(`ref-${overrides.status??"draft"}`); const row={id:g.id(),orderId:graph.order.id,returnRequestId:ret.returnRequest.id,channel:"test",externalRefundId:overrides.externalRefundId??null,type:overrides.type??"return",status:overrides.status??"draft",currency:"EUR",subtotalAmount:overrides.subtotalAmount??120,shippingAmount:0,taxAmount:0,marketplaceFeeAdjustment:null,paymentFeeAdjustment:null,totalAmount:overrides.totalAmount??120,reason:"return",idempotencyKey:overrides.idempotencyKey??`idem-${g.id()}`,submittedAt:null,succeededAt:null,failedAt:null,lastError:null,createdAt:deterministicClock.now().toISOString(),updatedAt:deterministicClock.now().toISOString()}; await db.insert(schema.refunds).values(row).run(); const item={id:g.id(),refundId:row.id,orderItemId:graph.orderItem.id,returnItemId:ret.returnItem.id,quantity:1,amount:row.totalAmount,createdAt:row.createdAt}; await db.insert(schema.refundAllocations).values(item).run(); await db.insert(schema.refundAttempts).values({id:g.id(),refundId:row.id,attemptNumber:1,channel:"test",status:"created",externalRefundId:null,requestSnapshot:JSON.stringify({amount:row.totalAmount}),responseSnapshot:null,errorCode:null,errorMessage:null,createdAt:row.createdAt}).run(); return { refund: row, refundItem: item }; }
export async function tableCounts(db:any, tables=trackedTables) { const out:any={}; for (const [k,t] of Object.entries(tables)) out[k]=Number((await db.select({c:sql<number>`count(*)`}).from(t as any))[0].c); return out; }
export const trackedTables = { products:schema.products, productPhotos:schema.productPhotos, stockMovements:schema.stockMovements, orders:schema.orders, orderItems:schema.orderItems, shipments:schema.shipments, shipmentEvents:schema.shipmentEvents, returns:schema.returnRequests, returnItems:schema.returnItems, returnEvents:schema.returnEvents, refunds:schema.refunds, refundItems:schema.refundAllocations, refundAttempts:schema.refundAttempts, invoices:schema.invoices, financeEntries:schema.financeEntries, customers:schema.customers, marketplaceConnections:schema.marketplaceConnections, backgroundJobs:schema.backgroundJobs, outboxEvents:schema.outboxEvents };
export async function snapshotDb(db:any, allowed:string[]=[]){ const counts=await tableCounts(db); const sums:any={}; for (const [k,t] of Object.entries(trackedTables)) { if (allowed.includes(k)) continue; const rows=await db.select().from(t as any); sums[k]=createHash("sha256").update(JSON.stringify(rows,(_key,v)=>String(_key).toLowerCase().includes("email")?"<redacted>":v)).digest("hex"); } return {counts,sums}; }
export function compareSnapshots(a:any,b:any,allowed:string[]=[]){ const mismatches:string[]=[]; for(const k of Object.keys(a.counts)) if(!allowed.includes(k)&&a.counts[k]!==b.counts[k]) mismatches.push(`${k}: count ${a.counts[k]} -> ${b.counts[k]}`); for(const k of Object.keys(a.sums)) if(a.sums[k]!==b.sums[k]) mismatches.push(`${k}: checksum changed`); return {pass:mismatches.length===0,mismatches}; }
export function paymentExecutionSpy(){ const calls:any[]=[]; return { calls, refund:(input:any)=>calls.push({kind:"refund",input}) }; }
export function idempotencyKey(kind:string,id:string){ return `${kind}:2026-01-02:${id}`; }
