import { and, asc, desc, eq, like, or, sql, gt } from "drizzle-orm";
import type { Address, OrderStatus, PaymentStatus } from "@noctella/shared";
import * as sqliteSchema from "../../db/schema.sqlite";
import * as postgresSchema from "../../db/schema.postgres";
import type { CreateOrderItemInput, OrderDetailProjection, OrderItemRepositoryRecord, OrderListProjection, OrderRepositoryBundle, OrderRepositoryRecord, UpdateOrderPaymentStatusInput, UpdateOrderStatusInput } from "./types";

type Schema = typeof sqliteSchema | typeof postgresSchema; type Db = any;
const all=<T>(q:any):T[]=>Array.isArray(q)?q:(q?.all?q.all():[]); const one=<T>(q:any):T|undefined=>all<T>(q)[0];
const then=<T,U>(value:T|Promise<T>,next:(value:T)=>U|Promise<U>):U|Promise<U>=>value instanceof Promise?value.then(next):next(value);
const resultRows=<T>(q:any,dialect:"sqlite"|"postgres"):T[]|Promise<T[]>=>dialect==="sqlite"?all<T>(q):Promise.resolve(q).then((rows:any)=>Array.isArray(rows)?rows:rows.all());
const resultOne=<T>(q:any,dialect:"sqlite"|"postgres"):T|undefined|Promise<T|undefined>=>then(resultRows<T>(q,dialect),rows=>rows[0]);
function date(v:unknown){ return v instanceof Date ? v.toISOString() : String(v); }
function addr(v:unknown):Address{ return typeof v === "string" ? JSON.parse(v) : v as Address; }
function order(r:any):OrderRepositoryRecord{ return { id:r.id, orderNumber:r.orderNumber, orderDraftId:r.orderDraftId??undefined, offerId:r.offerId??undefined, customerId:r.customerId??undefined, guestEmail:r.guestEmail, status:r.status, paymentStatus:r.paymentStatus, paymentProvider:r.paymentProvider??undefined, paymentReference:r.paymentReference??undefined, subtotalAmount:Number(r.subtotalAmount), shippingAmount:Number(r.shippingAmount??0), taxAmount:Number(r.taxAmount??0), totalAmount:Number(r.totalAmount), currency:r.currency, billingAddress:addr(r.billingAddress), shippingAddress:addr(r.shippingAddress), notes:r.notes??undefined, shippingMethodId:r.shippingMethodId??undefined, shippingMethodLabel:r.shippingMethodLabel??undefined, createdAt:date(r.createdAt), updatedAt:date(r.updatedAt), idempotencyKey:r.orderDraftId??undefined, version:1 }; }
function item(r:any):OrderItemRepositoryRecord{ return { id:r.id, orderId:r.orderId, productId:r.productId, productSku:r.productSku, productTitle:r.productTitle, productSlug:r.productSlug, productType:r.productType, productImageUrl:r.productImageUrl??undefined, quantity:Number(r.quantity) as 1, unitPrice:Number(r.unitPrice), totalPrice:Number(r.totalPrice), currency:r.currency, createdAt:date(r.createdAt), updatedAt:date(r.updatedAt) }; }
function listProj(r:any):OrderListProjection{ const o=order(r); return { id:o.id, orderNumber:o.orderNumber, guestEmail:o.guestEmail.replace(/(^.).*(@.*$)/,"$1***$2"), status:o.status, paymentStatus:o.paymentStatus, paymentProvider:o.paymentProvider, subtotalAmount:o.subtotalAmount, totalAmount:o.totalAmount, currency:o.currency, createdAt:o.createdAt, updatedAt:o.updatedAt }; }
export function createDrizzleOrderRepositories(db:Db, schema:Schema, dialect:"sqlite"|"postgres"):OrderRepositoryBundle{ const {orders,orderItems,products,productPhotos,pickingTasks,packingTasks,shipments}=schema as any; const page=(q:{page:number;pageSize:number})=>({limit:q.pageSize,offset:(q.page-1)*q.pageSize}); const count=(where?:unknown)=>then(resultOne<any>(db.select({count:sql<number>`count(*)`}).from(orders).where(where),dialect),row=>Number(row?.count??0)); const rows=(where:unknown,q:{page:number;pageSize:number})=>resultRows<any>(db.select().from(orders).where(where).orderBy(desc(orders.createdAt), desc(orders.id)).limit(page(q).limit).offset(page(q).offset),dialect);
 const read:any={ getById:(id:string)=>then(resultOne<any>(db.select().from(orders).where(eq(orders.id,id)),dialect),r=>r?order(r):undefined), getByOrderNumber:(n:string)=>then(resultOne<any>(db.select().from(orders).where(eq(orders.orderNumber,n)),dialect),r=>r?order(r):undefined), getByExternalOrderId:()=>(undefined), getByIdempotencyKey:(k:string)=>then(resultOne<any>(db.select().from(orders).where(eq(orders.orderDraftId,k)),dialect),r=>r?order(r):undefined), getByOfferId:(offerId:string)=>then(resultOne<any>(db.select().from(orders).where(eq(orders.offerId,offerId)),dialect),r=>r?order(r):undefined), list:(q:any)=>then(rows(undefined,q),values=>then(count(),total=>({items:values.map(listProj),total}))), search:(term:string,q:any)=>{const w=or(like(orders.orderNumber,`%${term}%`),like(orders.guestEmail,`%${term}%`)); return then(rows(w,q),values=>then(count(w),total=>({items:values.map(listProj),total})));}, count:()=>count(), listByChannel:(_:string,q:any)=>then(rows(undefined,q),values=>then(count(),total=>({items:values.map(listProj),total}))), listByStatus:(s:OrderStatus,q:any)=>{const w=eq(orders.status,s); return then(rows(w,q),values=>then(count(w),total=>({items:values.map(listProj),total})));}, listByPaymentStatus:(s:PaymentStatus,q:any)=>{const w=eq(orders.paymentStatus,s); return then(rows(w,q),values=>then(count(w),total=>({items:values.map(listProj),total})));}, listUpdatedSince:(iso:string,q:any)=>then(rows(gt(orders.updatedAt,iso),q),values=>values.map(listProj)), getOrderSummary:()=>then(count(),total=>({total,byStatus:{},byPaymentStatus:{}})), getOrderDetailProjection:(id:string)=>then(resultOne<any>(db.select().from(orders).where(eq(orders.id,id)),dialect),r=>{if(!r)return undefined; const o=order(r); return then(itemRead.listByOrder(id),(items:any[])=>({...listProj(r), paymentReference:o.paymentReference, shippingAmount:o.shippingAmount, taxAmount:o.taxAmount, billingAddress:o.billingAddress, shippingAddress:o.shippingAddress, notes:o.notes, shippingMethodId:o.shippingMethodId, shippingMethodLabel:o.shippingMethodLabel, items} as OrderDetailProjection));}) };
 const itemRead:any={ getById:(id:string)=>then(resultOne<any>(db.select().from(orderItems).where(eq(orderItems.id,id)),dialect),r=>r?item(r):undefined), listByOrder:(orderId:string)=>then(resultRows<any>(db.select().from(orderItems).where(eq(orderItems.orderId,orderId)).orderBy(asc(orderItems.createdAt),asc(orderItems.id)),dialect),values=>values.map(item)), countByOrder:(orderId:string)=>then(resultOne<any>(db.select({count:sql<number>`count(*)`}).from(orderItems).where(eq(orderItems.orderId,orderId)),dialect),r=>Number(r?.count??0)), listByProduct:(productId:string,q:any)=>then(resultRows<any>(db.select().from(orderItems).where(eq(orderItems.productId,productId)).orderBy(desc(orderItems.createdAt),desc(orderItems.id)).limit(page(q).limit).offset(page(q).offset),dialect),values=>values.map(item)) };
 const write:any={ create:(input:OrderRepositoryRecord)=>{const row={...input,orderDraftId:input.orderDraftId??input.idempotencyKey??null,customerId:input.customerId??null,paymentProvider:input.paymentProvider??null,paymentReference:input.paymentReference??null,billingAddress:dialect==="sqlite"?JSON.stringify(input.billingAddress):input.billingAddress,shippingAddress:dialect==="sqlite"?JSON.stringify(input.shippingAddress):input.shippingAddress,notes:input.notes??null,shippingMethodId:input.shippingMethodId??null,shippingMethodLabel:input.shippingMethodLabel??null,createdAt:dialect==="postgres"?new Date(input.createdAt):input.createdAt,updatedAt:dialect==="postgres"?new Date(input.updatedAt):input.updatedAt}; const q=db.insert(orders).values(row).returning?.(); if(dialect==="postgres") return then(resultRows<any>(q,dialect),values=>values[0]?order(values[0]):input); const got=q?all<any>(q)[0]:undefined; if(!q) db.insert(orders).values(row).run(); return (got?order(got):input);}, updateStatus:(i:UpdateOrderStatusInput)=>{const updatedAt=dialect==="postgres"?new Date():new Date().toISOString();const q=db.update(orders).set({status:i.status,updatedAt}).where(eq(orders.id,i.id));if(dialect==="postgres")return then(Promise.resolve(q),()=>read.getById(i.id));q.run?.();return read.getById(i.id);}, updatePaymentStatus:(i:UpdateOrderPaymentStatusInput)=>{const updatedAt=dialect==="postgres"?new Date():new Date().toISOString();const q=db.update(orders).set({paymentStatus:i.paymentStatus,updatedAt}).where(eq(orders.id,i.id));if(dialect==="postgres")return then(Promise.resolve(q),()=>read.getById(i.id));q.run?.();return read.getById(i.id);}, updateCompletionState:()=>undefined, updateCancellationState:(i:any)=>write.updateStatus({id:i.id,status:"cancelled"}), findByIdempotencyKey:read.getByIdempotencyKey, findByExternalOrderId:()=>(undefined), getVersionForUpdate:()=>(1), updateWithExpectedVersion:(id:string,_v:number,patch:any)=> patch.status?write.updateStatus({id,status:patch.status}):read.getById(id),
  // Sprint 132: guarded Cash on Delivery settlement transition - a single conditional UPDATE, row-count-verified, mirroring shipment-core's markProcessingOrderShipped (Sprint 131). Never touches any other paymentStatus/paymentProvider pair.
  markPendingCashOnDeliveryOrderPaid:(id:string,updatedAt:string)=>{const result:any=db.update(orders).set({paymentStatus:"paid",updatedAt}).where(and(eq(orders.id,id),eq(orders.paymentStatus,"pending"),eq(orders.paymentProvider,"cash_on_delivery"))).run?.(); return Number(result?.changes??0)===1;} };
 read.hasActiveFulfillmentTasks=(orderId:string)=>{ if(dialect!=="sqlite") throw new Error("ORDER_ACTIVE_FULFILLMENT_CHECK_REQUIRES_SQLITE_TRANSACTION"); return Boolean(one<any>(db.select({id:pickingTasks.id}).from(pickingTasks).where(and(eq(pickingTasks.orderId,orderId),sql`${pickingTasks.status} <> 'Cancelled'`)).limit(1))||one<any>(db.select({id:packingTasks.id}).from(packingTasks).where(and(eq(packingTasks.orderId,orderId),sql`${packingTasks.status} <> 'Cancelled'`)).limit(1))||one<any>(db.select({id:shipments.id}).from(shipments).where(and(eq(shipments.orderId,orderId),sql`${shipments.status} NOT IN ('cancelled','returned')`)).limit(1))); };
 // Sprint 86: primaryPhotoUrl must stay aligned with Sprint 85's publicly-visible ProductPhoto
 // policy (listPubliclyVisibleByProduct in repositories/product-read/drizzle.ts) - Ready and
 // Processing are both snapshot-eligible because LocalPhotoStorage (the only storage backend
 // implemented today) fully writes the file before the ProductPhoto row exists, so "Processing"
 // already refers to a fully-written, publicly-servable file; Failed is excluded as the model's
 // genuine negative signal. This duplicates that policy locally (cross-repository wiring into the
 // product-read repository was rejected as too broad for this defect fix) - photo selection
 // should later be consolidated behind one shared helper/repository policy.
 const primaryPhotoUrl=(id:string)=>then(resultOne<any>(db.select({url:productPhotos.url}).from(productPhotos).where(and(eq(productPhotos.productId,id),or(eq(productPhotos.processingStatus,"Ready"),eq(productPhotos.processingStatus,"Processing")))).orderBy(desc(productPhotos.isPrimary),asc(productPhotos.sortOrder),asc(productPhotos.id)),dialect),row=>row?.url);
 const itemWrite:any={ create:(input:CreateOrderItemInput)=>{const values={...input,productImageUrl:input.productImageUrl??null,createdAt:dialect==="postgres"?new Date(input.createdAt):input.createdAt,updatedAt:dialect==="postgres"?new Date(input.updatedAt):input.updatedAt};const q=db.insert(orderItems).values(values).returning?.();if(dialect==="postgres")return then(resultRows<any>(q,dialect),rows=>rows[0]?item(rows[0]):input as any);if(!q)db.insert(orderItems).values(values).run();return(q?item(all<any>(q)[0]):input as any);}, createMany:(inputs:CreateOrderItemInput[])=>dialect==="postgres"?Promise.all(inputs.map((i:any)=>itemWrite.create(i))):inputs.map((i:any)=>itemWrite.create(i)), validateProductReferences:(ids:string[])=>{const resolve=(id:string)=>then(resultOne<any>(db.select().from(products).where(eq(products.id,id)),dialect),p=>{if(!p)return undefined;return then(primaryPhotoUrl(id),imageUrl=>({id:p.id,sku:p.sku,title:p.title,wooProductName:p.wooProductName??null,slug:p.slug,type:p.type,priceEur:p.priceEur==null?null:Number(p.priceEur),wooListingPriceEur:p.wooListingPriceEur==null?null:Number(p.wooListingPriceEur),stockQuantity:Number(p.stockQuantity),status:p.status,salePausedAt:p.salePausedAt==null?null:date(p.salePausedAt),allowCashOnDelivery:Boolean(p.allowCashOnDelivery),imageUrl,shippingProfile:p.shippingProfile??null}));});const values=ids.map(resolve);return dialect==="postgres"?Promise.all(values).then(rows=>rows.filter(Boolean)):values.filter(Boolean);}, listForUpdate:itemRead.listByOrder, getPurchasedQuantityByProduct:(productId:string)=>then(itemRead.listByProduct(productId,{page:1,pageSize:1000}),(items:any[])=>items.reduce((s:number,i:any)=>s+i.quantity,0)), updateSnapshot:()=>undefined };
 return {orders:{read,write},orderItems:{read:itemRead,write:itemWrite}}; }
