import type { Address, Order, OrderItem, OrderStatus, PaymentStatus, PriceCurrency } from "@noctella/shared";

export interface OrderRepositoryRecord extends Order { version?: number; idempotencyKey?: string; externalOrderId?: string; channel?: "Internal"|"Direct"|"LocalPickup"|string }
export interface OrderItemRepositoryRecord extends OrderItem {}
export interface OrderListProjection { id:string; orderNumber:string; guestEmail:string; status:OrderStatus; paymentStatus:PaymentStatus; subtotalAmount?: number; totalAmount:number; currency:PriceCurrency|string; createdAt:string; updatedAt:string }
export interface OrderDetailProjection extends OrderListProjection { paymentReference?: string; shippingAmount?: number; taxAmount?: number; billingAddress:Address; shippingAddress:Address; notes?:string; items:OrderItemRepositoryRecord[] }
export interface OrderSummaryProjection { total:number; byStatus:Record<string,number>; byPaymentStatus:Record<string,number> }
export interface OrderFinancialReadinessProjection { orderId:string; ready:boolean; issues:string[] }
export interface CreateOrderItemInput { id:string; orderId:string; productId:string; productSku:string; productTitle:string; productSlug:string; productType:string; productImageUrl?:string|null; quantity:number; unitPrice:number; totalPrice:number; currency:string; createdAt:string; updatedAt:string }
export interface CreateInternalOrderInput { id?:string; orderNumber?:string; orderDraftId:string; idempotencyKey?:string; externalOrderId?:string; channel:"Internal"|"Direct"|"LocalPickup"; customerId?:string; guestEmail:string; status:OrderStatus; paymentStatus:PaymentStatus; paymentProvider?:string; paymentReference?:string; currency:PriceCurrency|string; billingAddress:Address; shippingAddress:Address; subtotalAmount:number; totalAmount:number; notes?:string; items:Array<{productId:string; quantity:number}> }
export interface UpdateOrderStatusInput { id:string; status:OrderStatus; expectedVersion?:number }
export interface UpdateOrderPaymentStatusInput { id:string; paymentStatus:PaymentStatus; expectedVersion?:number }
export interface CancelOrderInput { id:string; reason?:string; expectedVersion?:number }
export interface SaleRollbackInput { orderId:string; idempotencyKey:string; reason?:string }
export interface OrderWriteConflict { code:"IDEMPOTENCY_CONFLICT"|"OPTIMISTIC_CONFLICT"|"UNIQUE_CONFLICT"; message:string }
export interface OrderWriteIssue { code:string; message:string; field?:string }
export interface OrderExecutionResult<T=OrderDetailProjection> { ok:boolean; value?:T; conflict?:OrderWriteConflict; issues?:OrderWriteIssue[] }
export interface OrderReadRepository { getById(id:string):Promise<OrderRepositoryRecord|undefined>; getByOrderNumber(n:string):Promise<OrderRepositoryRecord|undefined>; getByExternalOrderId(id:string):Promise<OrderRepositoryRecord|undefined>; getByIdempotencyKey(key:string):Promise<OrderRepositoryRecord|undefined>; getByOfferId(offerId:string):Promise<OrderRepositoryRecord|undefined>; list(q:{page:number;pageSize:number}):Promise<{items:OrderListProjection[];total:number}>; search(term:string,q:{page:number;pageSize:number}):Promise<{items:OrderListProjection[];total:number}>; count():Promise<number>; listByChannel(c:string,q:{page:number;pageSize:number}):Promise<{items:OrderListProjection[];total:number}>; listByStatus(s:OrderStatus,q:{page:number;pageSize:number}):Promise<{items:OrderListProjection[];total:number}>; listByPaymentStatus(s:PaymentStatus,q:{page:number;pageSize:number}):Promise<{items:OrderListProjection[];total:number}>; listUpdatedSince(iso:string,q:{page:number;pageSize:number}):Promise<OrderListProjection[]>; getOrderSummary():Promise<OrderSummaryProjection>; getOrderDetailProjection(id:string):Promise<OrderDetailProjection|undefined> }
export interface OrderItemReadRepository { getById(id:string):Promise<OrderItemRepositoryRecord|undefined>; listByOrder(orderId:string):Promise<OrderItemRepositoryRecord[]>; countByOrder(orderId:string):Promise<number>; listByProduct(productId:string,q:{page:number;pageSize:number}):Promise<OrderItemRepositoryRecord[]> }
export interface OrderWriteRepository { create(input:OrderRepositoryRecord):Promise<OrderRepositoryRecord>; updateStatus(input:UpdateOrderStatusInput):Promise<OrderRepositoryRecord|undefined>; updatePaymentStatus(input:UpdateOrderPaymentStatusInput):Promise<OrderRepositoryRecord|undefined>; updateCompletionState(id:string,completed:boolean):Promise<void>; updateCancellationState(input:CancelOrderInput):Promise<void>; findByIdempotencyKey(key:string):Promise<OrderRepositoryRecord|undefined>; findByExternalOrderId(id:string):Promise<OrderRepositoryRecord|undefined>; getVersionForUpdate(id:string):Promise<number|undefined>; updateWithExpectedVersion(id:string,expectedVersion:number,patch:Partial<OrderRepositoryRecord>):Promise<OrderRepositoryRecord|undefined> }
export interface OrderItemWriteRepository { create(input:CreateOrderItemInput):Promise<OrderItemRepositoryRecord>; createMany(input:CreateOrderItemInput[]):Promise<OrderItemRepositoryRecord[]>; validateProductReferences(ids:string[]):Promise<Array<{id:string;sku:string;title:string;slug:string;type:string;priceEur:number;stockQuantity:number;status:string;imageUrl?:string}>>; listForUpdate(orderId:string):Promise<OrderItemRepositoryRecord[]>; getPurchasedQuantityByProduct(productId:string):Promise<number>; updateSnapshot(id:string,patch:Partial<CreateOrderItemInput>):Promise<void> }
export interface OrderRepositoryBundle { orders:{read:OrderReadRepository;write:OrderWriteRepository}; orderItems:{read:OrderItemReadRepository;write:OrderItemWriteRepository} }
