import { randomUUID } from "node:crypto";
import { StockMovementType, type StockMovement } from "@noctella/shared";
import type { ManualStockAdjustmentInput, StockMovementListQuery } from "../../validation/stockMovement";
import { BadRequestError, NotFoundError } from "../../services/errors";
import type { UnitOfWork } from "../../services/unitOfWork";
import type { StockBalanceProjection, StockMovementCreateInput, StockMovementRepositoryBundle } from "../../repositories/stock/types";
export interface StockUseCaseContext { unitOfWork: UnitOfWork; repositories: StockMovementRepositoryBundle }
type SyncStockMovementRepositories = { read: { getBalance(productId: string): StockBalanceProjection | undefined; findByIdempotencyKey(key: string): StockMovement | undefined }; write: { create(input: StockMovementCreateInput): StockMovement } };
export async function getStockBalanceUseCase(ctx: StockUseCaseContext, productId: string) { const b=await ctx.repositories.stockMovements.read.getBalance(productId); if(!b) throw new NotFoundError("Product not found"); return b; }
export async function getStockHistoryUseCase(ctx: StockUseCaseContext, query: StockMovementListQuery) { return ctx.repositories.stockMovements.read.getHistory(query); }
export async function createManualStockAdjustmentUseCase(ctx: StockUseCaseContext, input: ManualStockAdjustmentInput) { if (!Number.isInteger(input.quantityDelta)) throw new BadRequestError("Delta must be an integer"); if (input.quantityDelta === 0) throw new BadRequestError("Delta must not be zero"); return ctx.unitOfWork.run(({repositories}) => { const repo = repositories.stock.stockMovements as unknown as SyncStockMovementRepositories; const key = input.idempotencyKey ?? `manual:${input.productId}:${input.quantityDelta}:${input.note ?? ""}`; const existing = repo.read.findByIdempotencyKey(key); if (existing) return existing; const balance = repo.read.getBalance(input.productId); if (!balance) throw new NotFoundError("Product not found"); const stockAfter = balance.quantity + input.quantityDelta; if (stockAfter < 0) throw new BadRequestError("Insufficient stock for movement"); const now = new Date().toISOString(); return repo.write.create({ id: randomUUID(), productId: input.productId, type: StockMovementType.ManualAdjustment, quantityDelta: input.quantityDelta, stockBefore: balance.quantity, stockAfter, note: input.note, createdByAdminUserId: input.createdByAdminUserId, idempotencyKey: key, createdAt: now, updatedAt: now }); }); }
