export type Currency="EUR"; export type ISODateTime=string; export type SaleId=string; export type SaleLineId=string; export type SaleVersion=string; export type SaleStatus="Pending"|"Processing"|"Paid"|"Shipped"|"Delivered"|"Completed"|"Cancelled"|"Refunded"|string; export type SaleSource="Manual"|"Marketplace"|"Order"|string; export type SaleChannel="Internal"|"Direct"|"LocalPickup"|"Other"|"eBay"|"Etsy"|"WooCommerce"|string;
export interface Money{readonly amount:number;readonly currency:Currency}
export interface SaleCustomerSnapshot{readonly customerId:string|null;readonly email:string|null;readonly billingAddress:string|null;readonly shippingAddress:string|null}
export interface SalePaymentSnapshot{readonly status:string;readonly provider:string|null;readonly reference:string|null}
export interface SaleFulfillmentSnapshot{readonly status:string|null;readonly shippingStatus:string|null;readonly trackingNumber:string|null}
export interface SaleMarketplaceReference{readonly channel:SaleChannel|null;readonly marketplaceOrderId:string|null;readonly externalOrderId:string|null;readonly externalOrderNumber:string|null;readonly externalTransactionId:string|null;readonly connectionId:string|null}
export interface SaleFinancialSnapshot{readonly subtotalAmount:number;readonly shippingAmount:number;readonly taxAmount:number;readonly totalAmount:number;readonly grossRevenue:number|null;readonly shippingCharged:number|null;readonly shippingCost:number|null;readonly marketplaceFee:number|null;readonly promotedFee:number|null;readonly paymentFee:number|null;readonly itemCost:number|null;readonly netRevenue:number|null;readonly profit:number|null;readonly currency:Currency}
export interface SaleInventoryReference{readonly productId:string|null;readonly stockMovementId:string|null;readonly inventoryReservationId:string|null;readonly inventoryLocationId:string|null}
export interface SaleReceiptReference{readonly invoiceId:string|null;readonly invoiceNumber:string|null}
export interface SaleLine{readonly id:SaleLineId;readonly saleId:SaleId;readonly productId:string|null;readonly sku:string|null;readonly title:string;readonly slug:string|null;readonly productType:string|null;readonly imageUrl:string|null;readonly quantity:number;readonly unitPrice:number;readonly totalPrice:number;readonly currency:Currency;readonly stockMovementId:string|null;readonly createdAt:ISODateTime;readonly updatedAt:SaleVersion}
export interface Sale{readonly id:SaleId;readonly reference:string;readonly orderDraftId:string|null;readonly source:SaleSource;readonly status:SaleStatus;readonly paymentStatus:string;readonly customer:SaleCustomerSnapshot;readonly payment:SalePaymentSnapshot;readonly fulfillment:SaleFulfillmentSnapshot;readonly marketplace:SaleMarketplaceReference;readonly financials:SaleFinancialSnapshot;readonly receipt:SaleReceiptReference;readonly notes:string|null;readonly idempotencyKey:string|null;readonly createdAt:ISODateTime;readonly updatedAt:SaleVersion;readonly completedAt:string|null;readonly lines:readonly SaleLine[]}
export interface CreateSaleInput extends Sale{} export type UpdateSaleInput=Partial<Omit<Sale,"id"|"lines"|"createdAt">> & {readonly updatedAt:ISODateTime}; export type AddSaleLineInput=SaleLine; export type UpdateSaleLineInput=Partial<Omit<SaleLine,"id"|"saleId"|"createdAt">> & {readonly updatedAt?:ISODateTime};
export interface SaleRepositoryFilter{readonly status?:SaleStatus;readonly source?:SaleSource;readonly channel?:SaleChannel;readonly productId?:string|null;readonly customerId?:string|null;readonly reference?:string;readonly externalOrderId?:string;readonly paymentStatus?:string;readonly dateFrom?:ISODateTime;readonly dateTo?:ISODateTime;readonly limit?:number;readonly offset?:number}
export interface SaleRepositoryPage{readonly rows:readonly Sale[];readonly total:number;readonly limit:number;readonly offset:number}
export type SaleRepositoryResult<T>={readonly ok:true;readonly value:T}|{readonly ok:false;readonly issue:{readonly code:"not_found"|"optimistic_conflict"|"duplicate_reference"|"duplicate_external_order"|"duplicate_idempotency_key";readonly message:string}};
export interface SaleRepository{create(input:CreateSaleInput):Sale;findById(id:SaleId):Sale|null;findByReference(reference:string):Sale|null;findByExternalOrderId(externalOrderId:string):Sale|null;findByIdempotencyKey(idempotencyKey:string):Sale|null;list(filter?:SaleRepositoryFilter):SaleRepositoryPage;update(id:SaleId,input:UpdateSaleInput):Sale|null;updateWithVersion(id:SaleId,expectedVersion:SaleVersion,input:UpdateSaleInput):SaleRepositoryResult<Sale>;addLine(input:AddSaleLineInput):SaleLine;updateLine(id:SaleLineId,input:UpdateSaleLineInput):SaleLine|null;removeLine(id:SaleLineId):boolean}
export interface SalesRepositories{readonly saleRepository:SaleRepository} export type SalesRepositoryDriver="sqlite"|"test-memory"|"postgres"|"supabase-postgres";
