import type { ID } from "./index";

export enum ErpClientStatus { Disconnected="Disconnected", Connected="Connected", Degraded="Degraded", Unauthorized="Unauthorized", VersionMismatch="VersionMismatch", Error="Error" }
export enum ErpIntegrationCapability { ReadProducts="ReadProducts", ReadInventory="ReadInventory", ReadProductPhotos="ReadProductPhotos", IdentityCheck="IdentityCheck", FieldMapping="FieldMapping", SyncCheckpoint="SyncCheckpoint", ValidateCommands="ValidateCommands" }
export interface ErpIntegrationHealth { status: ErpClientStatus; apiVersion: string; minimumClientVersion: string; latestClientVersion: string; serverTime: string; database: "Healthy"|"Degraded"; readOnly: boolean; writesEnabled: boolean; degradedServices: string[]; }
export interface ErpProductReference { centralProductId: ID; erpReferenceId?: string; sku?: string; noctellaId?: string; }
export interface ErpProductProjection extends ErpProductReference { title: string; status: string; category?: string; collection?: string; brand?: string; condition?: string; dimensions?: { length?: number; width?: number; height?: number; unit?: string }; weight?: { value?: number; unit?: string }; purchaseCost?: number; priceEur: number; physicalStock: number; reservedStock: number; reservedStockSupported: boolean; availableStock: number; primaryPhoto?: string; workflowMetadata?: Record<string, unknown>; updatedAt: string; }
export interface ErpProductMapping { erpField: string; owner: ErpFieldOwnership; targetField?: string; writableInFuture: boolean; currentSprintMode: "ReadOnly"|"Unsupported"|"Deferred"; notes: string; dataLossRisk: "None"|"Low"|"Medium"|"High"; }
export enum ErpFieldOwnership { ERP="ERP", Web="Web", Shared="Shared", Derived="Derived" }
export interface ErpSyncCheckpoint { checkpointToken: string; generatedAt: string; latestProductUpdatedAt?: string; latestStockMovementCreatedAt?: string; latestOrderUpdatedAt?: string; latestShipmentUpdatedAt?: string; latestReturnRefundUpdatedAt?: string; apiVersion: string; schemaVersion: string; }
export interface ErpCommandEnvelope { commandId: string; requestId: string; clientId: string; clientVersion: string; commandType: string; entityType: string; entityId?: string; idempotencyKey: string; payload: unknown; createdAt: string; }
export interface ErpCommandResult { commandId?: string; requestId?: string; status: "Valid"|"Invalid"|"NotEnabled"; errors: string[]; readOnly: boolean; }
export interface ErpIntegrationError { code: string; message: string; }
export interface ErpApiVersionInfo { apiVersion: string; minimumSupportedErpClientVersion: string; latestSupportedErpClientVersion: string; serverTime: string; compatible: boolean; }

export enum ErpMigrationSourceType { LocalStorageJson="LocalStorageJson", SupabaseJson="SupabaseJson", ManualJson="ManualJson" }
export enum ErpMigrationEntityType { Product="Product", Supplier="Supplier", Purchase="Purchase", PurchaseProduct="PurchaseProduct", HistoricalSale="HistoricalSale", Invoice="Invoice", FinanceRecord="FinanceRecord", ShippingRecord="ShippingRecord", Customer="Customer", Category="Category", Collection="Collection", Brand="Brand", Location="Location", MarketplaceReference="MarketplaceReference", SynchronizationMetadata="SynchronizationMetadata", Setting="Setting", Unsupported="Unsupported" }
export enum ErpMigrationAction { Create="Create", Match="Match", UpdateCandidate="UpdateCandidate", Conflict="Conflict", Skip="Skip", Unsupported="Unsupported" }
export enum ErpMigrationSeverity { Info="Info", Warning="Warning", Error="Error", Blocking="Blocking" }
export enum ErpMigrationIssueType { DuplicateSku="DuplicateSku", DuplicateErpId="DuplicateErpId", DuplicateNoctellaId="DuplicateNoctellaId", ExistingProductMatch="ExistingProductMatch", AmbiguousProductMatch="AmbiguousProductMatch", MissingRequiredField="MissingRequiredField", InvalidValue="InvalidValue", InvalidDate="InvalidDate", InvalidQuantity="InvalidQuantity", UnsupportedCurrency="UnsupportedCurrency", UnknownCategory="UnknownCategory", UnknownCollection="UnknownCollection", UnknownSupplier="UnknownSupplier", MissingProductReference="MissingProductReference", HistoricalSaleConflict="HistoricalSaleConflict", InvoiceConflict="InvoiceConflict", FieldLoss="FieldLoss", UnsupportedEntity="UnsupportedEntity", SensitiveField="SensitiveField", CredentialField="CredentialField", InvalidRelationship="InvalidRelationship", Unknown="Unknown" }
export interface ErpMigrationIssue { type: ErpMigrationIssueType; severity: ErpMigrationSeverity; message: string; entityType?: ErpMigrationEntityType; sourceId?: string; field?: string; }
export interface ErpMigrationConflict { type: ErpMigrationIssueType; severity: ErpMigrationSeverity; entityType: ErpMigrationEntityType; sourceId?: string; targetIds?: string[]; message: string; }
export interface ErpMigrationFieldMapping { sourceField: string; targetField?: string; classification: "mapped"|"metadata"|"derived"|"deferred"|"unsupported"; valuePreview?: unknown; targetValuePreview?: unknown; risk?: string; }
export interface ErpMigrationEntityPreview { sourceEntityType: ErpMigrationEntityType; sourceId: string; targetEntityType: ErpMigrationEntityType; targetId?: string|null; action: ErpMigrationAction; mappedFields: ErpMigrationFieldMapping[]; differences: ErpMigrationFieldMapping[]; dependencies: string[]; warnings: ErpMigrationIssue[]; blockingIssues: ErpMigrationIssue[]; unsupportedFields: string[]; maskedSensitiveFields: string[]; checksum: string; }
export interface ErpMigrationSummary { entityCounts: Record<string, number>; actionCounts: Record<string, number>; blockingCount: number; warningCount: number; fieldLossCount: number; maskedPiiCount: number; }
export interface ErpMigrationManifestEntry { sourceEntityType: ErpMigrationEntityType; sourceId: string; targetEntityType: ErpMigrationEntityType; targetId: string|null; action: ErpMigrationAction; mappingVersion: string; idempotencyKey: string; dependencies: string[]; warnings: ErpMigrationIssue[]; blockingIssues: ErpMigrationIssue[]; sourceChecksum: string; targetSnapshotChecksum: string|null; }
export interface ErpMigrationManifest { dryRun: true; mappingVersion: string; generatedAt: string; entries: ErpMigrationManifestEntry[]; }
export interface ErpMigrationSourceFingerprint { algorithm: "sha256"; value: string; }
export interface ErpMigrationCapabilities { dryRunOnly: true; supportedSourceTypes: ErpMigrationSourceType[]; supportedDomains: string[]; maxRecords: number; maxUploadBytes: number; noExecutionEndpoint: true; }
export interface ErpMigrationValidationResult { ok: boolean; sourceType: ErpMigrationSourceType; sourceVersion?: string; fingerprint: ErpMigrationSourceFingerprint; issues: ErpMigrationIssue[]; entityCounts: Record<string, number>; dryRun: true; }
export interface ErpMigrationPreviewResult extends ErpMigrationValidationResult { generatedAt: string; mappingVersion: string; summary: ErpMigrationSummary; entityPreviews: ErpMigrationEntityPreview[]; conflicts: ErpMigrationConflict[]; dependencies: string[]; manifestPreview: ErpMigrationManifest; maskedPiiSummary: Record<string, number>; }
