export enum SupplierStatus { Active = "Active", Inactive = "Inactive" }
export enum SupplierType { AuctionHouse = "AuctionHouse", Dealer = "Dealer", Marketplace = "Marketplace", PrivateSeller = "PrivateSeller", Wholesaler = "Wholesaler", Other = "Other" }
export enum PurchaseStatus { Draft = "Draft", Ordered = "Ordered", PartiallyReceived = "PartiallyReceived", Received = "Received", Cancelled = "Cancelled" }
export enum PurchaseSourceType { Auction = "Auction", Dealer = "Dealer", Marketplace = "Marketplace", Private = "Private", Wholesale = "Wholesale", Other = "Other" }
export enum LandedCostAllocationMethod { Equal = "Equal", ByItemCost = "ByItemCost", ByQuantity = "ByQuantity", ByWeight = "ByWeight", Manual = "Manual" }
export interface Supplier { id:string; erpReferenceId?:string|null; name:string; normalizedName:string; supplierType:SupplierType; countryCode?:string|null; city?:string|null; email?:string|null; phone?:string|null; website?:string|null; taxNumber?:string|null; notes?:string|null; status:SupplierStatus; createdAt:string; updatedAt:string; }
export interface Purchase { id:string; erpReferenceId?:string|null; supplierId?:string|null; sourceType:PurchaseSourceType; externalReference?:string|null; invoiceReferenceNumber?:string|null; auctionHouse?:string|null; auctionDate?:string|null; currency:"EUR"; itemSubtotal:number; buyerPremium?:number|null; shippingCost?:number|null; customsCost?:number|null; packagingCost?:number|null; taxVat?:number|null; miscellaneousCost?:number|null; totalCost?:number|null; status:PurchaseStatus; orderedAt?:string|null; receivedAt?:string|null; notes?:string|null; createdAt:string; updatedAt:string; }
export interface PurchaseLine { id:string; purchaseId:string; productId?:string|null; sourceLineReference?:string|null; titleSnapshot:string; quantity:number; receivedQuantity:number; unitPurchaseCost:number; weight?:number|null; manualAllocatedCost?:number|null; createdAt:string; updatedAt:string; }
export interface PurchaseAllocation { id:string; purchaseId:string; purchaseLineId:string; productId?:string|null; allocationMethod:LandedCostAllocationMethod; allocatedShippingCost?:number|null; allocatedCustomsCost?:number|null; allocatedPackagingCost?:number|null; allocatedBuyerPremium?:number|null; allocatedMiscCost?:number|null; allocatedTaxVat?:number|null; allocatedTotalCost:number; createdAt:string; updatedAt:string; }
export interface PurchaseReceipt { id:string; purchaseId:string; idempotencyKey:string; receivedAt:string; note?:string|null; createdAt:string; }
export interface PurchaseReceiptLine { id:string; receiptId:string; purchaseLineId:string; quantityReceived:number; stockMovementId?:string|null; createdAt:string; }
export interface PurchaseEvent { id:string; purchaseId:string; eventType:string; safeMetadata?:Record<string, unknown>|null; createdAt:string; }
export interface LandedCostSummary { purchaseId:string; currency:"EUR"; allocationMethod:LandedCostAllocationMethod; complete:boolean; reconciled:boolean; totalCost:number|null; allocatedTotal:number|null; lines:Array<{ purchaseLineId:string; productId?:string|null; baseItemCost:number; allocatedBuyerPremium:number|null; allocatedShipping:number|null; allocatedCustoms:number|null; allocatedPackaging:number|null; allocatedTaxVat:number|null; allocatedMiscellaneous:number|null; landedUnitCost:number|null; landedTotalCost:number|null; complete:boolean; }>; }
export type ErpSupplierProjection = Supplier & { purchaseCount:number; lastPurchaseAt?:string|null };
export type ErpPurchaseProjection = Purchase & { supplier?:Supplier|null; lines:PurchaseLine[]; allocations:PurchaseAllocation[]; receipts:PurchaseReceipt[]; };
export interface ErpSupplierCreateCommand { erpReferenceId?:string; name:string; supplierType:SupplierType; countryCode?:string; city?:string; email?:string; phone?:string; website?:string; taxNumber?:string; notes?:string; }
export type ErpSupplierUpdateCommand = Partial<ErpSupplierCreateCommand> & { expectedUpdatedAt?:string; status?:SupplierStatus };
export interface ErpPurchaseCreateCommand extends Partial<Purchase> { lines: Array<Partial<PurchaseLine> & { titleSnapshot:string; quantity:number; unitPurchaseCost:number }>; }
export type ErpPurchaseUpdateCommand = Partial<ErpPurchaseCreateCommand> & { expectedUpdatedAt?:string };
export interface ErpPurchaseReceiptCommand { idempotencyKey?:string; receivedAt?:string; note?:string; lines:Array<{ purchaseLineId:string; quantityReceived:number }>; }
export interface ErpPurchaseAllocationCommand { allocationMethod:LandedCostAllocationMethod; manual?:Array<{ purchaseLineId:string; allocatedBuyerPremium?:number; allocatedShippingCost?:number; allocatedCustomsCost?:number; allocatedPackagingCost?:number; allocatedTaxVat?:number; allocatedMiscCost?:number; allocatedTotalCost:number }>; finalize?:boolean; }
