export type CurrencyCode="EUR"; export type ISODateTime=string; export type Version=string; export type PurchaseId=string; export type PurchaseLineId=string; export type SupplierId=string; export type PurchaseReceiptId=string;
export type PurchaseStatus="Draft"|"Ordered"|"PartiallyReceived"|"Received"|"Cancelled"|string; export type SupplierStatus="Active"|"Inactive"|string;
export interface PurchaseLineRecord{readonly id:PurchaseLineId;readonly purchaseId:PurchaseId;readonly productId:string|null;readonly sourceLineReference:string|null;readonly titleSnapshot:string;readonly quantity:number;readonly receivedQuantity:number;readonly unitPurchaseCost:number;readonly weight:number|null;readonly manualAllocatedCost:number|null;readonly createdAt:ISODateTime;readonly updatedAt:Version}
export interface PurchaseRecord{readonly id:PurchaseId;readonly erpReferenceId:string|null;readonly supplierId:SupplierId|null;readonly sourceType:string;readonly externalReference:string|null;readonly invoiceReferenceNumber:string|null;readonly auctionHouse:string|null;readonly auctionDate:string|null;readonly currency:CurrencyCode;readonly itemSubtotal:number;readonly buyerPremium:number|null;readonly shippingCost:number|null;readonly customsCost:number|null;readonly packagingCost:number|null;readonly taxVat:number|null;readonly miscellaneousCost:number|null;readonly totalCost:number|null;readonly status:PurchaseStatus;readonly orderedAt:string|null;readonly receivedAt:string|null;readonly notes:string|null;readonly createdAt:ISODateTime;readonly updatedAt:Version;readonly lines:readonly PurchaseLineRecord[]}
export interface SupplierRecord{readonly id:SupplierId;readonly erpReferenceId:string|null;readonly name:string;readonly normalizedName:string;readonly supplierType:string;readonly countryCode:string|null;readonly city:string|null;readonly email:string|null;readonly phone:string|null;readonly website:string|null;readonly taxNumber:string|null;readonly notes:string|null;readonly status:SupplierStatus;readonly createdAt:ISODateTime;readonly updatedAt:Version}
export interface PurchaseReceiptLineRecord{readonly id:string;readonly receiptId:PurchaseReceiptId;readonly purchaseLineId:PurchaseLineId;readonly quantityReceived:number;readonly stockMovementId:string|null;readonly createdAt:ISODateTime}
export interface PurchaseReceiptRecord{readonly id:PurchaseReceiptId;readonly purchaseId:PurchaseId;readonly idempotencyKey:string;readonly receivedAt:ISODateTime;readonly note:string|null;readonly createdAt:ISODateTime;readonly lines:readonly PurchaseReceiptLineRecord[]}
export type CreatePurchaseInput=Omit<PurchaseRecord,"lines"> & {readonly lines: readonly Omit<PurchaseLineRecord,"purchaseId">[]}; export type UpdatePurchaseInput=Partial<Omit<CreatePurchaseInput,"id"|"createdAt"|"lines">> & {readonly updatedAt:ISODateTime};
export type CreateSupplierInput=SupplierRecord; export type UpdateSupplierInput=Partial<Omit<SupplierRecord,"id"|"createdAt">> & {readonly updatedAt:ISODateTime}; export type AppendPurchaseReceiptInput=PurchaseReceiptRecord;
export interface PurchaseRepository{create(input:CreatePurchaseInput):PurchaseRecord;findById(id:PurchaseId):PurchaseRecord|null;findByReference(reference:string):PurchaseRecord|null;list(query?:{readonly status?:string;readonly supplierId?:string;readonly limit?:number;readonly offset?:number}):{readonly rows:readonly PurchaseRecord[];readonly total:number;readonly limit:number;readonly offset:number};existsByReference(reference:string):boolean;update(id:PurchaseId,patch:UpdatePurchaseInput):PurchaseRecord|null;updateWithVersion(id:PurchaseId,expectedUpdatedAt:Version,patch:UpdatePurchaseInput):{readonly ok:true;readonly value:PurchaseRecord}|{readonly ok:false;readonly issue:{readonly code:"not_found"|"optimistic_conflict";readonly message:string}};addLine(line:PurchaseLineRecord):PurchaseLineRecord;updateLine(id:PurchaseLineId,patch:Partial<Omit<PurchaseLineRecord,"id"|"purchaseId"|"createdAt">>):PurchaseLineRecord|null;removeLine(id:PurchaseLineId):boolean}
export interface SupplierRepository{create(input:CreateSupplierInput):SupplierRecord;findById(id:SupplierId):SupplierRecord|null;findByCode(code:string):SupplierRecord|null;findByName(name:string):readonly SupplierRecord[];list(query?:{readonly status?:string;readonly limit?:number;readonly offset?:number}):readonly SupplierRecord[];existsByCode(code:string):boolean;update(id:SupplierId,patch:UpdateSupplierInput):SupplierRecord|null;updateWithVersion(id:SupplierId,expectedUpdatedAt:Version,patch:UpdateSupplierInput):{readonly ok:true;readonly value:SupplierRecord}|{readonly ok:false;readonly issue:{readonly code:"not_found"|"optimistic_conflict";readonly message:string}}}
export interface PurchaseReceiptRepository{append(input:AppendPurchaseReceiptInput):PurchaseReceiptRecord;findById(id:PurchaseReceiptId):PurchaseReceiptRecord|null;findByIdempotencyKey(key:string):PurchaseReceiptRecord|null;listByPurchase(id:PurchaseId):readonly PurchaseReceiptRecord[];listByPurchaseLine(id:PurchaseLineId):readonly PurchaseReceiptRecord[];listByReference(reference:string):readonly PurchaseReceiptRecord[]}
export interface PurchaseRepositories{readonly purchases:PurchaseRepository;readonly suppliers:SupplierRepository;readonly receipts:PurchaseReceiptRepository} export type PurchaseRepositoryDriver="sqlite"|"test-memory"|"postgres"|"supabase-postgres";
