import * as pgSchema from "../../db/schema.postgres";
import type { AddReturnEventRecordInput, CreateReturnItemRecordInput, CreateReturnRecordInput, ReturnRepositoryBundle, ReturnRepositoryQuery } from "./types";
type Adapter={select:(t:string,p?:(r:any)=>boolean)=>any[];insert:(t:string,r:any)=>any;update:(t:string,p:(r:any)=>boolean,set:any)=>any[];count:(t:string,p?:(r:any)=>boolean)=>number;bind?:(v:any)=>any;uniqueOn?:(t:string,c:string[])=>void;transaction?:Function;queries?:any[]};
const T={returns:"return_requests",items:"return_items",events:"return_events"}; const b=(a:Adapter,v:any)=>a.bind?a.bind(v):v; const norm=(r:any)=>r?{...r,externalReference:r.externalReference??r.externalReturnId??null,version:r.version??0}:null; const page=(a:any[],q:ReturnRepositoryQuery={})=>a.sort((x,y)=>String(y.updatedAt??y.createdAt).localeCompare(String(x.updatedAt??x.createdAt))||String(x.id).localeCompare(String(y.id))).slice(q.offset??0,(q.offset??0)+(q.limit??25)); const like=(v:any,s:string)=>String(v??"").toLowerCase().includes(s.toLowerCase());
export function createPostgresReturnRepositoryBundle(adapter:Adapter):ReturnRepositoryBundle{ void pgSchema.returnRequests; adapter.uniqueOn?.(T.returns,["idempotencyKey"]); adapter.uniqueOn?.(T.events,["idempotencyKey"]);
 const all=(q:ReturnRepositoryQuery={})=>page(adapter.select(T.returns,(r)=> (!q.status||r.status===b(adapter,q.status))&&(!q.reason||r.reason===b(adapter,q.reason))&&(!q.orderId||r.orderId===b(adapter,q.orderId))&&(!q.updatedSince||r.updatedAt>b(adapter,q.updatedSince))&&(!q.search||[r.id,r.orderId,r.externalReturnId,r.externalReference].some(x=>like(x,q.search!)))&&(!q.productId||adapter.select(T.items,i=>i.productId===q.productId&&i.returnRequestId===r.id).length>0)).map(norm),q);
 const itemsBy=(p:(r:any)=>boolean)=>adapter.select(T.items,p).sort((a,b)=>String(a.id).localeCompare(String(b.id))).map((r:any)=>({...r,inspectionResult:r.inspectionResult??null,quantityCompleted:r.quantityCompleted??null,completedAt:r.completedAt??null}));
 const eventsBy=(p:(r:any)=>boolean)=>adapter.select(T.events,p).sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt))||String(a.id).localeCompare(String(b.id)));
 const itemRead:any={getById:(id:string)=>itemsBy(r=>r.id===b(adapter,id))[0]??null,listByReturn:(id:string)=>itemsBy(r=>r.returnRequestId===b(adapter,id)),listByOrderItem:(id:string)=>itemsBy(r=>r.orderItemId===b(adapter,id)),listByProduct:(id:string)=>itemsBy(r=>r.productId===b(adapter,id)),countByReturn:(id:string)=>itemRead.listByReturn(id).length,getReturnedQuantityByOrderItem:(id:string)=>itemRead.listByOrderItem(id).reduce((a:any,i:any)=>a+(i.quantityReceived??i.quantityRequested??0),0),getCompletedQuantityByOrderItem:(id:string)=>itemRead.listByOrderItem(id).reduce((a:any,i:any)=>a+(i.quantityCompleted??0),0)};
 const eventRead:any={getById:(id:string)=>eventsBy(r=>r.id===b(adapter,id))[0]??null,listByReturn:(id:string)=>eventsBy(r=>r.returnRequestId===b(adapter,id)),listByOrder:(id:string)=>eventsBy(r=>r.orderId===b(adapter,id)||read.getById(r.returnRequestId)?.orderId===id),countByReturn:(id:string)=>eventRead.listByReturn(id).length,getLatestByReturn:(id:string)=>eventRead.listByReturn(id).at(-1)??null};
 const proj=(r:any)=>({...r,itemCount:itemRead.countByReturn(r.id)}); const read:any={getById:(id:string)=>norm(adapter.select(T.returns,r=>r.id===b(adapter,id))[0]??null),getByOrderId:(id:string)=>all({orderId:id,limit:100000}),getByExternalReference:(x:string)=>norm(adapter.select(T.returns,r=>r.externalReference===b(adapter,x)||r.externalReturnId===x)[0]??null),getByIdempotencyKey:(k:string)=>norm(adapter.select(T.returns,r=>r.idempotencyKey===b(adapter,k))[0]??null),list:(q?:ReturnRepositoryQuery)=>({rows:all(q).map(proj),total:all({...q,limit:100000,offset:0}).length,limit:q?.limit??25,offset:q?.offset??0}),search:(t:string,q?:ReturnRepositoryQuery)=>read.list({...q,search:t}),count:(q?:ReturnRepositoryQuery)=>all({...q,limit:100000,offset:0}).length,listByStatus:(x:string,q?:ReturnRepositoryQuery)=>all({...q,status:x}).map(proj),listByReason:(x:string,q?:ReturnRepositoryQuery)=>all({...q,reason:x}).map(proj),listByProduct:(x:string,q?:ReturnRepositoryQuery)=>all({...q,productId:x}).map(proj),listUpdatedSince:(x:string,q?:ReturnRepositoryQuery)=>all({...q,updatedSince:x}).map(proj),getEligibilityProjection:(orderId:string)=>{const rs=read.getByOrderId(orderId); const ids=new Set(rs.map((r:any)=>r.id)); const its=adapter.select(T.items,i=>ids.has(i.returnRequestId)); return {orderId,returnedQuantity:its.reduce((a,i)=>a+(i.quantityReceived??i.quantityRequested??0),0),completedQuantity:its.reduce((a,i)=>a+(i.quantityCompleted??0),0),activeReturnCount:rs.filter((r:any)=>!["completed","cancelled","closed","rejected"].includes(String(r.status))).length};},getReturnSummary:(id:string)=>{const r=read.getById(id); return r?proj(r):null;},getReturnDetailProjection:(id:string)=>{const r=read.getById(id); return r?{...r,items:itemRead.listByReturn(id),history:eventRead.listByReturn(id)}:null;}};
 const patch=(id:string,set:any,exp?:number|null)=>{const cur=read.getById(id); if(!cur||(exp!=null&&cur.version!==exp))return null; const [r]=adapter.update(T.returns,x=>x.id===b(adapter,id),{...set,version:(cur.version??0)+1}); return norm(r);};
 const write:any={create:(i:CreateReturnRecordInput)=>norm(adapter.insert(T.returns,{...i,externalReturnId:i.externalReturnId??i.externalReference,version:i.version??0})),updateStatus:(i:any)=>patch(i.id,{status:i.status,updatedAt:i.updatedAt},i.expectedVersion),updateApprovalState:(i:any)=>patch(i.id,i,i.expectedVersion),updateRejectionState:(i:any)=>patch(i.id,i,i.expectedVersion),updateReceiptState:(i:any)=>patch(i.id,i,i.expectedVersion),updateInspectionState:(i:any)=>patch(i.id,i,i.expectedVersion),updateCompletionState:(i:any)=>patch(i.id,i,i.expectedVersion),updateCancellationState:(i:any)=>patch(i.id,i,i.expectedVersion),findByIdempotencyKey:read.getByIdempotencyKey,findByExternalReference:read.getByExternalReference,findActiveByOrderItem:(id:string)=>itemRead.listByOrderItem(id).map((i:any)=>read.getById(i.returnRequestId)).filter(Boolean),getVersionForUpdate:(id:string)=>read.getById(id)?.version??null,updateWithExpectedVersion:(id:string,v:any,e:number)=>{const r=patch(id,v,e); return r?{ok:true,value:r}:{ok:false,issue:{code:"optimistic",message:"Expected version mismatch"},conflict:{code:"optimistic",message:"Expected version mismatch"}};}};
 const itemWrite:any={create:(i:CreateReturnItemRecordInput)=>adapter.insert(T.items,i),createMany:(xs:any[])=>xs.map((x)=>itemWrite.create(x)),listForUpdate:itemRead.listByReturn,updateReceivedQuantity:(id:string,q:number,u:string)=>adapter.update(T.items,r=>r.id===id,{quantityReceived:q,updatedAt:u})[0]??null,updateInspectionResult:(id:string,r:any,c:string|null,n:string|null,u:string)=>adapter.update(T.items,x=>x.id===id,{inspectionResult:r,condition:c,inspectionNote:n,updatedAt:u})[0]??null,updateCompletionState:(id:string,q:number,c:string|null,u:string)=>adapter.update(T.items,r=>r.id===id,{quantityCompleted:q,completedAt:c,updatedAt:u})[0]??null};
 const eventWrite:any={append:(i:AddReturnEventRecordInput)=>adapter.insert(T.events,i),appendIdempotent:(i:AddReturnEventRecordInput)=>i.idempotencyKey&&eventWrite.findByIdempotencyKey(i.idempotencyKey)||eventWrite.append(i),findByIdempotencyKey:(k:string)=>eventsBy(r=>r.idempotencyKey===b(adapter,k))[0]??null,listForUpdate:eventRead.listByReturn};
 return {returns:{read,write},items:{read:itemRead,write:itemWrite},events:{read:eventRead,write:eventWrite}};
}
