import { and, asc, desc, eq, gt, like, or, sql } from "drizzle-orm";
import * as s from "../../db/schema.sqlite";
import type { DbClient } from "../../db/client";
import type { AddReturnEventRecordInput, CreateReturnItemRecordInput, CreateReturnRecordInput, ReturnItemRepositoryRecord, ReturnRepositoryBundle, ReturnRepositoryQuery, ReturnRepositoryRecord } from "./types";
const lim=(q?:ReturnRepositoryQuery)=>q?.limit??25, off=(q?:ReturnRepositoryQuery)=>q?.offset??0; const j=(v:unknown)=>v==null?null:typeof v==="string"?v:JSON.stringify(v); const p=(v:unknown)=>v==null?null:typeof v==="string"?JSON.parse(v):v as any;
function rr(r:any):ReturnRepositoryRecord{return {externalReference:r.externalReference??r.externalReturnId??null,idempotencyKey:r.idempotencyKey??null,version:r.version??0,...r};}
function ri(r:any):ReturnItemRepositoryRecord{return {quantityCompleted:r.quantityCompleted??null,inspectionResult:p(r.inspectionResult),completedAt:r.completedAt??null,...r};}
function ev(r:any){return {...r,orderId:r.orderId??null,payloadSnapshot:p(r.payloadSnapshot),idempotencyKey:r.idempotencyKey??null};}
export function createSqliteReturnRepositoryBundle(db:DbClient):ReturnRepositoryBundle{
 const rows=(q:ReturnRepositoryQuery={})=>{const where:any[]=[]; if(q.status)where.push(eq(s.returnRequests.status,q.status)); if(q.reason)where.push(eq(s.returnRequests.reason,q.reason)); if(q.orderId)where.push(eq(s.returnRequests.orderId,q.orderId)); if(q.updatedSince)where.push(gt(s.returnRequests.updatedAt,q.updatedSince)); if(q.search)where.push(or(like(s.returnRequests.id,`%${q.search}%`),like(s.returnRequests.orderId,`%${q.search}%`),like(s.returnRequests.externalReturnId,`%${q.search}%`))); let out=(db.select().from(s.returnRequests).where(where.length?and(...where):undefined as any).orderBy(desc(s.returnRequests.updatedAt),asc(s.returnRequests.id)).limit(lim(q)).offset(off(q)).all?.()??[]) as any[]; if(q.productId){ const ids=new Set((db.select().from(s.returnItems).where(eq(s.returnItems.productId,q.productId)).all?.()??[]).map((x:any)=>x.returnRequestId)); out=out.filter(x=>ids.has(x.id)); } return out.map(rr); };
 const count=(q:ReturnRepositoryQuery={})=>rows({...q,limit:100000,offset:0}).length; const proj=(r:ReturnRepositoryRecord)=>({...r,itemCount:itemRead.countByReturn(r.id)});
 const read:any={getById:(id:string)=>{const [r]=db.select().from(s.returnRequests).where(eq(s.returnRequests.id,id)).limit(1).all() as any[]; return r?rr(r):null;}, getByOrderId:(id:string)=>rows({orderId:id,limit:100000}), getByExternalReference:(x:string)=>rows({limit:100000}).find(r=>r.externalReference===x||r.externalReturnId===x)??null, getByIdempotencyKey:(k:string)=>rows({limit:100000}).find(r=>r.idempotencyKey===k)??null, list:(q?:ReturnRepositoryQuery)=>({rows:rows(q).map(proj),total:count(q),limit:lim(q),offset:off(q)}), search:(t:string,q?:ReturnRepositoryQuery)=>read.list({...q,search:t}), count, listByStatus:(x:string,q?:ReturnRepositoryQuery)=>rows({...q,status:x}).map(proj), listByReason:(x:string,q?:ReturnRepositoryQuery)=>rows({...q,reason:x}).map(proj), listByProduct:(x:string,q?:ReturnRepositoryQuery)=>rows({...q,productId:x}).map(proj), listUpdatedSince:(x:string,q?:ReturnRepositoryQuery)=>rows({...q,updatedSince:x}).map(proj), getEligibilityProjection:(orderId:string)=>{const rs=rows({orderId,limit:100000}); const ids=new Set(rs.map(r=>r.id)); const its=(db.select().from(s.returnItems).all() as any[]).filter(i=>ids.has(i.returnRequestId)); return {orderId,returnedQuantity:its.reduce((a,i)=>a+(i.quantityReceived??i.quantityRequested??0),0),completedQuantity:its.reduce((a,i)=>a+(i.quantityCompleted??0),0),activeReturnCount:rs.filter(r=>!["completed","cancelled","closed","rejected"].includes(String(r.status))).length};}, getReturnSummary:(id:string)=>{const r=read.getById(id); return r?proj(r):null;}, getReturnDetailProjection:(id:string)=>{const r=read.getById(id); return r?{...r,items:itemRead.listByReturn(id),history:eventRead.listByReturn(id)}:null;}};
 const patch=(id:string,set:any,exp?:number|null)=>{const cur=read.getById(id); if(!cur||(exp!=null&&cur.version!==exp))return null; db.update(s.returnRequests).set({...set,version:(cur.version??0)+1}).where(eq(s.returnRequests.id,id)).run(); return read.getById(id);};
 const write:any={create:(i:CreateReturnRecordInput)=>{db.insert(s.returnRequests).values({...i,externalReturnId:i.externalReturnId??i.externalReference,idempotencyKey:i.idempotencyKey,version:i.version??0} as any).run(); return read.getById(i.id)!;}, updateStatus:(i:any)=>patch(i.id,{status:i.status,updatedAt:i.updatedAt},i.expectedVersion), updateApprovalState:(i:any)=>patch(i.id,i,i.expectedVersion), updateRejectionState:(i:any)=>patch(i.id,i,i.expectedVersion), updateReceiptState:(i:any)=>patch(i.id,i,i.expectedVersion), updateInspectionState:(i:any)=>patch(i.id,i,i.expectedVersion), updateCompletionState:(i:any)=>patch(i.id,i,i.expectedVersion), updateCancellationState:(i:any)=>patch(i.id,i,i.expectedVersion), findByIdempotencyKey:read.getByIdempotencyKey, findByExternalReference:read.getByExternalReference, findActiveByOrderItem:(id:string)=>itemRead.listByOrderItem(id).map((it:any)=>read.getById(it.returnRequestId)).filter(Boolean), getVersionForUpdate:(id:string)=>read.getById(id)?.version??null, updateWithExpectedVersion:(id:string,v:any,e:number)=>{const r=patch(id,{...v,updatedAt:v.updatedAt??new Date().toISOString()},e); return r?{ok:true,value:r}:{ok:false,issue:{code:"optimistic",message:"Expected version mismatch"},conflict:{code:"optimistic",message:"Expected version mismatch"}};}};
 const itemRead:any={getById:(id:string)=>{const [r]=db.select().from(s.returnItems).where(eq(s.returnItems.id,id)).limit(1).all() as any[]; return r?ri(r):null;}, listByReturn:(id:string)=>(db.select().from(s.returnItems).where(eq(s.returnItems.returnRequestId,id)).orderBy(asc(s.returnItems.id)).all() as any[]).map(ri), listByOrderItem:(id:string)=>(db.select().from(s.returnItems).where(eq(s.returnItems.orderItemId,id)).orderBy(asc(s.returnItems.id)).all() as any[]).map(ri), listByProduct:(id:string)=>(db.select().from(s.returnItems).where(eq(s.returnItems.productId,id)).orderBy(asc(s.returnItems.id)).all() as any[]).map(ri), countByReturn:(id:string)=>itemRead.listByReturn(id).length, getReturnedQuantityByOrderItem:(id:string)=>itemRead.listByOrderItem(id).reduce((a:any,i:any)=>a+(i.quantityReceived??i.quantityRequested??0),0), getCompletedQuantityByOrderItem:(id:string)=>itemRead.listByOrderItem(id).reduce((a:any,i:any)=>a+(i.quantityCompleted??0),0)};
 const itemWrite:any={create:(i:CreateReturnItemRecordInput)=>{db.insert(s.returnItems).values({...i,inspectionResult:j(i.inspectionResult)} as any).run(); return itemRead.getById(i.id)!;}, createMany:(xs:any[])=>xs.map((x)=>itemWrite.create(x)), listForUpdate:itemRead.listByReturn, updateReceivedQuantity:(id:string,q:number,u:string)=>{db.update(s.returnItems).set({quantityReceived:q,updatedAt:u} as any).where(eq(s.returnItems.id,id)).run(); return itemRead.getById(id);}, updateInspectionResult:(id:string,r:any,c:string|null,n:string|null,u:string)=>{db.update(s.returnItems).set({inspectionResult:j(r),condition:c,inspectionNote:n,updatedAt:u} as any).where(eq(s.returnItems.id,id)).run(); return itemRead.getById(id);}, updateCompletionState:(id:string,q:number,c:string|null,u:string)=>{db.update(s.returnItems).set({quantityCompleted:q,completedAt:c,updatedAt:u} as any).where(eq(s.returnItems.id,id)).run(); return itemRead.getById(id);}};
 const eventRead:any={getById:(id:string)=>{const [r]=db.select().from(s.returnEvents).where(eq(s.returnEvents.id,id)).limit(1).all() as any[]; return r?ev(r):null;}, listByReturn:(id:string)=>(db.select().from(s.returnEvents).where(eq(s.returnEvents.returnRequestId,id)).orderBy(asc(s.returnEvents.createdAt),asc(s.returnEvents.id)).all() as any[]).map(ev), listByOrder:(id:string)=>eventRead.listByReturn(id).filter((e:any)=>e.orderId===id||read.getById(e.returnRequestId)?.orderId===id), countByReturn:(id:string)=>eventRead.listByReturn(id).length, getLatestByReturn:(id:string)=>eventRead.listByReturn(id).at(-1)??null};
 const eventWrite:any={append:(i:AddReturnEventRecordInput)=>{db.insert(s.returnEvents).values({...i,payloadSnapshot:j(i.payloadSnapshot)} as any).run(); return eventRead.getById(i.id)!;}, appendIdempotent:(i:AddReturnEventRecordInput)=>i.idempotencyKey&&eventWrite.findByIdempotencyKey(i.idempotencyKey)||eventWrite.append(i), findByIdempotencyKey:(k:string)=>(db.select().from(s.returnEvents).where(eq((s.returnEvents as any).idempotencyKey,k)).limit(1).all() as any[]).map(ev)[0]??null, listForUpdate:eventRead.listByReturn};
 return {returns:{read,write},items:{read:itemRead,write:itemWrite},events:{read:eventRead,write:eventWrite}};
}
