import type { ReturnItemCondition, ReturnReason, ReturnResolution, ReturnStatus, ReturnStockDisposition } from "@noctella/shared";
export type JsonRecord = Record<string, unknown>;
export interface ReturnRepositoryRecord { id:string; orderId:string; marketplaceOrderId:string|null; shipmentId:string|null; channel:string|null; externalReturnId:string|null; externalReturnNumber:string|null; externalReference:string|null; idempotencyKey:string|null; status:ReturnStatus|string; reason:ReturnReason|string; reasonDetails:string|null; requestedResolution:ReturnResolution|string; approvedResolution:ReturnResolution|string|null; buyerMessage:string|null; internalNote:string|null; requestedAt:string; authorizedAt:string|null; receivedAt:string|null; inspectedAt:string|null; completedAt:string|null; cancelledAt:string|null; returnCarrierCode:string|null; returnTrackingNumber:string|null; returnTrackingUrl:string|null; buyerShippedAt:string|null; lastError:string|null; version:number; createdAt:string; updatedAt:string }
export interface ReturnItemRepositoryRecord { id:string; returnRequestId:string; orderItemId:string; productId:string|null; quantityRequested:number; quantityApproved:number|null; quantityReceived:number|null; quantityCompleted:number|null; condition:ReturnItemCondition|string|null; stockDisposition:ReturnStockDisposition|string|null; inspectionNote:string|null; inspectionResult:JsonRecord|null; completedAt:string|null; createdAt:string; updatedAt:string }
export interface ReturnEventRepositoryRecord { id:string; returnRequestId:string; orderId:string|null; eventType:string; previousStatus:string|null; newStatus:string|null; payloadSnapshot:JsonRecord|null; errorCode:string|null; errorMessage:string|null; idempotencyKey:string|null; createdAt:string }
export type ReturnListProjection = Pick<ReturnRepositoryRecord,"id"|"orderId"|"status"|"reason"|"requestedAt"|"createdAt"|"updatedAt"|"externalReference"> & { itemCount:number };
export interface ReturnDetailProjection extends ReturnRepositoryRecord { items: ReturnItemProjection[]; history: ReturnHistoryProjection[] }
export type ReturnItemProjection = ReturnItemRepositoryRecord;
export interface ReturnEligibilityProjection { orderId:string; returnedQuantity:number; completedQuantity:number; activeReturnCount:number }
export type ReturnHistoryProjection = ReturnEventRepositoryRecord;
export interface ReturnRepositoryQuery { limit?:number; offset?:number; status?:string; reason?:string; productId?:string; orderId?:string; search?:string; updatedSince?:string }
export interface ReturnRepositoryPage<T> { rows:T[]; total:number; limit:number; offset:number }
export type CreateReturnRecordInput = Omit<ReturnRepositoryRecord,"version"> & { version?:number };
export type CreateReturnItemRecordInput = ReturnItemRepositoryRecord;
export interface UpdateReturnStatusInput { id:string; status:string; updatedAt:string; expectedVersion?:number|null }
export interface UpdateReturnApprovalStateInput extends UpdateReturnStatusInput { authorizedAt?:string|null; approvedResolution?:string|null; internalNote?:string|null }
export interface UpdateReturnRejectionStateInput extends UpdateReturnStatusInput { internalNote?:string|null; lastError?:string|null }
export interface UpdateReturnReceiptStateInput extends UpdateReturnStatusInput { receivedAt?:string|null; returnCarrierCode?:string|null; returnTrackingNumber?:string|null; returnTrackingUrl?:string|null }
export interface UpdateReturnInspectionStateInput extends UpdateReturnStatusInput { inspectedAt?:string|null; internalNote?:string|null }
export interface UpdateReturnCompletionStateInput extends UpdateReturnStatusInput { completedAt?:string|null }
export interface UpdateReturnCancellationStateInput extends UpdateReturnStatusInput { cancelledAt?:string|null; internalNote?:string|null }
export interface AddReturnEventRecordInput extends ReturnEventRepositoryRecord {}
export interface ReturnRepositoryConflict { code:"conflict"|"unique"|"optimistic"; message:string; field?:string }
export interface ReturnRepositoryIssue { code:string; message:string }
export type ReturnRepositoryResult<T> = { ok:true; value:T } | { ok:false; issue:ReturnRepositoryIssue; conflict?:ReturnRepositoryConflict };
export interface ReturnReadRepository { getById(id:string):ReturnRepositoryRecord|null|Promise<ReturnRepositoryRecord|null>; getByOrderId(orderId:string):ReturnRepositoryRecord[]|Promise<ReturnRepositoryRecord[]>; getByExternalReference(ref:string):ReturnRepositoryRecord|null|Promise<ReturnRepositoryRecord|null>; getByIdempotencyKey(key:string):ReturnRepositoryRecord|null|Promise<ReturnRepositoryRecord|null>; list(q?:ReturnRepositoryQuery):ReturnRepositoryPage<ReturnListProjection>|Promise<ReturnRepositoryPage<ReturnListProjection>>; search(term:string,q?:ReturnRepositoryQuery):ReturnRepositoryPage<ReturnListProjection>|Promise<ReturnRepositoryPage<ReturnListProjection>>; count(q?:ReturnRepositoryQuery):number|Promise<number>; listByStatus(status:string,q?:ReturnRepositoryQuery):ReturnListProjection[]|Promise<ReturnListProjection[]>; listByReason(reason:string,q?:ReturnRepositoryQuery):ReturnListProjection[]|Promise<ReturnListProjection[]>; listByProduct(productId:string,q?:ReturnRepositoryQuery):ReturnListProjection[]|Promise<ReturnListProjection[]>; listUpdatedSince(since:string,q?:ReturnRepositoryQuery):ReturnListProjection[]|Promise<ReturnListProjection[]>; getEligibilityProjection(orderId:string):ReturnEligibilityProjection|Promise<ReturnEligibilityProjection>; getReturnSummary(id:string):ReturnListProjection|null|Promise<ReturnListProjection|null>; getReturnDetailProjection(id:string):ReturnDetailProjection|null|Promise<ReturnDetailProjection|null> }
export interface ReturnWriteRepository { create(input:CreateReturnRecordInput):ReturnRepositoryRecord|Promise<ReturnRepositoryRecord>; updateStatus(input:UpdateReturnStatusInput):ReturnRepositoryRecord|null|Promise<ReturnRepositoryRecord|null>; updateApprovalState(input:UpdateReturnApprovalStateInput):ReturnRepositoryRecord|null|Promise<ReturnRepositoryRecord|null>; updateRejectionState(input:UpdateReturnRejectionStateInput):ReturnRepositoryRecord|null|Promise<ReturnRepositoryRecord|null>; updateReceiptState(input:UpdateReturnReceiptStateInput):ReturnRepositoryRecord|null|Promise<ReturnRepositoryRecord|null>; updateInspectionState(input:UpdateReturnInspectionStateInput):ReturnRepositoryRecord|null|Promise<ReturnRepositoryRecord|null>; updateCompletionState(input:UpdateReturnCompletionStateInput):ReturnRepositoryRecord|null|Promise<ReturnRepositoryRecord|null>; updateCancellationState(input:UpdateReturnCancellationStateInput):ReturnRepositoryRecord|null|Promise<ReturnRepositoryRecord|null>; findByIdempotencyKey(key:string):ReturnRepositoryRecord|null|Promise<ReturnRepositoryRecord|null>; findByExternalReference(ref:string):ReturnRepositoryRecord|null|Promise<ReturnRepositoryRecord|null>; findActiveByOrderItem(orderItemId:string):ReturnRepositoryRecord[]|Promise<ReturnRepositoryRecord[]>; getVersionForUpdate(id:string):number|null|Promise<number|null>; updateWithExpectedVersion(id:string, values:Partial<ReturnRepositoryRecord>, expectedVersion:number):ReturnRepositoryResult<ReturnRepositoryRecord>|Promise<ReturnRepositoryResult<ReturnRepositoryRecord>> }
export interface ReturnItemReadRepository { getById(id:string):ReturnItemRepositoryRecord|null|Promise<ReturnItemRepositoryRecord|null>; listByReturn(id:string):ReturnItemRepositoryRecord[]|Promise<ReturnItemRepositoryRecord[]>; listByOrderItem(id:string):ReturnItemRepositoryRecord[]|Promise<ReturnItemRepositoryRecord[]>; listByProduct(id:string):ReturnItemRepositoryRecord[]|Promise<ReturnItemRepositoryRecord[]>; countByReturn(id:string):number|Promise<number>; getReturnedQuantityByOrderItem(id:string):number|Promise<number>; getCompletedQuantityByOrderItem(id:string):number|Promise<number> }
export interface ReturnItemWriteRepository { create(input:CreateReturnItemRecordInput):ReturnItemRepositoryRecord|Promise<ReturnItemRepositoryRecord>; createMany(input:CreateReturnItemRecordInput[]):ReturnItemRepositoryRecord[]|Promise<ReturnItemRepositoryRecord[]>; listForUpdate(id:string):ReturnItemRepositoryRecord[]|Promise<ReturnItemRepositoryRecord[]>; updateReceivedQuantity(id:string, quantity:number, updatedAt:string):ReturnItemRepositoryRecord|null|Promise<ReturnItemRepositoryRecord|null>; updateInspectionResult(id:string, result:JsonRecord|null, condition:string|null, note:string|null, updatedAt:string):ReturnItemRepositoryRecord|null|Promise<ReturnItemRepositoryRecord|null>; updateCompletionState(id:string, quantityCompleted:number, completedAt:string|null, updatedAt:string):ReturnItemRepositoryRecord|null|Promise<ReturnItemRepositoryRecord|null> }
export interface ReturnEventReadRepository { getById(id:string):ReturnEventRepositoryRecord|null|Promise<ReturnEventRepositoryRecord|null>; listByReturn(id:string):ReturnEventRepositoryRecord[]|Promise<ReturnEventRepositoryRecord[]>; listByOrder(id:string):ReturnEventRepositoryRecord[]|Promise<ReturnEventRepositoryRecord[]>; countByReturn(id:string):number|Promise<number>; getLatestByReturn(id:string):ReturnEventRepositoryRecord|null|Promise<ReturnEventRepositoryRecord|null> }
export interface ReturnEventWriteRepository { append(input:AddReturnEventRecordInput):ReturnEventRepositoryRecord|Promise<ReturnEventRepositoryRecord>; appendIdempotent(input:AddReturnEventRecordInput):ReturnEventRepositoryRecord|Promise<ReturnEventRepositoryRecord>; findByIdempotencyKey(key:string):ReturnEventRepositoryRecord|null|Promise<ReturnEventRepositoryRecord|null>; listForUpdate(id:string):ReturnEventRepositoryRecord[]|Promise<ReturnEventRepositoryRecord[]> }
export interface ReturnRepositoryBundle { returns:{read:ReturnReadRepository; write:ReturnWriteRepository}; items:{read:ReturnItemReadRepository; write:ReturnItemWriteRepository}; events:{read:ReturnEventReadRepository; write:ReturnEventWriteRepository} }
export type ReturnRepositoryDriver = "sqlite"|"postgres"|"supabase-postgres"|"test-memory";
