import { randomUUID } from "node:crypto";
import { and, asc, desc, eq, inArray, lte } from "drizzle-orm";
import { BackgroundJobStatus, BackgroundJobType } from "@noctella/shared";
import type { DbClient } from "../db/client";
import { backgroundJobs } from "../db/schema";
import { syncExternalListingStock, syncProductStock, enqueueChannelListings } from "./stockSync";
import { refreshShipmentStatus, submitMarketplaceShipment } from "./shipments";
import { executeMarketplaceRefund } from "./returns";

export type JobErrorType = "Validation"|"Authentication"|"Authorization"|"NotFound"|"RateLimit"|"Timeout"|"Temporary"|"Permanent"|"Conflict"|"Lock"|"Unknown";
export function sanitizeError(error: unknown): { type: JobErrorType; message: string; retryable: boolean } { const e = error as { type?: string; message?: string; retryable?: boolean }; const type = (["Validation","Authentication","Authorization","NotFound","RateLimit","Timeout","Temporary","Permanent","Conflict","Lock"] as string[]).includes(String(e.type)) ? String(e.type) as JobErrorType : "Unknown"; return { type, message: String(e.message ?? type).replace(/Bearer\s+\S+|access_token[^,}\s]*/gi, "[redacted]").slice(0, 500), retryable: e.retryable ?? ["RateLimit","Timeout","Temporary","Unknown","Lock"].includes(type) }; }
export async function enqueueJob(db: DbClient, input: { type: string; payload?: unknown; idempotencyKey: string; channel?: string; productId?: string; externalListingId?: string; priority?: number; runAfter?: string; maxAttempts?: number }) { const now = new Date().toISOString(); const row = { id: randomUUID(), type: input.type, status: BackgroundJobStatus.Pending, channel: input.channel, productId: input.productId, externalListingId: input.externalListingId, payloadSnapshot: JSON.stringify(input.payload ?? {}), idempotencyKey: input.idempotencyKey, priority: input.priority ?? 0, attemptCount: 0, maxAttempts: input.maxAttempts ?? 5, runAfter: input.runAfter ?? now, createdAt: now, updatedAt: now }; try { await db.insert(backgroundJobs).values(row).run(); return row; } catch { const [existing] = await db.select().from(backgroundJobs).where(eq(backgroundJobs.idempotencyKey, input.idempotencyKey)); return existing; } }
export async function claimJobs(db: DbClient, workerId: string, batchSize = 1, now = new Date().toISOString()) { return db.transaction((tx) => { const due = tx.select().from(backgroundJobs).where(and(inArray(backgroundJobs.status, [BackgroundJobStatus.Pending, BackgroundJobStatus.RetryPending]), lte(backgroundJobs.runAfter, now))).orderBy(asc(backgroundJobs.priority), asc(backgroundJobs.runAfter)).limit(batchSize).all(); const claimed = []; for (const job of due) { const updated = tx.update(backgroundJobs).set({ status: BackgroundJobStatus.Processing, lockedAt: now, lockedBy: workerId, updatedAt: now }).where(and(eq(backgroundJobs.id, job.id), inArray(backgroundJobs.status, [BackgroundJobStatus.Pending, BackgroundJobStatus.RetryPending]))).returning().all()[0]; if (updated) claimed.push(updated); } return claimed; }); }
export async function completeJob(db: DbClient, id: string) { const now = new Date().toISOString(); await db.update(backgroundJobs).set({ status: BackgroundJobStatus.Succeeded, completedAt: now, lockedAt: null, lockedBy: null, updatedAt: now }).where(eq(backgroundJobs.id, id)).run(); }
export async function failJob(db: DbClient, id: string, error: unknown) { const [job] = await db.select().from(backgroundJobs).where(eq(backgroundJobs.id, id)); if (!job) return; const safe = sanitizeError(error); const now = new Date().toISOString(); const attempts = job.attemptCount + 1; const status = safe.retryable && attempts < job.maxAttempts ? BackgroundJobStatus.RetryPending : (safe.retryable ? BackgroundJobStatus.DeadLetter : BackgroundJobStatus.Failed); const delay = Math.round(1000 * Math.pow(2, Math.max(0, attempts - 1))); await db.update(backgroundJobs).set({ status, attemptCount: attempts, runAfter: new Date(Date.now()+delay).toISOString(), lockedAt: null, lockedBy: null, lastError: `${safe.type}: ${safe.message}`, updatedAt: now, completedAt: status === BackgroundJobStatus.Failed || status === BackgroundJobStatus.DeadLetter ? now : null }).where(eq(backgroundJobs.id, id)).run(); }
export async function retryJob(db: DbClient, id: string) { const now = new Date().toISOString(); await db.update(backgroundJobs).set({ status: BackgroundJobStatus.Pending, runAfter: now, lockedAt: null, lockedBy: null, updatedAt: now }).where(eq(backgroundJobs.id, id)).run(); }
export async function cancelJob(db: DbClient, id: string) { const now = new Date().toISOString(); await db.update(backgroundJobs).set({ status: BackgroundJobStatus.Cancelled, completedAt: now, lockedAt: null, lockedBy: null, updatedAt: now }).where(eq(backgroundJobs.id, id)).run(); }
export async function recoverStaleJobs(db: DbClient, olderThanIso: string) { await db.update(backgroundJobs).set({ status: BackgroundJobStatus.RetryPending, lockedAt: null, lockedBy: null }).where(and(eq(backgroundJobs.status, BackgroundJobStatus.Processing), lte(backgroundJobs.lockedAt, olderThanIso))).run(); }
export async function executeJob(db: DbClient, job: typeof backgroundJobs.$inferSelect) { const payload = JSON.parse(job.payloadSnapshot || "{}"); if (job.type === BackgroundJobType.StockSyncListing) await syncExternalListingStock(db, job.externalListingId ?? payload.externalListingId, job.id); else if (job.type === BackgroundJobType.StockSyncProduct) await syncProductStock(db, job.productId ?? payload.productId, job.channel ?? undefined, job.id); else if (job.type === BackgroundJobType.StockSyncChannel) await enqueueChannelListings(db, job.channel ?? payload.channel); else if (job.type === BackgroundJobType.SubmitMarketplaceShipment || job.type === "submit_marketplace_shipment") await submitMarketplaceShipment(db, payload.shipmentId); else if (job.type === BackgroundJobType.RefreshShipmentStatus || job.type === "refresh_shipment_status") await refreshShipmentStatus(db, payload.shipmentId); else if (job.type === BackgroundJobType.SubmitMarketplaceRefund || job.type === "submit_marketplace_refund") await executeMarketplaceRefund(db, payload.refundId); else if ([BackgroundJobType.RefreshMarketplaceReturn, BackgroundJobType.RefreshMarketplaceRefund, BackgroundJobType.CloseMarketplaceReturn, "refresh_marketplace_return", "refresh_marketplace_refund", "close_marketplace_return"].includes(job.type as any)) { /* fake adapter-safe no-op refresh/close hook */ } else throw { type: "Validation", message: "Unsupported job type", retryable: false }; await completeJob(db, job.id); }
export async function runDueJobs(db: DbClient, workerId: string = randomUUID(), batchSize = 10) { const jobs = await claimJobs(db, workerId, batchSize); for (const job of jobs) { try { await executeJob(db, job); } catch (error) { await failJob(db, job.id, error); } } return jobs.length; }
export async function listJobs(db: DbClient, q: { status?: string; type?: string; channel?: string; productId?: string; page?: number; pageSize?: number }) { const filters = [q.status && eq(backgroundJobs.status, q.status), q.type && eq(backgroundJobs.type, q.type), q.channel && eq(backgroundJobs.channel, q.channel), q.productId && eq(backgroundJobs.productId, q.productId)].filter(Boolean) as any[]; return db.select().from(backgroundJobs).where(filters.length ? and(...filters) : undefined).orderBy(desc(backgroundJobs.createdAt)).limit(q.pageSize ?? 50).offset(((q.page ?? 1)-1)*(q.pageSize ?? 50)); }
