import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import Database from "better-sqlite3";
import { getDatabaseConfig, redactSecrets, safeDatabaseStatus, type CutoverState } from "../db/config";
import { migrationTransformations, schemaVersion } from "../db/schema.postgres";
import { runProductReadRepositoryAudit } from "../scripts/productReadRepositoryAudit";

export const requiredSprint24Tables = ["categories","collections","products","product_photos","product_images","ai_listing_drafts","offers","orders","order_items","payments","stock_movements","marketplace_connections","publish_jobs","publish_attempts","external_listings","marketplace_webhook_events","marketplace_orders","marketplace_order_items","marketplace_sync_runs","marketplace_import_attempts","background_jobs","marketplace_inventory_snapshots","stock_sync_conflicts","stock_sync_audit","shipments","shipment_items","shipment_events","shipment_tracking_updates","sale_financials","return_requests","return_items","return_events","refunds","refund_allocations","sale_reversals","refund_attempts","erp_integration_clients","erp_integration_audit","erp_sync_checkpoints","erp_command_executions","product_erp_metadata","suppliers","purchases","purchase_lines","purchase_allocations","purchase_receipts","purchase_receipt_lines","purchase_events","customers","customer_addresses","customer_consents","customer_events","erp_customer_links","invoices","invoice_lines","invoice_events","finance_entries","warehouses","warehouse_locations","stock_reservations","picking_tasks","picking_task_lines","packing_tasks","packing_task_lines","warehouse_events"];
requiredSprint24Tables.splice(requiredSprint24Tables.indexOf("sale_financials") + 1, 0, "sale_completion_executions");
export type Difference = { table?: string; column?: string; kind: string; message: string };
export type ParityResult = { status: "PASS"|"FAIL"; blocking: Difference[]; warnings: Difference[]; tables: { name: string; sqlite: boolean; postgres: boolean; columns: number }[]; checksum: string };
function schemaSql(){ return fs.readFileSync(path.join(__dirname,"../db/schema.sql"),"utf8") + "\n" + fs.readFileSync(path.join(__dirname,"../db/schema.sqlite.ts"),"utf8"); }
export function parseSqliteSchema(sql=schemaSql()) { const tables = new Map<string,{columns:string[]; indexes:string[]}>(); const re=/CREATE TABLE IF NOT EXISTS\s+(\w+)\s*\(([\s\S]*?)\);/g; let m; while((m=re.exec(sql))){ const cols=m[2].split(/,\n/).map(s=>s.trim()).filter(Boolean).map(s=>s.split(/\s+/)[0].replace(/"/g,"")); tables.set(m[1],{columns:cols,indexes:[]}); } const ts=/sqliteTable\("([^"]+)"/g; while((m=ts.exec(sql))){ if(!tables.has(m[1])) tables.set(m[1],{columns:["id"],indexes:[]}); } const ir=/CREATE (?:UNIQUE )?INDEX IF NOT EXISTS\s+(\w+)\s+ON\s+(\w+)/g; while((m=ir.exec(sql))){ tables.get(m[2])?.indexes.push(m[1]); } return tables; }
export function runSchemaParity(): ParityResult { const model=parseSqliteSchema(); const blocking: Difference[]=[]; const warnings: Difference[]=[{kind:"type",message:"SQLite text/json/integer booleans require explicit PostgreSQL transformations"}]; const tables=requiredSprint24Tables.map(name=>{ const t=model.get(name); if(!t) blocking.push({table:name,kind:"missing-table",message:`${name} is missing from SQLite schema model`}); return {name,sqlite:Boolean(t),postgres:true,columns:t?.columns.length ?? 0}; }); const checksum=crypto.createHash("sha256").update(JSON.stringify(tables)).digest("hex"); return {status:blocking.length?"FAIL":"PASS",blocking,warnings,tables,checksum}; }
export function createMigrationPreview(sqlitePath=process.env.DATABASE_URL ?? ":memory:") { const db=new Database(sqlitePath, sqlitePath===":memory:" ? {} : {readonly:true,fileMustExist:true}); const schema=parseSqliteSchema(); const counts: Record<string,number>={}; const blocking: Difference[]=[]; const warnings: Difference[]=[]; for (const table of requiredSprint24Tables) { try { counts[table]=(db.prepare(`SELECT COUNT(*) as count FROM ${table}`).get() as {count:number}).count; } catch { counts[table]=0; warnings.push({table,kind:"missing-source-table",message:`${table} could not be counted in source`}); } } const ordered=requiredSprint24Tables.slice(); const checksum=crypto.createHash("sha256").update(JSON.stringify({counts,ordered,columns:[...schema].map(([k,v])=>[k,v.columns])})).digest("hex"); db.close(); return { migrationVersion:"sprint-24", sourceDriver:"sqlite", targetDriver:"supabase-postgres", generatedAt:new Date().toISOString(), sourceSchemaVersion:"sqlite-current", targetSchemaVersion:schemaVersion, tableOrder:ordered, sourceRowCounts:counts, tableChecksums:Object.fromEntries(ordered.map(t=>[t,crypto.createHash("sha256").update(`${t}:${counts[t]}`).digest("hex")])), dependencyGraph:{}, requiredTransformations:migrationTransformations, warnings, blockingIssues:blocking, dryRun:true, rollbackPrerequisites:["verified SQLite backup","PostgreSQL schema backup","rollback manifest"], sourceDatabaseFingerprint:checksum }; }
export function checkSqliteIntegrity(sqlitePath=process.env.DATABASE_URL ?? "./data/dev.sqlite") { if (!fs.existsSync(sqlitePath)) return {status:"WARN", present:false, integrity:"not-found", fingerprint:null}; try { const db=new Database(sqlitePath,{readonly:true}); const integrity=(db.prepare("PRAGMA integrity_check").get() as {integrity_check:string}).integrity_check; db.close(); const fingerprint=crypto.createHash("sha256").update(fs.readFileSync(sqlitePath)).digest("hex"); return {status:integrity==="ok"?"PASS":"FAIL",present:true,integrity,fingerprint}; } catch { return {status:"FAIL", present:true, integrity:"corrupt-or-not-sqlite", fingerprint:null}; } }
export function checkBackupReadiness(sqlitePath=process.env.DATABASE_URL ?? "./data/dev.sqlite") { const source=checkSqliteIntegrity(sqlitePath); return { sqliteBackupPresent: fs.existsSync(`${sqlitePath}.bak`), sqliteIntegrity: source.integrity, sourceFingerprint: source.fingerprint, postgresSchemaBackupPrerequisite: "required-before-cutover", migrationManifestPresence: false, rollbackManifestPrerequisite: "required", restoreVerificationMetadata: "prepared" }; }
export async function getDatabaseHealth() { let status; try { status=safeDatabaseStatus(); } catch(e) { return {status:"FAIL", error:redactSecrets(String(e))}; } const parity=runSchemaParity(); const readAudit=runProductReadRepositoryAudit(); const readOk=readAudit.status === "PASS"; return { status:"PASS", ...status, schemaVersion, parityStatus:parity.status, blockingIssueCount:parity.blocking.length, warningCount:parity.warnings.length, lastPreviewTimestamp:null, connectivity:{sqlite:"configured", supabase: status.supabaseConfigured ? "configured-not-contacted" : "not-configured", latencyMs:null}, migrationReadiness: parity.status === "PASS" && status.cutoverState !== "SupabasePrimary" ? "preview-ready" : "blocked", activeProductReadRepositoryDriver: status.activeDriver, productReadRepositoryInitialized: readOk, productReadParityStatus: parity.status, productReadDirectAccessAuditStatus: readAudit.status, publicCatalogReadRepositoryStatus: readOk ? "repository-backed" : "audit-failed", erpReadRepositoryStatus: readOk ? "repository-backed" : "audit-failed" }; }
export function validateCutoverState(state: CutoverState){ return ["SQLiteOnly","SupabasePreview","SupabaseStaging","CutoverReady","SupabasePrimary","RollbackMode"].includes(state); }
export function createMigrationPlan(){ return {dryRun:true,batches:requiredSprint24Tables.map((table,order)=>({table,order,idempotencyKey:`sprint24:${table}`}))}; }
export function validateMigrationPlan(){ return {valid:true, executionEnabled:getDatabaseConfig().executionEnabled}; }
export function executeMigrationBatch(){ if(!getDatabaseConfig().executionEnabled) throw new Error("Migration execution disabled by default"); return {status:"disabled-in-sprint-24"}; }
export const verifyMigrationBatch=()=>({verified:false,dryRun:true});
export const rollbackMigrationBatch=()=>({rolledBack:false,metadataPrepared:true});
export const finalizeMigration=()=>({finalized:false,reason:"production cutover excluded from Sprint 24"});

export function compareSchemaModels(sqliteModel: Record<string,{columns:string[]; unique?:string[]; indexes?:string[]; foreignKeys?:string[]}>, postgresModel: Record<string,{columns:string[]; unique?:string[]; indexes?:string[]; foreignKeys?:string[]}>): ParityResult {
  const blocking: Difference[]=[]; const warnings: Difference[]=[];
  const names=Object.keys(sqliteModel).sort();
  const tables=names.map((name)=>{ const s=sqliteModel[name]; const p=postgresModel[name]; if(!p) blocking.push({table:name,kind:"missing-table",message:`${name} missing in postgres`});
    for(const c of s.columns) if(!p?.columns.includes(c)) blocking.push({table:name,column:c,kind:"missing-column",message:`${name}.${c} missing in postgres`});
    for(const c of s.unique??[]) if(!p?.unique?.includes(c)) blocking.push({table:name,column:c,kind:"missing-unique",message:`${name}.${c} unique missing in postgres`});
    for(const c of s.indexes??[]) if(!p?.indexes?.includes(c)) blocking.push({table:name,column:c,kind:"missing-index",message:`${name}.${c} index missing in postgres`});
    for(const c of s.foreignKeys??[]) if(!p?.foreignKeys?.includes(c)) blocking.push({table:name,column:c,kind:"missing-foreign-key",message:`${name}.${c} foreign key missing in postgres`});
    return {name, sqlite:true, postgres:Boolean(p), columns:s.columns.length}; });
  const checksum=crypto.createHash("sha256").update(JSON.stringify({tables,blocking})).digest("hex");
  return {status:blocking.length?"FAIL":"PASS",blocking,warnings,tables,checksum};
}

function readPostgresMigrationSet(): string {
  const directory = path.join(__dirname, "../db/postgres-migrations");
  return fs.readdirSync(directory).filter((file) => file.endsWith(".sql")).sort().map((file) => fs.readFileSync(path.join(directory, file), "utf8")).join("\n");
}

export function validatePostgresMigrationSql(sqlText = readPostgresMigrationSet()) {
  const createTables = [...sqlText.matchAll(/CREATE TABLE IF NOT EXISTS\s+(\w+)/g)].map((m)=>m[1]);
  const missingTables = requiredSprint24Tables.filter((table)=>!createTables.includes(table));
  const hasDrop = /DROP\s+TABLE|DROP\s+COLUMN/i.test(sqlText);
  const indexes = [...sqlText.matchAll(/CREATE INDEX IF NOT EXISTS\s+(\w+)/g)].map((m)=>m[1]);
  const foreignKeys = [...sqlText.matchAll(/FOREIGN KEY/g)].length;
  return { status: missingTables.length || hasDrop ? "FAIL" as const : "PASS" as const, tableCount:new Set(createTables.filter((table) => requiredSprint24Tables.includes(table))).size, missingTables, hasDrop, indexCount:indexes.length, foreignKeyCount:foreignKeys, repeatedMigrationStrategy:"CREATE TABLE/INDEX IF NOT EXISTS; constraints are additive and validated before cutover" };
}
