import crypto from "node:crypto";
import { and, desc, eq, like, or, sql } from "drizzle-orm";
import type { DbClient } from "../db/client";
import { audit } from "./erpIntegration";
import { BadRequestError, ConflictError, NotFoundError } from "./errors";
import { customerAddresses, customerConsents, customerEvents, customerIdentityLinks, customerMergeHistory, customerNotes, customerPreferences, customerProfiles, customerStatistics, customerTags, customerWatchlist, erpCommandExecutions, erpIntegrationAudit, financeEntries, invoices, orders, refunds, returnRequests, shipments } from "../db/schema";

const now = () => new Date().toISOString();
const id = () => crypto.randomUUID();
const clean = (v:any) => typeof v === "string" && v.trim() ? v.trim() : null;
export const maskEmail = (v?:string|null) => v ? v.replace(/^(.).+(@.+)$/, "$1***$2") : null;
export const maskPhone = (v?:string|null) => v ? `${v.slice(0,2)}***${v.slice(-2)}` : null;
export const maskText = (v?:string|null) => v ? "[REDACTED]" : null;
export function redactCustomer(c:any, reveal=false){ return reveal ? c : { ...c, email:maskEmail(c.email), phone:maskPhone(c.phone), vatNumber:maskText(c.vatNumber) }; }
function fp(a:any){ return [a?.line1,a?.line2,a?.postalCode,a?.city,a?.country].map((x:any)=>String(x??"").trim().toLowerCase()).filter(Boolean).join("|") || null; }
async function event(db:DbClient, customerId:string, eventType:string, entityType?:string, entityId?:string, meta?:unknown){ await db.insert(customerEvents).values({ id:id(), customerId, eventType, entityType:entityType??null, entityId:entityId??null, safeMetadata:JSON.stringify(meta??{}), occurredAt:now() }); }

export async function listCustomers(db:DbClient,q:any={}){ const limit=Math.min(Number(q.limit??25),100), offset=Number(q.offset??0); const where=q.search?or(like(customerProfiles.name,`%${q.search}%`),like(customerProfiles.email,`%${q.search}%`),like(customerProfiles.erpReferenceId,`%${q.search}%`)):undefined; const rows=await db.select().from(customerProfiles).where(where).orderBy(desc(customerProfiles.updatedAt)).limit(limit).offset(offset); return { items:rows.map(r=>redactCustomer(r)), page:{ limit, offset, count:rows.length } }; }
export async function getCustomer(db:DbClient, customerId:string, reveal=false){ const [c]=await db.select().from(customerProfiles).where(eq(customerProfiles.id,customerId)).limit(1); if(!c) return null; const addresses=await db.select().from(customerAddresses).where(eq(customerAddresses.customerId,customerId)); const tags=await db.select().from(customerTags).where(eq(customerTags.customerId,customerId)); return { ...redactCustomer(c,reveal), addresses: reveal?addresses:addresses.map(a=>({...a,line1:maskText(a.line1),line2:maskText(a.line2),postalCode:maskText(a.postalCode)})), tags:tags.map(t=>t.tag) }; }
export async function createCustomer(db:DbClient, clientId:string, body:any){ const p=body.payload??body; const row={ id:id(), erpReferenceId:clean(p.erpReferenceId), marketplaceBuyerId:clean(p.marketplaceBuyerId), email:clean(p.email), phone:clean(p.phone), vatNumber:clean(p.vatNumber), name:clean(p.name), status:p.status??"Active", source:p.source??"ERP", createdAt:now(), updatedAt:now() }; await db.insert(customerProfiles).values(row); for(const a of p.addresses??[]) await db.insert(customerAddresses).values({ id:id(), customerId:row.id, type:a.type??"Shipping", name:clean(a.name), line1:clean(a.line1), line2:clean(a.line2), city:clean(a.city), region:clean(a.region), postalCode:clean(a.postalCode), country:clean(a.country), fingerprint:fp(a), createdAt:now(), updatedAt:now() }); await event(db,row.id,"CustomerCreated","Customer",row.id); await audit(db,clientId,null,"CustomerCreate","Succeeded",{customerId:row.id}); return getCustomer(db,row.id); }
export async function updateCustomer(db:DbClient, clientId:string, body:any){ const p=body.payload??body; const customerId=p.customerId??p.id; const [cur]=await db.select().from(customerProfiles).where(eq(customerProfiles.id,customerId)).limit(1); if(!cur) throw new Error("Customer not found"); await db.update(customerProfiles).set({ erpReferenceId:clean(p.erpReferenceId)??cur.erpReferenceId, marketplaceBuyerId:clean(p.marketplaceBuyerId)??cur.marketplaceBuyerId, email:clean(p.email)??cur.email, phone:clean(p.phone)??cur.phone, vatNumber:clean(p.vatNumber)??cur.vatNumber, name:clean(p.name)??cur.name, status:p.status??cur.status, updatedAt:now() }).where(eq(customerProfiles.id,customerId)); await event(db,customerId,"CustomerUpdated","Customer",customerId); await audit(db,clientId,null,"CustomerUpdate","Succeeded",{customerId}); return getCustomer(db,customerId); }
export async function addNote(db:DbClient, clientId:string, body:any){ const p=body.payload??body; const note={ id:id(), customerId:p.customerId, body:String(p.body??""), version:Number(p.version??1), archivedAt:null, safeMetadata:JSON.stringify(p.safeMetadata??{}), createdBy:clientId, createdAt:now(), updatedAt:now() }; await db.insert(customerNotes).values(note); await event(db,p.customerId,"NoteAdded","CustomerNote",note.id,{masked:true}); await audit(db,clientId,null,"CustomerNoteAdd","Succeeded",{customerId:p.customerId,noteId:note.id}); return { ...note, body: p.reveal ? note.body : maskText(note.body) }; }
export async function tagCustomer(db:DbClient, clientId:string, body:any){ const p=body.payload??body; const tag=String(p.tag??"").trim(); if(!tag) throw new Error("tag required"); try{ await db.insert(customerTags).values({ id:id(), customerId:p.customerId, tag, createdAt:now() }); }catch{} await event(db,p.customerId,"TagChanged","CustomerTag",tag,{tag}); await audit(db,clientId,null,"CustomerTag","Succeeded",{customerId:p.customerId,tag}); return { customerId:p.customerId, tag }; }
export async function setPreferences(db:DbClient, clientId:string, body:any){ const p=body.payload??body, t=now(); await db.insert(customerPreferences).values({ customerId:p.customerId, language:clean(p.language), currency:clean(p.currency), preferredMarketplace:clean(p.preferredMarketplace), safeMetadata:JSON.stringify(p.safeMetadata??{}), updatedAt:t }).onConflictDoUpdate({ target:customerPreferences.customerId, set:{ language:clean(p.language), currency:clean(p.currency), preferredMarketplace:clean(p.preferredMarketplace), safeMetadata:JSON.stringify(p.safeMetadata??{}), updatedAt:t } }); await event(db,p.customerId,"PreferenceChanged","CustomerPreferences",p.customerId); await audit(db,clientId,null,"CustomerPreferences","Succeeded",{customerId:p.customerId}); return getPreferences(db,p.customerId); }
export async function getPreferences(db:DbClient, customerId:string){ return (await db.select().from(customerPreferences).where(eq(customerPreferences.customerId,customerId)).limit(1))[0]??null; }
export async function getConsents(db:DbClient, customerId:string){ return { items: await db.select().from(customerConsents).where(eq(customerConsents.customerId,customerId)).orderBy(desc(customerConsents.createdAt)), deleteExecutes:false, exportExecutes:false }; }
export async function addConsent(db:DbClient, clientId:string, body:any){ const p=body.payload??body; const row={ id:id(), customerId:p.customerId, consentType:p.consentType??"Privacy", granted:!!p.granted, privacyVersion:p.privacyVersion??null, requestType:p.requestType??null, safeMetadata:JSON.stringify(p.safeMetadata??{}), createdAt:now() }; await db.insert(customerConsents).values(row); await event(db,p.customerId,"ConsentChanged","CustomerConsent",row.id,{consentType:row.consentType,requestType:row.requestType}); await audit(db,clientId,null,"CustomerConsent","Succeeded",{customerId:p.customerId,consentType:row.consentType}); return row; }
export async function listNotes(db:DbClient, customerId:string){ const rows=await db.select().from(customerNotes).where(eq(customerNotes.customerId,customerId)).orderBy(desc(customerNotes.createdAt)); return { items: rows.map(r=>({...r, body: r.archivedAt ? "[ARCHIVED]" : maskText(r.body)})), archiveInsteadOfDelete:true, versionHistory:true }; }
export async function getStatistics(db:DbClient, customerId:string){ const os=await db.select().from(orders).where(eq(orders.customerId,customerId)); const inv=await db.select().from(invoices).where(eq(invoices.customerId,customerId)); const refs=await db.select().from(refunds).where(os.length?or(...os.map((o:any)=>eq(refunds.orderId,o.id))):sql`0=1`); const rets=await db.select().from(returnRequests).where(os.length?or(...os.map((o:any)=>eq(returnRequests.orderId,o.id))):sql`0=1`); const paid=os.filter((o:any)=>o.paymentStatus==="paid"||o.paymentStatus==="Paid"); const total=paid.length?paid.reduce((s:number,o:any)=>s+Number(o.totalAmount??0),0):null; const last=paid.map((o:any)=>o.createdAt).sort().pop()??null; const stat={ customerId, lifetimeValue:total, orderCount:os.length||null, averageOrderValue:total!=null&&paid.length?total/paid.length:null, refundPercent:os.length?refs.length/os.length*100:null, returnPercent:os.length?rets.length/os.length*100:null, lastPurchaseAt:last, favouriteCategory:null, favouriteMarketplace:null, favouriteBrand:null, country:null, currency:os[0]?.currency??inv[0]?.currency??null, customerScore:total==null?null:Math.min(100,total/10), daysSinceLastPurchase:last?Math.floor((Date.now()-Date.parse(last))/86400000):null, calculatedAt:now() }; await db.insert(customerStatistics).values(stat).onConflictDoUpdate({ target:customerStatistics.customerId, set:stat }); return stat; }
export async function related(db:DbClient, customerId:string, kind:string){ const map:any={orders,invoices,refunds,returns:returnRequests,watchlist:customerWatchlist}; const table=map[kind]; if(!table) return {items:[]}; return { items: await db.select().from(table).where(kind==="returns"?eq(table.orderId,customerId):eq(table.customerId,customerId)) }; }
export async function timeline(db:DbClient, customerId:string){ const [os, inv, sh, ret, ref, notes, watch, pref, tags, audits, evs]=await Promise.all([db.select().from(orders).where(eq(orders.customerId,customerId)),db.select().from(invoices).where(eq(invoices.customerId,customerId)),db.select().from(shipments),db.select().from(returnRequests),db.select().from(refunds),db.select().from(customerNotes).where(eq(customerNotes.customerId,customerId)),db.select().from(customerWatchlist).where(eq(customerWatchlist.customerId,customerId)),db.select().from(customerPreferences).where(eq(customerPreferences.customerId,customerId)),db.select().from(customerTags).where(eq(customerTags.customerId,customerId)),db.select().from(erpIntegrationAudit),db.select().from(customerEvents).where(eq(customerEvents.customerId,customerId))]); const orderIds=new Set(os.map((o:any)=>o.id)); const items:any[]=[]; os.forEach((o:any)=>items.push({type:"Order",entityId:o.id,occurredAt:o.createdAt,readOnly:true})); inv.forEach((x:any)=>items.push({type:"Invoice",entityId:x.id,occurredAt:x.createdAt,readOnly:true})); sh.filter((x:any)=>orderIds.has(x.orderId)).forEach((x:any)=>items.push({type:"Shipment",entityId:x.id,occurredAt:x.createdAt,readOnly:true})); ret.filter((x:any)=>orderIds.has(x.orderId)).forEach((x:any)=>items.push({type:"Return",entityId:x.id,occurredAt:x.createdAt,readOnly:true})); ref.filter((x:any)=>orderIds.has(x.orderId)).forEach((x:any)=>items.push({type:"Refund",entityId:x.id,occurredAt:x.createdAt,readOnly:true})); notes.forEach((x:any)=>items.push({type:"Note",entityId:x.id,occurredAt:x.createdAt,body:maskText(x.body),readOnly:true})); watch.forEach((x:any)=>items.push({type:"Watcher",entityId:x.id,occurredAt:x.createdAt,readOnly:true})); pref.forEach((x:any)=>items.push({type:"Preference",entityId:x.customerId,occurredAt:x.updatedAt,readOnly:true})); tags.forEach((x:any)=>items.push({type:"Tag",entityId:x.id,occurredAt:x.createdAt,readOnly:true})); audits.filter((a:any)=>String(a.safeMetadata??"").includes(customerId)).forEach((a:any)=>items.push({type:"Audit",entityId:a.id,occurredAt:a.createdAt,readOnly:true})); evs.forEach((x:any)=>items.push({type:x.eventType,entityId:x.entityId,occurredAt:x.occurredAt,readOnly:true})); return { items:items.sort((a,b)=>String(b.occurredAt).localeCompare(String(a.occurredAt))), readOnly:true }; }
export async function mergeCandidates(db:DbClient, input:any){ const p=input.payload??input; const rows=await db.select().from(customerProfiles); const cands=[] as any[]; const addrFp=fp(p.shippingAddress)||fp(p.billingAddress); for(const c of rows){ const reasons=[]; if(p.erpReferenceId&&p.erpReferenceId===c.erpReferenceId) reasons.push("ERP Reference"); if(p.marketplaceBuyerId&&p.marketplaceBuyerId===c.marketplaceBuyerId) reasons.push("Marketplace Buyer ID"); if(p.email&&p.email===c.email) reasons.push("Email"); if(p.phone&&p.phone===c.phone) reasons.push("Phone"); if(p.vatNumber&&p.vatNumber===c.vatNumber) reasons.push("VAT Number"); const addrs=await db.select().from(customerAddresses).where(eq(customerAddresses.customerId,c.id)); if(addrFp&&addrs.some((a:any)=>a.fingerprint===addrFp)) reasons.push("Shipping Address"); if(reasons.length) cands.push({ customer:redactCustomer(c), reasons, autoMerged:false }); } return { candidates:cands, autoMerge:false, executionRequired:true }; }
/** Sprint 47B: an Accepted merge-command row older than this is treated as abandoned, not genuinely in-flight — same policy value as Sprint 46B's Sales/Invoice hardening, kept as a local constant rather than an import so this file's command lifecycle stays self-contained and independent of the Sales/Invoice bridge module. */
const CUSTOMER_MERGE_ACCEPTED_STALE_MS = 60_000;
function mergeChecksum(sourceCustomerId:unknown, targetCustomerId:unknown){ return crypto.createHash("sha256").update(JSON.stringify({ sourceCustomerId, targetCustomerId })).digest("hex"); }
function safeErrorCodeFor(error:unknown):string{ if(error instanceof BadRequestError) return "BadRequestError"; if(error instanceof ConflictError) return "ConflictError"; if(error instanceof NotFoundError) return "NotFoundError"; return "InternalError"; }
function parseMergeReplay(row:any){ const meta=row.safeResultMetadata?JSON.parse(row.safeResultMetadata):{}; return { status:"Completed", idempotent:true, targetCustomerId:meta.targetCustomerId, sourceCustomerId:meta.sourceCustomerId }; }
/**
 * Sprint 47B. The Accepted claim/reset (establishing which row this attempt
 * owns) is deliberately done as a plain statement *outside* the transaction
 * below, not folded into it. Reason: if it were inside and the transaction
 * rolled back on failure, the row would revert to its pre-attempt state (or
 * not exist at all for a brand-new key), and the post-failure "mark Failed"
 * step would need a fragile update-or-insert fallback to cope with either
 * case. Keeping the claim outside guarantees a row always exists by the time
 * the transaction runs, so failure handling is always a single plain UPDATE.
 * Everything from customerMergeHistory through the Completed update is one
 * synchronous db.transaction() — it commits or rolls back as one unit, so a
 * Completed row can never exist without its history/event/audit rows.
 */
export async function executeMerge(db:DbClient, clientId:string, body:any){
  const p=body.payload??body, key=p.idempotencyKey??body.idempotencyKey;
  const checksum=mergeChecksum(p.sourceCustomerId,p.targetCustomerId);
  const [existing]=await db.select().from(erpCommandExecutions).where(and(eq(erpCommandExecutions.clientId,clientId),eq(erpCommandExecutions.idempotencyKey,key))).limit(1);

  let rowId:string;
  if(existing){
    if(existing.requestChecksum!==checksum) throw new ConflictError("Idempotency key was already used with a different payload");
    if(existing.status==="Completed") return parseMergeReplay(existing);
    if(existing.status==="Accepted"){
      const isStale=Date.now()-new Date(existing.createdAt).getTime()>CUSTOMER_MERGE_ACCEPTED_STALE_MS;
      if(!isStale) throw new ConflictError("ERP command is already in progress");
    }
    rowId=existing.id;
    await db.update(erpCommandExecutions).set({status:"Accepted",safeErrorCode:null,completedAt:null,createdAt:now()}).where(eq(erpCommandExecutions.id,rowId));
  } else {
    rowId=id();
    try {
      await db.insert(erpCommandExecutions).values({ id:rowId, clientId, commandId:p.commandId??key, requestId:p.requestId??null, idempotencyKey:key, commandType:"MergeCustomer", entityType:"Customer", entityId:p.targetCustomerId, status:"Accepted", requestChecksum:checksum, createdAt:now() });
    } catch (error:any) {
      if(String(error?.message??error).includes("UNIQUE constraint failed")) return executeMerge(db,clientId,body);
      throw error;
    }
  }

  try {
    return db.transaction((tx) => {
      tx.insert(customerMergeHistory).values({ id:crypto.randomUUID(), sourceCustomerId:p.sourceCustomerId, targetCustomerId:p.targetCustomerId, idempotencyKey:key, safeMetadata:JSON.stringify({explicit:true}), createdAt:now() }).run();
      tx.insert(customerEvents).values({ id:crypto.randomUUID(), customerId:p.targetCustomerId, eventType:"CustomerMerged", entityType:"Customer", entityId:p.sourceCustomerId, safeMetadata:JSON.stringify({}), occurredAt:now() }).run();
      tx.insert(erpIntegrationAudit).values({ id:crypto.randomUUID(), clientId, requestId:p.requestId??null, action:"CustomerMerge", result:"Succeeded", safeMetadata:JSON.stringify({sourceCustomerId:p.sourceCustomerId,targetCustomerId:p.targetCustomerId}), errorCode:null, createdAt:now() }).run();
      const meta={sourceCustomerId:p.sourceCustomerId,targetCustomerId:p.targetCustomerId};
      tx.update(erpCommandExecutions).set({status:"Completed",completedAt:now(),safeErrorCode:null,resultReference:p.targetCustomerId,safeResultMetadata:JSON.stringify(meta)}).where(eq(erpCommandExecutions.id,rowId)).run();
      return { status:"Completed", idempotent:false, targetCustomerId:p.targetCustomerId, sourceCustomerId:p.sourceCustomerId };
    });
  } catch (error) {
    await db.update(erpCommandExecutions).set({status:"Failed",safeErrorCode:safeErrorCodeFor(error),completedAt:now()}).where(eq(erpCommandExecutions.id,rowId));
    throw error;
  }
}
