import crypto from "node:crypto";
import { and, desc, eq, gt, like, or, sql } from "drizzle-orm";
import { z } from "zod";
import { categories, collections, erpIntegrationAudit, erpIntegrationClients, erpSyncCheckpoints, productPhotos, products, stockMovements, orders, shipments, returnRequests, refunds } from "../db/schema";
import type { DbClient } from "../db/client";
import { ErpClientStatus, ErpFieldOwnership, type ErpCommandResult, type ErpProductMapping } from "@noctella/shared";

export const ERP_API_VERSION = "2026-07-sprint16";
export const MIN_ERP_CLIENT_VERSION = "0.1.0";
export const LATEST_ERP_CLIENT_VERSION = "0.1.0";
export const FUTURE_COMMANDS = ["CreateProduct", "UpdateProduct", "AdjustStock", "CreatePurchase", "CompleteSale", "CreateShipment"];
export const ERP_MODULES = ["Inventory", "Product Workspace", "Purchasing", "Marketplace Manager", "Synchronization", "Web Catalog", "WooCommerce Bridge", "Sales", "Invoices", "Finance", "Barcode & Labels", "Shipping", "Analytics / Reports", "CRM", "Settings"].map((name) => ({ name, mode: ["Inventory", "Product Workspace"].includes(name) ? "ReadOnly" : "Deferred" }));

export function hashErpKey(raw: string, salt = process.env.ERP_INTEGRATION_KEY_SALT ?? "noctella-erp-sprint16"): string { return crypto.createHmac("sha256", salt).update(raw).digest("hex"); }
export function constantTimeEqual(a: string, b: string): boolean { const ab=Buffer.from(a); const bb=Buffer.from(b); const len=Math.max(ab.length, bb.length); const ap=Buffer.concat([ab, Buffer.alloc(len-ab.length)]); const bp=Buffer.concat([bb, Buffer.alloc(len-bb.length)]); return crypto.timingSafeEqual(ap,bp) && ab.length===bb.length; }
export function isVersionSupported(v?: string): boolean { return !!v && v === LATEST_ERP_CLIENT_VERSION; }
export function redactError(message: string): string { return message.replace(/(X-Noctella-ERP-Key|erp[_-]?key|secret|token)=[^\s]+/gi, "$1=[REDACTED]"); }

export async function authenticateErp(db: DbClient, key?: string, clientVersion?: string, requestId?: string) {
  const safeMeta = { clientVersion, status: "attempt" };
  if (!key) { await audit(db, null, requestId, "ErpAuth", "Rejected", safeMeta, "MissingKey"); return { ok:false as const, status: ErpClientStatus.Unauthorized, error:"ERP authentication required"}; }
  const envKey = process.env.ERP_INTEGRATION_KEY;
  if (envKey && constantTimeEqual(hashErpKey(key), hashErpKey(envKey))) { await audit(db, "env", requestId, "ErpAuth", "Accepted", safeMeta); return { ok:true as const, clientId:"env", keyVersion: process.env.ERP_INTEGRATION_KEY_VERSION ?? "env"}; }
  const rows = await db.select().from(erpIntegrationClients);
  for (const row of rows) if (row.isActive && constantTimeEqual(hashErpKey(key), row.keyHash)) { await db.update(erpIntegrationClients).set({ lastSeenAt: new Date().toISOString(), lastClientVersion: clientVersion, updatedAt: new Date().toISOString() }).where(eq(erpIntegrationClients.id,row.id)); await audit(db,row.id,requestId,"ErpAuth","Accepted",safeMeta); return { ok:true as const, clientId:row.id, keyVersion:row.keyVersion}; }
  await audit(db, null, requestId, "ErpAuth", "Rejected", safeMeta, "InvalidKey"); return { ok:false as const, status: ErpClientStatus.Unauthorized, error:"ERP authentication failed"};
}
export async function audit(db: DbClient, clientId: string|null, requestId: string|undefined|null, action: string, result: string, safeMetadata?: unknown, errorCode?: string) { await db.insert(erpIntegrationAudit).values({ id: crypto.randomUUID(), clientId, requestId: requestId ?? null, action, result, safeMetadata: JSON.stringify(safeMetadata ?? {}), errorCode: errorCode ?? null, createdAt: new Date().toISOString() }); }

export function versionInfo(clientVersion?: string) { return { apiVersion: ERP_API_VERSION, minimumSupportedErpClientVersion: MIN_ERP_CLIENT_VERSION, latestSupportedErpClientVersion: LATEST_ERP_CLIENT_VERSION, serverTime: new Date().toISOString(), compatible: clientVersion ? isVersionSupported(clientVersion) : true }; }
export function capabilities() { return { apiVersion: ERP_API_VERSION, readOnly: false, writesEnabled: true, capabilities: ["ReadProducts", "ReadInventory", "ReadProductPhotos", "IdentityCheck", "FieldMapping", "SyncCheckpoint", "ValidateCommands", "CreateProduct", "UpdateProduct", "AdjustStock"], modules: ERP_MODULES.map((m) => ["Inventory", "Product Workspace"].includes(m.name) ? { ...m, mode: "ReadWrite" } : m), deferred: ["Purchasing", "Sales", "Invoices", "Finance", "Shipping", "CRM", "Reports", "WMS"] }; }
export async function health(db: DbClient) { await db.select({ count: sql<number>`count(*)` }).from(products); return { status: ErpClientStatus.Connected, apiVersion: ERP_API_VERSION, minimumClientVersion: MIN_ERP_CLIENT_VERSION, latestClientVersion: LATEST_ERP_CLIENT_VERSION, serverTime: new Date().toISOString(), database: "Healthy", readOnly: true, writesEnabled: false, degradedServices: [] }; }

export async function listProductProjections(db: DbClient, q: any) { const limit=Math.min(Number(q.limit??25),100), offset=Number(q.offset??0); const filters=[] as any[]; if(q.search) filters.push(or(like(products.title, `%${q.search}%`), like(products.sku, `%${q.search}%`))); if(q.status) filters.push(eq(products.status, q.status)); if(q.categoryId) filters.push(eq(products.categoryId,q.categoryId)); if(q.collectionId) filters.push(eq(products.collectionId,q.collectionId)); if(q.updatedSince) filters.push(gt(products.updatedAt,q.updatedSince)); const where=filters.length?and(...filters):undefined; const rows= await db.select({ p: products, c: categories, col: collections }).from(products).leftJoin(categories, eq(products.categoryId,categories.id)).leftJoin(collections, eq(products.collectionId,collections.id)).where(where).orderBy(products.updatedAt, products.id).limit(limit).offset(offset); return { items: await Promise.all(rows.map(r=>project(db,r.p,r.c?.name,r.col?.name))), pagination:{ limit, offset, count: rows.length } }; }
export async function project(db: DbClient, p: any, category?: string, collection?: string) { const [photo]=await db.select().from(productPhotos).where(eq(productPhotos.productId,p.id)).orderBy(desc(productPhotos.isPrimary), productPhotos.sortOrder).limit(1); return { centralProductId:p.id, erpReferenceId:p.erpReferenceId ?? undefined, sku:p.sku, title:p.title, status:p.status, category, collection, brand:p.brand ?? undefined, condition:p.condition ?? undefined, dimensions:{ length:p.lengthValue??undefined, width:p.widthValue??undefined, height:p.heightValue??undefined, unit:p.dimensionUnit??undefined }, weight:{ value:p.weightValue??undefined, unit:p.weightUnit??undefined }, purchaseCost:p.purchaseCost??undefined, priceEur:p.priceEur, physicalStock:p.stockQuantity, reservedStock:0, reservedStockSupported:false, availableStock:p.stockQuantity, primaryPhoto:photo?.url, workflowMetadata:{ deferred:true }, updatedAt:p.updatedAt }; }
export async function getProductProjection(db: DbClient, id: string) { const [r]=await db.select({ p: products, c: categories, col: collections }).from(products).leftJoin(categories, eq(products.categoryId,categories.id)).leftJoin(collections, eq(products.collectionId,collections.id)).where(eq(products.id,id)); return r ? project(db,r.p,r.c?.name,r.col?.name) : undefined; }
export async function identityCheck(db: DbClient, input: {erpReferenceId?:string; sku?:string; noctellaId?:string}) { if (!input.erpReferenceId && !input.noctellaId && (!input.sku || !input.sku.trim())) return { result:"Invalid", matches:[], notes:["Provide erpReferenceId, noctellaId, or non-blank sku"]}; const matches=[] as any[]; if(input.erpReferenceId) matches.push(...await db.select().from(products).where(eq(products.erpReferenceId,input.erpReferenceId))); if(input.sku?.trim()) matches.push(...await db.select().from(products).where(eq(products.sku,input.sku.trim()))); const uniq=[...new Map(matches.map((m:any)=>[m.id,m])).values()]; if(uniq.length===1) return { result:"Match", product: await getProductProjection(db, uniq[0].id) }; if(uniq.length>1) return { result:"Ambiguous", matches:uniq.map((m:any)=>({centralProductId:m.id, sku:m.sku, erpReferenceId:m.erpReferenceId}))}; return { result: input.noctellaId ? "CreateCandidate" : "CreateCandidate", matches:[]}; }
export const PRODUCT_FIELD_MAPPING: ErpProductMapping[] = ["id","noctellaId","sku","barcodeValue","name","category","collection","brand","countryOfOrigin","era","material","condition","provenance","previousOwner","auctionHouse","invoiceReferenceNumber","height","width","depth","diameter","weight","purchaseSource","storageLocation","buyPrice","shippingCost","packagingCost","miscCosts","expectedSalePrice","actualSalePrice","status","productWorkflowStatus","photoStatus","authenticationStatus","marketplaceStatus","notes","availableQuantity","createdAt","updatedAt"].map((f)=>({ erpField:f, owner: f==="availableQuantity"?ErpFieldOwnership.Derived:["sku","name","category","collection","brand","condition","height","width","weight","status","createdAt","updatedAt"].includes(f)?ErpFieldOwnership.Web:ErpFieldOwnership.ERP, targetField: ({name:"title", era:"period", material:"materials", buyPrice:"purchaseCost", expectedSalePrice:"priceEur", availableQuantity:"stockQuantity"} as any)[f] ?? f, writableInFuture: !["id","sku","availableQuantity","createdAt","updatedAt"].includes(f), currentSprintMode: ["depth","diameter","provenance","productWorkflowStatus","photoStatus","authenticationStatus"].includes(f)?"Deferred":"ReadOnly", notes: f==="availableQuantity"?"Derived from central inventory; ERP must not own stock.": f==="depth"||f==="diameter"?"No central target yet; explicitly deferred to avoid silent loss.":"Sprint 16 read-only mapping.", dataLossRisk: ["depth","diameter","provenance"].includes(f)?"Medium":"None" }));
export async function checkpoint(db: DbClient) { const latest=async(t:any,c:any)=> (await db.select({ v: sql<string>`max(${c})` }).from(t))[0]?.v; const generatedAt=new Date().toISOString(); const body={ checkpointToken: hashErpKey(`${generatedAt}:${ERP_API_VERSION}`).slice(0,32), generatedAt, latestProductUpdatedAt: await latest(products, products.updatedAt), latestStockMovementCreatedAt: await latest(stockMovements, stockMovements.createdAt), latestOrderUpdatedAt: await latest(orders, orders.updatedAt), latestShipmentUpdatedAt: await latest(shipments, shipments.updatedAt), latestReturnRefundUpdatedAt: (await latest(returnRequests, returnRequests.updatedAt)) ?? (await latest(refunds, refunds.updatedAt)), apiVersion:ERP_API_VERSION, schemaVersion:"sprint16" }; return body; }
export async function acknowledge(db: DbClient, clientId:string, requestId:string|undefined, token:string, meta:unknown) { const existing=requestId? await db.select().from(erpSyncCheckpoints).where(eq(erpSyncCheckpoints.requestId, requestId)).limit(1):[]; if(existing.length) return existing[0]; const row={ id:crypto.randomUUID(), clientId, requestId: requestId??null, checkpointToken: token, acknowledgedAt:new Date().toISOString(), safeMetadata:JSON.stringify(meta??{}), createdAt:new Date().toISOString() }; await db.insert(erpSyncCheckpoints).values(row); return row; }
export function validateCommandEnvelope(input: unknown): ErpCommandResult { const schema=z.object({ commandId:z.string().min(1), requestId:z.string().min(1), clientId:z.string().min(1), clientVersion:z.string().min(1), commandType:z.string().min(1), entityType:z.string().min(1), entityId:z.string().optional(), idempotencyKey:z.string().min(1), payload:z.unknown(), createdAt:z.string().min(1) }); const parsed=schema.safeParse(input); if(!parsed.success) return { status:"Invalid", errors:parsed.error.issues.map(i=>i.message), readOnly:true }; if(!FUTURE_COMMANDS.includes(parsed.data.commandType)) return { commandId:parsed.data.commandId, requestId:parsed.data.requestId, status:"Invalid", errors:["Unsupported commandType"], readOnly:true }; return { commandId:parsed.data.commandId, requestId:parsed.data.requestId, status:["CreateProduct","UpdateProduct","AdjustStock"].includes(parsed.data.commandType)?"Valid":"NotEnabled", errors:[], readOnly:false }; }
