import crypto from "crypto";
import { sql } from "drizzle-orm";
import { ReportComparisonMode, ReportCompleteness, ReportExportFormat, ReportGranularity, ReportPeriod } from "@noctella/shared";
import { audit } from "./erpIntegration";
import type { DbClient as InventoryDbClient } from "../db/client";
import { createGetInventoryTotalQuantityUseCase } from "../application/inventory";
import { createInventoryApplicationContextForDb } from "./inventoryApplicationContextForDb";
import { createProductReadServiceContextForDb } from "../repositories/product-read/factory";

type DbClient={ get:(q:any)=>any; all:(q:any)=>any; run:(q:any)=>any };
const MAX_RANGE_DAYS=370, MAX_EXPORT_ROWS=1000;
export const CUSTOMER_SEGMENT_RULES = { New:"first order is within the report period or no prior order history", Active:"last purchase is within 90 days", Repeat:"two or more completed orders", HighValue:"lifetime value is at or above the configured high-value threshold", AtRisk:"last purchase is between 90 and 180 days", Dormant:"last purchase is older than 180 days", RefundRisk:"customer refund rate is above the configured risk threshold" } as const;
const now=()=>new Date().toISOString();
const n=(v:any)=>v==null?null:Math.round(Number(v)*100)/100;
const z=(v:any)=>Number(v??0);
const pct=(a:number,b:number)=>b===0?null:n((a-b)/b*100);
const metric=(key:string,value:any,currency=false)=>({key,label:key,value:n(value),currency:currency?"EUR":undefined,completeness:value==null?ReportCompleteness.Incomplete:ReportCompleteness.Complete,issueCodes:value==null?["UNKNOWN_VALUE"]:[]});
const issue=(code:string,message:string)=>({code,severity:"Incomplete" as const,message});
export function maskCustomer(v?:string|null){ if(!v)return null; const [a,b]=String(v).split("@"); return b?`${a.slice(0,2)}***@${b}`:`${String(v).slice(0,2)}***`; }
function parseDate(s?:any){ const d=s?new Date(String(s)):null; return d && !Number.isNaN(d.getTime())?d:null; }
export function resolveFilters(q:any={}){ const tz=String(q.timezone??"UTC"); const period=String(q.period??ReportPeriod.Last30Days); const end=new Date(); let start=new Date(end); const day=86400000; const qStart=(d:Date)=>new Date(Date.UTC(d.getUTCFullYear(),Math.floor(d.getUTCMonth()/3)*3,1)); if(period===ReportPeriod.Today) start=new Date(Date.UTC(end.getUTCFullYear(),end.getUTCMonth(),end.getUTCDate())); else if(period===ReportPeriod.Yesterday){ const y=new Date(Date.UTC(end.getUTCFullYear(),end.getUTCMonth(),end.getUTCDate())-day); start=y; end.setTime(y.getTime()+day-1); } else if(period===ReportPeriod.Last7Days) start=new Date(end.getTime()-6*day); else if(period===ReportPeriod.ThisMonth) start=new Date(Date.UTC(end.getUTCFullYear(),end.getUTCMonth(),1)); else if(period===ReportPeriod.PreviousMonth){ start=new Date(Date.UTC(end.getUTCFullYear(),end.getUTCMonth()-1,1)); end.setTime(Date.UTC(start.getUTCFullYear(),start.getUTCMonth()+1,1)-1); } else if(period===ReportPeriod.ThisQuarter){ start=qStart(end); } else if(period===ReportPeriod.PreviousQuarter){ const cur=qStart(end); start=new Date(Date.UTC(cur.getUTCFullYear(),cur.getUTCMonth()-3,1)); end.setTime(cur.getTime()-1); } else if(period===ReportPeriod.ThisYear) start=new Date(Date.UTC(end.getUTCFullYear(),0,1)); else if(period===ReportPeriod.PreviousYear){ start=new Date(Date.UTC(end.getUTCFullYear()-1,0,1)); end.setTime(Date.UTC(end.getUTCFullYear(),0,1)-1); } else if(period===ReportPeriod.Custom){ const a=parseDate(q.dateFrom), b=parseDate(q.dateTo); if(!a||!b||a>b) throw Object.assign(new Error("Invalid custom date range"),{statusCode:400}); start=a; end.setTime(b.getTime()); } else start=new Date(end.getTime()-29*day);
 const days=Math.ceil((end.getTime()-start.getTime())/day)+1; if(days>MAX_RANGE_DAYS) throw Object.assign(new Error("Report range is too large"),{statusCode:413}); const comparisonMode=String(q.comparisonMode??ReportComparisonMode.None); const comparison:any={}; if(comparisonMode===ReportComparisonMode.PreviousPeriod){ const len=end.getTime()-start.getTime(); comparison.comparisonDateTo=new Date(start.getTime()-1).toISOString(); comparison.comparisonDateFrom=new Date(start.getTime()-1-len).toISOString(); } if(comparisonMode===ReportComparisonMode.PreviousYear){ comparison.comparisonDateFrom=new Date(Date.UTC(start.getUTCFullYear()-1,start.getUTCMonth(),start.getUTCDate(),start.getUTCHours(),start.getUTCMinutes(),start.getUTCSeconds())).toISOString(); comparison.comparisonDateTo=new Date(Date.UTC(end.getUTCFullYear()-1,end.getUTCMonth(),end.getUTCDate(),end.getUTCHours(),end.getUTCMinutes(),end.getUTCSeconds())).toISOString(); }
 return { period, dateFrom:start.toISOString(), dateTo:end.toISOString(), granularity:String(q.granularity??ReportGranularity.Day), comparisonMode, ...comparison, channel:q.channel, category:q.category, collection:q.collection, brand:q.brand, supplier:q.supplier, warehouse:q.warehouse, location:q.location, country:q.country, status:q.status, product:q.product, customer:q.customer, timezone:tz };
}
const base=(reportType:string,filters:any,issues:any[]=[])=>({reportType,generatedAt:now(),currency:"EUR" as const,filters,completeness:issues.length?ReportCompleteness.Incomplete:ReportCompleteness.Complete,issues,timezone:{requested:filters.timezone??"UTC",internal:"UTC" as const}});
async function one(db:DbClient,q:any){ return db.get(q)??{}; } async function many(db:DbClient,q:any){ return db.all(q)??[]; }
async function inv(db:DbClient){ const r=await one(db,sql`SELECT COUNT(*) products, SUM(CASE WHEN status='Sold' THEN 1 ELSE 0 END) sold, SUM(CASE WHEN status!='Sold' THEN COALESCE(purchase_cost,0)*stock_quantity ELSE 0 END) cost, SUM(CASE WHEN status!='Sold' THEN price_eur*stock_quantity ELSE 0 END) value, SUM(CASE WHEN purchase_cost IS NULL THEN 1 ELSE 0 END) missing_cost, SUM(CASE WHEN length_value IS NULL OR width_value IS NULL OR height_value IS NULL THEN 1 ELSE 0 END) missing_dimensions, SUM(CASE WHEN country_of_origin IS NULL THEN 1 ELSE 0 END) missing_provenance FROM products`); const ph=await one(db,sql`SELECT COUNT(*) c FROM products p WHERE NOT EXISTS (SELECT 1 FROM product_photos pp WHERE pp.product_id=p.id)`); const res=await one(db,sql`SELECT SUM(quantity) reserved FROM stock_reservations WHERE status='Active'`); const totalQuantity=await createGetInventoryTotalQuantityUseCase(createInventoryApplicationContextForDb(db as unknown as InventoryDbClient)).execute(); return {activeProductCount:z(r.products)-z(r.sold),soldArchiveCount:z(r.sold),physicalStockQuantity:totalQuantity,reservedQuantity:z(res.reserved),availableQuantity:Math.max(0,totalQuantity-z(res.reserved)),activeInventoryPurchaseCost:n(r.cost),expectedInventoryValue:n(r.value),expectedProfit:n(z(r.value)-z(r.cost)),productsMissingCost:z(r.missing_cost),productsMissingPhotos:z(ph.c),productsMissingDimensions:z(r.missing_dimensions),productsMissingProvenance:z(r.missing_provenance)}; }
async function purchasing(db:DbClient){ const r=await one(db,sql`SELECT COUNT(*) purchaseCount, SUM(item_subtotal) itemSubtotal, SUM(buyer_premium) buyerPremium, SUM(shipping_cost) shipping, SUM(customs_cost) customs, SUM(packaging_cost) packaging, SUM(tax_vat) taxVat, SUM(miscellaneous_cost) miscellaneous, SUM(COALESCE(total_cost,item_subtotal+COALESCE(buyer_premium,0)+COALESCE(shipping_cost,0)+COALESCE(customs_cost,0)+COALESCE(packaging_cost,0)+COALESCE(tax_vat,0)+COALESCE(miscellaneous_cost,0))) totalSpend, AVG(total_cost) averageLandedCost, SUM(CASE WHEN status='Received' THEN 1 ELSE 0 END) receivedCount, SUM(CASE WHEN status='Partial' THEN 1 ELSE 0 END) partialCount, SUM(CASE WHEN status='Draft' THEN 1 ELSE 0 END) draftCount FROM purchases`); return Object.fromEntries(Object.entries(r).map(([k,v])=>[k,n(v)])); }
async function sales(db:DbClient){ const r=await one(db,sql`SELECT COUNT(DISTINCT o.id) orderCount, SUM(CASE WHEN o.status IN ('Completed','Paid','Shipped','Delivered') THEN 1 ELSE 0 END) completedSaleCount, SUM(o.subtotal_amount) grossRevenue, SUM(o.shipping_amount) shippingCharged, SUM(o.tax_amount) taxVat, AVG(o.total_amount) averageOrderValue FROM orders o`); const f=await one(db,sql`SELECT SUM(item_cost) itemCost, SUM(net_revenue) netRevenue, SUM(profit) originalProfit, SUM(CASE WHEN marketplace_fee IS NULL OR payment_fee IS NULL THEN 1 ELSE 0 END) incompleteFinancialCount FROM sale_financials`); const ref=await one(db,sql`SELECT COUNT(*) refundCount, SUM(total_amount) totalRefunded FROM refunds WHERE status IN ('Succeeded','Completed')`); return {...Object.fromEntries(Object.entries(r).map(([k,v])=>[k,n(v)])),...Object.fromEntries(Object.entries(f).map(([k,v])=>[k,n(v)])),totalRefunded:n(ref.totalRefunded),adjustedProfit:n(z(f.originalProfit)-z(ref.totalRefunded)),refundCount:z(ref.refundCount)}; }
async function customers(db:DbClient){ const r=await one(db,sql`SELECT COUNT(*) customerCount FROM customers`); const o=await one(db,sql`SELECT COUNT(DISTINCT customer_id) activeCustomers, AVG(total_amount) averageLifetimeValue FROM orders WHERE customer_id IS NOT NULL`); const rep=await one(db,sql`SELECT COUNT(*) repeatCustomerCount FROM (SELECT customer_id FROM orders WHERE customer_id IS NOT NULL GROUP BY customer_id HAVING COUNT(*)>1)`); return {customerCount:z(r.customerCount),repeatCustomerCount:z(rep.repeatCustomerCount),averageLifetimeValue:n(o.averageLifetimeValue),activeCustomers:z(o.activeCustomers)}; }
async function wh(db:DbClient){ const r=await one(db,sql`SELECT (SELECT COUNT(*) FROM stock_reservations WHERE status='Active') activeReservations,(SELECT COUNT(*) FROM picking_tasks WHERE status='Pending') pickingPending,(SELECT COUNT(*) FROM packing_tasks WHERE status='Pending') packingPending,(SELECT COUNT(*) FROM packing_tasks WHERE status='ReadyForShipment') shipmentReadyCount,(SELECT COUNT(*) FROM warehouses) warehouseCount,(SELECT COUNT(*) FROM warehouse_locations) locationCount`); return Object.fromEntries(Object.entries(r).map(([k,v])=>[k,z(v)])); }
async function rr(db:DbClient){ const r=await one(db,sql`SELECT (SELECT COUNT(*) FROM return_requests) returnCount,(SELECT COUNT(*) FROM refunds) refundCount,(SELECT SUM(total_amount) FROM refunds WHERE status IN ('Succeeded','Completed')) totalRefunded`); return {...r,returnRate:null,refundRate:null}; }
export async function dashboard(db:DbClient,q:any){ const filters=resolveFilters(q); return {...base("dashboard",filters,[issue("RATE_DENOMINATOR_UNKNOWN","Some rates require linked completed-order denominators.")]),inventory:{...await inv(db),stockAgingSummary:(await stockAging(db,q)).buckets},purchasing:await purchasing(db),sales:await sales(db),returnsRefunds:await rr(db),customers:await customers(db),warehouse:await wh(db)}; }
async function breakdown(db:DbClient,dim:string,col:string){ return (await many(db,sql.raw(`SELECT COALESCE(${col},'Unknown') k, COUNT(*) c, SUM(stock_quantity) qty, SUM(price_eur*stock_quantity) value FROM products GROUP BY COALESCE(${col},'Unknown') ORDER BY k`))).map((x:any)=>({dimension:dim,key:x.k,label:x.k,metrics:[metric("count",x.c),metric("quantity",x.qty),metric("value",x.value,true)]})); }
export async function inventoryReport(db:DbClient,q:any){ const filters=resolveFilters(q); const driver=process.env.DATABASE_DRIVER==="postgres"||process.env.DATABASE_DRIVER==="supabase-postgres"?process.env.DATABASE_DRIVER:"sqlite"; const products=(await createProductReadServiceContextForDb(db as unknown as InventoryDbClient,driver).repositories.products.list({sort:"sku_asc",limit:100})).map((p:any)=>({id:p.id,sku:p.sku,title:p.title,status:p.status,stockQuantity:p.stockQuantity,priceEur:p.priceEur,purchaseCost:p.purchaseCost})); return {...base("inventory",filters),metrics:await inv(db),breakdowns:[...await breakdown(db,"category","category_id"),...await breakdown(db,"brand","brand"),...await breakdown(db,"condition","condition"),...await breakdown(db,"workflowStatus","status")],products}; }
export async function stockAging(db:DbClient,q:any){ const filters=resolveFilters(q); const rows=await many(db,sql`SELECT id,sku,COALESCE((SELECT received_at FROM purchases pu JOIN purchase_lines pl ON pl.purchase_id=pu.id WHERE pl.product_id=products.id AND received_at IS NOT NULL ORDER BY received_at LIMIT 1),created_at) d, CASE WHEN EXISTS (SELECT 1 FROM purchase_lines pl WHERE pl.product_id=products.id) THEN 'purchase/received/created' ELSE 'created' END source, stock_quantity qty FROM products ORDER BY sku`); const counts:any={"0-30":0,"31-60":0,"61-90":0,"91-180":0,"181-365":0,"365+":0,unknown:0}; const t=Date.now(); for(const r of rows){ if(!r.d){counts.unknown++;continue} const days=(t-new Date(r.d).getTime())/86400000; const k=days<=30?"0-30":days<=60?"31-60":days<=90?"61-90":days<=180?"91-180":days<=365?"181-365":"365+"; counts[k]+=z(r.qty)||1; } return {...base("inventory-aging",filters),buckets:Object.entries(counts).map(([k,v])=>({dimension:"ageBucket",key:k,label:k,metrics:[metric("quantity",v)]})),dateSources:["purchase.receivedAt","purchase.orderedAt","product.createdAt"]}; }
export async function genericReport(db:DbClient,type:string,q:any){ const filters=resolveFilters(q); if(type==="purchasing") return {...base(type,filters),metrics:await purchasing(db),breakdowns:[],series:await many(db,sql`SELECT substr(COALESCE(ordered_at,created_at),1,7) period, SUM(COALESCE(total_cost,item_subtotal)) value FROM purchases GROUP BY 1 ORDER BY 1`).then((a:any[])=>a.map(x=>({...x,changePercent:null})))}; if(type==="suppliers") return {...base(type,filters),suppliers:await many(db,sql`SELECT s.id,s.name maskedName,COUNT(p.id) purchaseCount,SUM(COALESCE(p.total_cost,p.item_subtotal)) totalSpend,AVG(p.total_cost) averageLandedCost FROM suppliers s LEFT JOIN purchases p ON p.supplier_id=s.id GROUP BY s.id,s.name ORDER BY s.name`)}; if(type==="customers"){ const customerMetrics=await customers(db); return {...base(type,filters),metrics:customerMetrics,segments:Object.fromEntries(Object.keys(CUSTOMER_SEGMENT_RULES).map(k=>[k,k==="Repeat"?customerMetrics.repeatCustomerCount:0])),customers:await many(db,sql`SELECT id, substr(email,1,2)||'***' maskedEmail, country_code countryCode FROM customers ORDER BY created_at DESC LIMIT 100`)}; } if(type==="returns-refunds") return {...base(type,filters),metrics:await rr(db),breakdowns:await many(db,sql`SELECT reason k, COUNT(*) c FROM return_requests GROUP BY reason ORDER BY reason`).then((a:any[])=>a.map(x=>({dimension:"reason",key:x.k,label:x.k,metrics:[metric("count",x.c)]})))}; if(type==="shipping") return {...base(type,filters),metrics:await one(db,sql`SELECT COUNT(*) shipmentCount,SUM(shipping_cost) shippingCost,SUM(CASE WHEN status='Delivered' THEN 1 ELSE 0 END) deliveredCount,SUM(CASE WHEN tracking_number IS NULL THEN 1 ELSE 0 END) trackingIncompleteCount FROM shipments`),breakdowns:await many(db,sql`SELECT carrier_code k, COUNT(*) c FROM shipments GROUP BY carrier_code ORDER BY carrier_code`).then((a:any[])=>a.map(x=>({dimension:"carrier",key:x.k,label:x.k,metrics:[metric("count",x.c)]})))}; if(type==="warehouse") return {...base(type,filters),metrics:await wh(db),breakdowns:await many(db,sql`SELECT COALESCE(l.code,'Unassigned') k, COUNT(a.product_id) c FROM warehouse_locations l LEFT JOIN product_location_assignments a ON a.warehouse_location_id=l.id GROUP BY l.code ORDER BY l.code`).then((a:any[])=>a.map(x=>({dimension:"location",key:x.k,label:x.k,metrics:[metric("products",x.c)]})))}; if(type==="finance"||type==="profit"||type==="cashflow-summary") return {...base(type,filters),metrics:{...await sales(db),purchaseOutflows:(await purchasing(db)).totalSpend,refundOutflows:(await rr(db)).totalRefunded,netOperationalCashMovement:null},sections:{notice:"Operational reporting, not formal accounting."}}; return {...base(type,filters),metrics:await sales(db),breakdowns:[],series:[]}; }
export function capabilities(){ return {availableReports:["dashboard","inventory","inventory-aging","inventory-readiness","purchasing","suppliers","sales","channels","finance","profit","cashflow-summary","customers","customer-segments","returns-refunds","shipping","warehouse"],supportedFilters:["period","dateFrom","dateTo","granularity","comparisonMode","channel","category","collection","brand","supplier","warehouse","location","country","status","product","customer"],supportedPeriods:Object.values(ReportPeriod),supportedGranularities:Object.values(ReportGranularity),supportedComparisons:Object.values(ReportComparisonMode),exportFormats:Object.values(ReportExportFormat),maximumRangeDays:MAX_RANGE_DAYS,maximumExportRows:MAX_EXPORT_ROWS,completenessBehavior:"Unknown values are null/incomplete and never fabricated.",generatedAt:now()}; }
function csvCell(v:any){ const s=v==null?"":String(v); const safe=/^[=+\-@]/.test(s)?`'${s}`:s; return /[",\n]/.test(safe)?`"${safe.replace(/"/g,'""')}"`:safe; }
export async function exportReport(db:DbClient,type:string,format:string,q:any,clientId?:string,requestId?:string){ const filters=resolveFilters(q); const driver=process.env.DATABASE_DRIVER==="postgres"||process.env.DATABASE_DRIVER==="supabase-postgres"?process.env.DATABASE_DRIVER:"sqlite"; const rows=(await createProductReadServiceContextForDb(db as unknown as InventoryDbClient,driver).repositories.products.listForExport({sort:"sku_asc",limit:MAX_EXPORT_ROWS+1})).map((p:any)=>({id:p.id,sku:p.sku,title:String(p.title).replace(/[\r\n]/g," "),status:p.status,stockQuantity:p.stockQuantity,priceEur:p.priceEur})); if(rows.length>MAX_EXPORT_ROWS) throw Object.assign(new Error("Export row limit exceeded"),{statusCode:413}); const columns=["id","sku","title","status","stockQuantity","priceEur"]; const result={...base(type,filters),filename:`noctella-${type.replace(/[^a-z0-9-]/gi,"-")}-${new Date().toISOString().slice(0,10)}.${format}`,format,columns,rows,rowCount:rows.length,rowLimit:MAX_EXPORT_ROWS}; try { await audit(db as any,clientId??null,requestId??null,"ErpReportExport","Success",{reportType:type,filtersHash:crypto.createHash("sha256").update(JSON.stringify(filters)).digest("hex"),rowCount:rows.length,durationMs:0,result:"Success"}); } catch { /* report generation remains read-only if audit storage is unavailable */ } if(format==="csv") return {contentType:"text/csv",filename:result.filename,body:[columns.join(","),...rows.map((r:any)=>columns.map(c=>csvCell(r[c])).join(","))].join("\n")}; return result; }
