import { createHash, randomUUID } from "node:crypto";
import { and, desc, eq, like, sql } from "drizzle-orm";
import { ErpInvoiceStatus, ErpInvoiceType, OrderStatus, PaymentProvider, PaymentStatus, PriceCurrency } from "@noctella/shared";
import type { DbClient } from "../db/client";
import { erpCommandExecutions, financeEntries, invoiceEvents, invoiceLines, invoices, marketplaceOrders, orderItems, orders, products, refunds, saleFinancials, saleReversals, shipments } from "../db/schema";
import { BadRequestError, ConflictError, NotFoundError } from "./errors";
import { createFinanceEntry, createFinanceEntrySync } from "./financePostings";
import { completeSale, getSaleCompletionReadiness } from "./shipments";
import { createSalesServiceApplication } from "./salesServiceApplication";
import type { SaleOutput } from "../application/sales";
const now=()=>new Date().toISOString(); const money=(n:number)=>Number(n.toFixed(2)); const sum=(p:unknown)=>createHash("sha256").update(JSON.stringify(p??{})).digest("hex");
function parse(v:any,d:any=null){try{return v?JSON.parse(v):d}catch{return d}} function mask(e:string|null|undefined){if(!e)return null; const [a,b]=e.split("@"); return `${a.slice(0,2)}***@${b??"masked"}`}
async function command(db:DbClient,clientId:string,env:any,type:string,entityType:string,entityId?:string){ if(!env?.idempotencyKey) throw new BadRequestError("idempotencyKey is required"); const checksum=sum(env.payload??env); const [e]=await db.select().from(erpCommandExecutions).where(and(eq(erpCommandExecutions.clientId,clientId),eq(erpCommandExecutions.idempotencyKey,env.idempotencyKey))).limit(1); if(e){ if(e.requestChecksum!==checksum) throw new ConflictError("Idempotency key was already used with a different payload"); return {replay:true,result:{status:e.status,entityId:e.entityId,resultReference:e.resultReference,safeResultMetadata:parse(e.safeResultMetadata,{})}}} await db.insert(erpCommandExecutions).values({id:randomUUID(),clientId,commandId:env.commandId??env.idempotencyKey,requestId:env.requestId??null,idempotencyKey:env.idempotencyKey,commandType:type,entityType,entityId:entityId??null,status:"Accepted",requestChecksum:checksum,createdAt:now()}); return {replay:false}; }
async function finish(db:DbClient,clientId:string,key:string,status:string,entityId:string|null,meta:any){ await db.update(erpCommandExecutions).set({status,entityId,resultReference:entityId,safeResultMetadata:JSON.stringify(meta??{}),completedAt:now()}).where(and(eq(erpCommandExecutions.clientId,clientId),eq(erpCommandExecutions.idempotencyKey,key))); }
async function orderCore(db:DbClient,id:string){ const [o]=await db.select().from(orders).where(eq(orders.id,id)); if(!o) throw new NotFoundError("Order not found"); const items=await db.select().from(orderItems).where(eq(orderItems.orderId,id)); return {o,items}; }
export async function customerProjection(db:DbClient, orderId:string, detail=false){ const {o}=await orderCore(db,orderId); const billing=parse(o.billingAddress,{}), shipping=parse(o.shippingAddress,{}); const name=billing.name??shipping.name??null; return {id:o.customerId,guest:!o.customerId,email:detail?o.guestEmail:null,maskedEmail:mask(o.guestEmail),name,billingAddress:detail?billing:undefined,shippingAddress:detail?shipping:undefined}; }
export async function adjustedFinancials(db:DbClient, orderId:string){ const {o,items}=await orderCore(db,orderId); const [sf]=await db.select().from(saleFinancials).where(eq(saleFinancials.orderId,orderId)); const [{totalRefunded}]=await db.select({totalRefunded:sql<number>`coalesce(sum(${refunds.totalAmount}),0)`}).from(refunds).where(and(eq(refunds.orderId,orderId),eq(refunds.status,"succeeded"))); const requiredKnown=!!sf && sf.shippingCost!=null && sf.itemCost!=null; const gross=sf?.grossRevenue??o.totalAmount; const shippingCost=sf?.shippingCost??null; const itemCost=sf?.itemCost??items.reduce((a,i)=>a,0); const fees=[sf?.marketplaceFee,sf?.promotedFee,sf?.paymentFee]; const feesKnown=fees.every(v=>v!=null); const net=sf?sf.netRevenue:money(o.totalAmount-o.taxAmount-(shippingCost??0)-(feesKnown?fees.reduce((a,v)=>a+Number(v),0):0)); return {currency:"EUR",grossRevenue:gross,shippingCharged:o.shippingAmount,discounts:0,taxVat:o.taxAmount,marketplaceFee:sf?.marketplaceFee??null,promotedFee:sf?.promotedFee??null,paymentFee:sf?.paymentFee??null,shippingCost,itemCost,netRevenue:requiredKnown?net:null,profit:sf?.profit??null,completeness:requiredKnown?"Complete":"Incomplete",totalRefunded:totalRefunded??0,feeAdjustments:null,netRetainedRevenue:requiredKnown?money(net-(totalRefunded??0)):null,adjustedProfit:sf?.profit!=null?money(sf.profit-(totalRefunded??0)):null,adjustedCompleteness:requiredKnown?"Complete":"Incomplete"}; }
async function projectSale(db:DbClient,sale:SaleOutput){ const id=sale.id; const [mo]=await db.select().from(marketplaceOrders).where(eq(marketplaceOrders.internalOrderId,id)); const [sh]=await db.select().from(shipments).where(eq(shipments.orderId,id)).orderBy(desc(shipments.createdAt)).limit(1); const [inv]=await db.select().from(invoices).where(eq(invoices.orderId,id)).orderBy(desc(invoices.createdAt)).limit(1); return {centralOrderId:id,marketplaceOrderId:mo?.id??null,channel:mo?.channel??sale.marketplace.channel??"Internal",orderNumber:sale.reference,customer:await customerProjection(db,id,false),saleDate:sale.createdAt,paymentStatus:sale.paymentStatus,orderStatus:sale.status,shipmentStatus:sh?.status??null,completionStatus:sale.status===OrderStatus.Completed?"Completed":"Open",items:sale.lines.map(i=>({orderItemId:i.id,productId:i.productId,sku:i.sku,title:i.title,quantity:i.quantity,unitPrice:i.unitPrice,lineTotal:i.totalPrice,itemCost:null})),financials:await adjustedFinancials(db,id),invoiceStatus:inv?.status??null,invoiceNumber:inv?.invoiceNumber??null,updatedAt:sale.updatedAt}; }
export async function saleProjection(db:DbClient, id:string){ return projectSale(db,await createSalesServiceApplication(db).getSale.execute({saleId:id})); }
export async function listSales(db:DbClient,q:any={}){ const page=Number(q.page??1),pageSize=Number(q.pageSize??50),application=createSalesServiceApplication(db); if(q.search){const filters:any[]=[like(orders.orderNumber,`%${q.search}%`)];if(q.orderStatus)filters.push(eq(orders.status,String(q.orderStatus)));if(q.paymentStatus)filters.push(eq(orders.paymentStatus,String(q.paymentStatus)));const rows=await db.select({id:orders.id}).from(orders).where(and(...filters)).orderBy(desc(orders.createdAt)).limit(pageSize).offset((page-1)*pageSize);return{items:await Promise.all(rows.map(async row=>projectSale(db,await application.getSale.execute({saleId:row.id})))),page,pageSize};} const result=await application.listSales.execute({status:q.orderStatus,paymentStatus:q.paymentStatus,limit:pageSize,offset:(page-1)*pageSize}); return {items:await Promise.all(result.rows.map(row=>projectSale(db,row))),page,pageSize}; }
export async function createInternalSale(db:DbClient,input:any){ if(!["Internal","Direct","LocalPickup","Other"].includes(input.channel)) throw new BadRequestError("Marketplace impersonation is not allowed"); if(input.currency!==PriceCurrency.Eur) throw new BadRequestError("EUR only"); const addr=input.customer?.address??{fullName:input.customer?.name??"Guest",line1:"ERP internal sale",city:"N/A",postalCode:"N/A",country:"N/A"}; const orderDraftId=input.orderDraftId??`erp-${randomUUID()}`; return createSalesServiceApplication(db).createInternalSale.execute({orderDraftId,idempotencyKey:orderDraftId,channel:"Internal",customerId:input.customer?.id,guestEmail:input.customer?.email??"guest@example.invalid",status:OrderStatus.Processing,paymentStatus:input.paymentStatus??PaymentStatus.Paid,paymentProvider:PaymentProvider.CashOnDelivery,paymentReference:input.paymentReference??"erp-internal",currency:PriceCurrency.Eur,billingAddress:addr,shippingAddress:addr,subtotalAmount:input.subtotalAmount,totalAmount:input.totalAmount,items:input.lines.map((l:any)=>({productId:l.productId,quantity:l.quantity??1})),notes:input.notes}); }
export async function createInvoiceDraft(db:DbClient,orderId:string,input:any={}){ const {o,items}=await orderCore(db,orderId); if(o.currency!=="EUR") throw new BadRequestError("EUR only"); if(input.erpReferenceId){ const [e]=await db.select().from(invoices).where(eq(invoices.erpReferenceId,input.erpReferenceId)).limit(1); if(e) return getInvoice(db,e.id); } if ((input.discountAmount??0) < 0 || (input.shippingAmount??0) < 0 || (input.taxVatAmount??0) < 0) throw new BadRequestError("Invoice amounts cannot be negative"); const t=now(), id=randomUUID(); const subtotal=items.reduce((a,i)=>a+i.totalPrice,0), total=money(subtotal+o.shippingAmount+o.taxAmount-(input.discountAmount??0)); await db.insert(invoices).values({id,erpReferenceId:input.erpReferenceId??null,orderId,customerId:o.customerId,invoiceNumber:null,invoiceType:input.invoiceType??ErpInvoiceType.SalesInvoice,status:ErpInvoiceStatus.Draft,currency:"EUR",issuedAt:null,dueAt:input.dueAt??null,paidAt:null,cancelledAt:null,sellerSnapshot:JSON.stringify({name:"Noctella"}),customerSnapshot:JSON.stringify(await customerProjection(db,orderId,true)),billingAddressSnapshot:o.billingAddress,shippingAddressSnapshot:o.shippingAddress,subtotal,shippingAmount:o.shippingAmount,discountAmount:input.discountAmount??0,taxVatAmount:o.taxAmount,totalAmount:total,notes:input.notes??null,sourceSnapshot:JSON.stringify({order:o}),createdAt:t,updatedAt:t}); for(const it of items) await db.insert(invoiceLines).values({id:randomUUID(),invoiceId:id,orderItemId:it.id,productId:it.productId,skuSnapshot:it.productSku,titleSnapshot:it.productTitle,quantity:it.quantity,unitPrice:it.unitPrice,discountAmount:0,taxVatAmount:0,lineTotal:it.totalPrice,createdAt:t}); await invoiceEvent(db,id,"Created",null,ErpInvoiceStatus.Draft,{orderId}); return getInvoice(db,id); }
export async function getInvoice(db:DbClient,id:string){ const [inv]=await db.select().from(invoices).where(eq(invoices.id,id)); if(!inv) throw new NotFoundError("Invoice not found"); return {...inv,lines:await db.select().from(invoiceLines).where(eq(invoiceLines.invoiceId,id))}; }
export async function listInvoices(db:DbClient,q:any={}){ const f:any[]=[]; if(q.orderId)f.push(eq(invoices.orderId,String(q.orderId))); if(q.status)f.push(eq(invoices.status,String(q.status))); const rows=await db.select().from(invoices).where(f.length?and(...f):undefined).orderBy(desc(invoices.createdAt)).limit(Number(q.pageSize??50)).offset((Number(q.page??1)-1)*Number(q.pageSize??50)); return {items:rows,page:Number(q.page??1),pageSize:Number(q.pageSize??50)}; }
export async function updateInvoiceDraft(db:DbClient,id:string,input:any){ const inv:any=await getInvoice(db,id); if(inv.status!==ErpInvoiceStatus.Draft) throw new ConflictError("Issued invoice snapshots are immutable"); if(input.expectedUpdatedAt && input.expectedUpdatedAt!==inv.updatedAt) throw new ConflictError("Invoice has changed"); await db.update(invoices).set({dueAt:input.dueAt??inv.dueAt,notes:input.notes??inv.notes,updatedAt:now()}).where(eq(invoices.id,id)); await invoiceEvent(db,id,"Updated",inv.status,inv.status,{fields:Object.keys(input)}); return getInvoice(db,id); }
export const INVOICE_STATUS_TRANSITIONS: Partial<Record<ErpInvoiceStatus, ErpInvoiceStatus[]>> = { [ErpInvoiceStatus.Draft]:[ErpInvoiceStatus.Issued,ErpInvoiceStatus.Cancelled], [ErpInvoiceStatus.Issued]:[ErpInvoiceStatus.Cancelled,ErpInvoiceStatus.Voided,ErpInvoiceStatus.Paid], [ErpInvoiceStatus.Cancelled]:[], [ErpInvoiceStatus.Voided]:[], [ErpInvoiceStatus.Paid]:[] };
function assertInvoiceTransition(current:string, target:string){ const allowed=INVOICE_STATUS_TRANSITIONS[current as ErpInvoiceStatus]??[]; if(!allowed.includes(target as ErpInvoiceStatus)) throw new BadRequestError("Invalid invoice status transition"); }
/** Sync terminal-method (.get/.all/.run) sibling of the query logic below — required inside db.transaction(), whose better-sqlite3 callback must be synchronous (no await). */
function nextInvoiceNumberSync(tx:any, year:number){ const row:any=tx.select({count:sql<number>`count(*)`}).from(invoices).where(like(invoices.invoiceNumber,`NOCT-${year}-%`)).get(); return `NOCT-${year}-${String(Number(row.count)+1).padStart(6,"0")}`; }
function withInvoiceLines(tx:any, row:any){ return { ...row, lines: tx.select().from(invoiceLines).where(eq(invoiceLines.invoiceId,row.id)).all() }; }
/**
 * The full write sequence (status/number/timestamps, invoice event, finance
 * entry) runs inside one synchronous db.transaction() so it commits or rolls
 * back atomically — see Sprint 45B. The outer function stays `async` (never
 * awaiting anything itself) purely so a synchronous throw from inside the
 * transaction still surfaces as a rejected Promise to existing callers/tests.
 */
export async function issueInvoice(db:DbClient,id:string,input:any={}){ for(let attempt=0; attempt<5; attempt++){ try { return db.transaction((tx) => { const row:any=tx.select().from(invoices).where(eq(invoices.id,id)).get(); if(!row) throw new NotFoundError("Invoice not found"); if(row.status===ErpInvoiceStatus.Issued) return withInvoiceLines(tx,row); assertInvoiceTransition(row.status,ErpInvoiceStatus.Issued); const year=new Date().getUTCFullYear(); const num=input.invoiceNumber??nextInvoiceNumberSync(tx,year); const t=input.issueAt??now(); tx.update(invoices).set({status:ErpInvoiceStatus.Issued,invoiceNumber:num,issuedAt:t,updatedAt:t}).where(and(eq(invoices.id,id),eq(invoices.status,ErpInvoiceStatus.Draft))).run(); tx.insert(invoiceEvents).values({id:randomUUID(),invoiceId:id,eventType:"Issued",previousStatus:ErpInvoiceStatus.Draft,newStatus:ErpInvoiceStatus.Issued,safeMetadata:JSON.stringify({invoiceNumber:num}),createdAt:t}).run(); createFinanceEntrySync(tx as unknown as DbClient,{invoiceId:id,orderId:row.orderId,entryType:"IssuedInvoice",amount:row.totalAmount,sourceReference:num,idempotencyKey:`invoice-issued:${id}`,occurredAt:t,snapshot:row}); const updated:any=tx.select().from(invoices).where(eq(invoices.id,id)).get(); return withInvoiceLines(tx,updated); }); } catch (error:any) { if(String(error?.message??error).includes("UNIQUE constraint failed") && !input.invoiceNumber) continue; throw error; } } throw new ConflictError("Could not allocate a unique invoice number"); }
export async function setInvoiceStatus(db:DbClient,id:string,status:string){ return db.transaction((tx) => { const row:any=tx.select().from(invoices).where(eq(invoices.id,id)).get(); if(!row) throw new NotFoundError("Invoice not found"); const previousStatus=row.status; if(previousStatus===status) return withInvoiceLines(tx,row); assertInvoiceTransition(previousStatus,status); const t=now(); tx.update(invoices).set({status,cancelledAt:[ErpInvoiceStatus.Cancelled,ErpInvoiceStatus.Voided].includes(status as any)?t:row.cancelledAt,paidAt:status===ErpInvoiceStatus.Paid?t:row.paidAt,updatedAt:t}).where(eq(invoices.id,id)).run(); tx.insert(invoiceEvents).values({id:randomUUID(),invoiceId:id,eventType:status,previousStatus,newStatus:status,safeMetadata:JSON.stringify({}),createdAt:t}).run(); if(previousStatus===ErpInvoiceStatus.Issued && (status===ErpInvoiceStatus.Cancelled||status===ErpInvoiceStatus.Voided)){ const entryType=status===ErpInvoiceStatus.Cancelled?"InvoiceCancelled":"InvoiceVoided"; createFinanceEntrySync(tx as unknown as DbClient,{orderId:row.orderId,invoiceId:id,entryType,amount:-row.totalAmount,sourceReference:row.invoiceNumber,idempotencyKey:`invoice-${status.toLowerCase()}:${id}`,occurredAt:t,snapshot:row}); } const updated:any=tx.select().from(invoices).where(eq(invoices.id,id)).get(); return withInvoiceLines(tx,updated); }); }
async function invoiceEvent(db:DbClient,invoiceId:string,eventType:string,previousStatus:any,newStatus:any,safeMetadata:any){ await db.insert(invoiceEvents).values({id:randomUUID(),invoiceId,eventType,previousStatus,newStatus,safeMetadata:JSON.stringify(safeMetadata??{}),createdAt:now()}); }
export const getInvoiceEvents=(db:DbClient,id:string)=>db.select().from(invoiceEvents).where(eq(invoiceEvents.invoiceId,id)).orderBy(desc(invoiceEvents.createdAt));
export { createFinanceEntry };
export async function listFinanceEntries(db:DbClient,q:any={}){ const f:any[]=[]; if(q.orderId)f.push(eq(financeEntries.orderId,String(q.orderId))); if(q.entryType)f.push(eq(financeEntries.entryType,String(q.entryType))); return {items:await db.select().from(financeEntries).where(f.length?and(...f):undefined).orderBy(desc(financeEntries.occurredAt)).limit(Number(q.pageSize??50)).offset((Number(q.page??1)-1)*Number(q.pageSize??50))}; }
export async function financeSummary(db:DbClient,q:any={}){ const sales=await db.select().from(saleFinancials); const refs=await db.select().from(refunds).where(eq(refunds.status,"succeeded")); const gross=money(sales.reduce((a,s)=>a+s.grossRevenue,0)), totalRefunds=money(refs.reduce((a,r)=>a+r.totalAmount,0)); const itemCost=money(sales.reduce((a,s)=>a+s.itemCost,0)); const feesKnown=sales.every(s=>s.marketplaceFee!=null&&s.paymentFee!=null); const fees=feesKnown?money(sales.reduce((a,s)=>a+(s.marketplaceFee??0)+(s.promotedFee??0)+(s.paymentFee??0),0)):null; const shippingCost=sales.every(s=>s.shippingCost!=null)?money(sales.reduce((a,s)=>a+s.shippingCost,0)):null; const profit=sales.length?money(sales.reduce((a,s)=>a+s.profit,0)):null; return {currency:"EUR",grossRevenue:gross,totalRefunds,netRevenue:money(gross-totalRefunds),itemCost,fees,shippingCost,profit,adjustedProfit:profit==null?null:money(profit-totalRefunds),completeness:feesKnown?"Complete":"Incomplete"}; }
export async function executeSalesCommand(db:DbClient,clientId:string,env:any,type:string,id?:string){ const c=await command(db,clientId,env,type,type.includes("Invoice")?"Invoice":"Order",id); if(c.replay)return c.result; let out:any; const p=env.payload??{}; if(type==="CreateInternalSale") out=await createInternalSale(db,p); else if(type==="CompleteSale") out=await completeSale(db,id!); else if(type==="CreateInvoice") out=await createInvoiceDraft(db,id!,p); else if(type==="UpdateInvoice") out=await updateInvoiceDraft(db,id!,p); else if(type==="IssueInvoice") out=await issueInvoice(db,id!,p); else if(type==="CancelInvoice") out=await setInvoiceStatus(db,id!,ErpInvoiceStatus.Cancelled); else if(type==="VoidInvoice") out=await setInvoiceStatus(db,id!,ErpInvoiceStatus.Voided); else if(type==="MarkInvoicePaid") out=await setInvoiceStatus(db,id!,ErpInvoiceStatus.Paid); await finish(db,clientId,env.idempotencyKey,"Completed",out.id??out.orderId??id,{type,entityId:out.id??out.orderId??id}); return out; }
export { getSaleCompletionReadiness };
export async function refundSummary(db:DbClient,orderId:string){ return {orderId,totalRefunded:(await adjustedFinancials(db,orderId)).totalRefunded,refunds:await db.select().from(refunds).where(eq(refunds.orderId,orderId))}; }
export async function reversalSummary(db:DbClient,orderId:string){ const reversals=await db.select().from(saleReversals).where(eq(saleReversals.orderId,orderId)); return {orderId,reversed:reversals.length>0,reversals}; }
