import crypto from "node:crypto";
import { sql } from "drizzle-orm";
import type { DbClient } from "../db/client";
import { BadRequestError, ConflictError, NotFoundError } from "./errors";
import { audit } from "./erpIntegration";

type Env={commandId:string;requestId?:string;commandType:string;entityType?:string;entityId?:string;idempotencyKey:string;payload?:any};
const now=()=>new Date().toISOString();
const id=()=>crypto.randomUUID();
const sum=(v:any)=>crypto.createHash("sha256").update(JSON.stringify(v??{})).digest("hex");
const safe=(v:any)=>JSON.stringify(v??{}).slice(0,4000);
async function all(db:DbClient, q:any){ return (await db.all(q)) as any[]; }
async function get(db:DbClient, q:any){ return ((await db.all(q)) as any[])[0]; }
async function exec(db:DbClient, clientId:string, env:Env, type:string, entityType:string, entityId?:string){
 if(!env?.idempotencyKey||!env?.commandId) throw new BadRequestError("Valid ERP command envelope is required");
 const checksum=sum({type,entityId,payload:env.payload??{}});
 const existing=await get(db, sql`SELECT * FROM erp_command_executions WHERE client_id=${clientId} AND idempotency_key=${env.idempotencyKey} LIMIT 1`);
 if(existing){ if(existing.request_checksum!==checksum) throw new ConflictError("Idempotency key was already used for a different payload"); return existing; }
 await db.run(sql`INSERT INTO erp_command_executions (id,client_id,command_id,request_id,idempotency_key,command_type,entity_type,entity_id,status,request_checksum,created_at) VALUES (${id()},${clientId},${env.commandId},${env.requestId??null},${env.idempotencyKey},${type},${entityType},${entityId??null},'Accepted',${checksum},${now()})`); return null;
}
async function done(db:DbClient, clientId:string, env:Env, type:string, entityType:string, entityId:string|null, meta:any){ await db.run(sql`UPDATE erp_command_executions SET status='Succeeded', entity_type=${entityType}, entity_id=${entityId}, result_reference=${entityId}, safe_result_metadata=${safe(meta)}, completed_at=${now()} WHERE client_id=${clientId} AND idempotency_key=${env.idempotencyKey}`); await audit(db, clientId, env.requestId, type, "Succeeded", meta); return {status:"Succeeded",...meta}; }
function prior(r:any){return {status:r.status, entityId:r.entity_id, resultReference:r.result_reference, metadata:r.safe_result_metadata?JSON.parse(r.safe_result_metadata):{}}}
async function event(db:DbClient, e:any){ await db.run(sql`INSERT INTO warehouse_events (id,warehouse_id,location_id,product_id,order_id,shipment_id,reservation_id,picking_task_id,packing_task_id,event_type,safe_metadata,created_at) VALUES (${id()},${e.warehouseId??null},${e.locationId??null},${e.productId??null},${e.orderId??null},${e.shipmentId??null},${e.reservationId??null},${e.pickingTaskId??null},${e.packingTaskId??null},${e.eventType},${safe(e.meta)},${now()})`); }

export async function availability(db:DbClient, productId:string){ const p=await get(db, sql`SELECT id, stock_quantity FROM products WHERE id=${productId}`); if(!p) throw new NotFoundError("Product not found"); await expireReservations(db); const r=await get(db, sql`SELECT COALESCE(SUM(quantity),0) reserved, COUNT(*) count FROM stock_reservations WHERE product_id=${productId} AND status='Active'`); const physical=Number(p.stock_quantity??0), reserved=Number(r?.reserved??0); return {productId, physicalQuantity:physical, reservedQuantity:reserved, availableQuantity:Math.max(0, physical-reserved), activeReservationCount:Number(r?.count??0)}; }
export async function createWarehouse(db:DbClient, clientId:string, env:Env){ const ex=await exec(db,clientId,env,"CreateWarehouse","Warehouse"); if(ex) return prior(ex); const p=env.payload??{}; if(!String(p.code??'').trim()||!String(p.name??'').trim()) throw new BadRequestError("Warehouse code and name are required"); const wid=id(); await db.run(sql`INSERT INTO warehouses (id,erp_reference_id,name,code,status,country_code,city,address_summary,created_at,updated_at) VALUES (${wid},${p.erpReferenceId??null},${p.name},${p.code},${p.status??'Active'},${p.countryCode??null},${p.city??null},${p.addressSummary??null},${now()},${now()})`); await event(db,{warehouseId:wid,eventType:"WarehouseCreated",meta:{code:p.code}}); return done(db,clientId,env,"CreateWarehouse","Warehouse",wid,{warehouseId:wid}); }
export const listWarehouses=(db:DbClient)=>all(db, sql`SELECT * FROM warehouses ORDER BY code`);
export async function getWarehouse(db:DbClient,wid:string){ const w=await get(db,sql`SELECT * FROM warehouses WHERE id=${wid}`); if(!w) throw new NotFoundError("Warehouse not found"); return w; }
export async function updateWarehouseStatus(db:DbClient, clientId:string, env:Env, wid:string, status:string){ const ex=await exec(db,clientId,env,status==='Active'?"ReactivateWarehouse":"DeactivateWarehouse","Warehouse",wid); if(ex) return prior(ex); await getWarehouse(db,wid); await db.run(sql`UPDATE warehouses SET status=${status}, updated_at=${now()} WHERE id=${wid}`); await event(db,{warehouseId:wid,eventType:`Warehouse${status}`,meta:{}}); return done(db,clientId,env,status==='Active'?"ReactivateWarehouse":"DeactivateWarehouse","Warehouse",wid,{warehouseId:wid,status}); }
export async function createWarehouseLocation(db:DbClient, clientId:string, env:Env){ const ex=await exec(db,clientId,env,"CreateWarehouseLocation","WarehouseLocation"); if(ex) return prior(ex); const p=env.payload??{}; if(!p.warehouseId||!String(p.code??'').trim()||!String(p.name??'').trim()) throw new BadRequestError("warehouseId, code and name are required"); await getWarehouse(db,p.warehouseId); if(p.parentLocationId){ const par=await get(db,sql`SELECT * FROM warehouse_locations WHERE id=${p.parentLocationId}`); if(!par||par.warehouse_id!==p.warehouseId) throw new BadRequestError("Parent location must belong to same warehouse"); } const lid=id(); await db.run(sql`INSERT INTO warehouse_locations (id,warehouse_id,parent_location_id,erp_reference_id,code,name,location_type,status,sort_order,created_at,updated_at) VALUES (${lid},${p.warehouseId},${p.parentLocationId??null},${p.erpReferenceId??null},${p.code},${p.name},${p.locationType??'Bin'},${p.status??'Active'},${p.sortOrder??0},${now()},${now()})`); await event(db,{warehouseId:p.warehouseId,locationId:lid,eventType:"LocationCreated",meta:{code:p.code}}); return done(db,clientId,env,"CreateWarehouseLocation","WarehouseLocation",lid,{locationId:lid}); }
export const listWarehouseLocations=(db:DbClient, warehouseId?:string)=>all(db, warehouseId?sql`SELECT * FROM warehouse_locations WHERE warehouse_id=${warehouseId} ORDER BY sort_order, code`:sql`SELECT * FROM warehouse_locations ORDER BY warehouse_id, sort_order, code`);
export async function assignProductLocation(db:DbClient, clientId:string, env:Env){ const ex=await exec(db,clientId,env,"AssignProductLocation","ProductLocationAssignment"); if(ex) return prior(ex); const p=env.payload??{}; const loc=await get(db,sql`SELECT * FROM warehouse_locations WHERE id=${p.warehouseLocationId}`); if(!loc) throw new NotFoundError("Location not found"); if(loc.status!=="Active") throw new BadRequestError("Inactive location cannot receive assignment"); const prod=await get(db,sql`SELECT id FROM products WHERE id=${p.productId}`); if(!prod) throw new NotFoundError("Product not found"); const aid=id(); if(p.isPrimary) await db.run(sql`UPDATE product_location_assignments SET is_primary=0 WHERE product_id=${p.productId}`); await db.run(sql`INSERT OR IGNORE INTO product_location_assignments (id,product_id,warehouse_location_id,is_primary,reference_note,created_at,updated_at) VALUES (${aid},${p.productId},${p.warehouseLocationId},${p.isPrimary?1:0},${p.referenceNote??null},${now()},${now()})`); await event(db,{warehouseId:loc.warehouse_id,locationId:p.warehouseLocationId,productId:p.productId,eventType:"ProductLocationAssigned",meta:{isPrimary:!!p.isPrimary}}); return done(db,clientId,env,"AssignProductLocation","ProductLocationAssignment",aid,{assignmentId:aid}); }
export const getProductLocations=(db:DbClient, productId:string)=>all(db,sql`SELECT a.*, l.code location_code, l.name location_name, w.code warehouse_code FROM product_location_assignments a JOIN warehouse_locations l ON l.id=a.warehouse_location_id JOIN warehouses w ON w.id=l.warehouse_id WHERE a.product_id=${productId} ORDER BY a.is_primary DESC, w.code, l.code`);
export async function createReservation(db:DbClient, clientId:string, env:Env){ const ex=await exec(db,clientId,env,"CreateReservation","StockReservation"); if(ex) return prior(ex); const p=env.payload??{}; const qty=Number(p.quantity); if(!Number.isInteger(qty)||qty<=0) throw new BadRequestError("Positive integer quantity is required"); if(!p.reservationReference||!p.reason) throw new BadRequestError("reservationReference and reason are required"); const av=await availability(db,p.productId); if(qty>av.availableQuantity) throw new ConflictError("Reservation exceeds available quantity"); const rid=id(); await db.run(sql`INSERT INTO stock_reservations (id,order_id,product_id,reservation_reference,reason,quantity,status,expires_at,created_at,updated_at) VALUES (${rid},${p.orderId??null},${p.productId},${p.reservationReference},${p.reason},${qty},'Active',${p.expiresAt??null},${now()},${now()})`); await event(db,{productId:p.productId,orderId:p.orderId,reservationId:rid,eventType:"ReservationCreated",meta:{quantity:qty,reason:p.reason}}); return done(db,clientId,env,"CreateReservation","StockReservation",rid,{reservationId:rid}); }
export const listReservations=(db:DbClient,q:any={})=>all(db,sql`SELECT * FROM stock_reservations WHERE (${q.productId??null} IS NULL OR product_id=${q.productId??null}) AND (${q.orderId??null} IS NULL OR order_id=${q.orderId??null}) AND (${q.status??null} IS NULL OR status=${q.status??null}) ORDER BY created_at DESC LIMIT ${Number(q.limit??100)}`);
export async function changeReservation(db:DbClient, clientId:string, env:Env, rid:string, status:string){ const type=status==='Released'?"ReleaseReservation":status==='Cancelled'?"CancelReservation":"ConsumeReservation"; const ex=await exec(db,clientId,env,type,"StockReservation",rid); if(ex) return prior(ex); const r=await get(db,sql`SELECT * FROM stock_reservations WHERE id=${rid}`); if(!r) throw new NotFoundError("Reservation not found"); if(["Expired","Cancelled"].includes(r.status)&&status==='Consumed') throw new BadRequestError("Reservation cannot be consumed"); if(r.status==='Active') await db.run(sql`UPDATE stock_reservations SET status=${status}, released_at=${status==='Released'?now():r.released_at}, consumed_at=${status==='Consumed'?now():r.consumed_at}, updated_at=${now()} WHERE id=${rid}`); await event(db,{productId:r.product_id,orderId:r.order_id,reservationId:rid,eventType:`Reservation${status}`,meta:{}}); return done(db,clientId,env,type,"StockReservation",rid,{reservationId:rid,status}); }
export async function expireReservations(db:DbClient){ await db.run(sql`UPDATE stock_reservations SET status='Expired', updated_at=${now()} WHERE status='Active' AND expires_at IS NOT NULL AND expires_at < ${now()}`); }
async function orderLines(db:DbClient, orderId:string){ const o=await get(db,sql`SELECT * FROM orders WHERE id=${orderId}`); if(!o) throw new NotFoundError("Order not found"); return all(db,sql`SELECT * FROM order_items WHERE order_id=${orderId}`); }
export async function createPickingTask(db:DbClient, clientId:string, env:Env, orderId:string){ const ex=await exec(db,clientId,env,"CreatePickingTask","PickingTask",orderId); if(ex) return prior(ex); const lines=await orderLines(db,orderId); if(!lines.length) throw new BadRequestError("Order has no items"); const tid=id(); await db.run(sql`INSERT INTO picking_tasks (id,order_id,status,assigned_client_id,safe_notes,created_at,updated_at) VALUES (${tid},${orderId},'Pending',${clientId},${env.payload?.safeNotes??null},${now()},${now()})`); for(const l of lines) await db.run(sql`INSERT INTO picking_task_lines (id,picking_task_id,product_id,order_item_id,requested_quantity,picked_quantity,short_quantity,created_at,updated_at) VALUES (${id()},${tid},${l.product_id},${l.id},${l.quantity},0,0,${now()},${now()})`); await event(db,{orderId,pickingTaskId:tid,eventType:"PickingCreated",meta:{lineCount:lines.length}}); return done(db,clientId,env,"CreatePickingTask","PickingTask",tid,{pickingTaskId:tid}); }
export const getPickingTask=(db:DbClient,tid:string)=>get(db,sql`SELECT * FROM picking_tasks WHERE id=${tid}`);
export const listPickingTasks=(db:DbClient,q:any={})=>all(db,sql`SELECT * FROM picking_tasks WHERE (${q.orderId??null} IS NULL OR order_id=${q.orderId??null}) ORDER BY created_at DESC LIMIT ${Number(q.limit??100)}`);
export async function updatePicking(db:DbClient,clientId:string,env:Env,tid:string, action:string, lineId?:string){ const ex=await exec(db,clientId,env,action,"PickingTask",tid); if(ex)return prior(ex); const t=await getPickingTask(db,tid); if(!t) throw new NotFoundError("Picking task not found"); if(action==='StartPickingTask') await db.run(sql`UPDATE picking_tasks SET status='InProgress', started_at=COALESCE(started_at,${now()}), updated_at=${now()} WHERE id=${tid}`); if(action==='ConfirmPickedLine'){ const p=env.payload??{}; const l=await get(db,sql`SELECT * FROM picking_task_lines WHERE id=${lineId} AND picking_task_id=${tid}`); const q=Number(p.pickedQuantity??l.requested_quantity); if(q<0||q>l.requested_quantity) throw new BadRequestError("pickedQuantity cannot exceed requestedQuantity"); await db.run(sql`UPDATE picking_task_lines SET picked_quantity=${q}, short_quantity=0, updated_at=${now()} WHERE id=${lineId}`); } if(action==='MarkPickingShort'){ const p=env.payload??{}; const l=await get(db,sql`SELECT * FROM picking_task_lines WHERE id=${lineId} AND picking_task_id=${tid}`); const q=Number(p.shortQuantity??(l.requested_quantity-l.picked_quantity)); if(q<0||q>l.requested_quantity) throw new BadRequestError("shortQuantity cannot exceed requestedQuantity"); await db.run(sql`UPDATE picking_task_lines SET short_quantity=${q}, updated_at=${now()} WHERE id=${lineId}`); } if(action==='CompletePickingTask'){ const bad=await get(db,sql`SELECT COUNT(*) c FROM picking_task_lines WHERE picking_task_id=${tid} AND picked_quantity + short_quantity < requested_quantity`); if(Number(bad.c)>0) throw new BadRequestError("Every line must be picked or short"); await db.run(sql`UPDATE picking_tasks SET status='Picked', completed_at=${now()}, updated_at=${now()} WHERE id=${tid}`);} if(action==='CancelPickingTask') await db.run(sql`UPDATE picking_tasks SET status='Cancelled', cancelled_at=${now()}, updated_at=${now()} WHERE id=${tid}`); await event(db,{orderId:t.order_id,pickingTaskId:tid,eventType:action,meta:{lineId}}); return done(db,clientId,env,action,"PickingTask",tid,{pickingTaskId:tid}); }
export async function createPackingTask(db:DbClient, clientId:string, env:Env, orderId:string){ const ex=await exec(db,clientId,env,"CreatePackingTask","PackingTask",orderId); if(ex) return prior(ex); const pick=env.payload?.pickingTaskId?await getPickingTask(db,env.payload.pickingTaskId):await get(db,sql`SELECT * FROM picking_tasks WHERE order_id=${orderId} AND status='Picked' ORDER BY completed_at DESC LIMIT 1`); if(!pick) throw new BadRequestError("Completed picking task is required"); const lines=await all(db,sql`SELECT * FROM picking_task_lines WHERE picking_task_id=${pick.id}`); const tid=id(); await db.run(sql`INSERT INTO packing_tasks (id,order_id,picking_task_id,status,package_count,created_at,updated_at) VALUES (${tid},${orderId},${pick.id},'Pending',1,${now()},${now()})`); for(const l of lines) await db.run(sql`INSERT INTO packing_task_lines (id,packing_task_id,product_id,order_item_id,quantity,created_at) VALUES (${id()},${tid},${l.product_id},${l.order_item_id},${l.picked_quantity},${now()})`); await event(db,{orderId,pickingTaskId:pick.id,packingTaskId:tid,eventType:"PackingCreated",meta:{}}); return done(db,clientId,env,"CreatePackingTask","PackingTask",tid,{packingTaskId:tid}); }
export const getPackingTask=(db:DbClient,tid:string)=>get(db,sql`SELECT * FROM packing_tasks WHERE id=${tid}`);
export const listPackingTasks=(db:DbClient,q:any={})=>all(db,sql`SELECT * FROM packing_tasks WHERE (${q.orderId??null} IS NULL OR order_id=${q.orderId??null}) ORDER BY created_at DESC LIMIT ${Number(q.limit??100)}`);
export async function updatePacking(db:DbClient,clientId:string,env:Env,tid:string,action:string){ const ex=await exec(db,clientId,env,action,"PackingTask",tid); if(ex)return prior(ex); const t=await getPackingTask(db,tid); if(!t) throw new NotFoundError("Packing task not found"); const p=env.payload??{}; if(action==='StartPackingTask') await db.run(sql`UPDATE packing_tasks SET status='InProgress', started_at=COALESCE(started_at,${now()}), updated_at=${now()} WHERE id=${tid}`); if(action==='UpdatePackingTask'){ if(p.packageCount!==undefined&&Number(p.packageCount)<=0) throw new BadRequestError("packageCount must be positive"); if(p.totalWeight!==undefined&&Number(p.totalWeight)<0) throw new BadRequestError("totalWeight must not be negative"); await db.run(sql`UPDATE packing_tasks SET package_count=${p.packageCount??t.package_count}, total_weight=${p.totalWeight??t.total_weight}, dimensions_snapshot=${p.dimensions?JSON.stringify(p.dimensions):t.dimensions_snapshot}, packing_materials_snapshot=${p.materials?JSON.stringify(p.materials):t.packing_materials_snapshot}, updated_at=${now()} WHERE id=${tid}`); } if(action==='CompletePackingTask') await db.run(sql`UPDATE packing_tasks SET status='Packed', completed_at=${now()}, updated_at=${now()} WHERE id=${tid}`); if(action==='MarkPackingReady') await db.run(sql`UPDATE packing_tasks SET status='ReadyForShipment', completed_at=COALESCE(completed_at,${now()}), updated_at=${now()} WHERE id=${tid}`); if(action==='CancelPackingTask') await db.run(sql`UPDATE packing_tasks SET status='Cancelled', updated_at=${now()} WHERE id=${tid}`); await event(db,{orderId:t.order_id,packingTaskId:tid,eventType:action,meta:{}}); return done(db,clientId,env,action,"PackingTask",tid,{packingTaskId:tid}); }
export const shipmentReadyQueue=(db:DbClient)=>all(db,sql`SELECT o.id orderId,o.order_number orderNumber,p.shipment_id shipmentId,substr(o.guest_email,1,2)||'***' customerMaskedSummary,NULL carrier,NULL trackingAvailability,pt.status packingStatus,p.package_count packageCount,p.total_weight totalWeight,p.completed_at readyAt FROM packing_tasks p JOIN orders o ON o.id=p.order_id LEFT JOIN picking_tasks pt ON pt.id=p.picking_task_id WHERE p.status='ReadyForShipment' ORDER BY p.completed_at DESC`);
export const warehouseEvents=(db:DbClient,q:any={})=>all(db,sql`SELECT * FROM warehouse_events WHERE (${q.productId??null} IS NULL OR product_id=${q.productId??null}) AND (${q.orderId??null} IS NULL OR order_id=${q.orderId??null}) ORDER BY created_at DESC LIMIT ${Number(q.limit??100)} OFFSET ${Number(q.offset??0)}`);
