import crypto from "node:crypto";
import { and, desc, eq, SQL } from "drizzle-orm";
import { MarketplaceConnectionStatus, PublishChannel, PublishJobStatus, type ExternalListing, type MarketplaceConnection, type PublishAttempt, type PublishExecutionResult, type PublishJob } from "@noctella/shared";
import type { DbClient } from "../db/client";
import { externalListings, marketplaceConnections, publishAttempts, publishJobs } from "../db/schema";
import { BadRequestError, ConflictError, NotFoundError } from "./errors";
import { getProductById } from "./products";
import { buildPublishPayload, validatePublish } from "./publishing";
import { decryptCredential, encryptCredential } from "./credentialEncryption";
import { getMarketplaceAdapter, type MarketplaceAdapter } from "./marketplaceAdapters";
import { createOAuthState, verifyOAuthState } from "./oauthState";

const supported = [PublishChannel.Ebay, PublishChannel.Etsy];
function now() { return new Date().toISOString(); }
function id(prefix: string) { return `${prefix}_${crypto.randomUUID()}`; }
function assertChannel(channel: PublishChannel) { if (!supported.includes(channel)) throw new BadRequestError("Unsupported marketplace channel"); }
function parse<T>(v: string | null | undefined, fallback: T): T { return v ? JSON.parse(v) as T : fallback; }
export function sanitizeMarketplaceError(e: unknown) { return e instanceof Error ? e.message.replace(/[A-Za-z0-9+/=_-]{8,}/g, "[redacted]") : "Marketplace request failed"; }
/**
 * Sprint 62B: statuses an adapter is known to report for a listing that is no longer live.
 * Anything not in this set (including an unrecognized/ambiguous status) is treated as blocking,
 * never as safely terminal - see executePublish's duplicate-active-listing guard.
 */
const TERMINAL_EXTERNAL_LISTING_STATUSES = new Set(["ended", "inactive", "sold", "closed"]);
function isTerminalListingStatus(status: string): boolean { return TERMINAL_EXTERNAL_LISTING_STATUSES.has(String(status ?? "").toLowerCase()); }
function conn(row: typeof marketplaceConnections.$inferSelect): MarketplaceConnection { return { id: row.id, channel: row.channel as PublishChannel, accountLabel: row.accountLabel, externalAccountId: row.externalAccountId ?? undefined, tokenExpiresAt: row.tokenExpiresAt ?? undefined, scopes: parse(row.scopes, []), status: row.status as MarketplaceConnectionStatus, lastError: row.lastError ?? undefined, createdAt: row.createdAt, updatedAt: row.updatedAt }; }
function job(row: typeof publishJobs.$inferSelect): PublishJob { return { id: row.id, productId: row.productId, channel: row.channel as PublishChannel, status: row.status as PublishJobStatus, idempotencyKey: row.idempotencyKey, payloadSnapshot: JSON.parse(row.payloadSnapshot), externalListingId: row.externalListingId ?? undefined, externalListingUrl: row.externalListingUrl ?? undefined, attemptCount: row.attemptCount, lastError: row.lastError ?? undefined, createdAt: row.createdAt, updatedAt: row.updatedAt, completedAt: row.completedAt ?? undefined }; }
function listing(row: typeof externalListings.$inferSelect): ExternalListing { return { id: row.id, productId: row.productId, channel: row.channel as PublishChannel, connectionId: row.connectionId, externalListingId: row.externalListingId, externalListingUrl: row.externalListingUrl ?? undefined, externalStatus: row.externalStatus, payloadSnapshot: JSON.parse(row.payloadSnapshot), publishedAt: row.publishedAt, updatedAt: row.updatedAt }; }
function attempt(row: typeof publishAttempts.$inferSelect): PublishAttempt { return { id: row.id, publishJobId: row.publishJobId, attemptNumber: row.attemptNumber, requestSnapshot: JSON.parse(row.requestSnapshot), responseSnapshot: parse(row.responseSnapshot, undefined), errorCode: row.errorCode ?? undefined, errorMessage: row.errorMessage ?? undefined, createdAt: row.createdAt }; }
export function getAdapter(channel: PublishChannel, adapter?: MarketplaceAdapter) { return adapter ?? getMarketplaceAdapter(channel); }

export async function listConnections(db: DbClient) { return (await db.select().from(marketplaceConnections)).map(conn); }
export async function getConnection(db: DbClient, channel: PublishChannel) { assertChannel(channel); const [r] = await db.select().from(marketplaceConnections).where(eq(marketplaceConnections.channel, channel)); return r ? conn(r) : undefined; }
export async function startConnect(channel: PublishChannel, accountLabel = "Default", adapter?: MarketplaceAdapter) { assertChannel(channel); const state = createOAuthState(channel, accountLabel); return { authorizationUrl: getAdapter(channel, adapter).getAuthorizationUrl(state), state, accountLabel }; }
export async function completeConnect(db: DbClient, channel: PublishChannel, code: string, state: string, _expectedState = "", accountLabel="Default", adapter?: MarketplaceAdapter) { assertChannel(channel); try { accountLabel = verifyOAuthState(state, channel).accountLabel || accountLabel; } catch (e) { throw new BadRequestError(e instanceof Error ? e.message : "OAuth state mismatch"); } const tokens = await getAdapter(channel, adapter).exchangeAuthorizationCode(code); const record = { id: id("conn"), channel, accountLabel, externalAccountId: tokens.externalAccountId, encryptedAccessToken: encryptCredential(tokens.accessToken), encryptedRefreshToken: tokens.refreshToken ? encryptCredential(tokens.refreshToken) : null, tokenExpiresAt: tokens.expiresAt, scopes: JSON.stringify(tokens.scopes ?? []), status: MarketplaceConnectionStatus.Connected, lastError: null, updatedAt: now() }; await db.insert(marketplaceConnections).values({ ...record, createdAt: now() }).onConflictDoUpdate({ target: [marketplaceConnections.channel, marketplaceConnections.accountLabel], set: record }); return (await getConnection(db, channel))!; }
async function active(db: DbClient, channel: PublishChannel) { const [r] = await db.select().from(marketplaceConnections).where(and(eq(marketplaceConnections.channel, channel), eq(marketplaceConnections.status, MarketplaceConnectionStatus.Connected))); if (!r?.encryptedAccessToken) throw new BadRequestError("Marketplace connection is not connected"); if (r.tokenExpiresAt && Date.parse(r.tokenExpiresAt) <= Date.now()) throw new BadRequestError("Marketplace connection is expired"); return r; }
export async function refreshConnection(db: DbClient, channel: PublishChannel, adapter?: MarketplaceAdapter) { const r = await active(db, channel); if (!r.encryptedRefreshToken) throw new BadRequestError("Refresh token is unavailable"); const tokens = await getAdapter(channel, adapter).refreshAccessToken(decryptCredential(r.encryptedRefreshToken)); await db.update(marketplaceConnections).set({ encryptedAccessToken: encryptCredential(tokens.accessToken), encryptedRefreshToken: tokens.refreshToken ? encryptCredential(tokens.refreshToken) : r.encryptedRefreshToken, tokenExpiresAt: tokens.expiresAt, scopes: JSON.stringify(tokens.scopes ?? parse(r.scopes, [])), status: MarketplaceConnectionStatus.Connected, updatedAt: now() }).where(eq(marketplaceConnections.id, r.id)); return (await getConnection(db, channel))!; }
export async function verifyConnection(db: DbClient, channel: PublishChannel, adapter?: MarketplaceAdapter) { const r = await active(db, channel); try { await getAdapter(channel, adapter).verifyConnection(decryptCredential(r.encryptedAccessToken!)); await db.update(marketplaceConnections).set({ lastError: null, updatedAt: now() }).where(eq(marketplaceConnections.id, r.id)); return { ok: true, connection: (await getConnection(db, channel))! }; } catch (e) { const msg = sanitizeMarketplaceError(e); await db.update(marketplaceConnections).set({ status: MarketplaceConnectionStatus.Error, lastError: msg, updatedAt: now() }).where(eq(marketplaceConnections.id, r.id)); return { ok: false, error: msg, connection: (await getConnection(db, channel))! }; } }
export async function disconnect(db: DbClient, channel: PublishChannel) { assertChannel(channel); const [r] = await db.select().from(marketplaceConnections).where(eq(marketplaceConnections.channel, channel)); if (!r) return undefined; await db.update(marketplaceConnections).set({ encryptedAccessToken: null, encryptedRefreshToken: null, status: MarketplaceConnectionStatus.Revoked, updatedAt: now() }).where(eq(marketplaceConnections.id, r.id)); return (await getConnection(db, channel))!; }
export async function executePublish(db: DbClient, productId: string, channel: PublishChannel, key?: string, adapter?: MarketplaceAdapter): Promise<PublishExecutionResult> { assertChannel(channel); const product = await getProductById(db, productId); const validation = validatePublish(product, channel); if (!validation.valid) throw new BadRequestError("Publish validation failed"); const connection = await active(db, channel); const payload = buildPublishPayload(product, product.images, channel); const idem = key ?? `${productId}:${channel}:${crypto.createHash("sha256").update(JSON.stringify(payload)).digest("hex")}`; const [existing] = await db.select().from(publishJobs).where(eq(publishJobs.idempotencyKey, idem)); if (existing) return { job: job(existing), externalListing: existing.externalListingId ? (await listExternalListings(db, productId)).find((l) => l.externalListingId === existing.externalListingId) : undefined };
  const sameChannelListings = await db.select().from(externalListings).where(and(eq(externalListings.productId, productId), eq(externalListings.channel, channel)));
  if (sameChannelListings.some((l) => !isTerminalListingStatus(l.externalStatus))) throw new ConflictError("An active listing already exists for this product on this channel");
  const jid = id("job"); await db.insert(publishJobs).values({ id: jid, productId, channel, status: PublishJobStatus.Processing, idempotencyKey: idem, payloadSnapshot: JSON.stringify(payload), attemptCount: 0, createdAt: now(), updatedAt: now() });
  try { const result = await getAdapter(channel, adapter).createListing(decryptCredential(connection.encryptedAccessToken!), payload); await db.insert(publishAttempts).values({ id: id("att"), publishJobId: jid, attemptNumber: 1, requestSnapshot: JSON.stringify(payload), responseSnapshot: JSON.stringify(result.raw ?? result), createdAt: now() }); const lid = id("ext"); await db.insert(externalListings).values({ id: lid, productId, channel, connectionId: connection.id, externalListingId: result.externalListingId, externalListingUrl: result.externalListingUrl, externalStatus: result.externalStatus, payloadSnapshot: JSON.stringify(payload), publishedAt: now(), updatedAt: now() }).onConflictDoNothing(); await db.update(publishJobs).set({ status: PublishJobStatus.Succeeded, externalListingId: result.externalListingId, externalListingUrl: result.externalListingUrl, attemptCount: 1, completedAt: now(), updatedAt: now() }).where(eq(publishJobs.id, jid)); } catch(e) { const err = getAdapter(channel, adapter).normalizeError(e); await db.insert(publishAttempts).values({ id: id("att"), publishJobId: jid, attemptNumber: 1, requestSnapshot: JSON.stringify(payload), errorCode: err.code, errorMessage: err.message, createdAt: now() }); await db.update(publishJobs).set({ status: err.retryable ? PublishJobStatus.RetryPending : PublishJobStatus.Failed, attemptCount: 1, lastError: err.message, updatedAt: now() }).where(eq(publishJobs.id, jid)); }
  const [r] = await db.select().from(publishJobs).where(eq(publishJobs.id, jid)); return { job: job(r) }; }
export async function listExternalListings(db: DbClient, productId: string) { return (await db.select().from(externalListings).where(eq(externalListings.productId, productId))).map(listing); }
export async function listPublishJobs(db: DbClient, filters: { channel?: PublishChannel; status?: PublishJobStatus; limit?: number; offset?: number } = {}) { const clauses: SQL[] = []; if (filters.channel) clauses.push(eq(publishJobs.channel, filters.channel)); if (filters.status) clauses.push(eq(publishJobs.status, filters.status)); const q = db.select().from(publishJobs).where(clauses.length ? and(...clauses) : undefined).orderBy(desc(publishJobs.createdAt)).limit(Math.min(filters.limit ?? 50, 100)).offset(filters.offset ?? 0); return (await q).map(job); }
export async function getPublishJob(db: DbClient, idv: string) { const [r] = await db.select().from(publishJobs).where(eq(publishJobs.id, idv)); if (!r) throw new NotFoundError("Publish job not found"); const atts = await db.select().from(publishAttempts).where(eq(publishAttempts.publishJobId, idv)); return { job: job(r), attempts: atts.map(attempt) }; }
export async function retryPublishJob(db: DbClient, idv: string, adapter?: MarketplaceAdapter) { const { job: j } = await getPublishJob(db, idv); const max = Number(process.env.MARKETPLACE_PUBLISH_MAX_RETRIES ?? 3); if (j.status !== PublishJobStatus.RetryPending || j.attemptCount >= max) throw new ConflictError("Publish job is not retryable"); const connection = await active(db, j.channel); const attemptNumber = j.attemptCount + 1; try { const result = await getAdapter(j.channel, adapter).createListing(decryptCredential(connection.encryptedAccessToken!), j.payloadSnapshot); await db.insert(publishAttempts).values({ id: id("att"), publishJobId: idv, attemptNumber, requestSnapshot: JSON.stringify(j.payloadSnapshot), responseSnapshot: JSON.stringify(result.raw ?? result), createdAt: now() }); await db.insert(externalListings).values({ id: id("ext"), productId: j.productId, channel: j.channel, connectionId: connection.id, externalListingId: result.externalListingId, externalListingUrl: result.externalListingUrl, externalStatus: result.externalStatus, payloadSnapshot: JSON.stringify(j.payloadSnapshot), publishedAt: now(), updatedAt: now() }).onConflictDoNothing(); await db.update(publishJobs).set({ status: PublishJobStatus.Succeeded, externalListingId: result.externalListingId, externalListingUrl: result.externalListingUrl, attemptCount: attemptNumber, lastError: null, completedAt: now(), updatedAt: now() }).where(eq(publishJobs.id, idv)); } catch (e) { const err = getAdapter(j.channel, adapter).normalizeError(e); await db.insert(publishAttempts).values({ id: id("att"), publishJobId: idv, attemptNumber, requestSnapshot: JSON.stringify(j.payloadSnapshot), errorCode: err.code, errorMessage: err.message, createdAt: now() }); await db.update(publishJobs).set({ status: err.retryable && attemptNumber < max ? PublishJobStatus.RetryPending : PublishJobStatus.Failed, attemptCount: attemptNumber, lastError: err.message, updatedAt: now() }).where(eq(publishJobs.id, idv)); } const { job: updated, attempts } = await getPublishJob(db, idv); return { job: updated, attempts }; }
export async function endExternalListing(db: DbClient, productId: string, listingId: string, adapter?: MarketplaceAdapter) { const [l] = await db.select().from(externalListings).where(and(eq(externalListings.productId, productId), eq(externalListings.id, listingId))); if (!l) throw new NotFoundError("External listing not found"); const c = await active(db, l.channel as PublishChannel); const result = await getAdapter(l.channel as PublishChannel, adapter).endListing(decryptCredential(c.encryptedAccessToken!), l.externalListingId); await db.update(externalListings).set({ externalStatus: result.externalStatus, updatedAt: now() }).where(eq(externalListings.id, l.id)); return { ok: true, externalListingId: l.externalListingId, status: result.externalStatus }; }
