import crypto from "node:crypto";
import { and, desc, eq, like } from "drizzle-orm";
import { MarketplaceOrderStatus, MarketplaceSyncError, MarketplaceSyncStatus, MarketplaceWebhookEventStatus, MarketplaceWebhookEventType, OrderStatus, PaymentProvider, PaymentStatus, PriceCurrency, PublishChannel } from "@noctella/shared";
import type { DbClient } from "../db/client";
import { externalListings, marketplaceConnections, marketplaceImportAttempts, marketplaceOrderItems, marketplaceOrders, marketplaceSyncRuns, marketplaceWebhookEvents, products } from "../db/schema";
import { BadRequestError, ConflictError, NotFoundError } from "./errors";
import { createOrder } from "./orders";
import { createPaymentSession, derivePaymentIdempotencyKey, findPaymentByProviderReference } from "../payments/paymentRepository";
import { decryptCredential } from "./credentialEncryption";
import { getMarketplaceAdapter, type MarketplaceAdapter, type NormalizedMarketplaceOrder } from "./marketplaceAdapters";
import { sanitizeMarketplaceError } from "./marketplacePublishing";

const paid = new Set(["paid", "processing"]);
function now() { return new Date().toISOString(); }
function id(p: string) { return `${p}_${crypto.randomUUID()}`; }
function adapter(channel: PublishChannel, a?: MarketplaceAdapter) { return a ?? getMarketplaceAdapter(channel); }
function parse(v?: string | null) { try { return v ? JSON.parse(v) : undefined; } catch { return undefined; } }
function mapStatus(s: string) { const v = s.toLowerCase(); if (v.includes("cancel")) return MarketplaceOrderStatus.Cancelled; if (v.includes("refund")) return MarketplaceOrderStatus.Refunded; if (v.includes("ship")) return MarketplaceOrderStatus.Shipped; if (v.includes("process")) return MarketplaceOrderStatus.Processing; if (v.includes("paid")) return MarketplaceOrderStatus.Paid; return MarketplaceOrderStatus.Pending; }
function mapListing(s: string) { const v = s.toLowerCase(); if (["active", "published", "live"].includes(v)) return "active"; if (["ended", "inactive", "sold", "closed"].includes(v)) return "ended"; return v || "unknown"; }
function classify(e: unknown) { const raw = e instanceof Error ? e.message : String(e); const msg = sanitizeMarketplaceError(e); const lower = raw.toLowerCase(); const type = lower.includes("currency") ? MarketplaceSyncError.Currency : lower.includes("stock") || lower.includes("insufficient") ? MarketplaceSyncError.Stock : lower.includes("validation") ? MarketplaceSyncError.Validation : lower.includes("permanent") ? MarketplaceSyncError.Permanent : lower.includes("not found") ? MarketplaceSyncError.NotFound : MarketplaceSyncError.Temporary; const retryable = [MarketplaceSyncError.Temporary, MarketplaceSyncError.Timeout, MarketplaceSyncError.RateLimit, MarketplaceSyncError.Stock].includes(type); return { type, message: msg, retryable }; }
async function active(db: DbClient, channel: PublishChannel) { const [c] = await db.select().from(marketplaceConnections).where(and(eq(marketplaceConnections.channel, channel), eq(marketplaceConnections.status, "connected"))); if (!c?.encryptedAccessToken) throw new BadRequestError("Marketplace connection is not connected"); return c; }
async function run<T>(db: DbClient, channel: PublishChannel, type: string, body: () => Promise<T>) { const t = now(), rid = id("sync"); await db.insert(marketplaceSyncRuns).values({ id: rid, channel, syncType: type, status: MarketplaceSyncStatus.Processing, startedAt: t, createdAt: t, updatedAt: t }); try { const out = await body(); await db.update(marketplaceSyncRuns).set({ status: MarketplaceSyncStatus.Succeeded, completedAt: now(), processedCount: 1, successCount: 1, updatedAt: now() }).where(eq(marketplaceSyncRuns.id, rid)); return out; } catch (e) { await db.update(marketplaceSyncRuns).set({ status: MarketplaceSyncStatus.Failed, completedAt: now(), processedCount: 1, failureCount: 1, lastError: sanitizeMarketplaceError(e), updatedAt: now() }).where(eq(marketplaceSyncRuns.id, rid)); throw e; } }
async function attempt(db: DbClient, marketplaceOrderId: string, attemptNumber: number, status: "succeeded" | "failed", err?: { type: MarketplaceSyncError; message: string; retryable: boolean }) { await db.insert(marketplaceImportAttempts).values({ id: id("matt"), marketplaceOrderId, attemptNumber, status, errorType: err?.type, errorMessage: err?.message, retryable: err?.retryable ?? false, createdAt: now() }); await db.update(marketplaceOrders).set({ importStatus: status, attemptCount: attemptNumber, lastError: err?.message ?? null, lastErrorType: err?.type ?? null, retryable: err?.retryable ?? false, updatedAt: now() }).where(eq(marketplaceOrders.id, marketplaceOrderId)); }

export async function importMarketplaceOrder(db: DbClient, channel: PublishChannel, externalOrderId: string, a?: MarketplaceAdapter) { return run(db, channel, "order_import", async () => { const [existing] = await db.select().from(marketplaceOrders).where(and(eq(marketplaceOrders.channel, channel), eq(marketplaceOrders.externalOrderId, externalOrderId))); if (existing?.internalOrderId) return getMarketplaceOrder(db, existing.id); if (existing && !existing.retryable) throw new ConflictError("Marketplace order is not retryable"); const conn = await active(db, channel); const order = await adapter(channel, a).fetchOrderById(decryptCredential(conn.encryptedAccessToken!), externalOrderId); return persistOrder(db, channel, conn.id, order); }); }

export async function persistOrder(db: DbClient, channel: PublishChannel, connectionId: string, order: NormalizedMarketplaceOrder) {
  const [existing] = await db.select().from(marketplaceOrders).where(and(eq(marketplaceOrders.channel, channel), eq(marketplaceOrders.externalOrderId, order.externalOrderId)));
  if (existing?.internalOrderId) return getMarketplaceOrder(db, existing.id);
  const status = mapStatus(order.status); const t = now(); const marketplaceOrderId = existing?.id ?? id("mord");
  const matched: { productId?: string; item: NormalizedMarketplaceOrder["items"][number] }[] = [];
  for (const item of order.items) { let productId: string | undefined; if (item.externalListingId) { const [l] = await db.select().from(externalListings).where(and(eq(externalListings.channel, channel), eq(externalListings.externalListingId, item.externalListingId))); productId = l?.productId; } if (!productId && item.sku) { const [p] = await db.select().from(products).where(eq(products.sku, item.sku)); productId = p?.id; } matched.push({ productId, item }); }
  if (!existing) db.transaction((tx) => { tx.insert(marketplaceOrders).values({ id: marketplaceOrderId, channel, externalOrderId: order.externalOrderId, externalOrderNumber: order.externalOrderNumber, marketplaceConnectionId: connectionId, status, importStatus: "pending", attemptCount: 0, retryable: true, currency: order.currency, subtotal: order.subtotal, shipping: order.shipping, tax: order.tax, total: order.total, buyerEmail: order.buyerEmail, buyerName: order.buyerName, shippingAddressSnapshot: JSON.stringify(order.shippingAddress ?? null), billingAddressSnapshot: JSON.stringify(order.billingAddress ?? null), rawPayloadSnapshot: JSON.stringify(order.raw ?? order), orderedAt: order.orderedAt, importedAt: t, updatedAt: t }).run(); for (const m of matched) tx.insert(marketplaceOrderItems).values({ id: id("mitem"), marketplaceOrderId, externalOrderItemId: m.item.externalOrderItemId, externalListingId: m.item.externalListingId, productId: m.productId, sku: m.item.sku, titleSnapshot: m.item.title, quantity: m.item.quantity, unitPrice: m.item.unitPrice, lineTotal: m.item.lineTotal, createdAt: t }).run(); });
  const attemptNumber = (existing?.attemptCount ?? 0) + 1;
  try {
    if (order.currency !== "EUR") throw new BadRequestError(`${MarketplaceSyncError.Currency}: unsupported currency`);
    if (matched.some((m) => m.item.quantity !== 1)) throw new BadRequestError("Validation: marketplace item quantities greater than 1 are not supported yet");
    if (status === MarketplaceOrderStatus.Paid || paid.has(order.status.toLowerCase())) {
      const productItems = matched.filter((m) => m.productId).map((m) => ({ productId: m.productId!, quantity: 1 as const }));
      if (productItems.length) { const orderDraftId = `marketplace:${channel}:${order.externalOrderId}`; const paymentReference = `${channel}:${order.externalOrderId}`; if (!(await findPaymentByProviderReference(db, PaymentProvider.Stripe, paymentReference))) { await createPaymentSession(db, { provider: PaymentProvider.Stripe, providerReference: paymentReference, status: PaymentStatus.Paid, amount: order.subtotal, currency: "EUR", idempotencyKey: derivePaymentIdempotencyKey(PaymentProvider.Stripe, orderDraftId) }); } const internal = await createOrder(db, { orderDraftId, guestEmail: order.buyerEmail ?? "marketplace@example.invalid", status: OrderStatus.Processing, paymentStatus: PaymentStatus.Paid, paymentProvider: PaymentProvider.Stripe, paymentReference, currency: PriceCurrency.Eur, billingAddress: { fullName: order.buyerName ?? "Marketplace buyer", line1: "Marketplace", city: "Marketplace", postalCode: "00000", country: "Unknown" }, shippingAddress: { fullName: order.buyerName ?? "Marketplace buyer", line1: "Marketplace", city: "Marketplace", postalCode: "00000", country: "Unknown" }, subtotalAmount: order.subtotal, totalAmount: order.subtotal, notes: `Imported from ${channel} order ${order.externalOrderId}`, items: productItems }); await db.update(marketplaceOrders).set({ internalOrderId: internal.id, status: MarketplaceOrderStatus.Processing, updatedAt: now() }).where(eq(marketplaceOrders.id, marketplaceOrderId)); }
    }
    await attempt(db, marketplaceOrderId, attemptNumber, "succeeded");
  } catch (e) { const err = classify(e); await attempt(db, marketplaceOrderId, attemptNumber, "failed", err); throw e; }
  return getMarketplaceOrder(db, marketplaceOrderId);
}

export async function processWebhook(db: DbClient, channel: PublishChannel, raw: Buffer, headers: Record<string, string | string[] | undefined>, a?: MarketplaceAdapter) { const ad = adapter(channel, a); const valid = await ad.verifyWebhookSignature(raw, headers); if (!valid) throw new BadRequestError(`${MarketplaceSyncError.Signature}: invalid webhook signature`); const evt = await ad.parseWebhookEvent(raw, headers); const t = now(); const [existing] = await db.select().from(marketplaceWebhookEvents).where(and(eq(marketplaceWebhookEvents.channel, channel), eq(marketplaceWebhookEvents.externalEventId, evt.externalEventId))); if (existing) return { event: existing, duplicate: true }; await db.insert(marketplaceWebhookEvents).values({ id: id("wh"), channel, externalEventId: evt.externalEventId, eventType: evt.eventType, status: MarketplaceWebhookEventStatus.Processing, signatureValid: true, payloadSnapshot: JSON.stringify(evt.payload), attemptCount: 1, receivedAt: t, createdAt: t, updatedAt: t }); const [row] = await db.select().from(marketplaceWebhookEvents).where(and(eq(marketplaceWebhookEvents.channel, channel), eq(marketplaceWebhookEvents.externalEventId, evt.externalEventId))); try { if (![MarketplaceWebhookEventType.OrderCreated, MarketplaceWebhookEventType.OrderPaid, MarketplaceWebhookEventType.ListingUpdated].includes(evt.eventType as MarketplaceWebhookEventType)) { await db.update(marketplaceWebhookEvents).set({ status: MarketplaceWebhookEventStatus.Ignored, processedAt: now(), updatedAt: now() }).where(eq(marketplaceWebhookEvents.id, row.id)); return { event: row }; } if (evt.externalOrderId) await importMarketplaceOrder(db, channel, evt.externalOrderId, a); if (evt.externalListingId) { const [listing] = await db.select().from(externalListings).where(and(eq(externalListings.channel, channel), eq(externalListings.externalListingId, evt.externalListingId))); if (listing) await syncExternalListing(db, listing.id, a); } await db.update(marketplaceWebhookEvents).set({ status: MarketplaceWebhookEventStatus.Processed, processedAt: now(), updatedAt: now() }).where(eq(marketplaceWebhookEvents.id, row.id)); return { event: row }; } catch (e) { await db.update(marketplaceWebhookEvents).set({ status: MarketplaceWebhookEventStatus.Failed, lastError: sanitizeMarketplaceError(e), processedAt: now(), updatedAt: now() }).where(eq(marketplaceWebhookEvents.id, row.id)); throw e; } }

export async function syncExternalListing(db: DbClient, listingId: string, a?: MarketplaceAdapter) { const [l] = await db.select().from(externalListings).where(eq(externalListings.id, listingId)); if (!l) throw new NotFoundError("External listing not found"); return run(db, l.channel as PublishChannel, "listing_status_sync", async () => { const c = await active(db, l.channel as PublishChannel); const result = await adapter(l.channel as PublishChannel, a).fetchListingStatus(decryptCredential(c.encryptedAccessToken!), l.externalListingId); const status = mapListing(result.externalStatus); if (status !== l.externalStatus) await db.update(externalListings).set({ externalStatus: status, updatedAt: now() }).where(eq(externalListings.id, l.id)); return { listingId: l.id, status, changed: status !== l.externalStatus }; }); }
export async function listExternalListingsForAdmin(db: DbClient, q: any) { const f = []; if (q.channel) f.push(eq(externalListings.channel, q.channel)); if (q.status) f.push(eq(externalListings.externalStatus, q.status)); if (q.productId) f.push(eq(externalListings.productId, q.productId)); const pageSize = Math.min(Number(q.pageSize ?? 20), 100); const rows = await db.select().from(externalListings).where(f.length ? and(...f) : undefined).orderBy(desc(externalListings.updatedAt)).limit(pageSize).offset((Number(q.page ?? 1) - 1) * pageSize); return { items: rows, page: Number(q.page ?? 1), pageSize }; }
export async function getExternalListing(db: DbClient, idv: string) { const [r] = await db.select().from(externalListings).where(eq(externalListings.id, idv)); if (!r) throw new NotFoundError("External listing not found"); return r; }
export async function listMarketplaceOrders(db: DbClient, q: any) { const f = []; if (q.channel) f.push(eq(marketplaceOrders.channel, q.channel)); if (q.status) f.push(eq(marketplaceOrders.status, q.status)); if (q.importStatus) f.push(eq(marketplaceOrders.importStatus, q.importStatus)); if (q.search) f.push(like(marketplaceOrders.externalOrderNumber, `%${q.search}%`)); const pageSize = Math.min(Number(q.pageSize ?? 20), 100); const rows = await db.select().from(marketplaceOrders).where(f.length ? and(...f) : undefined).orderBy(desc(marketplaceOrders.orderedAt)).limit(pageSize).offset((Number(q.page ?? 1) - 1) * pageSize); return { items: rows.map((r) => ({ ...r, rawPayloadSnapshot: parse(r.rawPayloadSnapshot) })), page: Number(q.page ?? 1), pageSize }; }
export async function getMarketplaceOrder(db: DbClient, idv: string) { const [r] = await db.select().from(marketplaceOrders).where(eq(marketplaceOrders.id, idv)); if (!r) throw new NotFoundError("Marketplace order not found"); const items = await db.select().from(marketplaceOrderItems).where(eq(marketplaceOrderItems.marketplaceOrderId, idv)); const attempts = await db.select().from(marketplaceImportAttempts).where(eq(marketplaceImportAttempts.marketplaceOrderId, idv)).orderBy(desc(marketplaceImportAttempts.attemptNumber)); return { ...r, rawPayloadSnapshot: parse(r.rawPayloadSnapshot), items, attempts }; }
export async function retryMarketplaceOrder(db: DbClient, idv: string, a?: MarketplaceAdapter) { const o = await getMarketplaceOrder(db, idv); const max = Number(process.env.MARKETPLACE_IMPORT_MAX_RETRIES ?? 3); if (o.internalOrderId || !o.retryable || o.attemptCount >= max) throw new ConflictError("Marketplace order is not retryable"); return importMarketplaceOrder(db, o.channel as PublishChannel, o.externalOrderId, a); }
export async function listSyncRuns(db: DbClient, q: any) { const f = []; if (q.channel) f.push(eq(marketplaceSyncRuns.channel, q.channel)); if (q.status) f.push(eq(marketplaceSyncRuns.status, q.status)); const rows = await db.select().from(marketplaceSyncRuns).where(f.length ? and(...f) : undefined).orderBy(desc(marketplaceSyncRuns.startedAt)).limit(Math.min(Number(q.pageSize ?? 20), 100)); return { items: rows }; }
export async function getSyncRun(db: DbClient, idv: string) { const [r] = await db.select().from(marketplaceSyncRuns).where(eq(marketplaceSyncRuns.id, idv)); if (!r) throw new NotFoundError("Sync run not found"); return r; }
export async function listWebhookEvents(db: DbClient, q: any) { const f = []; if (q.channel) f.push(eq(marketplaceWebhookEvents.channel, q.channel)); if (q.status) f.push(eq(marketplaceWebhookEvents.status, q.status)); return { items: await db.select().from(marketplaceWebhookEvents).where(f.length ? and(...f) : undefined).orderBy(desc(marketplaceWebhookEvents.receivedAt)).limit(50) }; }
