import type Database from "better-sqlite3";
import { OutboxEventStatus, type OutboxAttempt, type OutboxEvent, type OutboxRepository } from "./outbox";

function parse(row: any): OutboxEvent {
  return { id: row.id, eventType: row.event_type, aggregateType: row.aggregate_type, aggregateId: row.aggregate_id, idempotencyKey: row.idempotency_key, payload: JSON.parse(row.payload), status: row.status, attemptCount: row.attempt_count, maxAttempts: row.max_attempts, availableAt: row.available_at, lockedAt: row.locked_at, lockedBy: row.locked_by, lastErrorCode: row.last_error_code, lastErrorMessage: row.last_error_message, createdAt: row.created_at, updatedAt: row.updated_at, completedAt: row.completed_at, deadLetteredAt: row.dead_lettered_at };
}
function attempt(row: any): OutboxAttempt { return { id: row.id, outboxEventId: row.outbox_event_id, attemptNumber: row.attempt_number, startedAt: row.started_at, completedAt: row.completed_at, result: row.result, safeErrorCode: row.safe_error_code, safeErrorMessage: row.safe_error_message }; }
function json(payload: Record<string, unknown> | string) { return typeof payload === "string" ? payload : JSON.stringify(payload); }

export class SqliteOutboxRepository implements OutboxRepository {
  constructor(private readonly sqlite: Database.Database) {}
  async create(input: Omit<OutboxEvent,"status"|"attemptCount"|"createdAt"|"updatedAt"> & Partial<Pick<OutboxEvent,"status"|"attemptCount"|"createdAt"|"updatedAt">>): Promise<OutboxEvent> {
    const existing = await this.findByIdempotencyKey(input.idempotencyKey); if (existing) return existing;
    const now = input.createdAt ?? new Date().toISOString();
    this.sqlite.prepare(`INSERT INTO outbox_events (id,event_type,aggregate_type,aggregate_id,idempotency_key,payload,status,attempt_count,max_attempts,available_at,locked_at,locked_by,last_error_code,last_error_message,created_at,updated_at,completed_at,dead_lettered_at) VALUES (@id,@eventType,@aggregateType,@aggregateId,@idempotencyKey,@payload,@status,@attemptCount,@maxAttempts,@availableAt,@lockedAt,@lockedBy,@lastErrorCode,@lastErrorMessage,@createdAt,@updatedAt,@completedAt,@deadLetteredAt)`).run({ ...input, payload: json(input.payload), status: input.status ?? OutboxEventStatus.Pending, attemptCount: input.attemptCount ?? 0, createdAt: now, updatedAt: now, aggregateId: input.aggregateId ?? null, lockedAt: input.lockedAt ?? null, lockedBy: input.lockedBy ?? null, lastErrorCode: input.lastErrorCode ?? null, lastErrorMessage: input.lastErrorMessage ?? null, completedAt: input.completedAt ?? null, deadLetteredAt: input.deadLetteredAt ?? null });
    return (await this.getById(input.id))!;
  }
  async getById(id: string) { const row = this.sqlite.prepare("SELECT * FROM outbox_events WHERE id=?").get(id); return row ? parse(row) : undefined; }
  async findByIdempotencyKey(key: string) { const row = this.sqlite.prepare("SELECT * FROM outbox_events WHERE idempotency_key=?").get(key); return row ? parse(row) : undefined; }
  async listPending(now: string, limit: number) { return (this.sqlite.prepare("SELECT * FROM outbox_events WHERE status IN ('Pending','RetryPending') AND available_at <= ? AND locked_by IS NULL ORDER BY available_at ASC, created_at ASC, id ASC LIMIT ?").all(now, limit) as any[]).map(parse); }
  async claimNextBatch(workerId: string, now: string, limit: number) { const tx = this.sqlite.transaction(() => { const rows = this.sqlite.prepare("SELECT id FROM outbox_events WHERE status IN ('Pending','RetryPending') AND available_at <= ? AND locked_by IS NULL ORDER BY available_at ASC, created_at ASC, id ASC LIMIT ?").all(now, limit) as Array<{id:string}>; for (const row of rows) this.sqlite.prepare("UPDATE outbox_events SET status='Processing', locked_by=?, locked_at=?, updated_at=? WHERE id=? AND locked_by IS NULL AND status IN ('Pending','RetryPending')").run(workerId, now, now, row.id); return rows.map((r)=>this.sqlite.prepare("SELECT * FROM outbox_events WHERE id=? AND locked_by=?").get(r.id, workerId)).filter(Boolean).map(parse); }); return tx(); }
  async markProcessing(id:string, workerId:string, now:string){ this.sqlite.prepare("UPDATE outbox_events SET status='Processing', locked_by=?, locked_at=?, updated_at=? WHERE id=?").run(workerId,now,now,id); }
  async markSucceeded(id:string, now:string){ this.sqlite.prepare("UPDATE outbox_events SET status='Succeeded', locked_by=NULL, locked_at=NULL, completed_at=?, updated_at=? WHERE id=?").run(now,now,id); }
  async markRetryPending(id:string, now:string, availableAt:string, code:string, message:string){ this.sqlite.prepare("UPDATE outbox_events SET status='RetryPending', locked_by=NULL, locked_at=NULL, available_at=?, last_error_code=?, last_error_message=?, updated_at=? WHERE id=?").run(availableAt,code,message,now,id); }
  async markFailed(id:string, now:string, code:string, message:string){ this.sqlite.prepare("UPDATE outbox_events SET status='Failed', last_error_code=?, last_error_message=?, updated_at=? WHERE id=?").run(code,message,now,id); }
  async markDeadLetter(id:string, now:string, code:string, message:string){ this.sqlite.prepare("UPDATE outbox_events SET status='DeadLetter', locked_by=NULL, locked_at=NULL, dead_lettered_at=?, last_error_code=?, last_error_message=?, updated_at=? WHERE id=?").run(now,code,message,now,id); }
  async releaseStaleLocks(now:string, olderThan:string){ return this.sqlite.prepare("UPDATE outbox_events SET status='RetryPending', locked_by=NULL, locked_at=NULL, updated_at=? WHERE status='Processing' AND locked_at < ?").run(now,olderThan).changes; }
  async appendAttempt(a:OutboxAttempt){ this.sqlite.prepare("INSERT INTO outbox_attempts (id,outbox_event_id,attempt_number,started_at,completed_at,result,safe_error_code,safe_error_message) VALUES (?,?,?,?,?,?,?,?)").run(a.id,a.outboxEventId,a.attemptNumber,a.startedAt,a.completedAt??null,a.result,a.safeErrorCode??null,a.safeErrorMessage??null); }
  async listAttempts(eventId:string){ return (this.sqlite.prepare("SELECT * FROM outbox_attempts WHERE outbox_event_id=? ORDER BY attempt_number ASC").all(eventId) as any[]).map(attempt); }
}

export interface PostgresQueryAdapter { query<T=any>(sql: string, params?: unknown[]): Promise<{ rows: T[]; rowCount?: number | null }> }
export class PostgresOutboxRepository implements OutboxRepository {
  constructor(private readonly db: PostgresQueryAdapter) {}
  async create(input: any) { const existing=await this.findByIdempotencyKey(input.idempotencyKey); if(existing) return existing; const now=input.createdAt??new Date().toISOString(); await this.db.query(`INSERT INTO outbox_events (id,event_type,aggregate_type,aggregate_id,idempotency_key,payload,status,attempt_count,max_attempts,available_at,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)`,[input.id,input.eventType,input.aggregateType,input.aggregateId??null,input.idempotencyKey,input.payload,input.status??OutboxEventStatus.Pending,input.attemptCount??0,input.maxAttempts,input.availableAt,now,now]); return (await this.getById(input.id))!; }
  async getById(id:string){ const r=await this.db.query("SELECT * FROM outbox_events WHERE id=$1",[id]); return r.rows[0]?parse(r.rows[0]):undefined; }
  async findByIdempotencyKey(k:string){ const r=await this.db.query("SELECT * FROM outbox_events WHERE idempotency_key=$1",[k]); return r.rows[0]?parse(r.rows[0]):undefined; }
  async listPending(now:string,limit:number){ const r=await this.db.query("SELECT * FROM outbox_events WHERE status IN ('Pending','RetryPending') AND available_at <= $1 AND locked_by IS NULL ORDER BY available_at ASC, created_at ASC, id ASC LIMIT $2",[now,limit]); return r.rows.map(parse); }
  async claimNextBatch(w:string,n:string,l:number){ const r=await this.db.query("UPDATE outbox_events SET status='Processing', locked_by=$1, locked_at=$2, updated_at=$2 WHERE id IN (SELECT id FROM outbox_events WHERE status IN ('Pending','RetryPending') AND available_at <= $2 AND locked_by IS NULL ORDER BY available_at ASC, created_at ASC, id ASC LIMIT $3 FOR UPDATE SKIP LOCKED) RETURNING *",[w,n,l]); return r.rows.map(parse); }
  async markProcessing(id:string,w:string,n:string){await this.db.query("UPDATE outbox_events SET status='Processing', locked_by=$1, locked_at=$2, updated_at=$2 WHERE id=$3",[w,n,id]);}
  async markSucceeded(id:string,n:string){await this.db.query("UPDATE outbox_events SET status='Succeeded', locked_by=NULL, locked_at=NULL, completed_at=$1, updated_at=$1 WHERE id=$2",[n,id]);}
  async markRetryPending(id:string,n:string,a:string,c:string,m:string){await this.db.query("UPDATE outbox_events SET status='RetryPending', locked_by=NULL, locked_at=NULL, available_at=$1, last_error_code=$2, last_error_message=$3, updated_at=$4 WHERE id=$5",[a,c,m,n,id]);}
  async markFailed(id:string,n:string,c:string,m:string){await this.db.query("UPDATE outbox_events SET status='Failed', last_error_code=$1, last_error_message=$2, updated_at=$3 WHERE id=$4",[c,m,n,id]);}
  async markDeadLetter(id:string,n:string,c:string,m:string){await this.db.query("UPDATE outbox_events SET status='DeadLetter', locked_by=NULL, locked_at=NULL, dead_lettered_at=$1, last_error_code=$2, last_error_message=$3, updated_at=$4 WHERE id=$5",[n,c,m,n,id]);}
  async releaseStaleLocks(n:string,o:string){const r=await this.db.query("UPDATE outbox_events SET status='RetryPending', locked_by=NULL, locked_at=NULL, updated_at=$1 WHERE status='Processing' AND locked_at < $2",[n,o]); return r.rowCount??0;}
  async appendAttempt(a:OutboxAttempt){await this.db.query("INSERT INTO outbox_attempts (id,outbox_event_id,attempt_number,started_at,completed_at,result,safe_error_code,safe_error_message) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)",[a.id,a.outboxEventId,a.attemptNumber,a.startedAt,a.completedAt??null,a.result,a.safeErrorCode??null,a.safeErrorMessage??null]);}
  async listAttempts(id:string){const r=await this.db.query("SELECT * FROM outbox_attempts WHERE outbox_event_id=$1 ORDER BY attempt_number ASC",[id]); return r.rows.map(attempt);}
}
