import { randomUUID } from "node:crypto";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";
import { AiIntakePhotoFinalizationDestinationConflictError, BadRequestError } from "./errors";

export const PRODUCT_PHOTO_MAX_BYTES = 10 * 1024 * 1024;
export const PRODUCT_PHOTO_MIME_TYPES = ["image/jpeg", "image/png", "image/webp"] as const;

export interface StoredProductPhoto {
  filename: string;
  url: string;
  thumbnailUrl: string;
  mimeType: string;
  sizeBytes: number;
  width: number;
  height: number;
}

export interface PhotoStorage {
  saveProductPhoto(file: { buffer: Buffer; mimetype: string; size: number }): Promise<StoredProductPhoto>;
  deleteProductPhoto(photo: { url: string; thumbnailUrl: string }): Promise<void>;
}

const uploadRoot = process.env.PRODUCT_PHOTO_DIR ?? path.resolve(process.cwd(), "uploads/product-photos");
const publicBase = "/images/product-photos";

function validateUpload(file: { mimetype: string; size: number }) {
  if (!PRODUCT_PHOTO_MIME_TYPES.includes(file.mimetype as (typeof PRODUCT_PHOTO_MIME_TYPES)[number])) {
    throw new BadRequestError("Product photos must be JPEG, PNG, or WebP images");
  }
  if (file.size > PRODUCT_PHOTO_MAX_BYTES) {
    throw new BadRequestError("Product photos must be 10 MB or smaller");
  }
}

function safeFilename(suffix: string) {
  return `${Date.now()}-${randomUUID()}${suffix}`;
}

function filenameFromUrl(url: string) {
  if (!url.startsWith(`${publicBase}/`)) return undefined;
  const filename = path.basename(url);
  return /^[a-zA-Z0-9._-]+$/.test(filename) ? filename : undefined;
}

/**
 * Sprint 95: path-containment/traversal guard for a caller-supplied
 * deterministic storage key, matching the established safeJoin convention
 * (productPhotoStorageWorkflow.ts) already used for this exact storage root.
 */
function assertSafeDeterministicKey(key: string): void {
  if (!key || !/^[a-zA-Z0-9._-]+$/.test(key) || key.includes("..")) {
    throw new BadRequestError("Invalid canonical photo storage key");
  }
}

interface ProcessedProductPhoto {
  mainBytes: Buffer;
  thumbBytes: Buffer;
  width: number;
  height: number;
}

/**
 * Sprint 95: the Sharp processing core shared by both the random-filename
 * upload path (saveProductPhoto) and the deterministic-filename finalization
 * path (writeDeterministicProductPhoto) - one implementation of the main
 * (2000x2000 inside) + thumbnail (400x400 inside) WebP transform, never
 * duplicated.
 */
async function processProductPhoto(file: { buffer: Buffer; mimetype: string; size: number }): Promise<ProcessedProductPhoto> {
  validateUpload(file);
  const image = sharp(file.buffer, { failOn: "error" }).rotate();
  const metadata = await image.metadata();
  if (!metadata.width || !metadata.height) throw new BadRequestError("Uploaded file is not a valid image");

  const mainBytes = await image.clone().resize({ width: 2000, height: 2000, fit: "inside", withoutEnlargement: true }).webp({ quality: 86 }).toBuffer();
  const thumbBytes = await image.clone().resize({ width: 400, height: 400, fit: "inside", withoutEnlargement: true }).webp({ quality: 82 }).toBuffer();
  const output = await sharp(mainBytes).metadata();
  return { mainBytes, thumbBytes, width: output.width ?? metadata.width, height: output.height ?? metadata.height };
}

/**
 * Sprint 95: writes generated bytes to an absolute destination path
 * idempotently - if the destination is absent, writes it; if present with
 * byte-identical content, treats it as a successful idempotent no-op (a safe
 * retry after a crash between preparing files and committing the DB
 * transaction); if present with different content, throws a deterministic
 * conflict rather than silently overwriting it. Never deletes anything.
 */
async function writeIdempotent(destPath: string, bytes: Buffer, destinationKey: string): Promise<void> {
  let existing: Buffer | null = null;
  try {
    existing = await readFile(destPath);
  } catch (err: any) {
    if (err?.code !== "ENOENT") throw err;
  }
  if (existing === null) {
    await writeFile(destPath, bytes);
    return;
  }
  if (Buffer.compare(existing, bytes) === 0) return;
  throw new AiIntakePhotoFinalizationDestinationConflictError(
    `Canonical photo destination "${destinationKey}" already exists with different content.`,
  );
}

export interface DeterministicProductPhotoInput {
  buffer: Buffer;
  mimetype: string;
  size: number;
  /** Caller-supplied, server-derived (e.g. "<productId>-<productPhotoId>.webp") - never client input. */
  mainStorageKey: string;
  thumbnailStorageKey: string;
}

export interface DeterministicProductPhotoResult {
  mainStorageKey: string;
  thumbnailStorageKey: string;
  url: string;
  thumbnailUrl: string;
  mimeType: string;
  sizeBytes: number;
  width: number;
  height: number;
}

/**
 * Sprint 95: writes a ProductPhoto's main+thumbnail files to the same
 * canonical uploads/product-photos root as saveProductPhoto, but at
 * caller-supplied deterministic destination keys instead of a fresh
 * Date.now()/randomUUID name - reuses processProductPhoto for identical
 * Sharp transformations, MIME handling, and metadata extraction, and
 * writeIdempotent for safe, non-destructive retry behavior. Never touches
 * the staged intake-photo source file.
 */
export async function writeDeterministicProductPhoto(input: DeterministicProductPhotoInput): Promise<DeterministicProductPhotoResult> {
  assertSafeDeterministicKey(input.mainStorageKey);
  assertSafeDeterministicKey(input.thumbnailStorageKey);
  const { mainBytes, thumbBytes, width, height } = await processProductPhoto(input);
  await mkdir(uploadRoot, { recursive: true });

  const mainPath = path.join(uploadRoot, input.mainStorageKey);
  const thumbPath = path.join(uploadRoot, input.thumbnailStorageKey);
  await writeIdempotent(mainPath, mainBytes, input.mainStorageKey);
  await writeIdempotent(thumbPath, thumbBytes, input.thumbnailStorageKey);

  return {
    mainStorageKey: input.mainStorageKey,
    thumbnailStorageKey: input.thumbnailStorageKey,
    url: `${publicBase}/${input.mainStorageKey}`,
    thumbnailUrl: `${publicBase}/${input.thumbnailStorageKey}`,
    mimeType: "image/webp",
    sizeBytes: input.size,
    width,
    height,
  };
}

export class LocalPhotoStorage implements PhotoStorage {
  async saveProductPhoto(file: { buffer: Buffer; mimetype: string; size: number }): Promise<StoredProductPhoto> {
    const { mainBytes, thumbBytes, width, height } = await processProductPhoto(file);
    await mkdir(uploadRoot, { recursive: true });

    const base = safeFilename("").replace(/[^a-zA-Z0-9-]/g, "");
    const filename = `${base}.webp`;
    const thumbFilename = `${base}-thumb.webp`;
    await writeFile(path.join(uploadRoot, filename), mainBytes);
    await writeFile(path.join(uploadRoot, thumbFilename), thumbBytes);

    return {
      filename,
      url: `${publicBase}/${filename}`,
      thumbnailUrl: `${publicBase}/${thumbFilename}`,
      mimeType: "image/webp",
      sizeBytes: file.size,
      width,
      height,
    };
  }

  async deleteProductPhoto(photo: { url: string; thumbnailUrl: string }): Promise<void> {
    await Promise.all([photo.url, photo.thumbnailUrl].map(async (url) => {
      const filename = filenameFromUrl(url);
      if (filename) await rm(path.join(uploadRoot, filename), { force: true });
    }));
  }
}

export const photoStorage = new LocalPhotoStorage();
export const productPhotoStaticRoot = uploadRoot;
export const productPhotoStaticPath = publicBase;
