import { randomUUID } from "node:crypto";
import { and, desc, eq, sql } from "drizzle-orm";
import { BackgroundJobType, MarketplaceConnectionStatus, OrderStatus, PriceCurrency, PublishChannel, RefundStatus, RefundType, ReturnResolution, ReturnStatus, ReturnStockDisposition, StockMovementType } from "@noctella/shared";
import type { DbClient } from "../db/client";
import { orderItems, orders, marketplaceConnections, marketplaceOrders, refundAllocations, refundAttempts, refunds, returnEvents, returnItems, returnRequests, saleFinancials, saleReversals } from "../db/schema";
import { BadRequestError, NotFoundError } from "./errors";
import { applyStockMovementSync } from "./stockMovements";
import { enqueueProductStockSync } from "./stockSync";
import { enqueueJob, sanitizeError } from "./backgroundJobs";
import { decryptCredential } from "./credentialEncryption";
import { getMarketplaceAdapter, type MarketplaceAdapter } from "./marketplaceAdapters";

type AdapterResolver = (channel: PublishChannel | string) => MarketplaceAdapter;
let adapterResolver: AdapterResolver = (channel) => getMarketplaceAdapter(channel as PublishChannel);
export function setReturnMarketplaceAdapterResolver(resolver?: AdapterResolver) { adapterResolver = resolver ?? ((channel) => getMarketplaceAdapter(channel as PublishChannel)); }
function now() { return new Date().toISOString(); }
function clean(error: unknown) { return sanitizeError(error).message; }
async function event(db: DbClient | any, returnRequestId: string, eventType: string, previousStatus?: string | null, newStatus?: string | null, payload?: unknown) { await db.insert(returnEvents).values({ id: randomUUID(), returnRequestId, eventType, previousStatus: previousStatus ?? undefined, newStatus: newStatus ?? undefined, payloadSnapshot: JSON.stringify(payload ?? {}), createdAt: now() }).run(); }
async function requireOrder(db: DbClient, orderId: string) { const [order] = await db.select().from(orders).where(eq(orders.id, orderId)); if (!order) throw new NotFoundError("Order not found"); if (![OrderStatus.Completed, OrderStatus.Shipped].includes(order.status as OrderStatus)) throw new BadRequestError("Only fulfilled or completed orders can be returned"); return order; }

export async function createReturnRequest(db: DbClient, input: any) {
  const order = await requireOrder(db, input.orderId);
  if (input.externalReturnId && input.channel) { const [existing] = await db.select().from(returnRequests).where(and(eq(returnRequests.channel, input.channel), eq(returnRequests.externalReturnId, input.externalReturnId))); if (existing) return getReturnRequest(db, existing.id); }
  const items = input.items ?? [];
  if (!items.length) throw new BadRequestError("At least one return item is required");
  const purchased = await db.select().from(orderItems).where(eq(orderItems.orderId, order.id));
  for (const item of items) { const p = purchased.find((x) => x.id === item.orderItemId); if (!p) throw new BadRequestError("Return item does not belong to order"); if (item.quantityRequested < 1 || item.quantityRequested > p.quantity) throw new BadRequestError("Return quantity exceeds purchased quantity"); const [{ qty }] = await db.select({ qty: sql<number>`coalesce(sum(${returnItems.quantityRequested}),0)` }).from(returnItems).where(eq(returnItems.orderItemId, item.orderItemId)); if (qty + item.quantityRequested > p.quantity) throw new BadRequestError("Cumulative return quantity exceeds purchased quantity"); }
  const id = randomUUID(); const t = now();
  await db.transaction((tx) => { tx.insert(returnRequests).values({ id, orderId: order.id, marketplaceOrderId: input.marketplaceOrderId, shipmentId: input.shipmentId, channel: input.channel, externalReturnId: input.externalReturnId, externalReturnNumber: input.externalReturnNumber, status: ReturnStatus.Requested, reason: input.reason, reasonDetails: input.reasonDetails, requestedResolution: input.requestedResolution, buyerMessage: input.buyerMessage, internalNote: input.internalNote, requestedAt: input.requestedAt ?? t, returnCarrierCode: input.returnCarrierCode, returnTrackingNumber: input.returnTrackingNumber, returnTrackingUrl: input.returnTrackingUrl, buyerShippedAt: input.buyerShippedAt, createdAt: t, updatedAt: t }).run(); for (const item of items) { const p = purchased.find((x) => x.id === item.orderItemId)!; tx.insert(returnItems).values({ id: randomUUID(), returnRequestId: id, orderItemId: p.id, productId: p.productId, quantityRequested: item.quantityRequested, createdAt: t, updatedAt: t }).run(); } tx.insert(returnEvents).values({ id: randomUUID(), returnRequestId: id, eventType: "created", newStatus: ReturnStatus.Requested, payloadSnapshot: JSON.stringify(input), createdAt: t }).run(); });
  return getReturnRequest(db, id);
}
export async function getReturnRequest(db: DbClient, id: string) { const [r] = await db.select().from(returnRequests).where(eq(returnRequests.id, id)); if (!r) throw new NotFoundError("Return not found"); const items = await db.select().from(returnItems).where(eq(returnItems.returnRequestId, id)); return { ...r, items }; }
export async function listReturnRequests(db: DbClient, q: any = {}) { const filters = [q.orderId && eq(returnRequests.orderId, q.orderId), q.status && eq(returnRequests.status, q.status), q.channel && eq(returnRequests.channel, q.channel), q.reason && eq(returnRequests.reason, q.reason), q.externalReturnId && eq(returnRequests.externalReturnId, q.externalReturnId)].filter(Boolean) as any[]; return db.select().from(returnRequests).where(filters.length ? and(...filters) : undefined).orderBy(desc(returnRequests.createdAt)).limit(Number(q.pageSize ?? 50)).offset((Number(q.page ?? 1)-1)*Number(q.pageSize ?? 50)); }
export async function updateReturnRequest(db: DbClient, id: string, input: any) { await getReturnRequest(db, id); await db.update(returnRequests).set({ ...input, updatedAt: now() }).where(eq(returnRequests.id, id)); return getReturnRequest(db, id); }
async function transition(db: DbClient, id: string, to: ReturnStatus, eventType: string, allowed: ReturnStatus[], patch: any = {}) { const r = await getReturnRequest(db, id) as any; if (!allowed.includes(r.status)) throw new BadRequestError("Invalid return status transition"); await db.update(returnRequests).set({ ...patch, status: to, updatedAt: now() }).where(eq(returnRequests.id, id)); await event(db, id, eventType, r.status, to, patch); return getReturnRequest(db, id); }
export const authorizeReturn = (db: DbClient, id: string, input: any = {}) => transition(db, id, ReturnStatus.Authorized, "authorized", [ReturnStatus.Requested], { authorizedAt: now(), approvedResolution: input.approvedResolution ?? input.resolution });
export const rejectReturn = (db: DbClient, id: string, input: any = {}) => transition(db, id, ReturnStatus.Rejected, "rejected", [ReturnStatus.Requested, ReturnStatus.Authorized], { internalNote: input.internalNote });
export const markReturnInTransit = (db: DbClient, id: string, input: any = {}) => transition(db, id, ReturnStatus.InTransit, "in_transit", [ReturnStatus.Authorized, ReturnStatus.AwaitingShipment], { ...input, buyerShippedAt: input.buyerShippedAt ?? now() });
export const receiveReturn = (db: DbClient, id: string, input: any = {}) => transition(db, id, ReturnStatus.Received, "received", [ReturnStatus.Authorized, ReturnStatus.InTransit], { receivedAt: input.receivedAt ?? now() });
export async function inspectReturnItem(db: DbClient, id: string, input: any) { const r = await getReturnRequest(db, id) as any; if (![ReturnStatus.Received, ReturnStatus.Inspecting].includes(r.status)) throw new BadRequestError("Return must be received before inspection"); await db.update(returnItems).set({ quantityReceived: input.quantityReceived, condition: input.condition, stockDisposition: input.stockDisposition, inspectionNote: input.inspectionNote, updatedAt: now() }).where(and(eq(returnItems.returnRequestId, id), eq(returnItems.orderItemId, input.orderItemId))); await db.update(returnRequests).set({ status: ReturnStatus.Inspecting, inspectedAt: now(), updatedAt: now() }).where(eq(returnRequests.id, id)); await event(db, id, "item_inspected", r.status, ReturnStatus.Inspecting, input); return getReturnRequest(db, id); }
export const approveReturn = (db: DbClient, id: string, input: any = {}) => transition(db, id, input.partial ? ReturnStatus.PartiallyApproved : ReturnStatus.Approved, "approved", [ReturnStatus.Inspecting, ReturnStatus.Received], { approvedResolution: input.approvedResolution ?? ReturnResolution.Refund });
export async function completeReturn(db: DbClient, id: string) { const r = await getReturnRequest(db, id) as any; if (r.completedAt || r.status === ReturnStatus.Completed) return r; if (![ReturnStatus.Approved, ReturnStatus.PartiallyApproved].includes(r.status)) throw new BadRequestError("Return is not approved"); const t = now(); const sync: string[] = []; await db.transaction((tx) => { for (const item of r.items) { const disposition = item.stockDisposition ?? (item as any).stock_disposition; const productId = item.productId ?? (item as any).product_id; const qty = Math.min(item.quantityApproved ?? (item as any).quantity_approved ?? item.quantityReceived ?? (item as any).quantity_received ?? item.quantityRequested ?? (item as any).quantity_requested, item.quantityReceived ?? (item as any).quantity_received ?? item.quantityRequested ?? (item as any).quantity_requested); if (disposition === ReturnStockDisposition.ReturnToStock && productId && qty > 0) { applyStockMovementSync(tx, { productId, type: StockMovementType.ReturnIn, quantityDelta: qty, orderId: r.orderId, orderItemId: item.orderItemId, note: `Return ${id}`, idempotencyKey: `return-in:${id}:${item.id}` }); sync.push(productId); } } tx.update(returnRequests).set({ status: ReturnStatus.Completed, completedAt: t, updatedAt: t }).where(eq(returnRequests.id, id)).run(); tx.insert(returnEvents).values({ id: randomUUID(), returnRequestId: id, eventType: "completed", previousStatus: r.status, newStatus: ReturnStatus.Completed, payloadSnapshot: "{}", createdAt: t }).run(); }); for (const productId of sync) await enqueueProductStockSync(db, productId, `return-in:${id}:${productId}`); return getReturnRequest(db, id); }
export const cancelReturn = (db: DbClient, id: string, input: any = {}) => transition(db, id, ReturnStatus.Cancelled, "cancelled", [ReturnStatus.Requested, ReturnStatus.Authorized, ReturnStatus.AwaitingShipment, ReturnStatus.InTransit], { cancelledAt: now(), internalNote: input.internalNote });
export async function getReturnReadiness(db: DbClient, id: string) { const r = await getReturnRequest(db, id) as any; return { ready: !r.lastError, reasons: r.lastError ? [r.lastError] : [], allowedActions: ["authorize","reject","in-transit","receive","inspect","approve","complete","cancel"] }; }
export const getReturnEvents = (db: DbClient, id: string) => db.select().from(returnEvents).where(eq(returnEvents.returnRequestId, id)).orderBy(desc(returnEvents.createdAt));
export async function calculateMaximumRefund(db: DbClient, orderId: string) { const [o] = await db.select().from(orders).where(eq(orders.id, orderId)); if (!o) throw new NotFoundError("Order not found"); const [{ total }] = await db.select({ total: sql<number>`coalesce(sum(${refunds.totalAmount}),0)` }).from(refunds).where(and(eq(refunds.orderId, orderId), eq(refunds.status, RefundStatus.Succeeded))); return { currency: PriceCurrency.Eur, originalPaidAmount: o.totalAmount, refundedAmount: total, refundableAmount: Math.max(0, o.totalAmount - total) }; }
export async function validateRefundAmount(db: DbClient, orderId: string, amount: number) { const m = await calculateMaximumRefund(db, orderId); if (amount <= 0 || amount > m.refundableAmount) throw new BadRequestError("Refund exceeds refundable balance"); return m; }
export async function createRefund(db: DbClient, input: any) { const [existing] = await db.select().from(refunds).where(eq(refunds.idempotencyKey, input.idempotencyKey)); if (existing) return existing; if ((input.currency ?? PriceCurrency.Eur) !== PriceCurrency.Eur) throw new BadRequestError("Only EUR refunds are supported"); const total = (input.subtotalAmount ?? 0)+(input.shippingAmount ?? 0)+(input.taxAmount ?? 0); await validateRefundAmount(db, input.orderId, total); const t=now(); const row={ id: randomUUID(), orderId: input.orderId, returnRequestId: input.returnRequestId, channel: input.channel, type: input.type ?? RefundType.Partial, status: input.status ?? RefundStatus.Draft, currency: PriceCurrency.Eur, subtotalAmount: input.subtotalAmount ?? 0, shippingAmount: input.shippingAmount ?? 0, taxAmount: input.taxAmount ?? 0, marketplaceFeeAdjustment: input.marketplaceFeeAdjustment, paymentFeeAdjustment: input.paymentFeeAdjustment, totalAmount: total, reason: input.reason, idempotencyKey: input.idempotencyKey, createdAt: t, updatedAt: t }; await db.insert(refunds).values(row).run(); for (const a of input.allocations ?? []) await db.insert(refundAllocations).values({ id: randomUUID(), refundId: row.id, orderItemId: a.orderItemId, returnItemId: a.returnItemId, quantity: a.quantity, amount: a.amount, createdAt: t }).run(); return row; }
export async function getRefund(db: DbClient, id: string) { const [r] = await db.select().from(refunds).where(eq(refunds.id, id)); if (!r) throw new NotFoundError("Refund not found"); return { ...r, allocations: await db.select().from(refundAllocations).where(eq(refundAllocations.refundId, id)) }; }
export async function listRefunds(db: DbClient, q: any = {}) { const filters = [q.orderId && eq(refunds.orderId, q.orderId), q.status && eq(refunds.status, q.status), q.channel && eq(refunds.channel, q.channel), q.externalRefundId && eq(refunds.externalRefundId, q.externalRefundId)].filter(Boolean) as any[]; return db.select().from(refunds).where(filters.length ? and(...filters) : undefined).orderBy(desc(refunds.createdAt)).limit(Number(q.pageSize ?? 50)).offset((Number(q.page ?? 1)-1)*Number(q.pageSize ?? 50)); }
export async function submitRefund(db: DbClient, id: string) { const r:any = await getRefund(db, id); if (![RefundStatus.Draft, RefundStatus.Pending, RefundStatus.Failed].includes(r.status)) throw new BadRequestError("Refund cannot be submitted"); await db.update(refunds).set({ status: RefundStatus.Pending, submittedAt: now(), updatedAt: now() }).where(eq(refunds.id, id)); await enqueueJob(db, { type: BackgroundJobType.SubmitMarketplaceRefund, channel: r.channel, payload: { refundId: id }, idempotencyKey: `refund-submit:${id}` }); return getRefund(db, id); }
export async function cancelRefund(db: DbClient, id: string) { const r:any = await getRefund(db, id); if (![RefundStatus.Draft, RefundStatus.Pending, RefundStatus.Failed].includes(r.status)) throw new BadRequestError("Refund cannot be cancelled"); await db.update(refunds).set({ status: RefundStatus.Cancelled, updatedAt: now() }).where(eq(refunds.id, id)); return getRefund(db,id); }
export const retryRefund = submitRefund;
export async function executeMarketplaceRefund(db: DbClient, refundId: string) { const r:any = await getRefund(db, refundId); if (r.status === RefundStatus.Succeeded || r.externalRefundId) return r; if (r.status !== RefundStatus.Pending) throw new BadRequestError("Only pending refunds can be submitted"); if (!r.channel) throw new BadRequestError("Marketplace channel is required"); const [mo] = await db.select().from(marketplaceOrders).where(eq(marketplaceOrders.internalOrderId, r.orderId)); const [conn] = await db.select().from(marketplaceConnections).where(mo ? eq(marketplaceConnections.id, mo.marketplaceConnectionId) : eq(marketplaceConnections.channel, r.channel)); if (!conn || conn.status !== MarketplaceConnectionStatus.Connected || !conn.encryptedAccessToken) throw { type: "Authentication", message: "Marketplace connection missing", retryable: false }; const [{ count }] = await db.select({ count: sql<number>`count(*)` }).from(refundAttempts).where(eq(refundAttempts.refundId, refundId)); const attemptNumber = Number(count) + 1; const payload = { refundId, orderId: r.orderId, returnRequestId: r.returnRequestId, amount: r.totalAmount, currency: r.currency, externalOrderId: mo?.externalOrderId }; try { const result = await adapterResolver(r.channel).submitRefund(decryptCredential(conn.encryptedAccessToken), payload); await db.insert(refundAttempts).values({ id: randomUUID(), refundId, attemptNumber, channel: r.channel, status: "succeeded", externalRefundId: result.externalRefundId, requestSnapshot: JSON.stringify(payload), responseSnapshot: JSON.stringify(result.raw ?? result), createdAt: now() }).run(); await db.update(refunds).set({ status: RefundStatus.Succeeded, externalRefundId: result.externalRefundId ?? `refund-${refundId}`, succeededAt: now(), lastError: null, updatedAt: now() }).where(eq(refunds.id, refundId)); return getRefund(db, refundId); } catch (error) { const safe = adapterResolver(r.channel).normalizeReturnError(error); await db.insert(refundAttempts).values({ id: randomUUID(), refundId, attemptNumber, channel: r.channel, status: "failed", requestSnapshot: JSON.stringify(payload), errorCode: safe.type, errorMessage: safe.message.replace(/Bearer\s+\S+|access_token\S*|refresh_token\S*/gi, "[redacted]"), createdAt: now() }).run(); await db.update(refunds).set({ status: RefundStatus.Failed, failedAt: now(), lastError: `${safe.type}: ${safe.message}`.replace(/Bearer\s+\S+|access_token\S*|refresh_token\S*/gi, "[redacted]"), updatedAt: now() }).where(eq(refunds.id, refundId)); throw { type: safe.type, message: safe.message, retryable: safe.retryable }; } }
export async function getSaleReversalReadiness(db: DbClient, orderId: string) { const max = await calculateMaximumRefund(db, orderId); const completedReturns = await db.select().from(returnRequests).where(and(eq(returnRequests.orderId, orderId), eq(returnRequests.status, ReturnStatus.Completed))); const purchased = await db.select().from(orderItems).where(eq(orderItems.orderId, orderId)); let returnedQty = 0; for (const ret of completedReturns) { const its = await db.select().from(returnItems).where(eq(returnItems.returnRequestId, ret.id)); returnedQty += its.reduce((sum, item) => sum + Math.min(item.quantityApproved ?? item.quantityReceived ?? 0, item.quantityReceived ?? item.quantityRequested), 0); } const purchasedQty = purchased.reduce((sum, item) => sum + item.quantity, 0); const fullReturn = purchasedQty > 0 && returnedQty >= purchasedQty; return { ready: fullReturn && max.refundableAmount === 0, reasons: !fullReturn ? ["Full approved return is required"] : max.refundableAmount !== 0 ? ["Full refund is required"] : [], allowedActions: ["reverse"] }; }
export async function reverseCompletedSale(db: DbClient, input: any) { const key = input.idempotencyKey ?? `sale-reversal:${input.orderId}`; const [existing] = await db.select().from(saleReversals).where(eq(saleReversals.idempotencyKey, key)); if (existing) return existing; const readiness = await getSaleReversalReadiness(db, input.orderId); if (!readiness.ready) throw new BadRequestError(readiness.reasons.join("; ")); const [sf] = await db.select().from(saleFinancials).where(eq(saleFinancials.orderId, input.orderId)); const row = { id: randomUUID(), orderId: input.orderId, returnRequestId: input.returnRequestId, refundId: input.refundId, reversalType: "full", stockReversed: true, financialsReversed: true, originalSaleFinancialId: sf?.id, sourceSnapshot: JSON.stringify({ saleFinancial: sf ?? null, requested: input }), idempotencyKey: key, createdAt: now() }; await db.insert(saleReversals).values(row).run(); return row; }
export async function getReturnFinancialSummary(db: DbClient, orderId: string) { const [sf] = await db.select().from(saleFinancials).where(eq(saleFinancials.orderId, orderId)); const [{ subtotal, shipping, tax, total }] = await db.select({ subtotal: sql<number>`coalesce(sum(${refunds.subtotalAmount}),0)`, shipping: sql<number>`coalesce(sum(${refunds.shippingAmount}),0)`, tax: sql<number>`coalesce(sum(${refunds.taxAmount}),0)`, total: sql<number>`coalesce(sum(${refunds.totalAmount}),0)` }).from(refunds).where(and(eq(refunds.orderId, orderId), eq(refunds.status, RefundStatus.Succeeded))); const completedReturns = await db.select().from(returnRequests).where(and(eq(returnRequests.orderId, orderId), eq(returnRequests.status, ReturnStatus.Completed))); let returnedItemCost = 0; for (const ret of completedReturns) { const its = await db.select().from(returnItems).where(eq(returnItems.returnRequestId, ret.id)); for (const item of its) returnedItemCost += item.stockDisposition === ReturnStockDisposition.ReturnToStock ? 0 : 0; } const feeKnown = sf ? sf.marketplaceFee !== null && sf.paymentFee !== null : false; return { orderId, originalGrossRevenue: sf?.grossRevenue ?? 0, refundedSubtotal: subtotal, refundedShipping: shipping, refundedTax: tax, marketplaceFeeAdjustment: null, paymentFeeAdjustment: null, totalRefunded: total, netRetainedRevenue: (sf?.grossRevenue ?? 0) - total, returnedItemCost, stockDispositionWriteOffValue: null, adjustedProfit: sf && feeKnown ? sf.profit - total : undefined, adjustedProfitComplete: !!sf && feeKnown }; }
export function normalizeReturnError(error: unknown) { const safe = sanitizeError(error); return { type: safe.type, message: clean(error), retryable: safe.retryable }; }
