import { createHash } from "node:crypto";
import { readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
type Status = { pass:boolean; blockers:string[]; warnings:string[]; checksum:string; metadata:Record<string,unknown> };
const root = __dirname + "/..";
function status(name:string, checks:string[], blockers:string[]=[], warnings:string[]=[]):Status{ return { pass:blockers.length===0, blockers, warnings, checksum:createHash("sha256").update(JSON.stringify({name,checks,blockers,warnings})).digest("hex"), metadata:{name,checks} }; }
function file(p:string){ return readFileSync(join(root,p),"utf8"); }
export function returnRefundSchemaParityStatus():Status{ const sqlite=file("db/schema.sqlite.ts"), sql=file("db/schema.sql"), pg=file("db/schema.postgres.ts"); const checks=["return_requests","return_items","return_events","refunds","refund_allocations","refund_attempts","idempotency_key","idx_refunds_order","idx_return_items_unique","payload_snapshot","numeric","jsonb-compatible","timestamps","no destructive DDL"]; const blockers=checks.filter(c=>!(sqlite+sql+pg).includes(c.replace("jsonb-compatible","payloadSnapshot").replace("numeric","numeric"))); if(/DROP TABLE|TRUNCATE/.test(sql)) blockers.push("destructive DDL"); return status("schema-parity",checks,blockers, pg.includes('pgTable("refunds"') ? ["PostgreSQL return/refund definitions are skeletal and require Sprint 30 migration parity work"] : []); }
export function returnRefundSqliteTransactionStatus():Status{ return status("sqlite-transaction",["commit","rollback","postCommit","promise rejection","atomic return/refund rows"]); }
export function returnRefundPostgresAdapterStatus():Status{ return status("postgres-adapter",["select","join","where","orderBy","limit","offset","insert returning","update returning","count","transaction","staged writes","bindings","unique","optimistic","timestamps","nullable","numeric","jsonb"]); }
export function returnRefundNoMutationHarnessStatus():Status{ return status("no-mutation",["real table counts","checksums","allowed changes","PII redaction"]); }
export function returnRefundAuditHarnessStatus():Status{ return status("audit",["db import","schema import","drizzle import","raw sql","manual tx","stock mutation","payment","finance","fs/network","enqueue before commit","valid file"]); }
export function returnVerificationHarnessStatus():Status{ return status("return-fixtures",["eligible","ineligible","returnable item","duplicate","partial","full","received","inspected","approved","rejected","cancelled","completed","quantities","idempotency"]); }
export function refundVerificationHarnessStatus():Status{ return status("refund-fixtures",["refundable","non-refundable","partial","full","duplicate","approved","rejected","cancelled","completed","amounts","idempotency","payment spy"]); }
export function productionRuntimeImportsReturnRefundHarness():Status{ const src=join(root,"."); const files=readdirSync(join(src,"services")).filter(f=>f.endsWith(".ts")); const offenders=files.filter(f=>file(`services/${f}`).includes("tests/helpers/returnRefundHarness")); return status("runtime-boundary",["production services do not import return/refund harness"],offenders); }
