import { randomUUID } from "node:crypto";
import { and, desc, eq, sql } from "drizzle-orm";
import { BackgroundJobType, MarketplaceConnectionStatus, PriceCurrency, PublishChannel, RefundStatus, RefundType, ReturnStatus, ReturnStockDisposition } from "@noctella/shared";
import type { DbClient } from "../db/client";
import { orderItems, orders, marketplaceConnections, marketplaceOrders, refundAllocations, refundAttempts, refunds, returnItems, returnRequests, saleFinancials, saleReversals } from "../db/schema";
import { BadRequestError, NotFoundError } from "./errors";
import { createFinanceEntry } from "./financePostings";
import { decryptCredential } from "./credentialEncryption";
import { enqueueJob } from "./backgroundJobs";
import { getMarketplaceAdapter, type MarketplaceAdapter } from "./marketplaceAdapters";
type AdapterResolver = (channel: PublishChannel | string) => MarketplaceAdapter;
import { sanitizeError } from "./backgroundJobs";
let adapterResolver: AdapterResolver = (channel) => getMarketplaceAdapter(channel as PublishChannel);
export function setReturnMarketplaceAdapterResolver(resolver?: AdapterResolver) { adapterResolver = resolver ?? ((channel) => getMarketplaceAdapter(channel as PublishChannel)); }
const now = () => new Date().toISOString();
export async function calculateMaximumRefund(db: DbClient, orderId: string) { const [o] = await db.select().from(orders).where(eq(orders.id, orderId)); if (!o) throw new NotFoundError("Order not found"); const [{ total }] = await db.select({ total: sql<number>`coalesce(sum(${refunds.totalAmount}),0)` }).from(refunds).where(and(eq(refunds.orderId, orderId), eq(refunds.status, RefundStatus.Succeeded))); return { currency: PriceCurrency.Eur, originalPaidAmount: o.totalAmount, refundedAmount: total, refundableAmount: Math.max(0, o.totalAmount - total) }; }
export async function validateRefundAmount(db: DbClient, orderId: string, amount: number) { const m = await calculateMaximumRefund(db, orderId); if (amount <= 0 || amount > m.refundableAmount) throw new BadRequestError("Refund exceeds refundable balance"); return m; }
export async function createRefund(db: DbClient, input: any) { const [existing] = await db.select().from(refunds).where(eq(refunds.idempotencyKey, input.idempotencyKey)); if (existing) return existing; if ((input.currency ?? PriceCurrency.Eur) !== PriceCurrency.Eur) throw new BadRequestError("Only EUR refunds are supported"); const total = (input.subtotalAmount ?? 0)+(input.shippingAmount ?? 0)+(input.taxAmount ?? 0); await validateRefundAmount(db, input.orderId, total); const t=now(); const row={ id: randomUUID(), orderId: input.orderId, returnRequestId: input.returnRequestId, channel: input.channel, type: input.type ?? RefundType.Partial, status: input.status ?? RefundStatus.Draft, currency: PriceCurrency.Eur, subtotalAmount: input.subtotalAmount ?? 0, shippingAmount: input.shippingAmount ?? 0, taxAmount: input.taxAmount ?? 0, marketplaceFeeAdjustment: input.marketplaceFeeAdjustment, paymentFeeAdjustment: input.paymentFeeAdjustment, totalAmount: total, reason: input.reason, idempotencyKey: input.idempotencyKey, createdAt: t, updatedAt: t }; await db.insert(refunds).values(row).run(); if (row.status === RefundStatus.Succeeded) await createFinanceEntry(db, { orderId: row.orderId, refundId: row.id, entryType: "SuccessfulRefund", amount: -row.totalAmount, sourceReference: row.id, idempotencyKey: `refund-succeeded:${row.id}`, occurredAt: t, snapshot: row }); for (const a of input.allocations ?? []) await db.insert(refundAllocations).values({ id: randomUUID(), refundId: row.id, orderItemId: a.orderItemId, returnItemId: a.returnItemId, quantity: a.quantity, amount: a.amount, createdAt: t }).run(); return row; }
export async function getRefund(db: DbClient, id: string) { const [r] = await db.select().from(refunds).where(eq(refunds.id, id)); if (!r) throw new NotFoundError("Refund not found"); return { ...r, allocations: await db.select().from(refundAllocations).where(eq(refundAllocations.refundId, id)) }; }
export async function listRefunds(db: DbClient, q: any = {}) { const filters = [q.orderId && eq(refunds.orderId, q.orderId), q.status && eq(refunds.status, q.status), q.channel && eq(refunds.channel, q.channel), q.externalRefundId && eq(refunds.externalRefundId, q.externalRefundId)].filter(Boolean) as any[]; return db.select().from(refunds).where(filters.length ? and(...filters) : undefined).orderBy(desc(refunds.createdAt)).limit(Number(q.pageSize ?? 50)).offset((Number(q.page ?? 1)-1)*Number(q.pageSize ?? 50)); }
export async function submitRefund(db: DbClient, id: string) { const r:any = await getRefund(db, id); if (![RefundStatus.Draft, RefundStatus.Pending, RefundStatus.Failed].includes(r.status)) throw new BadRequestError("Refund cannot be submitted"); await db.update(refunds).set({ status: RefundStatus.Pending, submittedAt: now(), updatedAt: now() }).where(eq(refunds.id, id)); await enqueueJob(db, { type: BackgroundJobType.SubmitMarketplaceRefund, channel: r.channel, payload: { refundId: id }, idempotencyKey: `refund-submit:${id}` }); return getRefund(db, id); }
export async function cancelRefund(db: DbClient, id: string) { const r:any = await getRefund(db, id); if (![RefundStatus.Draft, RefundStatus.Pending, RefundStatus.Failed].includes(r.status)) throw new BadRequestError("Refund cannot be cancelled"); await db.update(refunds).set({ status: RefundStatus.Cancelled, updatedAt: now() }).where(eq(refunds.id, id)); return getRefund(db,id); }
export const retryRefund = submitRefund;
export async function executeMarketplaceRefund(db: DbClient, refundId: string) { const r:any = await getRefund(db, refundId); if (r.status === RefundStatus.Succeeded || r.externalRefundId) return r; if (r.status !== RefundStatus.Pending) throw new BadRequestError("Only pending refunds can be submitted"); if (!r.channel) throw new BadRequestError("Marketplace channel is required"); const [mo] = await db.select().from(marketplaceOrders).where(eq(marketplaceOrders.internalOrderId, r.orderId)); const [conn] = await db.select().from(marketplaceConnections).where(mo ? eq(marketplaceConnections.id, mo.marketplaceConnectionId) : eq(marketplaceConnections.channel, r.channel)); if (!conn || conn.status !== MarketplaceConnectionStatus.Connected || !conn.encryptedAccessToken) throw { type: "Authentication", message: "Marketplace connection missing", retryable: false }; const [{ count }] = await db.select({ count: sql<number>`count(*)` }).from(refundAttempts).where(eq(refundAttempts.refundId, refundId)); const attemptNumber = Number(count) + 1; const payload = { refundId, orderId: r.orderId, returnRequestId: r.returnRequestId, amount: r.totalAmount, currency: r.currency, externalOrderId: mo?.externalOrderId }; try { const result = await adapterResolver(r.channel).submitRefund(decryptCredential(conn.encryptedAccessToken), payload); await db.insert(refundAttempts).values({ id: randomUUID(), refundId, attemptNumber, channel: r.channel, status: "succeeded", externalRefundId: result.externalRefundId, requestSnapshot: JSON.stringify(payload), responseSnapshot: JSON.stringify(result.raw ?? result), createdAt: now() }).run(); await db.update(refunds).set({ status: RefundStatus.Succeeded, externalRefundId: result.externalRefundId ?? `refund-${refundId}`, succeededAt: now(), lastError: null, updatedAt: now() }).where(eq(refunds.id, refundId)); const updated = await getRefund(db, refundId); await createFinanceEntry(db, { orderId: updated.orderId, refundId: updated.id, entryType: "SuccessfulRefund", amount: -updated.totalAmount, sourceReference: updated.externalRefundId ?? updated.id, idempotencyKey: `refund-succeeded:${updated.id}`, occurredAt: updated.succeededAt, snapshot: updated }); return updated; } catch (error) { const safe = adapterResolver(r.channel).normalizeReturnError(error); await db.insert(refundAttempts).values({ id: randomUUID(), refundId, attemptNumber, channel: r.channel, status: "failed", requestSnapshot: JSON.stringify(payload), errorCode: safe.type, errorMessage: safe.message.replace(/Bearer\s+\S+|access_token\S*|refresh_token\S*/gi, "[redacted]"), createdAt: now() }).run(); await db.update(refunds).set({ status: RefundStatus.Failed, failedAt: now(), lastError: `${safe.type}: ${safe.message}`.replace(/Bearer\s+\S+|access_token\S*|refresh_token\S*/gi, "[redacted]"), updatedAt: now() }).where(eq(refunds.id, refundId)); throw { type: safe.type, message: safe.message, retryable: safe.retryable }; } }
export async function getSaleReversalReadiness(db: DbClient, orderId: string) { const max = await calculateMaximumRefund(db, orderId); const completedReturns = await db.select().from(returnRequests).where(and(eq(returnRequests.orderId, orderId), eq(returnRequests.status, ReturnStatus.Completed))); const purchased = await db.select().from(orderItems).where(eq(orderItems.orderId, orderId)); let returnedQty = 0; for (const ret of completedReturns) { const its = await db.select().from(returnItems).where(eq(returnItems.returnRequestId, ret.id)); returnedQty += its.reduce((sum, item) => sum + Math.min(item.quantityApproved ?? item.quantityReceived ?? 0, item.quantityReceived ?? item.quantityRequested), 0); } const purchasedQty = purchased.reduce((sum, item) => sum + item.quantity, 0); const fullReturn = purchasedQty > 0 && returnedQty >= purchasedQty; return { ready: fullReturn && max.refundableAmount === 0, reasons: !fullReturn ? ["Full approved return is required"] : max.refundableAmount !== 0 ? ["Full refund is required"] : [], allowedActions: ["reverse"] }; }
export async function reverseCompletedSale(db: DbClient, input: any) { const key = input.idempotencyKey ?? `sale-reversal:${input.orderId}`; const [existing] = await db.select().from(saleReversals).where(eq(saleReversals.idempotencyKey, key)); if (existing) return existing; const readiness = await getSaleReversalReadiness(db, input.orderId); if (!readiness.ready) throw new BadRequestError(readiness.reasons.join("; ")); const [sf] = await db.select().from(saleFinancials).where(eq(saleFinancials.orderId, input.orderId)); const row = { id: randomUUID(), orderId: input.orderId, returnRequestId: input.returnRequestId, refundId: input.refundId, reversalType: "full", stockReversed: true, financialsReversed: true, originalSaleFinancialId: sf?.id, sourceSnapshot: JSON.stringify({ saleFinancial: sf ?? null, requested: input }), idempotencyKey: key, createdAt: now() }; await db.insert(saleReversals).values(row).run(); await createFinanceEntry(db, { orderId: row.orderId, refundId: row.refundId, saleReversalId: row.id, entryType: "SaleReversal", amount: 0, sourceReference: row.id, idempotencyKey: `sale-reversal:${row.id}`, snapshot: row }); return row; }
export async function getReturnFinancialSummary(db: DbClient, orderId: string) { const [sf] = await db.select().from(saleFinancials).where(eq(saleFinancials.orderId, orderId)); const [{ subtotal, shipping, tax, total }] = await db.select({ subtotal: sql<number>`coalesce(sum(${refunds.subtotalAmount}),0)`, shipping: sql<number>`coalesce(sum(${refunds.shippingAmount}),0)`, tax: sql<number>`coalesce(sum(${refunds.taxAmount}),0)`, total: sql<number>`coalesce(sum(${refunds.totalAmount}),0)` }).from(refunds).where(and(eq(refunds.orderId, orderId), eq(refunds.status, RefundStatus.Succeeded))); const completedReturns = await db.select().from(returnRequests).where(and(eq(returnRequests.orderId, orderId), eq(returnRequests.status, ReturnStatus.Completed))); let returnedItemCost = 0; for (const ret of completedReturns) { const its = await db.select().from(returnItems).where(eq(returnItems.returnRequestId, ret.id)); for (const item of its) returnedItemCost += item.stockDisposition === ReturnStockDisposition.ReturnToStock ? 0 : 0; } const feeKnown = sf ? sf.marketplaceFee !== null && sf.paymentFee !== null : false; return { orderId, originalGrossRevenue: sf?.grossRevenue ?? 0, refundedSubtotal: subtotal, refundedShipping: shipping, refundedTax: tax, marketplaceFeeAdjustment: null, paymentFeeAdjustment: null, totalRefunded: total, netRetainedRevenue: (sf?.grossRevenue ?? 0) - total, returnedItemCost, stockDispositionWriteOffValue: null, adjustedProfit: sf && feeKnown ? sf.profit - total : undefined, adjustedProfitComplete: !!sf && feeKnown }; }
const clean=(e:unknown)=>String((e as any)?.message??e).replace(/Bearer\s+\S+|access_token\S*|refresh_token\S*/gi,"[redacted]");
export function normalizeReturnError(error: unknown) { const safe = sanitizeError(error); return { type: safe.type, message: clean(error), retryable: safe.retryable }; }
