export type SalesMigrationDecision="migrate"|"retain"|"reject";
export interface SalesMigrationMatrixRow {readonly functionName:string;readonly caller:string;readonly input:string;readonly output:string;readonly error:string;readonly logic:string;readonly persistence:string;readonly target:string;readonly inputMapper:string;readonly outputMapper:string;readonly errorMapper:string;readonly decision:SalesMigrationDecision;readonly reason:string}
const row=(value:SalesMigrationMatrixRow)=>Object.freeze(value);
export const salesServiceMigrationMatrix=Object.freeze([
  row({functionName:"saleProjection",caller:"GET /erp/sales/:id",input:"(DbClient,id)",output:"legacy ERP sale projection",error:"legacy not-found",logic:"reporting joins",persistence:"read-only",target:"GetSaleUseCase",inputMapper:"id -> saleId",outputMapper:"retained reporting projection",errorMapper:"route-compatible",decision:"migrate",reason:"base sale retrieval is supported; joins remain reporting-only"}),
  row({functionName:"listSales",caller:"GET /erp/sales",input:"(DbClient,query)",output:"{items,page,pageSize}",error:"legacy route error",logic:"filters/paging/projection; retained substring search",persistence:"read-only",target:"ListSalesUseCase/GetSaleUseCase",inputMapper:"supported filters -> limit/offset; search IDs -> saleId",outputMapper:"rows -> legacy projections",errorMapper:"route-compatible",decision:"migrate",reason:"base listing is supported; substring reference search remains a projection helper"}),
  row({functionName:"createInternalSale",caller:"ERP CreateInternalSale",input:"legacy ERP payload",output:"OrderWithItems",error:"BadRequest/NotFound",logic:"product validation, stock decrement, sync",persistence:"order+items+stock transaction",target:"CreateSaleUseCase",inputMapper:"unsupported atomically",outputMapper:"unchanged",errorMapper:"unchanged",decision:"retain",reason:"CreateSaleUseCase exposes no atomic legacy stock compatibility hook"}),
  row({functionName:"completeSale",caller:"shipment route and ERP command",input:"(DbClient,orderId)",output:"legacy completion response",error:"legacy/application-compatible",logic:"compatibility ports only",persistence:"adapter/use-case coordinator",target:"CompleteSaleApplicationAdapter",inputMapper:"S3D adapter",outputMapper:"S3D legacy mapper",errorMapper:"existing route handling",decision:"migrate",reason:"S3D supplies version, idempotency, readiness, costs, finance, timestamps and replay"}),
  row({functionName:"getSaleCompletionReadiness",caller:"shipment and ERP readiness routes",input:"(DbClient,orderId)",output:"legacy readiness",error:"legacy not-found",logic:"legacy reporting/capability port",persistence:"read-only",target:"retained adapter port",inputMapper:"none",outputMapper:"S3D readiness port",errorMapper:"unchanged",decision:"retain",reason:"no standalone readiness use case; required S3D port"}),
  row({functionName:"customerProjection",caller:"sale/invoice/customer ERP reads",input:"(DbClient,orderId,detail)",output:"masked customer projection",error:"legacy not-found",logic:"reporting/privacy projection",persistence:"read-only",target:"retained reporting helper",inputMapper:"none",outputMapper:"unchanged",errorMapper:"unchanged",decision:"retain",reason:"not representable by Sales read output"}),
  row({functionName:"adjustedFinancials",caller:"sale/finance/refund ERP reads",input:"(DbClient,orderId)",output:"adjusted finance projection",error:"legacy not-found",logic:"refund reporting",persistence:"read-only",target:"retained reporting helper",inputMapper:"none",outputMapper:"unchanged",errorMapper:"unchanged",decision:"retain",reason:"refund-adjusted projection is outside Sales use cases"}),
  ...["createInvoiceDraft","getInvoice","listInvoices","updateInvoiceDraft","issueInvoice","setInvoiceStatus","getInvoiceEvents","listFinanceEntries","financeSummary","refundSummary","reversalSummary"].map(functionName=>row({functionName,caller:"ERP invoice/finance routes",input:"legacy",output:"legacy",error:"legacy",logic:"invoice/finance/reporting",persistence:"retained legacy",target:"none",inputMapper:"none",outputMapper:"unchanged",errorMapper:"unchanged",decision:"retain",reason:"outside Sales service migration scope"})),
  row({functionName:"Update Sale workflow",caller:"none",input:"none",output:"none",error:"none",logic:"absent",persistence:"none",target:"UpdateSaleUseCase",inputMapper:"none",outputMapper:"none",errorMapper:"none",decision:"retain",reason:"no active legacy Sales service/ERP update export exists"}),
  row({functionName:"Cancel Sale workflow",caller:"none",input:"none",output:"none",error:"none",logic:"absent",persistence:"none",target:"CancelSaleUseCase",inputMapper:"none",outputMapper:"none",errorMapper:"none",decision:"retain",reason:"no active legacy Sales service/ERP cancel export exists"}),
  row({functionName:"RecordSalePayment",caller:"none",input:"none",output:"none",error:"none",logic:"excluded",persistence:"none",target:"none",inputMapper:"none",outputMapper:"none",errorMapper:"none",decision:"reject",reason:"explicitly excluded and unsupported by merged architecture"}),
]);
