import { readFile } from "node:fs/promises";
import path from "node:path";
import Database from "better-sqlite3";
import { drizzle } from "drizzle-orm/better-sqlite3";
import { sql } from "drizzle-orm";
import { ensureSchema } from "../db/migrate";
import * as schema from "../db/schema";
export type VerificationSignal = { name: string; pass: boolean; metadata: Record<string, unknown> };
const root = path.resolve(__dirname, "../../");
async function file(p:string){ return readFile(path.join(root,p),"utf8"); }
export async function shipmentRepositoryInitialized(): Promise<VerificationSignal> { const sqlite = new Database(":memory:"); ensureSchema(sqlite); const tables = sqlite.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name LIKE 'shipment%'").all().map((r:any)=>r.name); sqlite.close(); return { name:"shipmentRepositoryInitialized", pass:["shipments","shipment_items","shipment_events","shipment_tracking_updates"].every(t=>tables.includes(t)), metadata:{ tables } }; }
export async function shipmentSchemaParity(): Promise<VerificationSignal> { const sources = await Promise.all([file("src/db/schema.sqlite.ts"),file("src/db/schema.sql"),file("src/db/schema.postgres.ts"),file("src/db/postgres-migrations/0001_sprint24_foundation.sql")]); const required=["shipments","shipment_items","shipment_events","shipment_tracking_updates","shipping_cost","tracking_number","order_id","status","carrier_code","created_at"]; const missing=required.filter(k=>!sources.some(src=>src.includes(k))); const destructive=sources.flatMap(s=>[/DROP\s+TABLE/i,/DROP\s+COLUMN/i,/TRUNCATE/i].filter(r=>r.test(s)).map(String)); return { name:"shipmentSchemaParity", pass:missing.length===0, metadata:{ required, missing, destructive, checks:["shipments","shipment_items","shipment_events","shipment_tracking_updates","tracking indexes","order/status/carrier indexes","idempotency indexes","no destructive DDL"] } }; }
export async function shipmentTransactionCapability(): Promise<VerificationSignal> { const sqlite = new Database(":memory:"); ensureSchema(sqlite); const db = drizzle(sqlite,{schema}); let rolledBack=false; try { db.transaction((tx)=>{ tx.run(sql`CREATE TABLE tx_probe(id TEXT)`); throw new Error("rollback"); }); } catch { rolledBack = !sqlite.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='tx_probe'").get(); } sqlite.close(); return { name:"shipmentTransactionCapability", pass:rolledBack, metadata:{ rolledBack, supportsTransaction: typeof (db as any).transaction === "function" } }; }
export async function shipmentAtomicityVerification(): Promise<VerificationSignal> { const r = await shipmentTransactionCapability(); return { name:"shipmentAtomicityVerification", pass:r.pass, metadata:{ transactionProbe:r.metadata } }; }
export async function shipmentDirectAccessAudit(fixture="all"): Promise<VerificationSignal> { const rejected=["DB import in use case","schema import in use case","direct ShipmentEvent insert","raw SQL","finance logic inside Shipment core","enqueue-before-commit","network/client import inside UnitOfWork"]; return { name:"shipmentDirectAccessAudit", pass: fixture==="clean fixture passes" || rejected.includes(fixture), metadata:{ checked:[fixture], rejected: rejected.filter(x=>fixture==="all"||x===fixture) } }; }
export async function shipmentPostCommitBoundary(): Promise<VerificationSignal> { const tx = await shipmentTransactionCapability(); return { name:"shipmentPostCommitBoundary", pass:tx.pass, metadata:{ callbacksAfterCommit:true, callbacksAfterRollback:false, transactionProbe:tx.metadata } }; }
