import { ShipmentStatus } from "@noctella/shared";
import { createShipmentCoreContext } from "./shipment-core/runtime";
import { addShipmentEventUseCase, cancelShipmentUseCase, createShipmentUseCase, getShipmentDetailUseCase, getShipmentEventsUseCase, listShipmentsUseCase, markShipmentDeliveredUseCase, markShipmentFailedUseCase, markShipmentReturnedUseCase, updateShipmentStatusUseCase, updateShipmentTrackingUseCase, updateShipmentUseCase } from "./shipment-core/useCases";
export { completeSale, getSaleCompletionReadiness, getShipmentTracking, refreshShipmentStatus, refreshTracking, reopenSale, safeShippingError, setShipmentMarketplaceAdapterResolver, submitMarketplaceShipment } from "./shipmentsCompatibility";
const ctx = (db: unknown) => createShipmentCoreContext(db as any);
export const createShipment = async (db: unknown, input: any) => createShipmentUseCase(ctx(db), input);
export const getShipment = async (db: unknown, id: string) => getShipmentDetailUseCase(ctx(db), id);
export const getShipmentById = getShipment;
export const getShipmentForOrder = async (db: unknown, orderId: string) => (await listShipments(db, { orderId }))[0];
export const listShipments = async (db: unknown, q: any = {}) => listShipmentsUseCase(ctx(db), q);
export const updateShipment = async (db: unknown, id: string, input: any) => updateShipmentUseCase(ctx(db), id, input);
export const assignTracking = async (db: unknown, id: string, input: any) => updateShipmentTrackingUseCase(ctx(db), id, input);
export const updateShipmentTracking = assignTracking;
export const updateShipmentStatus = async (db: unknown, id: string, status: ShipmentStatus, payload?: any) => updateShipmentStatusUseCase(ctx(db), id, status, payload);
export const markReady = async (db: unknown, id: string) => updateShipmentStatus(db, id, ShipmentStatus.Ready);
export const markShipped = async (db: unknown, id: string, p?: any) => updateShipmentStatus(db, id, ShipmentStatus.InTransit, p);
export const markDelivered = async (db: unknown, id: string, p?: any) => markShipmentDeliveredUseCase(ctx(db), id, p);
export const markShipmentDelivered = markDelivered;
export const markDeliveryFailed = async (db: unknown, id: string, p?: any) => markShipmentFailedUseCase(ctx(db), id, p);
export const markFailed = markDeliveryFailed;
export const markShipmentFailed = markDeliveryFailed;
export const cancelShipment = async (db: unknown, id: string, p?: any) => cancelShipmentUseCase(ctx(db), id, p);
export const markReturned = async (db: unknown, id: string, p?: any) => markShipmentReturnedUseCase(ctx(db), id, p);
export const addShipmentEvent = async (db: unknown, id: string, input: any) => addShipmentEventUseCase(ctx(db), id, input);
export const getShipmentEvents = async (db: unknown, id: string) => getShipmentEventsUseCase(ctx(db), id);
