import { Router } from "express";

import { adjustedFinancials, customerProjection, executeSalesCommand, financeSummary, getInvoice, getInvoiceEvents, getSaleCompletionReadiness, listFinanceEntries, listInvoices, listSales, refundSummary, reversalSummary, saleProjection } from "../services/erpSalesFinanceBridge";
import multer from "multer";
import { eq } from "drizzle-orm";
import { db } from "../db/client";
import { categories, collections, erpIntegrationAudit, erpIntegrationClients, erpSyncCheckpoints, productPhotos, stockMovements, products } from "../db/schema";
import { acknowledge, authenticateErp, capabilities, checkpoint, getProductProjection, health, identityCheck, isVersionSupported, listProductProjections, PRODUCT_FIELD_MAPPING, validateCommandEnvelope, versionInfo, audit } from "../services/erpIntegration";
import { barcode, deleteProductPhoto, executeCreateProduct, executeStockAdjustment, executeUpdateProduct, labelData, reorderProductPhotos, setPrimaryProductPhoto, updateProductPhoto, uploadProductPhoto, workspace } from "../services/erpInventoryBridge";
import { handleRouteError } from "./errorHandler";
import { executePurchaseCommand, executeSupplierCommand, getPurchase, getPurchaseEvents, getPurchaseLandedCostSummary, listPurchases, listSuppliers, productPurchaseHistory } from "../services/erpPurchasingBridge";
import { buildErpMigrationManifestPreview, buildErpMigrationPreview, capabilities as migrationCapabilities, detectErpMigrationConflicts, ERP_MIGRATION_MAX_BYTES, validateErpMigrationSource } from "../services/erpMigration";

const router = Router();
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 10 * 1024 * 1024 } });
const key = (req: any) => req.header("X-Noctella-ERP-Key");
const version = (req: any) => req.header("X-Noctella-ERP-Client-Version");
const requestId = (req: any) => req.header("X-Noctella-ERP-Request-Id");
async function requireErp(req: any, res: any, next: any) { const auth = await authenticateErp(db, key(req), version(req), requestId(req)); if (!auth.ok) return res.status(401).json({ error: auth.error }); if (!isVersionSupported(version(req))) return res.status(409).json({ error: "ERP client version is not supported", version: versionInfo(version(req)) }); req.erp=auth; next(); }

router.options("*", (req, res) => { const allow=(process.env.ERP_CORS_ORIGINS??"").split(",").map(s=>s.trim()).filter(Boolean); const origin=req.header("origin"); if(origin && allow.includes(origin)) res.header("Access-Control-Allow-Origin", origin); res.header("Access-Control-Allow-Headers", "Content-Type,X-Noctella-ERP-Key,X-Noctella-ERP-Client-Version,X-Noctella-ERP-Request-Id"); res.sendStatus(204); });
router.get("/version", (req, res) => res.json(versionInfo(version(req))));
router.get("/health", async (req, res) => { const publicOnly=!key(req); const h=await health(db); res.json(publicOnly ? { status: h.status, apiVersion: h.apiVersion, serverTime: h.serverTime } : h); });
router.get("/capabilities", requireErp, (_req, res) => res.json(capabilities()));

function parseMigrationPayload(req: any, res: any) { const len=Number(req.header("content-length") ?? 0); if (len > ERP_MIGRATION_MAX_BYTES) { res.status(413).json({ error:"ERP migration preview payload is too large" }); return null; } return req.body?.source ?? req.body ?? {}; }
async function auditMigration(req:any, action:string, result:any, success=true, errorCode?:string) { await audit(db, req.erp?.clientId ?? null, requestId(req), action, success?"Success":"Failure", { sourceType:result?.sourceType, sourceFingerprint:result?.fingerprint?.value, entityCounts:result?.entityCounts, conflictCount:result?.conflicts?.length ?? 0, blockingCount:result?.summary?.blockingCount ?? result?.issues?.filter?.((i:any)=>i.severity==="Blocking")?.length ?? 0, dryRun:true }, errorCode); }
router.get("/migration/capabilities", requireErp, (_req, res) => res.json(migrationCapabilities()));
router.get("/migration/mapping", requireErp, (_req, res) => res.json({ mappingVersion:"sprint17-preview-v1", productFields: PRODUCT_FIELD_MAPPING, classifications:["mapped","metadata","derived","deferred","unsupported"], dryRun:true }));
router.post("/migration/validate", requireErp, async (req:any, res) => { const payload=parseMigrationPayload(req,res); if (!payload) return; const result=validateErpMigrationSource(payload, req.body?.sourceType); await auditMigration(req,"ErpMigrationValidate",result,result.ok,result.ok?undefined:"VALIDATION_FAILED"); res.status(result.ok?200:400).json(result); });
router.post("/migration/preview", requireErp, async (req:any, res) => { const payload=parseMigrationPayload(req,res); if (!payload) return; const result=await buildErpMigrationPreview(db,payload,req.body?.sourceType); await auditMigration(req,"ErpMigrationPreview",result,result.ok,result.ok?undefined:"PREVIEW_BLOCKED"); res.status(result.ok?200:400).json(result); });
router.post("/migration/conflicts", requireErp, async (req:any, res) => { const payload=parseMigrationPayload(req,res); if (!payload) return; const conflicts=await detectErpMigrationConflicts(db,payload); res.json({ dryRun:true, conflicts }); });
router.post("/migration/manifest-preview", requireErp, async (req:any, res) => { const payload=parseMigrationPayload(req,res); if (!payload) return; const result=await buildErpMigrationManifestPreview(db,payload,req.body?.sourceType); await auditMigration(req,"ErpMigrationManifestPreview",result,result.ok,result.ok?undefined:"MANIFEST_BLOCKED"); res.status(result.ok?200:400).json(result.manifestPreview); });


router.get("/sales", requireErp, async (req, res) => { try { res.json(await listSales(db, req.query)); } catch (err) { handleRouteError(err, res); } });
router.get("/sales/:id", requireErp, async (req, res) => { try { res.json(await saleProjection(db, req.params.id)); } catch (err) { handleRouteError(err, res); } });
router.get("/orders/:id/sales-summary", requireErp, async (req, res) => { try { res.json(await saleProjection(db, req.params.id)); } catch (err) { handleRouteError(err, res); } });
router.get("/orders/:id/financials", requireErp, async (req, res) => { try { res.json(await adjustedFinancials(db, req.params.id)); } catch (err) { handleRouteError(err, res); } });
router.get("/orders/:id/refund-summary", requireErp, async (req, res) => { try { res.json(await refundSummary(db, req.params.id)); } catch (err) { handleRouteError(err, res); } });
router.get("/orders/:id/reversal-summary", requireErp, async (req, res) => { try { res.json(await reversalSummary(db, req.params.id)); } catch (err) { handleRouteError(err, res); } });
router.get("/orders/:orderId/complete-sale/readiness", requireErp, async (req, res) => { try { res.json(await getSaleCompletionReadiness(db, req.params.orderId)); } catch (err) { handleRouteError(err, res); } });
router.get("/customers", requireErp, async (req, res) => { try { const sales=await listSales(db, req.query); res.json({items:sales.items.map((s:any)=>s.customer), page:sales.page, pageSize:sales.pageSize}); } catch (err) { handleRouteError(err, res); } });
router.get("/customers/:id", requireErp, async (_req, res) => res.json({ id: _req.params.id, source:"order-snapshot", noDuplicateCustomerTruth:true }));
router.get("/orders/:orderId/customer", requireErp, async (req, res) => { try { res.json(await customerProjection(db, req.params.orderId, true)); } catch (err) { handleRouteError(err, res); } });
router.get("/invoices", requireErp, async (req, res) => { try { res.json(await listInvoices(db, req.query)); } catch (err) { handleRouteError(err, res); } });
router.get("/invoices/:id", requireErp, async (req, res) => { try { res.json(await getInvoice(db, req.params.id)); } catch (err) { handleRouteError(err, res); } });
router.get("/orders/:orderId/invoices", requireErp, async (req, res) => { try { res.json(await listInvoices(db, { ...req.query, orderId:req.params.orderId })); } catch (err) { handleRouteError(err, res); } });
router.get("/invoices/:id/events", requireErp, async (req, res) => { try { res.json({items: await getInvoiceEvents(db, req.params.id)}); } catch (err) { handleRouteError(err, res); } });
router.get("/finance/entries", requireErp, async (req, res) => { try { res.json(await listFinanceEntries(db, req.query)); } catch (err) { handleRouteError(err, res); } });
router.get("/finance/summary", requireErp, async (req, res) => { try { res.json(await financeSummary(db, req.query)); } catch (err) { handleRouteError(err, res); } });
router.get("/finance/orders/:orderId", requireErp, async (req, res) => { try { res.json({ summary: await adjustedFinancials(db, req.params.orderId), entries: await listFinanceEntries(db, { orderId:req.params.orderId }) }); } catch (err) { handleRouteError(err, res); } });
router.post("/commands/sales/create", requireErp, async (req:any, res) => { try { res.status(201).json(await executeSalesCommand(db, req.erp.clientId, req.body, "CreateInternalSale")); } catch (err) { handleRouteError(err, res); } });
router.post("/commands/orders/:orderId/complete-sale", requireErp, async (req:any, res) => { try { res.json(await executeSalesCommand(db, req.erp.clientId, req.body, "CompleteSale", req.params.orderId)); } catch (err) { handleRouteError(err, res); } });
router.post("/commands/orders/:orderId/invoices/create", requireErp, async (req:any, res) => { try { res.status(201).json(await executeSalesCommand(db, req.erp.clientId, req.body, "CreateInvoice", req.params.orderId)); } catch (err) { handleRouteError(err, res); } });
router.post("/commands/invoices/:invoiceId/update", requireErp, async (req:any, res) => { try { res.json(await executeSalesCommand(db, req.erp.clientId, req.body, "UpdateInvoice", req.params.invoiceId)); } catch (err) { handleRouteError(err, res); } });
router.post("/commands/invoices/:invoiceId/issue", requireErp, async (req:any, res) => { try { res.json(await executeSalesCommand(db, req.erp.clientId, req.body, "IssueInvoice", req.params.invoiceId)); } catch (err) { handleRouteError(err, res); } });
router.post("/commands/invoices/:invoiceId/cancel", requireErp, async (req:any, res) => { try { res.json(await executeSalesCommand(db, req.erp.clientId, req.body, "CancelInvoice", req.params.invoiceId)); } catch (err) { handleRouteError(err, res); } });
router.post("/commands/invoices/:invoiceId/void", requireErp, async (req:any, res) => { try { res.json(await executeSalesCommand(db, req.erp.clientId, req.body, "VoidInvoice", req.params.invoiceId)); } catch (err) { handleRouteError(err, res); } });
router.post("/commands/invoices/:invoiceId/mark-paid", requireErp, async (req:any, res) => { try { res.json(await executeSalesCommand(db, req.erp.clientId, req.body, "MarkInvoicePaid", req.params.invoiceId)); } catch (err) { handleRouteError(err, res); } });

router.get("/suppliers", requireErp, async (req, res) => { try { res.json(await listSuppliers(db, req.query)); } catch (err) { handleRouteError(err, res); } });
router.get("/suppliers/:id", requireErp, async (req, res) => { try { res.json(await (await import("../services/erpPurchasingBridge")).getSupplier(db, req.params.id, true)); } catch (err) { handleRouteError(err, res); } });
router.post("/commands/suppliers/create", requireErp, async (req:any, res) => { try { res.status(201).json(await executeSupplierCommand(db, req.erp.clientId, req.body)); } catch (err) { handleRouteError(err, res); } });
router.post("/commands/suppliers/:supplierId/update", requireErp, async (req:any, res) => { try { res.json(await executeSupplierCommand(db, req.erp.clientId, req.body, req.params.supplierId)); } catch (err) { handleRouteError(err, res); } });
router.get("/purchases", requireErp, async (req, res) => { try { res.json(await listPurchases(db, req.query)); } catch (err) { handleRouteError(err, res); } });
router.get("/purchases/:id", requireErp, async (req, res) => { try { res.json(await getPurchase(db, req.params.id)); } catch (err) { handleRouteError(err, res); } });
router.get("/purchases/:id/events", requireErp, async (req, res) => { try { res.json({ items: await getPurchaseEvents(db, req.params.id) }); } catch (err) { handleRouteError(err, res); } });
router.get("/purchases/:id/landed-cost", requireErp, async (req, res) => { try { res.json(await getPurchaseLandedCostSummary(db, req.params.id)); } catch (err) { handleRouteError(err, res); } });
router.get("/products/:id/purchase-history", requireErp, async (req, res) => { try { res.json(await productPurchaseHistory(db, req.params.id)); } catch (err) { handleRouteError(err, res); } });
router.post("/commands/purchases/create", requireErp, async (req:any, res) => { try { res.status(201).json(await executePurchaseCommand(db, req.erp.clientId, req.body, "CreatePurchase")); } catch (err) { handleRouteError(err, res); } });
router.post("/commands/purchases/:purchaseId/update", requireErp, async (req:any, res) => { try { res.json(await executePurchaseCommand(db, req.erp.clientId, req.body, "UpdatePurchase", req.params.purchaseId)); } catch (err) { handleRouteError(err, res); } });
router.post("/commands/purchases/:purchaseId/allocate", requireErp, async (req:any, res) => { try { res.json(await executePurchaseCommand(db, req.erp.clientId, req.body, "AllocatePurchaseCosts", req.params.purchaseId)); } catch (err) { handleRouteError(err, res); } });
router.post("/commands/purchases/:purchaseId/receive", requireErp, async (req:any, res) => { try { res.json(await executePurchaseCommand(db, req.erp.clientId, req.body, "ReceivePurchase", req.params.purchaseId)); } catch (err) { handleRouteError(err, res); } });
router.post("/commands/purchases/:purchaseId/cancel", requireErp, async (req:any, res) => { try { res.json(await executePurchaseCommand(db, req.erp.clientId, req.body, "CancelPurchase", req.params.purchaseId)); } catch (err) { handleRouteError(err, res); } });

router.get("/products", requireErp, async (req, res) => res.json(await listProductProjections(db, req.query)));
router.get("/products/by-erp-reference/:erpReferenceId", requireErp, async (req, res) => { const [p]=await db.select().from(products).where(eq(products.erpReferenceId, req.params.erpReferenceId)).limit(1); if(!p) return res.status(404).json({ error:"Product not found" }); res.json(await getProductProjection(db,p.id)); });
router.get("/products/:id", requireErp, async (req, res) => { const p=await getProductProjection(db, req.params.id); if(!p) return res.status(404).json({ error:"Product not found" }); res.json(p); });
router.get("/products/:id/availability", requireErp, async (req, res) => { const p=await getProductProjection(db, req.params.id); if(!p) return res.status(404).json({ error:"Product not found" }); res.json({ productId:p.centralProductId, physicalStock:p.physicalStock, reservedStock:0, reservedStockSupported:false, availableStock:p.availableStock }); });
router.get("/products/:id/movements", requireErp, async (req, res) => res.json({ items: await db.select().from(stockMovements).where(eq(stockMovements.productId, req.params.id)).orderBy(stockMovements.createdAt), readOnly:true }));
router.get("/products/:id/photos", requireErp, async (req, res) => res.json({ items: await db.select().from(productPhotos).where(eq(productPhotos.productId, req.params.id)).orderBy(productPhotos.sortOrder), readOnly:true }));
router.get("/categories", requireErp, async (_req, res) => res.json({ items: await db.select().from(categories).orderBy(categories.displayOrder, categories.name) }));
router.get("/collections", requireErp, async (_req, res) => res.json({ items: await db.select().from(collections).orderBy(collections.displayOrder, collections.name) }));
router.post("/products/identity-check", requireErp, async (req, res) => res.json(await identityCheck(db, req.body ?? {})));
router.get("/mapping/product-fields", requireErp, (_req, res) => res.json({ fields: PRODUCT_FIELD_MAPPING, excluded: [{ erpField:"imageDataUrl", currentSprintMode:"Deferred", notes:"Deferred to ProductPhoto migration; not silently dropped." }] }));
router.get("/sync/checkpoint", requireErp, async (_req, res) => res.json(await checkpoint(db)));
router.post("/sync/acknowledge", requireErp, async (req:any, res) => res.json(await acknowledge(db, req.erp.clientId, requestId(req), req.body?.checkpointToken, req.body?.safeMetadata)));
router.post("/commands/validate", requireErp, (req, res) => res.json(validateCommandEnvelope(req.body)));
router.post("/commands/products/create", requireErp, async (req:any, res) => { try { res.status(201).json(await executeCreateProduct(db, req.erp.clientId, req.body)); } catch (err) { handleRouteError(err, res); } });
router.post("/commands/products/:productId/update", requireErp, async (req:any, res) => { try { res.json(await executeUpdateProduct(db, req.erp.clientId, req.params.productId, req.body)); } catch (err) { handleRouteError(err, res); } });
router.post("/commands/products/:productId/adjust-stock", requireErp, async (req:any, res) => { try { res.json(await executeStockAdjustment(db, req.erp.clientId, req.params.productId, req.body)); } catch (err) { handleRouteError(err, res); } });
router.get("/products/:id/workspace", requireErp, async (req, res) => { try { res.json(await workspace(db, req.params.id)); } catch (err) { handleRouteError(err, res); } });
router.get("/products/:id/barcode", requireErp, async (req, res) => { try { res.json(await barcode(db, req.params.id)); } catch (err) { handleRouteError(err, res); } });
router.get("/products/:id/label-data", requireErp, async (req, res) => { try { res.json(await labelData(db, req.params.id)); } catch (err) { handleRouteError(err, res); } });
router.post("/products/:id/photos/upload", requireErp, upload.single("photo"), async (req:any, res) => { try { if (!req.file) return res.status(400).json({ error:"Photo file is required" }); res.status(201).json(await uploadProductPhoto(db, req.params.id, req.file, typeof req.body.altText === "string" ? req.body.altText : undefined)); await audit(db, req.erp.clientId, requestId(req), "ErpPhotoUpload", "Succeeded", { productId:req.params.id }); } catch (err) { handleRouteError(err, res); } });
router.patch("/products/:id/photos/:photoId", requireErp, async (req:any, res) => { try { const out=await updateProductPhoto(db, req.params.id, req.params.photoId, typeof req.body.altText === "string" ? req.body.altText : undefined); await audit(db, req.erp.clientId, requestId(req), "ErpPhotoUpdate", "Succeeded", { productId:req.params.id, photoId:req.params.photoId }); res.json(out); } catch (err) { handleRouteError(err, res); } });
router.post("/products/:id/photos/:photoId/primary", requireErp, async (req:any, res) => { try { const out=await setPrimaryProductPhoto(db, req.params.id, req.params.photoId); await audit(db, req.erp.clientId, requestId(req), "ErpPhotoPrimary", "Succeeded", { productId:req.params.id, photoId:req.params.photoId }); res.json(out); } catch (err) { handleRouteError(err, res); } });
router.post("/products/:id/photos/reorder", requireErp, async (req:any, res) => { try { const out=await reorderProductPhotos(db, req.params.id, req.body.photoIds); await audit(db, req.erp.clientId, requestId(req), "ErpPhotoReorder", "Succeeded", { productId:req.params.id, count:req.body.photoIds?.length }); res.json(out); } catch (err) { handleRouteError(err, res); } });
router.delete("/products/:id/photos/:photoId", requireErp, async (req:any, res) => { try { const out=await deleteProductPhoto(db, req.params.id, req.params.photoId); await audit(db, req.erp.clientId, requestId(req), "ErpPhotoDelete", "Succeeded", { productId:req.params.id, photoId:req.params.photoId }); res.json(out); } catch (err) { handleRouteError(err, res); } });

router.get("/admin/overview", async (_req, res) => res.json({ writeCapabilities:["CreateProduct","UpdateProduct","AdjustStock","CreateSupplier","UpdateSupplier","CreatePurchase","UpdatePurchase","AllocatePurchaseCosts","ReceivePurchase","CancelPurchase"], recentCommandExecutions: await db.select().from((await import("../db/schema")).erpCommandExecutions).orderBy((await import("../db/schema")).erpCommandExecutions.createdAt).limit(20), version: versionInfo(), health: await health(db), capabilities: capabilities(), clients: await db.select({ id:erpIntegrationClients.id, name:erpIntegrationClients.name, keyVersion:erpIntegrationClients.keyVersion, isActive:erpIntegrationClients.isActive, lastSeenAt:erpIntegrationClients.lastSeenAt, lastClientVersion:erpIntegrationClients.lastClientVersion }).from(erpIntegrationClients), checkpoints: await db.select().from(erpSyncCheckpoints).orderBy(erpSyncCheckpoints.createdAt).limit(10), audit: await db.select().from(erpIntegrationAudit).orderBy(erpIntegrationAudit.createdAt).limit(20), mappingSummary: PRODUCT_FIELD_MAPPING }));
export default router;
