import { type Request, type Response, Router } from "express";
import { requirePermission } from "../auth/permissions";
import { db } from "../db/client";
import * as svc from "../services/returns";
import { handleRouteError } from "./errorHandler";
const router = Router();
const wrap = (fn: (req: Request, res: Response) => Promise<unknown>) => async (req: Request, res: Response) => { try { await fn(req,res); } catch (e) { handleRouteError(e,res); } };
router.post("/orders/:orderId/returns", requirePermission("orders.manage"), wrap(async (req: Request,res: Response)=>res.status(201).json(await svc.createReturnRequest(db,{...req.body, orderId:req.params.orderId}))));
router.get("/orders/:orderId/returns", requirePermission("orders.view"), wrap(async (req: Request,res: Response)=>res.json(await svc.listReturnRequests(db,{...req.query, orderId:req.params.orderId}))));
router.get("/returns", requirePermission("orders.view"), wrap(async (req: Request,res: Response)=>res.json(await svc.listReturnRequests(db,req.query))));
router.get("/returns/:id", requirePermission("orders.view"), wrap(async (req: Request,res: Response)=>res.json(await svc.getReturnRequest(db,req.params.id))));
router.patch("/returns/:id", requirePermission("orders.manage"), wrap(async (req: Request,res: Response)=>res.json(await svc.updateReturnRequest(db,req.params.id,req.body))));
router.post("/returns/:id/authorize", requirePermission("orders.manage"), wrap(async (req: Request,res: Response)=>res.json(await svc.authorizeReturn(db,req.params.id,req.body))));
router.post("/returns/:id/reject", requirePermission("orders.manage"), wrap(async (req: Request,res: Response)=>res.json(await svc.rejectReturn(db,req.params.id,req.body))));
router.post("/returns/:id/in-transit", requirePermission("orders.manage"), wrap(async (req: Request,res: Response)=>res.json(await svc.markReturnInTransit(db,req.params.id,req.body))));
router.post("/returns/:id/receive", requirePermission("orders.manage"), wrap(async (req: Request,res: Response)=>res.json(await svc.receiveReturn(db,req.params.id,req.body))));
router.post("/returns/:id/inspect", requirePermission("orders.manage"), wrap(async (req: Request,res: Response)=>res.json(await svc.inspectReturnItem(db,req.params.id,req.body))));
router.post("/returns/:id/approve", requirePermission("orders.manage"), wrap(async (req: Request,res: Response)=>res.json(await svc.approveReturn(db,req.params.id,req.body))));
router.post("/returns/:id/complete", requirePermission("orders.manage"), wrap(async (req: Request,res: Response)=>res.json(await svc.completeReturn(db,req.params.id))));
router.post("/returns/:id/cancel", requirePermission("orders.manage"), wrap(async (req: Request,res: Response)=>res.json(await svc.cancelReturn(db,req.params.id,req.body))));
router.get("/returns/:id/events", requirePermission("orders.view"), wrap(async (req: Request,res: Response)=>res.json(await svc.getReturnEvents(db,req.params.id))));
router.get("/returns/:id/readiness", requirePermission("orders.view"), wrap(async (req: Request,res: Response)=>res.json(await svc.getReturnReadiness(db,req.params.id))));
router.post("/orders/:orderId/refunds", requirePermission("orders.manage"), wrap(async (req: Request,res: Response)=>res.status(201).json(await svc.createRefund(db,{...req.body, orderId:req.params.orderId}))));
router.get("/orders/:orderId/refunds", requirePermission("orders.view"), wrap(async (req: Request,res: Response)=>res.json(await svc.listRefunds(db,{...req.query, orderId:req.params.orderId}))));
router.get("/refunds", requirePermission("orders.view"), wrap(async (req: Request,res: Response)=>res.json(await svc.listRefunds(db,req.query))));
router.get("/refunds/:id", requirePermission("orders.view"), wrap(async (req: Request,res: Response)=>res.json(await svc.getRefund(db,req.params.id))));
router.post("/refunds/:id/submit", requirePermission("orders.manage"), wrap(async (req: Request,res: Response)=>res.json(await svc.submitRefund(db,req.params.id))));
router.post("/refunds/:id/retry", requirePermission("orders.manage"), wrap(async (req: Request,res: Response)=>res.json(await svc.retryRefund(db,req.params.id))));
router.post("/refunds/:id/cancel", requirePermission("orders.manage"), wrap(async (req: Request,res: Response)=>res.json(await svc.cancelRefund(db,req.params.id))));
router.get("/orders/:orderId/sale-reversal/readiness", requirePermission("orders.view"), wrap(async (req: Request,res: Response)=>res.json(await svc.getSaleReversalReadiness(db,req.params.orderId))));
router.post("/orders/:orderId/sale-reversal", requirePermission("orders.manage"), wrap(async (req: Request,res: Response)=>res.status(201).json(await svc.reverseCompletedSale(db,{...req.body, orderId:req.params.orderId}))));
export default router;
