import { Router } from "express";
import { db } from "../db/client";
import * as svc from "../services/shipments";
const router = Router();
const wrap = (fn: any) => async (req: any, res: any, next: any) => { try { await fn(req,res,next); } catch(e) { next(e); } };
router.get("/shipments", wrap(async (req:any,res:any)=>res.json(await svc.listShipments(db, req.query))));
router.get("/shipments/:id", wrap(async (req:any,res:any)=>res.json(await svc.getShipment(db, req.params.id))));
router.patch("/shipments/:id", wrap(async (req:any,res:any)=>res.json(await svc.updateShipment(db, req.params.id, req.body))));
router.post("/shipments/:id/tracking", wrap(async (req:any,res:any)=>res.json(await svc.assignTracking(db, req.params.id, req.body))));
router.post("/shipments/:id/ready", wrap(async (req:any,res:any)=>res.json(await svc.markReady(db, req.params.id))));
router.post("/shipments/:id/ship", wrap(async (req:any,res:any)=>res.json(await svc.markShipped(db, req.params.id, req.body))));
router.post("/shipments/:id/deliver", wrap(async (req:any,res:any)=>res.json(await svc.markDelivered(db, req.params.id, req.body))));
router.post("/shipments/:id/delivery-failed", wrap(async (req:any,res:any)=>res.json(await svc.markDeliveryFailed(db, req.params.id, req.body))));
router.post("/shipments/:id/cancel", wrap(async (req:any,res:any)=>res.json(await svc.cancelShipment(db, req.params.id, req.body))));
router.post("/shipments/:id/return", wrap(async (req:any,res:any)=>res.json(await svc.markReturned(db, req.params.id, req.body))));
router.get("/shipments/:id/events", wrap(async (req:any,res:any)=>res.json(await svc.getShipmentEvents(db, req.params.id))));
router.post("/shipments/:id/refresh-tracking", wrap(async (req:any,res:any)=>res.json(await svc.refreshTracking(db, req.params.id, req.body))));
router.get("/shipments/:id/tracking", wrap(async (req:any,res:any)=>res.json(await svc.getShipmentTracking(db, req.params.id))));
router.post("/shipments/refresh-due", wrap(async (_req:any,res:any)=>res.json({ refreshed: 0, note: "scheduler-compatible endpoint; no permanent polling loop" })));
router.post("/orders/:orderId/shipments", wrap(async (req:any,res:any)=>res.status(201).json(await svc.createShipment(db, { ...req.body, orderId: req.params.orderId }))));
router.get("/orders/:orderId/shipments", wrap(async (req:any,res:any)=>res.json(await svc.listShipments(db, { ...req.query, orderId: req.params.orderId }))));
router.post("/orders/:orderId/complete-sale", wrap(async (req:any,res:any)=>res.json(await svc.completeSale(db, req.params.orderId))));
router.get("/orders/:orderId/complete-sale/readiness", wrap(async (req:any,res:any)=>res.json(await svc.getSaleCompletionReadiness(db, req.params.orderId))));
export default router;
