import { Router } from "express";
import { requirePermission } from "../auth/permissions";
import { db } from "../db/client";
import * as svc from "../services/shipments";
const router = Router();
const wrap = (fn: any) => async (req: any, res: any, next: any) => { try { await fn(req,res,next); } catch(e) { next(e); } };
router.get("/shipments", requirePermission("orders.view"), wrap(async (req:any,res:any)=>res.json(await svc.listShipments(db, req.query))));
router.get("/shipments/:id", requirePermission("orders.view"), wrap(async (req:any,res:any)=>res.json(await svc.getShipment(db, req.params.id))));
router.patch("/shipments/:id", requirePermission("orders.manage"), wrap(async (req:any,res:any)=>res.json(await svc.updateShipment(db, req.params.id, req.body))));
router.post("/shipments/:id/tracking", requirePermission("orders.manage"), wrap(async (req:any,res:any)=>res.json(await svc.assignTracking(db, req.params.id, req.body))));
router.post("/shipments/:id/ready", requirePermission("orders.manage"), wrap(async (req:any,res:any)=>res.json(await svc.markReady(db, req.params.id))));
router.post("/shipments/:id/ship", requirePermission("orders.manage"), wrap(async (req:any,res:any)=>res.json(await svc.markShipped(db, req.params.id, req.body))));
router.post("/shipments/:id/deliver", requirePermission("orders.manage"), wrap(async (req:any,res:any)=>res.json(await svc.markDelivered(db, req.params.id, req.body))));
router.post("/shipments/:id/delivery-failed", requirePermission("orders.manage"), wrap(async (req:any,res:any)=>res.json(await svc.markDeliveryFailed(db, req.params.id, req.body))));
router.post("/shipments/:id/cancel", requirePermission("orders.manage"), wrap(async (req:any,res:any)=>res.json(await svc.cancelShipment(db, req.params.id, req.body))));
router.post("/shipments/:id/return", requirePermission("orders.manage"), wrap(async (req:any,res:any)=>res.json(await svc.markReturned(db, req.params.id, req.body))));
router.get("/shipments/:id/events", requirePermission("orders.view"), wrap(async (req:any,res:any)=>res.json(await svc.getShipmentEvents(db, req.params.id))));
router.post("/shipments/:id/refresh-tracking", requirePermission("orders.manage"), wrap(async (req:any,res:any)=>res.json(await svc.refreshTracking(db, req.params.id, req.body))));
router.get("/shipments/:id/tracking", requirePermission("orders.view"), wrap(async (req:any,res:any)=>res.json(await svc.getShipmentTracking(db, req.params.id))));
router.post("/shipments/refresh-due", requirePermission("orders.manage"), wrap(async (_req:any,res:any)=>res.json({ refreshed: 0, note: "scheduler-compatible endpoint; no permanent polling loop" })));
router.post("/orders/:orderId/shipments", requirePermission("orders.manage"), wrap(async (req:any,res:any)=>res.status(201).json(await svc.createShipment(db, { ...req.body, orderId: req.params.orderId }))));
router.get("/orders/:orderId/shipments", requirePermission("orders.view"), wrap(async (req:any,res:any)=>res.json(await svc.listShipments(db, { ...req.query, orderId: req.params.orderId }))));
router.post("/orders/:orderId/complete-sale", requirePermission("orders.manage"), wrap(async (req:any,res:any)=>res.json(await svc.completeSale(db, req.params.orderId))));
router.get("/orders/:orderId/complete-sale/readiness", requirePermission("orders.view"), wrap(async (req:any,res:any)=>res.json(await svc.getSaleCompletionReadiness(db, req.params.orderId))));
export default router;
