import { Router } from "express";
import { and, desc, eq } from "drizzle-orm";
import { db } from "../db/client";
import { externalListings, stockSyncAudit, stockSyncConflicts } from "../db/schema";
import { enqueueChannelStockSync, enqueueProductStockSync, resolveStockSyncConflict, stockSyncSummary } from "../services/stockSync";
import { enqueueJob } from "../services/backgroundJobs";
import { BackgroundJobType } from "@noctella/shared";
const router = Router();
router.get("/audit", async (req, res, next) => { try { res.json({ items: await db.select().from(stockSyncAudit).orderBy(desc(stockSyncAudit.createdAt)).limit(Number(req.query.pageSize ?? 50)) }); } catch (e) { next(e); } });
router.get("/conflicts", async (req, res, next) => { try { const filters = [req.query.status && eq(stockSyncConflicts.status, String(req.query.status)), req.query.channel && eq(stockSyncConflicts.channel, String(req.query.channel)), req.query.productId && eq(stockSyncConflicts.productId, String(req.query.productId))].filter(Boolean) as any[]; res.json({ items: await db.select().from(stockSyncConflicts).where(filters.length ? and(...filters) : undefined).orderBy(desc(stockSyncConflicts.createdAt)).limit(Number(req.query.pageSize ?? 50)) }); } catch (e) { next(e); } });
router.get("/conflicts/:id", async (req, res, next) => { try { const [item] = await db.select().from(stockSyncConflicts).where(eq(stockSyncConflicts.id, req.params.id)); res.json(item); } catch (e) { next(e); } });
router.post("/conflicts/:id/resolve", async (req, res, next) => { try { res.json(await resolveStockSyncConflict(db, req.params.id, String(req.body?.action ?? "MarkResolved"))); } catch (e) { next(e); } });
router.get("/status", async (_req, res, next) => { try { res.json(await stockSyncSummary(db)); } catch (e) { next(e); } });
router.post("/products/:id", async (req, res, next) => { try { res.json({ jobs: await enqueueProductStockSync(db, req.params.id, "manual") }); } catch (e) { next(e); } });
router.post("/external-listings/:id", async (req, res, next) => { try { const [listing] = await db.select().from(externalListings).where(eq(externalListings.id, req.params.id)); if (!listing) return res.status(404).json({ error: "External listing not found" }); res.json(await enqueueJob(db, { type: BackgroundJobType.StockSyncListing, channel: listing.channel, productId: listing.productId, externalListingId: listing.id, payload: { externalListingId: listing.id }, idempotencyKey: `stock:manual:${listing.id}:${new Date().toISOString()}` })); } catch (e) { next(e); } });
router.post("/marketplaces/:channel", async (req, res, next) => { try { res.json(await enqueueChannelStockSync(db, req.params.channel)); } catch (e) { next(e); } });
router.post("/marketplaces/all", async (_req, res, next) => { try { res.json({ jobs: await Promise.all([enqueueChannelStockSync(db, "ebay"), enqueueChannelStockSync(db, "etsy")]) }); } catch (e) { next(e); } });
export default router;
