import { randomUUID, createHash } from "node:crypto";
import { OrderStatus, PaymentStatus, PriceCurrency, ProductStatus } from "@noctella/shared";
import type { UnitOfWork } from "../../services/unitOfWork";
import { BadRequestError, NotFoundError } from "../../services/errors";
import type { CreateInternalOrderInput, OrderDetailProjection, UpdateOrderPaymentStatusInput, UpdateOrderStatusInput, SaleRollbackInput } from "../../repositories/order/types";
import { decreaseInventoryForSaleInTransactionUseCase, restoreInventoryForSaleRollbackInTransactionUseCase } from "../../application/inventory";
import { createInventoryRepositoryBundleForDb, type InventoryRepositoryDriver } from "../../repositories/inventory/factory";

export interface Clock { now(): Date } export interface IdGenerator { id(): string } export interface PostCommitStockSyncPort { enqueue(productId:string, key:string): Promise<void> }
const clock:Clock={now:()=>new Date()}; const ids:IdGenerator={id:()=>randomUUID()};
export function stablePayload(input:unknown){ return createHash("sha256").update(JSON.stringify(input,Object.keys(input as object).sort())).digest("hex"); }
export function formatOrderNumber(date = new Date(), sequence = Math.floor(Math.random()*1_000_000)){ return `NOC-${date.getUTCFullYear()}${String(date.getUTCMonth()+1).padStart(2,"0")}${String(date.getUTCDate()).padStart(2,"0")}-${String(sequence).padStart(6,"0")}`; }
export function createInternalOrderUseCase(uow:UnitOfWork,sync?:PostCommitStockSyncPort,c:Clock=clock,g:IdGenerator=ids,driver:InventoryRepositoryDriver="sqlite"){ return { async execute(input:CreateInternalOrderInput):Promise<OrderDetailProjection>{ if(!["Internal","Direct","LocalPickup"].includes(input.channel)) throw new BadRequestError("Unsupported order channel"); if(input.paymentStatus!==PaymentStatus.Paid) throw new BadRequestError("Orders can only be created from paid payments"); if(!input.paymentReference?.trim()) throw new BadRequestError("Payment reference is required"); if(input.currency!==PriceCurrency.Eur && input.currency!=="EUR") throw new BadRequestError("Only EUR orders are supported for now"); if(input.items.some(i=>!Number.isInteger(i.quantity)||i.quantity<=0)) throw new BadRequestError("Order quantities must be positive integers"); const idem=input.idempotencyKey??input.orderDraftId; const keyHash=stablePayload({...input,id:undefined,orderNumber:undefined}); const affected:string[]=[]; const orderId=input.id??g.id(); const out=await uow.run(({repositories})=>{ const inventoryRepositories=createInventoryRepositoryBundleForDb(repositories.db,driver,driver==="sqlite"); const existing=repositories.order.orders.write.findByIdempotencyKey(idem) as any; if(existing?.id) return repositories.order.orders.read.getOrderDetailProjection(existing.id) as any; const products=repositories.order.orderItems.write.validateProductReferences(input.items.map(i=>i.productId)) as unknown as any[]; if(products.length!==input.items.length) throw new NotFoundError("Product not found"); const now=c.now().toISOString(); let subtotal=0; const itemRows=[] as any[]; for(const line of input.items){ const p=products.find((x:any)=>x.id===line.productId); if(!p||p.status!==ProductStatus.Published) throw new BadRequestError("Orders can only include published products"); if(p.stockQuantity < line.quantity) throw new BadRequestError("Insufficient stock"); subtotal += p.priceEur*line.quantity; itemRows.push({ id:g.id(), orderId, productId:p.id, productSku:p.sku, productTitle:p.title, productSlug:p.slug, productType:p.type, productImageUrl:p.imageUrl, quantity:line.quantity, unitPrice:p.priceEur, totalPrice:p.priceEur*line.quantity, currency:"EUR", createdAt:now, updatedAt:now }); }
 if(input.subtotalAmount!==subtotal||input.totalAmount!==subtotal) throw new BadRequestError("Submitted totals do not match current product prices"); repositories.order.orders.write.create({ id:orderId, orderNumber:input.orderNumber??formatOrderNumber(c.now()), orderDraftId:idem, guestEmail:input.guestEmail, customerId:input.customerId, status:input.status, paymentStatus:input.paymentStatus, paymentProvider:input.paymentProvider as any, paymentReference:input.paymentReference, subtotalAmount:subtotal, shippingAmount:0, taxAmount:0, totalAmount:subtotal, currency:"EUR" as any, billingAddress:input.billingAddress, shippingAddress:input.shippingAddress, notes:input.notes, createdAt:now, updatedAt:now, idempotencyKey:idem }); repositories.order.orderItems.write.createMany(itemRows); const mutate=(index:number):any=>{ if(index>=itemRows.length) return repositories.order.orders.read.getOrderDetailProjection(orderId) as any; const row=itemRows[index]; const result=decreaseInventoryForSaleInTransactionUseCase({clock:c,idGenerator:{newId:()=>g.id()}},inventoryRepositories,{productId:row.productId,quantity:row.quantity,orderId,orderItemId:row.id,note:`Sale for order ${orderId}`,idempotencyKey:`order-sale:${orderId}:${row.productId}`}); return result instanceof Promise?result.then(()=>{affected.push(row.productId);return mutate(index+1);}):((affected.push(row.productId)),mutate(index+1)); }; return mutate(0); }); for(const p of affected) await sync?.enqueue(p,`order-sale:${orderId}:${p}`).catch(()=>undefined); if(!out) throw new NotFoundError("Order not found"); void keyHash; return out; } }; }
export const getOrderDetailUseCase=(uow:UnitOfWork)=>({execute:(id:string)=>uow.run(({repositories})=>{const o=repositories.order.orders.read.getOrderDetailProjection(id); if(!o) throw new NotFoundError("Order not found"); return o;})});
export interface CreateDraftOrderFromOfferInput { offerId:string; productId:string; customerName:string; customerEmail:string; offeredAmount:number; currency:string }
/**
 * Draft Order creation is an explicit admin action on an Accepted offer, not
 * a side effect of accepting it. It only copies customer/product/amount/
 * currency onto a Draft order row — no inventory, payment, or shipment side
 * effects, unlike createInternalOrderUseCase.
 */
export function createDraftOrderFromOfferUseCase(uow:UnitOfWork,c:Clock=clock,g:IdGenerator=ids){ return { execute(input:CreateDraftOrderFromOfferInput):Promise<OrderDetailProjection>{ return uow.run(({repositories})=>{ const existing=repositories.order.orders.read.getByOfferId(input.offerId) as any; if(existing) throw new BadRequestError("Offer already has a Draft Order"); const products=repositories.order.orderItems.write.validateProductReferences([input.productId]) as unknown as any[]; const p=products[0]; if(!p) throw new NotFoundError("Product not found"); const now=c.now().toISOString(); const orderId=g.id(); const placeholderAddress={ fullName:input.customerName, line1:"", city:"", postalCode:"", country:"" }; repositories.order.orders.write.create({ id:orderId, orderNumber:formatOrderNumber(c.now()), offerId:input.offerId, guestEmail:input.customerEmail, status:OrderStatus.Draft, paymentStatus:PaymentStatus.Pending, subtotalAmount:input.offeredAmount, shippingAmount:0, taxAmount:0, totalAmount:input.offeredAmount, currency:input.currency, billingAddress:placeholderAddress as any, shippingAddress:placeholderAddress as any, createdAt:now, updatedAt:now } as any); repositories.order.orderItems.write.createMany([{ id:g.id(), orderId, productId:p.id, productSku:p.sku, productTitle:p.title, productSlug:p.slug, productType:p.type, productImageUrl:p.imageUrl, quantity:1, unitPrice:input.offeredAmount, totalPrice:input.offeredAmount, currency:input.currency, createdAt:now, updatedAt:now }]); return repositories.order.orders.read.getOrderDetailProjection(orderId) as any; }); } }; }
export const listOrdersUseCase=(uow:UnitOfWork)=>({execute:(q:any)=>uow.run(({repositories})=> q.search?repositories.order.orders.read.search(q.search,q):repositories.order.orders.read.list(q))});
export const updateOrderStatusUseCase=(uow:UnitOfWork)=>({execute:(i:UpdateOrderStatusInput)=>uow.run(({repositories})=>{const o=repositories.order.orders.write.updateStatus(i); if(!o) throw new NotFoundError("Order not found"); return repositories.order.orders.read.getOrderDetailProjection(i.id);})});
/** Completed is reserved exclusively for the completeSale() flow (shipment/payment readiness + optimistic concurrency, via sales-completion) — the generic transition Use Case must never reach it, so Shipped has no outgoing edges here. */
export const ORDER_STATUS_TRANSITIONS: Partial<Record<OrderStatus, OrderStatus[]>> = { [OrderStatus.Draft]:[OrderStatus.Pending,OrderStatus.Confirmed,OrderStatus.Cancelled], [OrderStatus.Pending]:[OrderStatus.Confirmed,OrderStatus.Processing,OrderStatus.Cancelled], [OrderStatus.Confirmed]:[OrderStatus.Processing,OrderStatus.Cancelled], [OrderStatus.Processing]:[OrderStatus.Shipped,OrderStatus.Cancelled], [OrderStatus.Shipped]:[], [OrderStatus.Completed]:[], [OrderStatus.Cancelled]:[] };
/**
 * Canonical Order status transition Use Case (Sprint 39A). Replaces
 * updateOrderStatusUseCase as the runtime entry point for status changes:
 * validates the current status against ORDER_STATUS_TRANSITIONS, treats a
 * same-status request as an idempotent success, and — only when
 * transitioning to Cancelled — restores Inventory via the same canonical
 * restoreInventoryForSaleRollbackInTransactionUseCase createSaleRollbackUseCase
 * already used. Orders with an offerId (Draft Orders created via
 * createDraftOrderFromOfferUseCase) never decrement Inventory at creation,
 * so cancelling one must not restore Inventory either.
 */
export function transitionOrderStatusUseCase(uow:UnitOfWork,c:Clock=clock,g:IdGenerator=ids,driver:InventoryRepositoryDriver="sqlite"){ return { execute(input:UpdateOrderStatusInput):Promise<OrderDetailProjection>{ return uow.run(({repositories})=>{ const order=repositories.order.orders.read.getById(input.id) as any; if(!order) throw new NotFoundError("Order not found"); if(order.status===input.status) return repositories.order.orders.read.getOrderDetailProjection(input.id) as any; const allowed=ORDER_STATUS_TRANSITIONS[order.status as OrderStatus]??[]; if(!allowed.includes(input.status)) throw new BadRequestError("Invalid order status transition"); if(input.status===OrderStatus.Cancelled && !order.offerId){ const inventoryRepositories=createInventoryRepositoryBundleForDb(repositories.db,driver,driver==="sqlite"); const items=repositories.order.orderItems.read.listByOrder(input.id) as unknown as any[]; const mutate=(index:number):any=>{ if(index>=items.length){ repositories.order.orders.write.updateStatus({id:input.id,status:input.status}); return repositories.order.orders.read.getOrderDetailProjection(input.id) as any; } const it=items[index]; const result=restoreInventoryForSaleRollbackInTransactionUseCase({clock:c,idGenerator:{newId:()=>g.id()}},inventoryRepositories,{productId:it.productId,quantity:it.quantity,orderId:input.id,orderItemId:it.id,note:"Order cancelled",idempotencyKey:`order-cancel:${input.id}:${it.productId}`}); return result instanceof Promise?result.then(()=>mutate(index+1)):mutate(index+1); }; return mutate(0); } repositories.order.orders.write.updateStatus({id:input.id,status:input.status}); return repositories.order.orders.read.getOrderDetailProjection(input.id) as any; }); } }; }
export const updateOrderPaymentStatusUseCase=(uow:UnitOfWork)=>({execute:(i:UpdateOrderPaymentStatusInput)=>uow.run(({repositories})=>{const o=repositories.order.orders.write.updatePaymentStatus(i); if(!o) throw new NotFoundError("Order not found"); return repositories.order.orders.read.getOrderDetailProjection(i.id);})});
export const cancelInternalOrderUseCase=(uow:UnitOfWork)=>({execute:(id:string)=>updateOrderStatusUseCase(uow).execute({id,status:OrderStatus.Cancelled as any})});
export const createSaleRollbackUseCase=(uow:UnitOfWork,sync?:PostCommitStockSyncPort,g:IdGenerator=ids,c:Clock=clock,driver:InventoryRepositoryDriver="sqlite")=>({async execute(input:SaleRollbackInput){const affected:string[]=[]; const out=await uow.run(({repositories})=>{const inventoryRepositories=createInventoryRepositoryBundleForDb(repositories.db,driver,driver==="sqlite"); const items=repositories.order.orderItems.read.listByOrder(input.orderId) as unknown as any[]; const mutate=(index:number):any=>{if(index>=items.length)return repositories.order.orders.write.updateStatus({id:input.orderId,status:OrderStatus.Cancelled as any});const it=items[index];const result=restoreInventoryForSaleRollbackInTransactionUseCase({clock:c,idGenerator:{newId:()=>g.id()}},inventoryRepositories,{productId:it.productId,quantity:it.quantity,orderId:input.orderId,orderItemId:it.id,note:input.reason,idempotencyKey:`${input.idempotencyKey}:${it.productId}`});return result instanceof Promise?result.then(()=>{affected.push(it.productId);return mutate(index+1);}):((affected.push(it.productId)),mutate(index+1));};const result=mutate(0);return result instanceof Promise?result.then(()=>repositories.order.orders.read.getOrderDetailProjection(input.orderId)):repositories.order.orders.read.getOrderDetailProjection(input.orderId);});for(const p of affected)await sync?.enqueue(p,`rollback:${input.orderId}:${p}`).catch(()=>undefined);return out;}});
