export const DRY_RUN_WARNING = "Dry Run / No Data Written — production migration execution is intentionally unavailable in Sprint 24.";
export const cutoverStateLabels = { SQLiteOnly:"SQLite only", SupabasePreview:"Supabase preview", SupabaseStaging:"Supabase staging", CutoverReady:"Cutover ready", SupabasePrimary:"Supabase primary", RollbackMode:"Rollback mode" } as const;
export function redactSecretText(value: string) { return value.replace(/postgres(?:ql)?:\/\/[^\s]+/gi,"postgres://[REDACTED]").replace(/(service_role|anon|key)[=:][^\s]+/gi,"$1=[REDACTED]"); }
export function mapOverview(input: any) { return { activeDriver: input.activeDriver ?? "sqlite", cutoverStateLabel: cutoverStateLabels[input.cutoverState as keyof typeof cutoverStateLabels] ?? "SQLite only", sqliteStatus: input.connectivity?.sqlite ?? "unknown", supabaseConfigured: Boolean(input.supabaseConfigured), parityStatus: input.parityStatus ?? "UNKNOWN", migrationReadiness: input.migrationReadiness ?? "blocked", blockingIssueCount: input.blockingIssueCount ?? 0, warningCount: input.warningCount ?? 0 }; }
export function mapParitySummary(input:any){ return { status: input.status, tableCount: input.tables?.length ?? 0, blocking: input.blocking?.length ?? 0, warnings: input.warnings?.length ?? 0 }; }
export function mapMigrationPreview(input:any){ return { dryRun: input.dryRun === true, tableCounts: input.sourceRowCounts ?? {}, tableOrder: input.tableOrder ?? [], transformations: input.requiredTransformations ?? [], warnings: input.warnings ?? [], blockingIssues: input.blockingIssues ?? [] }; }
export function mapHealth(input:any){ return { sqliteIntegrity: input.backup?.sqliteIntegrity ?? input.sqliteIntegrity ?? "unknown", supabaseConnection: input.connectivityStatus ?? input.connectivity?.supabase ?? "not-configured", latencyMs: input.latencyMs ?? null, schemaVersion: input.schemaVersion ?? "unknown", lastPreview: input.lastPreviewTimestamp ?? null, backupReady: Boolean(input.backup?.sqliteBackupPresent), rollbackReady: input.backup?.rollbackManifestPrerequisite === "required" }; }
export function createSafeManifestDownload(manifest:any){ return { filename:"sprint-24-migration-manifest-dry-run.json", content: JSON.stringify({...manifest,dryRun:true},null,2) }; }
export function hasProductionExecuteAction(actions:string[]){ return actions.some(a=>/execute production migration/i.test(a)); }
