import { api } from "./api";
export const allocationMethodLabels: Record<string,string> = { Equal:"Equal split", ByItemCost:"By item cost", ByQuantity:"By quantity", ByWeight:"By weight", Manual:"Manual" };
export function redactSafeError(input: unknown) { return JSON.stringify(input ?? {}).replace(/[A-Z0-9._%+-]+@[A-Z0-9.-]+/gi,"[redacted-email]").replace(/\b\+?[0-9][0-9 .-]{7,}\b/g,"[redacted-phone]"); }
export function mapSupplier(row:any){ return { id:row.id, name:row.name, status:row.status, type:row.supplierType, location:[row.countryCode,row.city].filter(Boolean).join(" / "), erpReferenceId:row.erpReferenceId ?? "—", purchaseCount:row.purchaseCount ?? 0, lastPurchase:row.lastPurchaseAt ?? "—", href:`/suppliers/${row.id}` }; }
export function mapPurchase(row:any){ return { id:row.id, supplierId:row.supplierId, status:row.status, source:row.sourceType, references:[row.erpReferenceId,row.externalReference,row.invoiceReferenceNumber].filter(Boolean).join(" / ") || "—", dates:[row.orderedAt,row.receivedAt].filter(Boolean).join(" / ") || "—", total:row.totalCost == null ? "Incomplete" : `€${Number(row.totalCost).toFixed(2)}`, href:`/purchases/${row.id}` }; }
export function mapLandedCostSummary(summary:any){ return { complete:!!summary.complete, reconciled:!!summary.reconciled, method:allocationMethodLabels[summary.allocationMethod] ?? summary.allocationMethod, lines:summary.lines ?? [] }; }
export function receiptStatus(purchase:any){ const lines=purchase.lines ?? []; if(!lines.length) return "No lines"; const received=lines.reduce((a:any,l:any)=>a+(l.receivedQuantity??0),0); const total=lines.reduce((a:any,l:any)=>a+(l.quantity??0),0); return `${received}/${total} received`; }
export function productLinkWarning(line:any){ return line.productId ? null : "Unlinked line: receipt will not create stock movement"; }
export function costCompleteness(summary:any){ return summary.complete && summary.reconciled ? "Complete" : "Incomplete landed cost"; }
export function commandStatusLabel(status:string){ return status === "Conflict" ? "Conflict — review required" : status; }
export function supplierHref(id:string){ return `/suppliers/${id}`; } export function purchaseHref(id:string){ return `/purchases/${id}`; } export function productHref(id:string){ return `/products/${id}`; }
export function buildPurchaseQuery(filters:any){ const q=new URLSearchParams(); for(const [k,v] of Object.entries(filters)) if(v) q.set(k,String(v)); return q.toString(); }
export const purchasingApi = { suppliers:(q="")=>api.get<any>(`/api/erp/suppliers${q?`?${q}`:""}`), supplier:(id:string)=>api.get<any>(`/api/erp/suppliers/${id}`), purchases:(q="")=>api.get<any>(`/api/erp/purchases${q?`?${q}`:""}`), purchase:(id:string)=>api.get<any>(`/api/erp/purchases/${id}`), landed:(id:string)=>api.get<any>(`/api/erp/purchases/${id}/landed-cost`) };
