import { describe, expect, it, vi } from "vitest";
import { api } from "./api";
import { buildReturnQuery, canCancelRefund, canRetryRefund, canTransitionReturn, financialAdjustment, getRefund, getReturn, getReturnEvents, getReturnReadiness, getSaleReversalReadiness, listRefunds, listReturns, refundReturnLink, returnOrderLink, returnShipmentLink, safeReturnError, stockDispositionLabel, type RefundRow, type ReturnRow } from "./returns";
vi.mock("./api", () => ({ api: { get: vi.fn() } }));
const mockedApi = vi.mocked(api);

describe("admin return/refund helpers", () => {
  const ret: ReturnRow = { id:"ret1", orderId:"ord1", shipmentId:"ship1", channel:"ebay", status:"requested", reason:"damaged", requestedResolution:"refund", requestedAt:"now" };
  const refund: RefundRow = { id:"ref1", orderId:"ord1", returnRequestId:"ret1", channel:"etsy", externalRefundId:"ext", type:"partial", status:"failed", currency:"EUR", subtotalAmount:20, shippingAmount:3, taxAmount:2, totalAmount:25 };
  it("maps return list/detail API calls and links", async () => { mockedApi.get.mockResolvedValueOnce([ret]); await listReturns({ orderId:"ord1", status:"requested" }); expect(mockedApi.get).toHaveBeenCalledWith("/returns?orderId=ord1&status=requested"); mockedApi.get.mockResolvedValueOnce(ret); await getReturn("ret1"); expect(mockedApi.get).toHaveBeenCalledWith("/returns/ret1"); mockedApi.get.mockResolvedValueOnce([]); await getReturnEvents("ret1"); expect(mockedApi.get).toHaveBeenCalledWith("/returns/ret1/events"); mockedApi.get.mockResolvedValueOnce({ ready:true, reasons:[], allowedActions:[] }); await getReturnReadiness("ret1"); expect(returnOrderLink(ret)).toBe("/orders/ord1"); expect(returnShipmentLink(ret)).toBe("/shipments/ship1"); });
  it("maps refund list/detail API calls and sale reversal readiness", async () => { mockedApi.get.mockResolvedValueOnce([refund]); await listRefunds({ channel:"etsy", status:"failed" }); expect(mockedApi.get).toHaveBeenCalledWith("/refunds?channel=etsy&status=failed"); mockedApi.get.mockResolvedValueOnce(refund); await getRefund("ref1"); expect(mockedApi.get).toHaveBeenCalledWith("/refunds/ref1"); mockedApi.get.mockResolvedValueOnce({ ready:false, reasons:["Full refund"] }); await getSaleReversalReadiness("ord1"); expect(mockedApi.get).toHaveBeenCalledWith("/orders/ord1/sale-reversal/readiness"); expect(refundReturnLink(refund)).toBe("/returns/ret1"); });
  it("builds filters/query strings", () => { expect(buildReturnQuery({ orderId:"o1", status:"completed", channel:undefined, reason:"damaged" })).toBe("orderId=o1&status=completed&reason=damaged"); });
  it("calculates transition, retry and cancel eligibility", () => { expect(canTransitionReturn("requested","authorize")).toBe(true); expect(canTransitionReturn("completed","cancel")).toBe(false); expect(canRetryRefund(refund)).toBe(true); expect(canCancelRefund({ ...refund, status:"succeeded" })).toBe(false); });
  it("redacts sensitive errors", () => { expect(safeReturnError("Bearer secret access_token=abc refresh_token=def authorization: token")).not.toContain("secret"); });
  it("maps financial adjustments and stock dispositions", () => { expect(financialAdjustment([refund, { ...refund, id:"ref2", totalAmount:5, shippingAmount:0, taxAmount:1 }])).toEqual({ totalRefunded:30, refundedShipping:3, refundedTax:3 }); expect(stockDispositionLabel("return_to_stock")).toBe("Return to stock"); expect(stockDispositionLabel("discard")).toBe("Discard"); expect(stockDispositionLabel()).toBe("Not inspected"); });
});
