import { ProductStatus, StockMovementType } from "@noctella/shared";
import type { InventoryApplicationContext } from "../../services/inventoryApplicationContext";
import { DuplicateSkuError, DuplicateStockLocationCodeError, InsufficientStockError, InventoryNotFoundError, ProductNotFoundError, StaleInventoryVersionError, StaleProductVersionError, StockLocationNotFoundError } from "../../repositories/inventory/errors";
import type { InventoryState, ProductRecord, StockLocationRecord, StockMovementRecord } from "../../repositories/inventory/types";
import { InsufficientInventoryError, InvalidInventoryQuantityError, InvalidSkuError, InventoryAlreadyInitializedError, InventoryNotInitializedError, InventoryOperationConflictError, InventoryVersionConflictError, ProductAlreadyExistsError, ProductNotFoundApplicationError, StockLocationNotFoundApplicationError } from "./errors";
import type { CreateProductInput, CreateStockLocationInput, GetStockLocationInput, InitializeInventoryInput, InventoryDto, InventoryMutationInput, ListStockLocationsInput, ProductDto, ProductIdInput, ProductSkuInput, SetInventoryQuantityInput, StockLocationDto, StockMovementDto, UpdateProductInput } from "./types";

const skuOk=(sku:string)=>/^[A-Z0-9][A-Z0-9._-]{1,63}$/.test(sku);
const positive=(n:number)=>Number.isInteger(n)&&n>0; const nonneg=(n:number)=>Number.isInteger(n)&&n>=0;
const ro=<T extends object>(x:T):Readonly<T>=>Object.freeze({ ...x });
const product=(p:ProductRecord):ProductDto=>Object.freeze({...p, purchaseCurrency:"EUR", marketplace:Object.freeze({...p.marketplace})});
const inv=(i:InventoryState):InventoryDto=>ro(i); const movement=(m:StockMovementRecord):StockMovementDto=>ro(m); const location=(l:StockLocationRecord):StockLocationDto=>ro(l);
function map(e:unknown):never{ if(e instanceof DuplicateSkuError) throw new ProductAlreadyExistsError(); if(e instanceof ProductNotFoundError) throw new ProductNotFoundApplicationError(); if(e instanceof StaleProductVersionError||e instanceof StaleInventoryVersionError) throw new InventoryVersionConflictError(); if(e instanceof InventoryNotFoundError) throw new InventoryNotInitializedError(); if(e instanceof InsufficientStockError) throw new InsufficientInventoryError(); if(e instanceof StockLocationNotFoundError) throw new StockLocationNotFoundApplicationError(); if(e instanceof DuplicateStockLocationCodeError) throw new InventoryOperationConflictError(); throw e; }
const same=(m:StockMovementRecord,input:{productId:string;quantity:number;type:string;note?:string|null;orderId?:string|null;orderItemId?:string|null})=>m.productId===input.productId&&m.quantityDelta===input.quantity&&m.type===input.type&&(m.note??null)===(input.note??null)&&(m.orderId??null)===(input.orderId??null)&&(m.orderItemId??null)===(input.orderItemId??null);
async function replay(ctx:InventoryApplicationContext,input:{idempotencyKey?:string;productId:string;quantity:number;type:string;note?:string|null;orderId?:string|null;orderItemId?:string|null}){ if(!input.idempotencyKey) return null; const m=await ctx.stockMovementRepository.findByIdempotencyKey(input.idempotencyKey); if(!m) return null; if(!same(m,input)) throw new InventoryOperationConflictError(); const current=await ctx.inventoryRepository.findByProduct(input.productId); if(!current) throw new InventoryNotInitializedError(); return inv(current); }
function now(ctx:InventoryApplicationContext){ return ctx.clock.now().toISOString(); }
export const createGetProductUseCase=(ctx:InventoryApplicationContext)=>({execute:async({productId}:ProductIdInput)=>{const p=await ctx.productRepository.findById(productId); if(!p) throw new ProductNotFoundApplicationError(); return product(p);}});
export const createGetProductBySkuUseCase=(ctx:InventoryApplicationContext)=>({execute:async({sku}:ProductSkuInput)=>{const p=await ctx.productRepository.findBySku(sku); if(!p) throw new ProductNotFoundApplicationError(); return product(p);}});
export const createListProductsUseCase=(ctx:InventoryApplicationContext)=>({execute:async()=> (await ctx.productRepository.list()).map(product)});
export const createGetInventoryUseCase=(ctx:InventoryApplicationContext)=>({execute:async({productId}:ProductIdInput)=>{const i=await ctx.inventoryRepository.findByProduct(productId); if(!i) throw new InventoryNotInitializedError(); return inv(i);}});
export const createListInventoryByProductUseCase=(ctx:InventoryApplicationContext)=>({execute:async({productId}:ProductIdInput)=> (await ctx.inventoryRepository.listByProduct(productId)).map(inv)});
export const createListStockMovementsUseCase=(ctx:InventoryApplicationContext)=>({execute:async({productId}:ProductIdInput)=> (await ctx.stockMovementRepository.listByProduct(productId)).map(movement)});
export const createGetStockLocationUseCase=(ctx:InventoryApplicationContext)=>({execute:async({id}:GetStockLocationInput)=>{const l=await ctx.stockLocationRepository.findById(id); if(!l) throw new StockLocationNotFoundApplicationError(); return location(l);}});
export const createListStockLocationsUseCase=(ctx:InventoryApplicationContext)=>({execute:async(input:ListStockLocationsInput={})=> (await ctx.stockLocationRepository.list(input.warehouseId)).map(location)});
export const createProductUseCase=(ctx:InventoryApplicationContext)=>({execute:async(input:CreateProductInput)=>{ if(!skuOk(input.sku)) throw new InvalidSkuError(); if(input.purchaseCurrency&&input.purchaseCurrency!=="EUR") throw new InvalidInventoryQuantityError("Only EUR is supported"); if(!nonneg(input.stockQuantity??1)) throw new InvalidInventoryQuantityError(); if(await ctx.productRepository.existsBySku(input.sku)) throw new ProductAlreadyExistsError(); const t=now(ctx), id=ctx.idGenerator.newId(); try{return await ctx.unitOfWork.run(async({repositories})=> product(await repositories.inventoryRepositories.products.create({...input,id,createdAt:t,updatedAt:t,status:input.status??ProductStatus.Draft,purchaseCurrency:"EUR"})));}catch(e){map(e);}}});
export const createUpdateProductUseCase=(ctx:InventoryApplicationContext)=>({execute:async(input:UpdateProductInput)=>{ if(input.sku&&!skuOk(input.sku)) throw new InvalidSkuError(); if(input.purchaseCurrency&&input.purchaseCurrency!=="EUR") throw new InvalidInventoryQuantityError("Only EUR is supported"); const {id,expectedVersion,...patch}=input; try{return await ctx.unitOfWork.run(async({repositories})=> product(await repositories.inventoryRepositories.products.updateWithVersion(id,{...patch,updatedAt:now(ctx)},expectedVersion)));}catch(e){map(e);}}});
export const createInitializeInventoryUseCase=(ctx:InventoryApplicationContext)=>({execute:async(input:InitializeInventoryInput)=>{ if(!nonneg(input.quantity)) throw new InvalidInventoryQuantityError(); const rep=await replay(ctx,{...input,type:StockMovementType.ManualAdjustment,quantity:input.quantity}); if(rep) return rep; try{return await ctx.unitOfWork.run(async({repositories})=>{ const p=await repositories.inventoryRepositories.products.findById(input.productId); if(!p) throw new ProductNotFoundApplicationError(); if(p.stockQuantity!==1&&p.stockQuantity!==input.quantity) throw new InventoryAlreadyInitializedError(); const t=now(ctx); const state=input.expectedVersion? await repositories.inventoryRepositories.inventory.updateWithVersion(input.productId,input.quantity,input.expectedVersion,t): await repositories.inventoryRepositories.inventory.create({productId:input.productId,quantity:input.quantity,updatedAt:t}); await repositories.inventoryRepositories.stockMovements.append({id:ctx.idGenerator.newId(),productId:input.productId,type:StockMovementType.ManualAdjustment,quantityDelta:input.quantity,stockBefore:p.stockQuantity,stockAfter:input.quantity,orderId:null,orderItemId:null,note:input.note??null,idempotencyKey:input.idempotencyKey??null,createdAt:t,updatedAt:t}); return inv(state);});}catch(e){map(e);}}});
async function change(ctx:InventoryApplicationContext,input:InventoryMutationInput,sign:1|-1){ if(!positive(input.quantity)) throw new InvalidInventoryQuantityError(); const q=sign*input.quantity; const type=sign>0?StockMovementType.PurchaseReceipt:StockMovementType.Sale; const rep=await replay(ctx,{...input,type,quantity:q}); if(rep) return rep; try{return await ctx.unitOfWork.run(async({repositories})=>{ const cur=await repositories.inventoryRepositories.inventory.findByProduct(input.productId); if(!cur) throw new InventoryNotInitializedError(); const next=cur.quantity+q; if(next<0) throw new InsufficientInventoryError(); const t=now(ctx); const state=await repositories.inventoryRepositories.inventory.updateWithVersion(input.productId,next,input.expectedVersion,t); await repositories.inventoryRepositories.stockMovements.append({id:ctx.idGenerator.newId(),productId:input.productId,type,quantityDelta:q,stockBefore:cur.quantity,stockAfter:next,orderId:input.orderId??null,orderItemId:input.orderItemId??null,note:input.note??null,idempotencyKey:input.idempotencyKey??null,createdAt:t,updatedAt:t}); return inv(state);});}catch(e){map(e);}}
export const createIncreaseInventoryUseCase=(ctx:InventoryApplicationContext)=>({execute:(input:InventoryMutationInput)=>change(ctx,input,1)});
export const createDecreaseInventoryUseCase=(ctx:InventoryApplicationContext)=>({execute:(input:InventoryMutationInput)=>change(ctx,input,-1)});
export const createSetInventoryQuantityUseCase=(ctx:InventoryApplicationContext)=>({execute:async(input:SetInventoryQuantityInput)=>{ if(!nonneg(input.quantity)) throw new InvalidInventoryQuantityError(); if(!input.note.trim()) throw new InventoryOperationConflictError(); const cur0=await ctx.inventoryRepository.findByProduct(input.productId); const delta=(cur0?input.quantity-cur0.quantity:input.quantity); const rep=await replay(ctx,{...input,type:StockMovementType.ManualAdjustment,quantity:delta}); if(rep) return rep; try{return await ctx.unitOfWork.run(async({repositories})=>{ const cur=await repositories.inventoryRepositories.inventory.findByProduct(input.productId); if(!cur) throw new InventoryNotInitializedError(); const t=now(ctx); const state=await repositories.inventoryRepositories.inventory.updateWithVersion(input.productId,input.quantity,input.expectedVersion,t); await repositories.inventoryRepositories.stockMovements.append({id:ctx.idGenerator.newId(),productId:input.productId,type:StockMovementType.ManualAdjustment,quantityDelta:input.quantity-cur.quantity,stockBefore:cur.quantity,stockAfter:input.quantity,orderId:null,orderItemId:null,note:input.note,idempotencyKey:input.idempotencyKey??null,createdAt:t,updatedAt:t}); return inv(state);});}catch(e){map(e);}}});
export const createStockLocationUseCase=(ctx:InventoryApplicationContext)=>({execute:async(input:CreateStockLocationInput)=>{ try{return await ctx.unitOfWork.run(async({repositories})=> location(await repositories.inventoryRepositories.stockLocations.create({id:ctx.idGenerator.newId(),...input,createdAt:now(ctx),updatedAt:now(ctx)})));}catch(e){map(e);}}});
