export enum CarrierCode { A1Post = "a1post", UPS = "ups", DHL = "dhl", FedEx = "fedex", DPD = "dpd", GLS = "gls", PostNord = "postnord", LocalPickup = "local_pickup", Other = "other" }
export enum ShipmentStatus { Draft = "draft", Ready = "ready", LabelPending = "label_pending", LabelCreated = "label_created", InTransit = "in_transit", Delivered = "delivered", DeliveryFailed = "delivery_failed", Cancelled = "cancelled", Returned = "returned" }
export enum MarketplaceFulfillmentStatus { Pending = "pending", Submitted = "submitted", Accepted = "accepted", Failed = "failed", Cancelled = "cancelled" }
export enum ShippingError { Validation = "Validation", Authentication = "Authentication", Authorization = "Authorization", NotFound = "NotFound", RateLimit = "RateLimit", Timeout = "Timeout", Temporary = "Temporary", Permanent = "Permanent", Tracking = "Tracking", Fulfillment = "Fulfillment", Financial = "Financial", Conflict = "Conflict", Unknown = "Unknown" }
export const CARRIER_CODE_VALUES = Object.values(CarrierCode);
export const SHIPMENT_STATUS_VALUES = Object.values(ShipmentStatus);
export const MARKETPLACE_FULFILLMENT_STATUS_VALUES = Object.values(MarketplaceFulfillmentStatus);
export type ShipmentItem = { id: string; shipmentId: string; orderItemId: string; quantity: number; createdAt: string };
export type ShipmentEvent = { id: string; shipmentId: string; eventType: string; previousStatus?: ShipmentStatus | string; newStatus?: ShipmentStatus | string; payloadSnapshot?: unknown; errorCode?: string; errorMessage?: string; createdAt: string };
export type ShipmentTracking = { id: string; shipmentId: string; source: string; externalStatus?: string; normalizedStatus?: ShipmentStatus | string; location?: string; description?: string; occurredAt?: string; payloadSnapshot?: unknown; createdAt: string };
export type Shipment = { id: string; orderId: string; marketplaceOrderId?: string; channel?: string; carrierCode: CarrierCode | string; customCarrierName?: string; trackingNumber?: string; trackingUrl?: string; status: ShipmentStatus | string; shippingCost: number; currency: "EUR"; shippedAt?: string; deliveredAt?: string; cancelledAt?: string; returnedAt?: string; externalFulfillmentId?: string; marketplaceFulfillmentStatus?: MarketplaceFulfillmentStatus | string; lastError?: string; createdAt: string; updatedAt: string; items: ShipmentItem[] };
export type ShipmentUpdateResult = { shipment: Shipment; marketplaceStatus?: MarketplaceFulfillmentStatus | string; retryable?: boolean; error?: string };
export type CompleteSaleResult = { orderId: string; status: string; completedAt?: string; alreadyCompleted: boolean; financials?: SaleFinancials; issues: string[] };
export type SaleFinancials = { orderId: string; grossRevenue: number; shippingCharged: number; shippingCost: number; marketplaceFee: number | null; promotedFee: number | null; paymentFee: number | null; taxVat: number; itemCost: number; netRevenue: number; profit: number; currency: "EUR"; completedAt: string };
