export interface AdminMenuItem {
  label: string;
  href: string;
}

export const adminMenuItems: AdminMenuItem[] = [
  { label: "Dashboard", href: "/" },
  { label: "Live Visitors", href: "/live-visitors" },
  { label: "Products", href: "/products" },
  { label: "Marketplaces", href: "/marketplaces" },
  { label: "Marketplace Orders", href: "/marketplace-orders" },
  { label: "Marketplace Sync", href: "/marketplace-sync" },
  { label: "External Listings", href: "/external-listings" },
  { label: "Publish Jobs", href: "/publish-jobs" },
  { label: "Background Jobs", href: "/background-jobs" },
  { label: "Stock Sync", href: "/stock-sync" },
  { label: "Stock Conflicts", href: "/stock-sync/conflicts" },
  { label: "Categories", href: "/categories" },
  { label: "Collections", href: "/collections" },
  { label: "AI Drafts", href: "/ai-drafts" },
  { label: "Orders", href: "/orders" },
  { label: "Returns", href: "/returns" },
  { label: "Refunds", href: "/refunds" },
  { label: "Stock", href: "/stock" },
  { label: "Customers", href: "/customers" },
  { label: "Offers", href: "/offers" },
  { label: "Marketing", href: "/marketing" },
  { label: "Reports", href: "/reports" },
  { label: "Analytics", href: "/analytics" },
  { label: "Shipping", href: "/shipping" },
  { label: "Shipments", href: "/shipments" },
  { label: "Complete Sales", href: "/complete-sales" },
  { label: "Payments", href: "/payments" },
  { label: "Currencies", href: "/currencies" },
  { label: "Coupons", href: "/coupons" },
  { label: "Pages", href: "/pages" },
  { label: "Blog / Stories", href: "/blog" },
  { label: "SEO", href: "/seo" },
  { label: "AI Support", href: "/ai-support" },
  { label: "Users & Roles", href: "/users-roles" },
  { label: "Settings", href: "/settings" },
];
