import { randomUUID } from "node:crypto";
import { BadRequestError, NotFoundError } from "../../services/errors";
import { OrderStatus, ReturnResolution, ReturnStatus, ReturnStockDisposition, StockMovementType } from "@noctella/shared";
import type { UnitOfWork } from "../../services/unitOfWork";

export interface ReturnPorts { getOrder(id:string): any; getOrderItem(id:string): any; getProduct(id:string): any; enqueueStockSync(productId:string,key:string): void }
export interface ReturnApplicationContext { unitOfWork: UnitOfWork; ports: ReturnPorts; clock?:()=>string; idGenerator?:()=>string }
const now=(c:ReturnApplicationContext)=>c.clock?.()??new Date().toISOString(); const id=(c:ReturnApplicationContext)=>c.idGenerator?.()??randomUUID();
const active=[ReturnStatus.Requested,ReturnStatus.Authorized,ReturnStatus.AwaitingShipment,ReturnStatus.InTransit,ReturnStatus.Received,ReturnStatus.Inspecting,ReturnStatus.Approved,ReturnStatus.PartiallyApproved].map(String);
const qty=(i:any)=>Number(i.quantityApproved??i.quantityReceived??i.quantityRequested??0);
function detail(repos:any,id:string){const d=repos.returns.read.getReturnDetailProjection(id); if(!d) throw new NotFoundError("Return not found"); return d;}
function event(c:ReturnApplicationContext,repos:any,r:any,type:string,prev:any,next:any,payload:any){return repos.events.write.append({id:id(c),returnRequestId:r.id,orderId:r.orderId,eventType:type,previousStatus:prev??null,newStatus:next??null,payloadSnapshot:payload??{},errorCode:null,errorMessage:null,idempotencyKey:`${type}:${r.id}:${next??"same"}:${prev??"none"}`,createdAt:now(c)});}
async function transition(c:ReturnApplicationContext,idv:string,to:ReturnStatus,type:string,allowed:ReturnStatus[],patch:any={}){return c.unitOfWork.run(({repositories})=>{const repos=repositories.returnRepositories; const r=repos.returns.read.getById(idv) as any; if(!r) throw new NotFoundError("Return not found"); if(!allowed.map(String).includes(String(r.status))) throw new BadRequestError("Invalid return status transition"); const updatedAt=now(c); const next=repos.returns.write.updateWithExpectedVersion(idv,{...patch,status:to,updatedAt},r.version) as any; if(!next.ok) throw new BadRequestError("Return was updated by another transaction"); event(c,repos,r,type,r.status,to,patch); return detail(repos,idv);});}
export async function createReturnUseCase(c:ReturnApplicationContext,input:any){return c.unitOfWork.run(({repositories})=>{const repos=repositories.returnRepositories; if(input.idempotencyKey){const ex=repos.returns.write.findByIdempotencyKey(input.idempotencyKey) as any; if(ex){ const exItems=repos.items.read.listByReturn(ex.id) as any[]; if(JSON.stringify(exItems.map(i=>({orderItemId:i.orderItemId,quantityRequested:i.quantityRequested})))!==JSON.stringify((input.items??[]).map((i:any)=>({orderItemId:i.orderItemId,quantityRequested:i.quantityRequested})))) throw new BadRequestError("Idempotency payload conflict"); return detail(repos,ex.id);} }
 const ext=input.externalReference??input.externalReturnId; if(ext){const ex=repos.returns.write.findByExternalReference(ext) as any; if(ex) return detail(repos,ex.id);} const order=c.ports.getOrder(input.orderId); if(!order) throw new NotFoundError("Order not found"); if(![OrderStatus.Completed,OrderStatus.Shipped].includes(order.status)) throw new BadRequestError("Only fulfilled or completed orders can be returned"); const t=now(c); const rid=id(c); const row={id:rid,orderId:input.orderId,marketplaceOrderId:input.marketplaceOrderId??null,shipmentId:input.shipmentId??null,channel:input.channel??null,externalReturnId:input.externalReturnId??null,externalReturnNumber:input.externalReturnNumber??null,externalReference:input.externalReference??input.externalReturnId??null,idempotencyKey:input.idempotencyKey??null,status:ReturnStatus.Requested,reason:input.reason,reasonDetails:input.reasonDetails??null,requestedResolution:input.requestedResolution??ReturnResolution.Refund,approvedResolution:null,buyerMessage:input.buyerMessage??null,internalNote:input.internalNote??null,requestedAt:t,authorizedAt:null,receivedAt:null,inspectedAt:null,completedAt:null,cancelledAt:null,returnCarrierCode:input.returnCarrierCode??null,returnTrackingNumber:input.returnTrackingNumber??null,returnTrackingUrl:input.returnTrackingUrl??null,buyerShippedAt:null,lastError:null,version:0,createdAt:t,updatedAt:t}; repos.returns.write.create(row as any);
 for(const it of input.items??[]){const oi=c.ports.getOrderItem(it.orderItemId); if(!oi) throw new NotFoundError("Order item not found"); if(oi.orderId!==input.orderId) throw new BadRequestError("Order item does not belong to order"); if(!c.ports.getProduct(oi.productId)) throw new NotFoundError("Product not found"); const q=Number(it.quantityRequested); if(!Number.isInteger(q)||q<=0) throw new BadRequestError("Return quantity must be a positive integer"); const already=repos.items.read.getReturnedQuantityByOrderItem(it.orderItemId) as number; if(already+q>oi.quantity) throw new BadRequestError("Cumulative return quantity exceeds purchased quantity"); repos.items.write.create({id:id(c),returnRequestId:rid,orderItemId:it.orderItemId,productId:oi.productId,quantityRequested:q,quantityApproved:null,quantityReceived:null,quantityCompleted:null,condition:null,stockDisposition:null,inspectionNote:null,inspectionResult:null,completedAt:null,createdAt:t,updatedAt:t});}
 event(c,repos,row,"requested",null,ReturnStatus.Requested,input); return detail(repos,rid);});}
export const getReturnDetailUseCase=(c:ReturnApplicationContext,id:string)=>c.unitOfWork.run(({repositories})=>detail(repositories.returnRepositories,id));
export const listReturnsUseCase=(c:ReturnApplicationContext,q:any={})=>c.unitOfWork.run(({repositories})=>(repositories.returnRepositories.returns.read.list({orderId:q.orderId,status:q.status,reason:q.reason,limit:Number(q.pageSize??50),offset:(Number(q.page??1)-1)*Number(q.pageSize??50)}) as any).rows);
export const updateReturnUseCase=(c:ReturnApplicationContext,idv:string,input:any)=>c.unitOfWork.run(({repositories})=>{const repos=repositories.returnRepositories; const r=repos.returns.read.getById(idv) as any; if(!r) throw new NotFoundError("Return not found"); const out=repos.returns.write.updateWithExpectedVersion(idv,{...input,updatedAt:now(c)},r.version) as any; if(!out.ok) throw new BadRequestError("Return was updated by another transaction"); return detail(repos,idv);});
export const authorizeReturnUseCase=(c:ReturnApplicationContext,id:string,input:any={})=>transition(c,id,ReturnStatus.Authorized,"authorized",[ReturnStatus.Requested],{authorizedAt:now(c),approvedResolution:input.approvedResolution??input.resolution??null});
export const rejectReturnUseCase=(c:ReturnApplicationContext,id:string,input:any={})=>transition(c,id,ReturnStatus.Rejected,"rejected",[ReturnStatus.Requested,ReturnStatus.Authorized],{internalNote:input.internalNote??null});
export const markReturnInTransitUseCase=(c:ReturnApplicationContext,id:string,input:any={})=>transition(c,id,ReturnStatus.InTransit,"in_transit",[ReturnStatus.Authorized,ReturnStatus.AwaitingShipment],{returnCarrierCode:input.returnCarrierCode??null,returnTrackingNumber:input.returnTrackingNumber??null,returnTrackingUrl:input.returnTrackingUrl??null,buyerShippedAt:input.buyerShippedAt??now(c)});
export const receiveReturnUseCase=(c:ReturnApplicationContext,id:string,input:any={})=>transition(c,id,ReturnStatus.Received,"received",[ReturnStatus.Authorized,ReturnStatus.InTransit],{receivedAt:input.receivedAt??now(c)});
export async function inspectReturnUseCase(c:ReturnApplicationContext,idv:string,input:any){return c.unitOfWork.run(({repositories})=>{const repos=repositories.returnRepositories; const r=repos.returns.read.getById(idv) as any; if(!r) throw new NotFoundError("Return not found"); if(![ReturnStatus.Received,ReturnStatus.Inspecting].map(String).includes(String(r.status))) throw new BadRequestError("Return must be received before inspection"); const items=repos.items.read.listByReturn(idv) as any[]; const item=items.find(i=>i.orderItemId===input.orderItemId); if(!item) throw new NotFoundError("Return item not found"); const rec=Number(input.quantityReceived??item.quantityRequested); if(rec>item.quantityRequested) throw new BadRequestError("Received quantity exceeds requested quantity"); repos.items.write.updateReceivedQuantity(item.id,rec,now(c)); repos.items.write.updateInspectionResult(item.id,{...(input.inspectionResult??{}),stockDisposition:input.stockDisposition??null},input.condition??null,input.inspectionNote??null,now(c)); repos.returns.write.updateInspectionState({id:idv,status:ReturnStatus.Inspecting,inspectedAt:now(c),updatedAt:now(c),expectedVersion:r.version}); event(c,repos,r,"item_inspected",r.status,ReturnStatus.Inspecting,input); return detail(repos,idv);});}
export const approveReturnUseCase=(c:ReturnApplicationContext,id:string,input:any={})=>transition(c,id,input.partial?ReturnStatus.PartiallyApproved:ReturnStatus.Approved,"approved",[ReturnStatus.Inspecting,ReturnStatus.Received],{approvedResolution:input.approvedResolution??ReturnResolution.Refund});
export async function completeReturnUseCase(c:ReturnApplicationContext,idv:string){const sync:string[]=[]; const res=await c.unitOfWork.run(({repositories})=>{const repos=repositories.returnRepositories; const r=repos.returns.read.getById(idv) as any; if(!r) throw new NotFoundError("Return not found"); if(r.completedAt||String(r.status)===String(ReturnStatus.Completed)) return detail(repos,idv); if(![ReturnStatus.Approved,ReturnStatus.PartiallyApproved].map(String).includes(String(r.status))) throw new BadRequestError("Return is not approved"); const t=now(c); for(const item of repos.items.write.listForUpdate(idv) as any[]){const qn=qty(item); if(item.stockDisposition===ReturnStockDisposition.ReturnToStock&&item.productId&&qn>0){const base=(repositories.stock.stockMovements.read.getProductBaseStock(item.productId) as any); if(base===undefined) throw new NotFoundError("Product not found"); const key=`return-in:${idv}:${item.id}`; const ex=repositories.stock.stockMovements.read.findByIdempotencyKey(key) as any; if(!ex) repositories.stock.stockMovements.write.create({id:id(c),productId:item.productId,type:StockMovementType.ReturnIn,quantityDelta:qn,stockBefore:Number(base),stockAfter:Number(base)+qn,orderId:r.orderId,orderItemId:item.orderItemId,note:`Return ${idv}`,idempotencyKey:key,createdAt:t,updatedAt:t}); sync.push(item.productId);} repos.items.write.updateCompletionState(item.id,qn,t,t);} repos.returns.write.updateCompletionState({id:idv,status:ReturnStatus.Completed,completedAt:t,updatedAt:t,expectedVersion:r.version}); event(c,repos,r,"completed",r.status,ReturnStatus.Completed,{}); return detail(repos,idv);}); for(const p of [...new Set(sync)]) c.ports.enqueueStockSync(p,`return-in:${idv}:${p}`); return res;}
export const cancelReturnUseCase=(c:ReturnApplicationContext,id:string,input:any={})=>transition(c,id,ReturnStatus.Cancelled,"cancelled",[ReturnStatus.Requested,ReturnStatus.Authorized,ReturnStatus.AwaitingShipment,ReturnStatus.InTransit],{cancelledAt:now(c),internalNote:input.internalNote??null});
export const getReturnReadinessUseCase=async(c:ReturnApplicationContext,id:string)=>{const r:any=await getReturnDetailUseCase(c,id); return {ready:!r.lastError,reasons:r.lastError?[r.lastError]:[],allowedActions:["authorize","reject","in-transit","receive","inspect","approve","complete","cancel"]};};
export const getReturnEventsUseCase=(c:ReturnApplicationContext,id:string)=>c.unitOfWork.run(({repositories})=>repositories.returnRepositories.events.read.listByReturn(id));
