import { capabilities, type RefundProviderCapabilities } from "../providerCapabilities";
import { createRefundProviderRegistry } from "../refundProviderRegistry";
import type { MarketplaceRefundPort } from "../marketplaceRefundPort";
import type { PaymentRefundPort } from "../paymentRefundPort";
import type { RefundCancelRequest, RefundExecutionRequest, RefundProviderResponse, RefundStatusRequest } from "../types";
import { unsupportedRefundCapability } from "../errors";
interface FakeOptions { capabilities?: Partial<RefundProviderCapabilities>; executeResult?: RefundProviderResponse; cancelResult?: RefundProviderResponse; statusResult?: RefundProviderResponse; }
const ok: RefundProviderResponse = { outcome:"success", externalRefundId:"fake-refund", providerStatus:"succeeded" };
export class FakeMarketplaceRefundProvider implements MarketplaceRefundPort { readonly calls: Array<{operation:string; request:unknown}> = []; readonly capabilities: RefundProviderCapabilities; constructor(private readonly options: FakeOptions = {}){ this.capabilities=capabilities(options.capabilities); } async executeRefund(request: RefundExecutionRequest){ this.calls.push({operation:"execute",request}); if(!this.capabilities.supportsExecuteRefund) throw unsupportedRefundCapability("executeRefund", "fake-marketplace"); return this.options.executeResult ?? ok; } async cancelRefund(request: RefundCancelRequest){ this.calls.push({operation:"cancel",request}); if(!this.capabilities.supportsCancelRefund) throw unsupportedRefundCapability("cancelRefund", "fake-marketplace"); return this.options.cancelResult ?? {outcome:"success",externalRefundId:request.externalRefundId??request.refundId,providerStatus:"cancelled"}; } async getRefundStatus(request: RefundStatusRequest){ this.calls.push({operation:"status",request}); if(!this.capabilities.supportsRefundStatus) throw unsupportedRefundCapability("getRefundStatus", "fake-marketplace"); return this.options.statusResult ?? {outcome:"success",externalRefundId:request.externalRefundId??request.refundId,providerStatus:"unknown"}; } }
export class FakePaymentRefundProvider implements PaymentRefundPort { readonly calls: Array<{operation:string; request:unknown}> = []; readonly capabilities: RefundProviderCapabilities; constructor(private readonly options: FakeOptions = {}){ this.capabilities=capabilities(options.capabilities); } async executeRefund(request: RefundExecutionRequest){ this.calls.push({operation:"execute",request}); if(!this.capabilities.supportsExecuteRefund) throw unsupportedRefundCapability("executeRefund", "fake-payment"); return this.options.executeResult ?? ok; } async cancelRefund(request: RefundCancelRequest){ this.calls.push({operation:"cancel",request}); if(!this.capabilities.supportsCancelRefund) throw unsupportedRefundCapability("cancelRefund", "fake-payment"); return this.options.cancelResult ?? {outcome:"success",externalRefundId:request.externalRefundId??request.refundId,providerStatus:"cancelled"}; } async getRefundStatus(request: RefundStatusRequest){ this.calls.push({operation:"status",request}); if(!this.capabilities.supportsRefundStatus) throw unsupportedRefundCapability("getRefundStatus", "fake-payment"); return this.options.statusResult ?? {outcome:"success",externalRefundId:request.externalRefundId??request.refundId,providerStatus:"unknown"}; } }
export const createFakeRefundProviderRegistry = (input: { marketplace?: Record<string, MarketplaceRefundPort>; payment?: Record<string, PaymentRefundPort> } = {}) => createRefundProviderRegistry({ marketplaceProviders: Object.entries(input.marketplace ?? {}).map(([providerId, provider])=>({providerId, provider})), paymentProviders: Object.entries(input.payment ?? {}).map(([providerId, provider])=>({providerId, provider})) });
