import type { PurchaseLineRecord, PurchaseReceiptRecord, PurchaseRecord, SupplierRecord } from "../../repositories/purchase/types";
export type SupplierOutput=Readonly<SupplierRecord>; export type PurchaseOutput=Readonly<PurchaseRecord>; export type ReceiptOutput=Readonly<PurchaseReceiptRecord>;
export interface CreateSupplierInput{readonly erpReferenceId?:string|null;readonly name:string;readonly supplierType?:string;readonly countryCode?:string|null;readonly city?:string|null;readonly email?:string|null;readonly phone?:string|null;readonly website?:string|null;readonly taxNumber?:string|null;readonly notes?:string|null;readonly status?:string}
export interface UpdateSupplierInput extends Partial<Omit<CreateSupplierInput,"erpReferenceId">>{readonly id:string;readonly expectedVersion?:string}
export interface CreatePurchaseLineInput{readonly productId?:string|null;readonly sourceLineReference?:string|null;readonly titleSnapshot:string;readonly quantity:number;readonly unitPurchaseCost:number;readonly weight?:number|null;readonly manualAllocatedCost?:number|null}
export interface CreatePurchaseInput{readonly erpReferenceId?:string|null;readonly supplierId?:string|null;readonly sourceType?:string;readonly externalReference?:string|null;readonly invoiceReferenceNumber?:string|null;readonly auctionHouse?:string|null;readonly auctionDate?:string|null;readonly currency?:"EUR";readonly buyerPremium?:number|null;readonly shippingCost?:number|null;readonly customsCost?:number|null;readonly packagingCost?:number|null;readonly taxVat?:number|null;readonly miscellaneousCost?:number|null;readonly status?:string;readonly orderedAt?:string|null;readonly notes?:string|null;readonly lines:readonly CreatePurchaseLineInput[]}
export interface UpdatePurchaseInput extends Partial<Omit<CreatePurchaseInput,"lines"|"currency">>{readonly id:string;readonly currency?:"EUR";readonly expectedVersion?:string}
export interface PurchaseIdInput{readonly id:string} export interface ListPurchasesInput{readonly status?:string;readonly supplierId?:string;readonly limit?:number;readonly offset?:number} export interface ListSuppliersInput{readonly status?:string;readonly limit?:number;readonly offset?:number}
export interface AddPurchaseLineInput extends CreatePurchaseLineInput{readonly purchaseId:string;readonly expectedVersion?:string}
export interface UpdatePurchaseLineInput extends Partial<CreatePurchaseLineInput>{readonly purchaseId:string;readonly lineId:string;readonly expectedVersion?:string}
export interface RemovePurchaseLineInput{readonly purchaseId:string;readonly lineId:string;readonly expectedVersion?:string}
export interface ReceivePurchaseInput{readonly purchaseId:string;readonly idempotencyKey:string;readonly receivedAt?:string;readonly note?:string|null;readonly lines:readonly {readonly purchaseLineId:string;readonly quantityReceived:number}[]}
export interface CancelPurchaseInput{readonly id:string;readonly expectedVersion?:string}
export interface MarkPurchaseOrderedInput{readonly id:string;readonly expectedVersion?:string}
export type PurchaseReceiptResult=Readonly<{purchase:PurchaseRecord;receipt:PurchaseReceiptRecord;replayed:boolean}>;
