import type { PurchaseApplicationContext } from "../../services/purchaseApplicationContext";
import type { PurchaseLineRecord, PurchaseRecord, SupplierRecord } from "../../repositories/purchase/types";
import { DuplicatePurchaseReferenceError, PurchaseReceiptIdempotencyConflictError } from "../../repositories/purchase/errors";
import { InvalidPurchaseQuantityError, InvalidPurchaseStatusTransitionError, PurchaseConcurrencyConflictError, PurchaseDuplicateReferenceError, PurchaseNotFoundError, PurchaseReceiptConflictError, PurchaseValidationError, SupplierDuplicateReferenceError, SupplierNotFoundError } from "./errors";
import type { AddPurchaseLineInput, CancelPurchaseInput, CreatePurchaseInput, CreateSupplierInput, ListPurchasesInput, ListSuppliersInput, MarkPurchaseOrderedInput, PurchaseIdInput, ReceivePurchaseInput, RemovePurchaseLineInput, UpdatePurchaseInput, UpdatePurchaseLineInput, UpdateSupplierInput } from "./types";

const ro=<T extends object>(x:T):Readonly<T>=>Object.freeze({...x});
const supplier=(s:SupplierRecord)=>ro(s); const purchase=(p:PurchaseRecord)=>Object.freeze({...p,lines:Object.freeze([...p.lines])});
const now=(ctx:PurchaseApplicationContext)=>ctx.clock.now().toISOString();
const norm=(s:string)=>s.trim().replace(/\s+/g," ").toLocaleLowerCase("en-US");
const num=(v:number|null|undefined)=>v==null?null:Number(v);
function totalOf(p:Pick<PurchaseRecord,"itemSubtotal"|"buyerPremium"|"shippingCost"|"customsCost"|"packagingCost"|"taxVat"|"miscellaneousCost">){const xs=[p.itemSubtotal,p.buyerPremium,p.shippingCost,p.customsCost,p.packagingCost,p.taxVat,p.miscellaneousCost]; return xs.some(x=>x==null)?null:xs.reduce((a:number,x)=>a+Number(x),0);}
function assertEur(c?:string|null){if(c&&c!=="EUR") throw new PurchaseValidationError("Purchasing accounting is EUR only");}
function assertEditable(p:PurchaseRecord){if(["Ordered","PartiallyReceived","Received","Cancelled"].includes(p.status)) throw new InvalidPurchaseStatusTransitionError("Purchase cannot be edited in current status");}
function assertLine(l:{quantity?:number;unitPurchaseCost?:number}){if(l.quantity!==undefined&&(!Number.isInteger(l.quantity)||l.quantity<=0)) throw new InvalidPurchaseQuantityError("Purchase line quantity must be a positive integer"); if(l.unitPurchaseCost!==undefined&&Number(l.unitPurchaseCost)<0) throw new PurchaseValidationError("Purchase cost cannot be negative");}
function map(e:unknown):never{if(e instanceof DuplicatePurchaseReferenceError) throw new PurchaseDuplicateReferenceError(); if(e instanceof PurchaseReceiptIdempotencyConflictError) throw new PurchaseReceiptConflictError(); throw e;}
function sameReceipt(a:any,input:ReceivePurchaseInput){return a.purchaseId===input.purchaseId&&a.lines.length===input.lines.length&&a.lines.every((l:any)=>input.lines.some(x=>x.purchaseLineId===l.purchaseLineId&&x.quantityReceived===l.quantityReceived));}
async function loadPurchase(ctx:PurchaseApplicationContext,id:string){const p=await ctx.purchaseRepository.findById(id); if(!p) throw new PurchaseNotFoundError(); return p;}
export const createSupplierUseCase=(ctx:PurchaseApplicationContext)=>({execute:async(input:CreateSupplierInput)=>{const name=String(input.name??"").trim(); if(!name) throw new PurchaseValidationError("Supplier name is required"); const t=now(ctx), id=ctx.idGenerator.newId(); try{return supplier(await ctx.unitOfWork.run(({repositories})=>repositories.purchaseRepositories.suppliers.create({id,erpReferenceId:input.erpReferenceId??null,name,normalizedName:norm(name),supplierType:input.supplierType??"Other",countryCode:input.countryCode??null,city:input.city??null,email:input.email??null,phone:input.phone??null,website:input.website??null,taxNumber:input.taxNumber??null,notes:input.notes??null,status:input.status??"Active",createdAt:t,updatedAt:t})));}catch(e){map(e)}}});
export const updateSupplierUseCase=(ctx:PurchaseApplicationContext)=>({execute:async(input:UpdateSupplierInput)=>{const cur=await ctx.supplierRepository.findById(input.id); if(!cur) throw new SupplierNotFoundError(); const {id,expectedVersion,...rest}=input; const patch:any={...rest,updatedAt:now(ctx)}; if(patch.name!==undefined){patch.name=String(patch.name).trim(); if(!patch.name) throw new PurchaseValidationError("Supplier name is required"); patch.normalizedName=norm(patch.name);} const r=await ctx.unitOfWork.run(({repositories})=>expectedVersion?repositories.purchaseRepositories.suppliers.updateWithVersion(id,expectedVersion,patch):repositories.purchaseRepositories.suppliers.update(id,patch)); if(!r) throw new SupplierNotFoundError(); if("ok" in r){if(!r.ok){if((r as any).issue.code==="optimistic_conflict") throw new PurchaseConcurrencyConflictError(); throw new SupplierNotFoundError()} return supplier((r as any).value)} return supplier(r);}});
export const getSupplierUseCase=(ctx:PurchaseApplicationContext)=>({execute:async({id}:PurchaseIdInput)=>{const s=await ctx.supplierRepository.findById(id); if(!s) throw new SupplierNotFoundError(); return supplier(s);}});
export const listSuppliersUseCase=(ctx:PurchaseApplicationContext)=>({execute:async(input:ListSuppliersInput={})=>(await ctx.supplierRepository.list(input)).map(supplier)});
export const createPurchaseUseCase=(ctx:PurchaseApplicationContext)=>({execute:async(input:CreatePurchaseInput)=>{assertEur(input.currency); if(!input.lines?.length) throw new PurchaseValidationError("Purchase requires at least one line"); for(const l of input.lines) assertLine(l); const t=now(ctx), id=ctx.idGenerator.newId(); const itemSubtotal=input.lines.reduce((a,l)=>a+l.quantity*l.unitPurchaseCost,0); const base={itemSubtotal,buyerPremium:num(input.buyerPremium),shippingCost:num(input.shippingCost),customsCost:num(input.customsCost),packagingCost:num(input.packagingCost),taxVat:num(input.taxVat),miscellaneousCost:num(input.miscellaneousCost)}; try{return purchase(await ctx.unitOfWork.run(({repositories})=>repositories.purchaseRepositories.purchases.create({id,erpReferenceId:input.erpReferenceId??null,supplierId:input.supplierId??null,sourceType:input.sourceType??"Other",externalReference:input.externalReference??null,invoiceReferenceNumber:input.invoiceReferenceNumber??null,auctionHouse:input.auctionHouse??null,auctionDate:input.auctionDate??null,currency:"EUR",...base,totalCost:totalOf(base),status:input.status??"Draft",orderedAt:input.orderedAt??null,receivedAt:null,notes:input.notes??null,createdAt:t,updatedAt:t,lines:input.lines.map(l=>({id:ctx.idGenerator.newId(),productId:l.productId??null,sourceLineReference:l.sourceLineReference??null,titleSnapshot:l.titleSnapshot,quantity:l.quantity,receivedQuantity:0,unitPurchaseCost:l.unitPurchaseCost,weight:l.weight??null,manualAllocatedCost:l.manualAllocatedCost??null,createdAt:t,updatedAt:t}))})));}catch(e){map(e)}}});
export const updatePurchaseUseCase=(ctx:PurchaseApplicationContext)=>({execute:async(input:UpdatePurchaseInput)=>{assertEur(input.currency); const cur=await loadPurchase(ctx,input.id); assertEditable(cur); const {id,expectedVersion,currency,...rest}=input; const patch:any={...rest,updatedAt:now(ctx)}; patch.totalCost=totalOf({...cur,...patch}); const r=await ctx.unitOfWork.run(({repositories})=>expectedVersion?repositories.purchaseRepositories.purchases.updateWithVersion(id,expectedVersion,patch):repositories.purchaseRepositories.purchases.update(id,patch)); if(!r) throw new PurchaseNotFoundError(); if("ok" in r){if(!r.ok){if((r as any).issue.code==="optimistic_conflict") throw new PurchaseConcurrencyConflictError(); throw new PurchaseNotFoundError()} return purchase((r as any).value)} return purchase(r);}});
export const addPurchaseLineUseCase=(ctx:PurchaseApplicationContext)=>({execute:async(input:AddPurchaseLineInput)=>{const p=await loadPurchase(ctx,input.purchaseId); assertEditable(p); assertLine(input); const t=now(ctx); const out=await ctx.unitOfWork.run(({repositories})=>repositories.purchaseRepositories.purchases.addLine({id:ctx.idGenerator.newId(),purchaseId:input.purchaseId,productId:input.productId??null,sourceLineReference:input.sourceLineReference??null,titleSnapshot:input.titleSnapshot,quantity:input.quantity,receivedQuantity:0,unitPurchaseCost:input.unitPurchaseCost,weight:input.weight??null,manualAllocatedCost:input.manualAllocatedCost??null,createdAt:t,updatedAt:t})); return ro(out);}});
export const updatePurchaseLineUseCase=(ctx:PurchaseApplicationContext)=>({execute:async(input:UpdatePurchaseLineInput)=>{const p=await loadPurchase(ctx,input.purchaseId); assertEditable(p); if(!p.lines.some(l=>l.id===input.lineId)) throw new PurchaseNotFoundError(); assertLine(input); const {purchaseId,lineId,...patch}=input; const out=await ctx.unitOfWork.run(({repositories})=>repositories.purchaseRepositories.purchases.updateLine(lineId,{...patch,updatedAt:now(ctx)})); if(!out) throw new PurchaseNotFoundError(); return ro(out);}});
export const removePurchaseLineUseCase=(ctx:PurchaseApplicationContext)=>({execute:async(input:RemovePurchaseLineInput)=>{const p=await loadPurchase(ctx,input.purchaseId); assertEditable(p); if(!p.lines.some(l=>l.id===input.lineId)) throw new PurchaseNotFoundError(); const ok=await ctx.unitOfWork.run(({repositories})=>repositories.purchaseRepositories.purchases.removeLine(input.lineId)); if(!ok) throw new PurchaseNotFoundError(); return ro({removed:true});}});
export const markPurchaseOrderedUseCase=(ctx:PurchaseApplicationContext)=>({execute:async(input:MarkPurchaseOrderedInput)=>{const p=await loadPurchase(ctx,input.id); if(p.status!=="Draft") throw new InvalidPurchaseStatusTransitionError(); const t=now(ctx); const r=await ctx.unitOfWork.run(({repositories})=>input.expectedVersion?repositories.purchaseRepositories.purchases.updateWithVersion(input.id,input.expectedVersion,{status:"Ordered",orderedAt:t,updatedAt:t}):repositories.purchaseRepositories.purchases.update(input.id,{status:"Ordered",orderedAt:t,updatedAt:t})); if(!r) throw new PurchaseNotFoundError(); if("ok" in r){if(!r.ok) throw new PurchaseConcurrencyConflictError(); return purchase(r.value)} return purchase(r);}});
export const cancelPurchaseUseCase=(ctx:PurchaseApplicationContext)=>({execute:async(input:CancelPurchaseInput)=>{const p=await loadPurchase(ctx,input.id); if(["Received","PartiallyReceived"].includes(p.status)) throw new InvalidPurchaseStatusTransitionError("Received purchases cannot be cancelled"); const r=await ctx.unitOfWork.run(({repositories})=>input.expectedVersion?repositories.purchaseRepositories.purchases.updateWithVersion(input.id,input.expectedVersion,{status:"Cancelled",updatedAt:now(ctx)}):repositories.purchaseRepositories.purchases.update(input.id,{status:"Cancelled",updatedAt:now(ctx)})); if(!r) throw new PurchaseNotFoundError(); if("ok" in r){if(!r.ok) throw new PurchaseConcurrencyConflictError(); return purchase(r.value)} return purchase(r);}});
export const getPurchaseUseCase=(ctx:PurchaseApplicationContext)=>({execute:async({id}:PurchaseIdInput)=>purchase(await loadPurchase(ctx,id))});
export const listPurchasesUseCase=(ctx:PurchaseApplicationContext)=>({execute:async(input:ListPurchasesInput={})=>{const r=await ctx.purchaseRepository.list(input); return Object.freeze({...r,rows:Object.freeze(r.rows.map(purchase))});}});
export const receivePurchaseUseCase=(ctx:PurchaseApplicationContext)=>({execute:async(input:ReceivePurchaseInput)=>{const existing=await ctx.purchaseReceiptRepository.findByIdempotencyKey(input.idempotencyKey); if(existing){if(!sameReceipt(existing,input)) throw new PurchaseReceiptConflictError(); return ro({purchase:await loadPurchase(ctx,input.purchaseId),receipt:existing,replayed:true});} const p=await loadPurchase(ctx,input.purchaseId); if(p.status==="Cancelled") throw new InvalidPurchaseStatusTransitionError("Cancelled purchases cannot be received"); if(!input.lines.length) throw new PurchaseValidationError("Receipt requires lines"); let receipt:any; const updated=await ctx.unitOfWork.run(async ({repositories})=>{const cur=await repositories.purchaseRepositories.purchases.findById(input.purchaseId); if(!cur) throw new PurchaseNotFoundError(); const t=now(ctx), rid=ctx.idGenerator.newId(); const rlines:any[]=[]; for(const x of input.lines){const line=cur.lines.find((l:PurchaseLineRecord)=>l.id===x.purchaseLineId); if(!line) throw new PurchaseNotFoundError(); const qty=Number(x.quantityReceived); if(!Number.isInteger(qty)||qty<=0||line.receivedQuantity+qty>line.quantity) throw new InvalidPurchaseQuantityError("Invalid receipt quantity"); let stockMovementId=null; if(line.productId){const inv=await repositories.inventoryRepositories.inventory.findByProduct(line.productId); if(!inv) throw new PurchaseValidationError("Inventory is not initialized"); const next=inv.quantity+qty; await repositories.inventoryRepositories.inventory.updateWithVersion(line.productId,next,inv.updatedAt,t); const m=await repositories.inventoryRepositories.stockMovements.append({id:ctx.idGenerator.newId(),productId:line.productId,type:"PurchaseReceipt",quantityDelta:qty,stockBefore:inv.quantity,stockAfter:next,orderId:null,orderItemId:null,note:`Purchase receipt ${input.purchaseId}`,idempotencyKey:`purchase-receipt:${input.idempotencyKey}:${line.id}`,createdAt:t,updatedAt:t}); stockMovementId=m.id;} rlines.push({id:ctx.idGenerator.newId(),receiptId:rid,purchaseLineId:line.id,quantityReceived:qty,stockMovementId,createdAt:t}); await repositories.purchaseRepositories.purchases.updateLine(line.id,{receivedQuantity:line.receivedQuantity+qty,updatedAt:t});} receipt=await repositories.purchaseRepositories.receipts.append({id:rid,purchaseId:input.purchaseId,idempotencyKey:input.idempotencyKey,receivedAt:input.receivedAt??t,note:input.note??null,createdAt:t,lines:rlines}); const after=(await repositories.purchaseRepositories.purchases.findById(input.purchaseId))!; const full=after.lines.every(l=>l.receivedQuantity>=l.quantity); return (await repositories.purchaseRepositories.purchases.update(input.purchaseId,{status:full?"Received":"PartiallyReceived",receivedAt:full?t:null,updatedAt:t}))!;}); return ro({purchase:updated,receipt,replayed:false});}});
