import { and, asc, desc, eq, sql } from "drizzle-orm";
import * as sqliteSchema from "../../db/schema.sqlite";
import type { AppendRefundEventInput, CreateRefundAttemptInput, CreateRefundInput, CreateRefundItemInput, RefundAttemptRecord, RefundEventRecord, RefundItemRecord, RefundListQuery, RefundRecord, RefundRepositories } from "./types";
type Db=any; const all=<T>(q:any):T[]=>Array.isArray(q)?q:(q?.all?q.all():[]); const one=<T>(q:any):T|undefined=>all<T>(q)[0]; const date=(v:any)=>v instanceof Date?v.toISOString():String(v); const json=(v:any)=>v==null?null:typeof v==="string"?JSON.parse(v):v; const enc=(v:any)=>v==null?null:typeof v==="string"?v:JSON.stringify(v);
function refund(r:any):RefundRecord{return{ id:String(r.id),orderId:r.orderId,returnRequestId:r.returnRequestId??null,channel:r.channel??null,externalRefundId:r.externalRefundId??null,type:r.type,status:r.status,currency:r.currency,subtotalAmount:Number(r.subtotalAmount),shippingAmount:Number(r.shippingAmount??0),taxAmount:Number(r.taxAmount??0),marketplaceFeeAdjustment:r.marketplaceFeeAdjustment==null?null:Number(r.marketplaceFeeAdjustment),paymentFeeAdjustment:r.paymentFeeAdjustment==null?null:Number(r.paymentFeeAdjustment),totalAmount:Number(r.totalAmount),reason:r.reason??null,idempotencyKey:r.idempotencyKey,submittedAt:r.submittedAt?date(r.submittedAt):null,succeededAt:r.succeededAt?date(r.succeededAt):null,failedAt:r.failedAt?date(r.failedAt):null,lastError:r.lastError??null,version:Number(r.version??0),createdAt:date(r.createdAt),updatedAt:date(r.updatedAt)}}
function item(r:any):RefundItemRecord{return{id:String(r.id),refundId:r.refundId,orderItemId:r.orderItemId??null,returnItemId:r.returnItemId??null,quantity:r.quantity==null?null:Number(r.quantity),amount:Number(r.amount),createdAt:date(r.createdAt)}}
function attempt(r:any):RefundAttemptRecord{return{id:String(r.id),refundId:r.refundId,attemptNumber:Number(r.attemptNumber),channel:r.channel??null,status:r.status,externalRefundId:r.externalRefundId??null,requestSnapshot:json(r.requestSnapshot)??{},responseSnapshot:json(r.responseSnapshot),errorCode:r.errorCode??null,errorMessage:r.errorMessage??null,orderId:r.orderId??null,idempotencyKey:r.idempotencyKey??null,createdAt:date(r.createdAt)}}
function event(r:any):RefundEventRecord{return{id:String(r.id),refundId:r.refundId,orderId:r.orderId??null,eventType:r.eventType,previousStatus:r.previousStatus??null,newStatus:r.newStatus??null,payloadSnapshot:json(r.payloadSnapshot),actor:r.actor??null,source:r.source??null,idempotencyKey:r.idempotencyKey??null,createdAt:date(r.createdAt)}}
export function createSqliteRefundRepositories(db:Db, selectedSchema:unknown=sqliteSchema):RefundRepositories{const {refunds,refundAllocations,refundAttempts,refundEvents}=selectedSchema as any; const count=(w:any)=>Number(one<any>(db.select({count:sql<number>`count(*)`}).from(refunds).where(w))?.count??0); const where=(q?:RefundListQuery)=>{ const parts=[q?.status?eq(refunds.status,q.status):undefined,q?.orderId?eq(refunds.orderId,q.orderId):undefined,q?.returnRequestId?eq(refunds.returnRequestId,q.returnRequestId):undefined].filter(Boolean) as any[]; return parts.length?and(...parts):undefined; };
 const readRefund=(w:any)=>one<any>(db.select().from(refunds).where(w)); const insert=(table:any,row:any,map:any)=>{const q=db.insert(table).values(row).returning?.(); if(q) return map(all<any>(q)[0]); db.insert(table).values(row).run?.(); return map(row)};
 const repo:any={create:(i:CreateRefundInput)=>insert(refunds,{...i,version:i.version??0},refund),findById:(id:string)=>{const r=readRefund(eq(refunds.id,id));return r?refund(r):null},findByIdempotencyKey:(k:string)=>{const r=readRefund(eq(refunds.idempotencyKey,k));return r?refund(r):null},findByExternalReference:(ref:string)=>{const r=readRefund(eq(refunds.externalRefundId,ref));return r?refund(r):null},findByReturnId:(id:string)=>all<any>(db.select().from(refunds).where(eq(refunds.returnRequestId,id)).orderBy(desc(refunds.createdAt),desc(refunds.id))).map(refund),findByOrderId:(id:string)=>all<any>(db.select().from(refunds).where(eq(refunds.orderId,id)).orderBy(desc(refunds.createdAt),desc(refunds.id))).map(refund),list:(q:RefundListQuery={})=>{const limit=q.limit??50,offset=q.offset??0,w=where(q);return{rows:all<any>(db.select().from(refunds).where(w).orderBy(desc(refunds.createdAt),desc(refunds.id)).limit(limit).offset(offset)).map(refund),total:count(w),limit,offset}},updateWithVersion:(id:string,expectedVersion:number,patch:any)=>{const current=repo.findById(id); if(!current) return {ok:false,issue:{code:"not_found",message:"Refund version update rejected"}}; if(current.version!==expectedVersion) return {ok:false,issue:{code:"optimistic_conflict",message:"Refund version update rejected"}}; const q=db.update(refunds).set({...patch,version:expectedVersion+1}).where(and(eq(refunds.id,id),eq(refunds.version,expectedVersion))).returning?.(); if(q) all<any>(q); else db.update(refunds).set({...patch,version:expectedVersion+1}).where(and(eq(refunds.id,id),eq(refunds.version,expectedVersion))).run?.(); const r=repo.findById(id); return r&&r.version===expectedVersion+1?{ok:true,value:r}:{ok:false,issue:{code:r?"optimistic_conflict":"not_found",message:"Refund version update rejected"}}}};
 const items:any={createMany:(xs:CreateRefundItemInput[])=>xs.map(x=>insert(refundAllocations,x,item)),listByRefundId:(id:string)=>all<any>(db.select().from(refundAllocations).where(eq(refundAllocations.refundId,id)).orderBy(asc(refundAllocations.createdAt),asc(refundAllocations.id))).map(item)};
 const attempts:any={create:(i:CreateRefundAttemptInput)=>insert(refundAttempts,{...i,requestSnapshot:enc(i.requestSnapshot),responseSnapshot:enc(i.responseSnapshot)},attempt),findById:(id:string)=>{const r=one<any>(db.select().from(refundAttempts).where(eq(refundAttempts.id,id)));return r?attempt(r):null},findLatestByRefundId:(id:string)=>{const r=one<any>(db.select().from(refundAttempts).where(eq(refundAttempts.refundId,id)).orderBy(desc(refundAttempts.attemptNumber),desc(refundAttempts.createdAt),desc(refundAttempts.id)));return r?attempt(r):null},listByRefundId:(id:string)=>all<any>(db.select().from(refundAttempts).where(eq(refundAttempts.refundId,id)).orderBy(asc(refundAttempts.attemptNumber),asc(refundAttempts.createdAt),asc(refundAttempts.id))).map(attempt),update:(id:string,patch:any)=>{const row={...patch}; if("requestSnapshot" in row) row.requestSnapshot=enc(row.requestSnapshot); if("responseSnapshot" in row) row.responseSnapshot=enc(row.responseSnapshot); const q=db.update(refundAttempts).set(row).where(eq(refundAttempts.id,id)).returning?.(); if(q) all<any>(q); else db.update(refundAttempts).set(row).where(eq(refundAttempts.id,id)).run?.(); return attempts.findById(id)}};
 const events:any={append:(i:AppendRefundEventInput)=>insert(refundEvents,{...i,payloadSnapshot:enc(i.payloadSnapshot)},event),listByRefundId:(id:string)=>all<any>(db.select().from(refundEvents).where(eq(refundEvents.refundId,id)).orderBy(asc(refundEvents.createdAt),asc(refundEvents.id))).map(event),findByIdempotencyKey:(k:string)=>{const r=one<any>(db.select().from(refundEvents).where(eq(refundEvents.idempotencyKey,k)));return r?event(r):null}};
 return{refunds:repo,refundItems:items,refundAttempts:attempts,refundEvents:events};}
