export type JsonRecord = Record<string, unknown>;
export interface RefundRecord { id:string; orderId:string; returnRequestId:string|null; channel:string|null; externalRefundId:string|null; type:string; status:string; currency:string; subtotalAmount:number; shippingAmount:number; taxAmount:number; marketplaceFeeAdjustment:number|null; paymentFeeAdjustment:number|null; totalAmount:number; reason:string|null; idempotencyKey:string; submittedAt:string|null; succeededAt:string|null; failedAt:string|null; lastError:string|null; version:number; createdAt:string; updatedAt:string }
export interface RefundItemRecord { id:string; refundId:string; orderItemId:string|null; returnItemId:string|null; quantity:number|null; amount:number; createdAt:string }
export interface RefundAttemptRecord { id:string; refundId:string; attemptNumber:number; channel:string|null; status:string; externalRefundId:string|null; requestSnapshot:JsonRecord; responseSnapshot:JsonRecord|null; errorCode:string|null; errorMessage:string|null; orderId:string|null; idempotencyKey:string|null; createdAt:string }
export interface RefundEventRecord { id:string; refundId:string; orderId:string|null; eventType:string; previousStatus:string|null; newStatus:string|null; payloadSnapshot:JsonRecord|null; actor:string|null; source:string|null; idempotencyKey:string|null; createdAt:string }
export type CreateRefundInput = Omit<RefundRecord,"version"> & { version?:number };
export type CreateRefundItemInput = RefundItemRecord;
export type CreateRefundAttemptInput = RefundAttemptRecord;
export type AppendRefundEventInput = RefundEventRecord;
export interface RefundListQuery { limit?:number; offset?:number; status?:string; orderId?:string; returnRequestId?:string }
export interface RefundPage { rows:RefundRecord[]; total:number; limit:number; offset:number }
export type RefundUpdatePatch = Partial<Omit<RefundRecord,"id"|"version"|"createdAt">>;
export type RefundUpdateResult = { ok:true; value:RefundRecord } | { ok:false; issue:{ code:"not_found"|"optimistic_conflict"; message:string } };
export interface RefundRepository { create(input:CreateRefundInput):RefundRecord|Promise<RefundRecord>; findById(id:string):RefundRecord|null|Promise<RefundRecord|null>; findByIdempotencyKey(key:string):RefundRecord|null|Promise<RefundRecord|null>; findByExternalReference(ref:string):RefundRecord|null|Promise<RefundRecord|null>; findByReturnId(returnRequestId:string):RefundRecord[]|Promise<RefundRecord[]>; findByOrderId(orderId:string):RefundRecord[]|Promise<RefundRecord[]>; list(query?:RefundListQuery):RefundPage|Promise<RefundPage>; updateWithVersion(id:string, expectedVersion:number, patch:RefundUpdatePatch):RefundUpdateResult|Promise<RefundUpdateResult> }
export interface RefundItemRepository { createMany(input:CreateRefundItemInput[]):RefundItemRecord[]|Promise<RefundItemRecord[]>; listByRefundId(refundId:string):RefundItemRecord[]|Promise<RefundItemRecord[]> }
export interface RefundAttemptRepository { create(input:CreateRefundAttemptInput):RefundAttemptRecord|Promise<RefundAttemptRecord>; findById(id:string):RefundAttemptRecord|null|Promise<RefundAttemptRecord|null>; findLatestByRefundId(refundId:string):RefundAttemptRecord|null|Promise<RefundAttemptRecord|null>; listByRefundId(refundId:string):RefundAttemptRecord[]|Promise<RefundAttemptRecord[]>; update(id:string, patch:Partial<Omit<RefundAttemptRecord,"id"|"refundId"|"createdAt">>):RefundAttemptRecord|null|Promise<RefundAttemptRecord|null> }
export interface RefundEventRepository { append(input:AppendRefundEventInput):RefundEventRecord|Promise<RefundEventRecord>; listByRefundId(refundId:string):RefundEventRecord[]|Promise<RefundEventRecord[]>; findByIdempotencyKey(key:string):RefundEventRecord|null|Promise<RefundEventRecord|null> }
export interface RefundRepositories { refunds:RefundRepository; refundItems:RefundItemRepository; refundAttempts:RefundAttemptRepository; refundEvents:RefundEventRepository }
export type RefundRepositoryDriver = "sqlite"|"postgres"|"supabase-postgres"|"test-memory";
