import { and, asc, eq, gt } from "drizzle-orm";
import type * as sqliteSchema from "../../db/schema.sqlite"; import type * as postgresSchema from "../../db/schema.postgres";
import { DuplicateSkuError, DuplicateStockLocationCodeError, InsufficientStockError, InventoryNotFoundError, ProductNotFoundError, StaleInventoryVersionError, StaleProductVersionError, StockLocationNotFoundError } from "./errors";
import type { ProductRepository } from "./productRepository"; import type { InventoryRepository } from "./inventoryRepository"; import type { StockMovementRepository } from "./stockMovementRepository"; import type { StockLocationRepository } from "./stockLocationRepository";
import type { AppendStockMovementInput, CreateProductInput, CreateStockLocationInput, ProductRecord, StockLocationRecord, StockMovementRecord, UpdateProductInput, UpdateStockLocationInput } from "./types";
type Schema = typeof sqliteSchema | typeof postgresSchema; type Db=any; type Execution="synchronous"|"asynchronous"; type Result<T>=T|Promise<T>;
const then=<T,U>(value:Result<T>,next:(value:T)=>Result<U>):Result<U>=>value instanceof Promise?value.then(next):next(value);
const rows=(q:any,execution:Execution):Result<any[]>=>execution==="synchronous"?(Array.isArray(q)?q:q.all()):Promise.resolve(q).then((value:any)=>Array.isArray(value)?value:value.all());
const first=(q:any,execution:Execution):Result<any>=>then(rows(q,execution),values=>values[0]??null);
const run=(q:any,execution:Execution):Result<unknown>=>execution==="synchronous"?q.run():Promise.resolve(q);
const norm=(o:Record<string,unknown>)=>Object.fromEntries(Object.entries(o).filter(([,v])=>v!==undefined)); const copy=<T>(v:T):T=>Object.freeze(structuredClone(v));
function product(row:any):ProductRecord{ return copy({ id:String(row.id), sku:String(row.sku), title:String(row.title), slug:String(row.slug), type:String(row.type), status:String(row.status), stockQuantity:Number(row.stockQuantity), priceEur:Number(row.priceEur), purchaseCost:row.purchaseCost==null?null:Number(row.purchaseCost), purchaseCurrency:row.purchaseCurrency==null?null:"EUR", categoryId:row.categoryId??null, collectionId:row.collectionId??null, createdAt:String(row.createdAt), updatedAt:String(row.updatedAt), marketplace:{ ebayTitle:row.ebayTitle??null, etsyTitle:row.etsyTitle??null, wooProductName:row.wooProductName??null } }); }
function inv(row:any){ return copy({ productId:String(row.id), locationId:null, quantity:Number(row.stockQuantity), updatedAt:String(row.updatedAt) }); }
function movement(r:any):StockMovementRecord{ return copy({ id:String(r.id), productId:String(r.productId), type:String(r.type), quantityDelta:Number(r.quantityDelta), stockBefore:Number(r.stockBefore), stockAfter:Number(r.stockAfter), orderId:r.orderId??null, orderItemId:r.orderItemId??null, note:r.note??null, idempotencyKey:r.idempotencyKey??null, createdAt:String(r.createdAt), updatedAt:String(r.updatedAt) }); }
function location(r:any):StockLocationRecord{ return copy({ id:String(r.id), warehouseId:String(r.warehouseId), code:String(r.code), name:String(r.name), status:String(r.status), locationType:String(r.locationType), sortOrder:Number(r.sortOrder), createdAt:String(r.createdAt), updatedAt:String(r.updatedAt) }); }
function valuesForProduct(i:CreateProductInput|UpdateProductInput){ const v:any={...i}; if(v.purchaseCurrency!==undefined&&v.purchaseCurrency!==null) v.purchaseCurrency="EUR"; return norm(v); }
export function createInventoryRepositories(db:Db,schema:Schema,execution:Execution="asynchronous"){ const {products,stockMovements,warehouseLocations}=schema as any;
 const productRepo:any={ create(input:any){ return then(this.existsBySku(input.sku),(exists:boolean)=>{ if(exists) throw new DuplicateSkuError(input.sku); return then(run(db.insert(products).values({customsWarning:false, isFeatured:false, allowMakeOffer:false, allowCashOnDelivery:false, showInArchiveAfterSale:false, ...valuesForProduct({...input, stockQuantity:input.stockQuantity??1})}),execution),()=>then(this.findById(input.id),(value:any)=>value!)); }); }, findById(id:any){ return then(first(db.select().from(products).where(eq(products.id,id)).limit(1),execution),r=>r?product(r):null); }, findBySku(sku:any){ return then(first(db.select().from(products).where(eq(products.sku,sku)).limit(1),execution),r=>r?product(r):null); }, list(){ return then(rows(db.select().from(products).orderBy(asc(products.sku),asc(products.id)),execution),values=>values.map(product)); }, update(id:any,input:any){ return then(this.findById(id),(existing:any)=>{ if(!existing) throw new ProductNotFoundError(id); return then(input.sku?this.existsBySku(input.sku,id):false,(duplicate:boolean)=>{ if(duplicate) throw new DuplicateSkuError(input.sku); return then(run(db.update(products).set(valuesForProduct(input)).where(eq(products.id,id)),execution),()=>then(this.findById(id),(value:any)=>value!)); }); }); }, updateWithVersion(id:any,input:any,expectedVersion:any){ return then(rows(db.update(products).set(valuesForProduct(input)).where(and(eq(products.id,id),eq(products.updatedAt,expectedVersion))).returning(),execution),(changed:any[])=>{ if(changed.length) return product(changed[0]); return then(this.findById(id),(existing:any)=>{ if(!existing) throw new ProductNotFoundError(id); throw new StaleProductVersionError(id); }); }); }, existsBySku(sku:any,excludeId:any){ return then(rows(db.select({id:products.id}).from(products).where(eq(products.sku,sku)),execution),values=>values.some((r:any)=>r.id!==excludeId)); } };
 const inventoryRepo:any={ create(input:any){ return then(productRepo.update(input.productId,{stockQuantity:input.quantity,updatedAt:input.updatedAt}),()=>then(this.findByProduct(input.productId),(value:any)=>value!)); }, findByProduct(productId:any){ return then(productRepo.findById(productId),r=>r?inv({id:r.id,stockQuantity:r.stockQuantity,updatedAt:r.updatedAt}):null); }, findByProductAndLocation(productId:any,locationId:any){ return locationId==null?this.findByProduct(productId):null; }, listByProduct(productId:any){ return then(this.findByProduct(productId),(r:any)=>r?[r]:[]); }, incrementQuantity(productId:any,quantity:any,updatedAt:any){ return then(this.findByProduct(productId),(cur:any)=>{ if(!cur) throw new InventoryNotFoundError(productId); return this.setQuantity(productId,cur.quantity+quantity,updatedAt); }); }, decrementQuantity(productId:any,quantity:any,updatedAt:any){ return then(this.findByProduct(productId),(cur:any)=>{ if(!cur) throw new InventoryNotFoundError(productId); if(cur.quantity<quantity) throw new InsufficientStockError(productId); return this.setQuantity(productId,cur.quantity-quantity,updatedAt); }); }, setQuantity(productId:any,quantity:any,updatedAt:any){ if(quantity<0||!Number.isInteger(quantity)) throw new InsufficientStockError(productId); return then(productRepo.update(productId,{stockQuantity:quantity,updatedAt}),()=>then(this.findByProduct(productId),(value:any)=>value!)); }, updateWithVersion(productId:any,quantity:any,expectedVersion:any,updatedAt:any){ return then(rows(db.update(products).set({stockQuantity:quantity,updatedAt}).where(and(eq(products.id,productId),eq(products.updatedAt,expectedVersion))).returning(),execution),(changed:any[])=>{ if(changed.length) return inv(changed[0]); return then(this.findByProduct(productId),(existing:any)=>{ if(!existing) throw new InventoryNotFoundError(productId); throw new StaleInventoryVersionError(productId); }); }); } };
 const movementRepo:any={ append(input:AppendStockMovementInput){ return then(run(db.insert(stockMovements).values(norm(input as any)),execution),()=>then(this.findById(input.id),(value:any)=>value!)); }, findById(id:any){ return then(first(db.select().from(stockMovements).where(eq(stockMovements.id,id)).limit(1),execution),r=>r?movement(r):null); }, listByProduct(productId:any){ return then(rows(db.select().from(stockMovements).where(eq(stockMovements.productId,productId)).orderBy(asc(stockMovements.createdAt),asc(stockMovements.id)),execution),values=>values.map(movement)); }, listByReference(ref:any){ const filters=[]; if(ref.orderId) filters.push(eq(stockMovements.orderId,ref.orderId)); if(ref.orderItemId) filters.push(eq(stockMovements.orderItemId,ref.orderItemId)); return then(rows(db.select().from(stockMovements).where(and(...filters)).orderBy(asc(stockMovements.createdAt),asc(stockMovements.id)),execution),values=>values.map(movement)); }, findByIdempotencyKey(key:any){ return then(first(db.select().from(stockMovements).where(eq(stockMovements.idempotencyKey,key)).limit(1),execution),r=>r?movement(r):null); } };
 const locationRepo:any={ create(input:CreateStockLocationInput){ return then(this.findByCode(input.warehouseId,input.code),(existing:any)=>{ if(existing) throw new DuplicateStockLocationCodeError(input.code); return then(run(db.insert(warehouseLocations).values(norm(input as any)),execution),()=>then(this.findById(input.id),(value:any)=>value!)); }); }, findById(id:any){ return then(first(db.select().from(warehouseLocations).where(eq(warehouseLocations.id,id)).limit(1),execution),r=>r?location(r):null); }, findByCode(warehouseId:any,code:any){ return then(first(db.select().from(warehouseLocations).where(and(eq(warehouseLocations.warehouseId,warehouseId),eq(warehouseLocations.code,code))).limit(1),execution),r=>r?location(r):null); }, list(warehouseId:any){ const q=db.select().from(warehouseLocations).where(warehouseId?eq(warehouseLocations.warehouseId,warehouseId):gt(warehouseLocations.id,"" as any)).orderBy(asc(warehouseLocations.sortOrder),asc(warehouseLocations.code),asc(warehouseLocations.id)); return then(rows(q,execution),values=>values.map(location)); }, updateWithVersion(id:any,input:UpdateStockLocationInput,expectedVersion:any){ return then(rows(db.update(warehouseLocations).set(norm(input as any)).where(and(eq(warehouseLocations.id,id),eq(warehouseLocations.updatedAt,expectedVersion))).returning(),execution),(changed:any[])=>{ if(changed.length) return location(changed[0]); return then(this.findById(id),(existing:any)=>{ if(!existing) throw new StockLocationNotFoundError(id); throw new StaleInventoryVersionError(id); }); }); } };
 return { products:productRepo as ProductRepository, inventory:inventoryRepo, stockMovements:movementRepo, stockLocations:locationRepo };
}
