import { and, asc, eq, gt } from "drizzle-orm";
import type * as sqliteSchema from "../../db/schema.sqlite"; import type * as postgresSchema from "../../db/schema.postgres";
import { DuplicateSkuError, DuplicateStockLocationCodeError, InsufficientStockError, InventoryNotFoundError, ProductNotFoundError, StaleInventoryVersionError, StaleProductVersionError, StockLocationNotFoundError } from "./errors";
import type { ProductRepository } from "./productRepository"; import type { InventoryRepository } from "./inventoryRepository"; import type { StockMovementRepository } from "./stockMovementRepository"; import type { StockLocationRepository } from "./stockLocationRepository";
import type { AppendStockMovementInput, CreateProductInput, CreateStockLocationInput, ProductRecord, StockLocationRecord, StockMovementRecord, UpdateProductInput, UpdateStockLocationInput } from "./types";
type Schema = typeof sqliteSchema | typeof postgresSchema; type Db=any; const rows=async(q:any)=>Array.isArray(q)?q:typeof q?.all==="function"?q.all():await q; const first=async(q:any)=>(await rows(q))[0]??null; const run=async(q:any)=>typeof q?.run==="function"?q.run():await q;
const norm=(o:Record<string,unknown>)=>Object.fromEntries(Object.entries(o).filter(([,v])=>v!==undefined)); const copy=<T>(v:T):T=>Object.freeze(structuredClone(v));
function product(row:any):ProductRecord{ return copy({ id:String(row.id), sku:String(row.sku), title:String(row.title), slug:String(row.slug), type:String(row.type), status:String(row.status), stockQuantity:Number(row.stockQuantity), priceEur:Number(row.priceEur), purchaseCost:row.purchaseCost==null?null:Number(row.purchaseCost), purchaseCurrency:row.purchaseCurrency==null?null:"EUR", categoryId:row.categoryId??null, collectionId:row.collectionId??null, createdAt:String(row.createdAt), updatedAt:String(row.updatedAt), marketplace:{ ebayTitle:row.ebayTitle??null, etsyTitle:row.etsyTitle??null, wooProductName:row.wooProductName??null } }); }
function inv(row:any){ return copy({ productId:String(row.id), locationId:null, quantity:Number(row.stockQuantity), updatedAt:String(row.updatedAt) }); }
function movement(r:any):StockMovementRecord{ return copy({ id:String(r.id), productId:String(r.productId), type:String(r.type), quantityDelta:Number(r.quantityDelta), stockBefore:Number(r.stockBefore), stockAfter:Number(r.stockAfter), orderId:r.orderId??null, orderItemId:r.orderItemId??null, note:r.note??null, idempotencyKey:r.idempotencyKey??null, createdAt:String(r.createdAt), updatedAt:String(r.updatedAt) }); }
function location(r:any):StockLocationRecord{ return copy({ id:String(r.id), warehouseId:String(r.warehouseId), code:String(r.code), name:String(r.name), status:String(r.status), locationType:String(r.locationType), sortOrder:Number(r.sortOrder), createdAt:String(r.createdAt), updatedAt:String(r.updatedAt) }); }
function valuesForProduct(i:CreateProductInput|UpdateProductInput){ const v:any={...i}; if(v.purchaseCurrency!==undefined&&v.purchaseCurrency!==null) v.purchaseCurrency="EUR"; return norm(v); }
export function createInventoryRepositories(db:Db,schema:Schema){ const {products,stockMovements,warehouseLocations}=schema as any;
 const productRepo:ProductRepository={ async create(input){ if(await this.existsBySku(input.sku)) throw new DuplicateSkuError(input.sku); await run(db.insert(products).values({...valuesForProduct({...input, stockQuantity:input.stockQuantity??1}), customsWarning:false, isFeatured:false, allowMakeOffer:false, allowCashOnDelivery:false, showInArchiveAfterSale:false})); return (await this.findById(input.id))!; }, async findById(id){ const r=await first(db.select().from(products).where(eq(products.id,id)).limit(1)); return r?product(r):null; }, async findBySku(sku){ const r=await first(db.select().from(products).where(eq(products.sku,sku)).limit(1)); return r?product(r):null; }, async list(){ return (await rows(db.select().from(products).orderBy(asc(products.sku),asc(products.id)))).map(product); }, async update(id,input){ const existing=await this.findById(id); if(!existing) throw new ProductNotFoundError(id); if(input.sku&&await this.existsBySku(input.sku,id)) throw new DuplicateSkuError(input.sku); await run(db.update(products).set(valuesForProduct(input)).where(eq(products.id,id))); return (await this.findById(id))!; }, async updateWithVersion(id,input,expectedVersion){ const changed=await rows(db.update(products).set(valuesForProduct(input)).where(and(eq(products.id,id),eq(products.updatedAt,expectedVersion))).returning()); if(!changed.length) { if(!await this.findById(id)) throw new ProductNotFoundError(id); throw new StaleProductVersionError(id); } return product(changed[0]); }, async existsBySku(sku,excludeId){ return (await rows(db.select({id:products.id}).from(products).where(eq(products.sku,sku)))).some((r:any)=>r.id!==excludeId); } };
 const inventoryRepo:InventoryRepository={ async create(input){ await productRepo.update(input.productId,{stockQuantity:input.quantity,updatedAt:input.updatedAt}); return (await this.findByProduct(input.productId))!; }, async findByProduct(productId){ const r=await productRepo.findById(productId); return r?inv({id:r.id,stockQuantity:r.stockQuantity,updatedAt:r.updatedAt}):null; }, async findByProductAndLocation(productId,locationId){ return locationId===null||locationId===undefined?this.findByProduct(productId):null; }, async listByProduct(productId){ const r=await this.findByProduct(productId); return r?[r]:[]; }, async incrementQuantity(productId,quantity,updatedAt){ const cur=await this.findByProduct(productId); if(!cur) throw new InventoryNotFoundError(productId); return this.setQuantity(productId,cur.quantity+quantity,updatedAt); }, async decrementQuantity(productId,quantity,updatedAt){ const cur=await this.findByProduct(productId); if(!cur) throw new InventoryNotFoundError(productId); if(cur.quantity<quantity) throw new InsufficientStockError(productId); return this.setQuantity(productId,cur.quantity-quantity,updatedAt); }, async setQuantity(productId,quantity,updatedAt){ if(quantity<0||!Number.isInteger(quantity)) throw new InsufficientStockError(productId); await productRepo.update(productId,{stockQuantity:quantity,updatedAt}); return (await this.findByProduct(productId))!; }, async updateWithVersion(productId,quantity,expectedVersion,updatedAt){ const changed=await rows(db.update(products).set({stockQuantity:quantity,updatedAt}).where(and(eq(products.id,productId),eq(products.updatedAt,expectedVersion))).returning()); if(!changed.length) { if(!await this.findByProduct(productId)) throw new InventoryNotFoundError(productId); throw new StaleInventoryVersionError(productId); } return inv(changed[0]); } };
 const movementRepo:StockMovementRepository={ async append(input:AppendStockMovementInput){ await run(db.insert(stockMovements).values(norm(input as any))); return (await this.findById(input.id))!; }, async findById(id){ const r=await first(db.select().from(stockMovements).where(eq(stockMovements.id,id)).limit(1)); return r?movement(r):null; }, async listByProduct(productId){ return (await rows(db.select().from(stockMovements).where(eq(stockMovements.productId,productId)).orderBy(asc(stockMovements.createdAt),asc(stockMovements.id)))).map(movement); }, async listByReference(ref){ const filters=[]; if(ref.orderId) filters.push(eq(stockMovements.orderId,ref.orderId)); if(ref.orderItemId) filters.push(eq(stockMovements.orderItemId,ref.orderItemId)); return (await rows(db.select().from(stockMovements).where(and(...filters)).orderBy(asc(stockMovements.createdAt),asc(stockMovements.id)))).map(movement); }, async findByIdempotencyKey(key){ const r=await first(db.select().from(stockMovements).where(eq(stockMovements.idempotencyKey,key)).limit(1)); return r?movement(r):null; } };
 const locationRepo:StockLocationRepository={ async create(input:CreateStockLocationInput){ if(await this.findByCode(input.warehouseId,input.code)) throw new DuplicateStockLocationCodeError(input.code); await run(db.insert(warehouseLocations).values(norm(input as any))); return (await this.findById(input.id))!; }, async findById(id){ const r=await first(db.select().from(warehouseLocations).where(eq(warehouseLocations.id,id)).limit(1)); return r?location(r):null; }, async findByCode(warehouseId,code){ const r=await first(db.select().from(warehouseLocations).where(and(eq(warehouseLocations.warehouseId,warehouseId),eq(warehouseLocations.code,code))).limit(1)); return r?location(r):null; }, async list(warehouseId){ const q=db.select().from(warehouseLocations).where(warehouseId?eq(warehouseLocations.warehouseId,warehouseId):gt(warehouseLocations.id,"" as any)).orderBy(asc(warehouseLocations.sortOrder),asc(warehouseLocations.code),asc(warehouseLocations.id)); return (await rows(q)).map(location); }, async updateWithVersion(id,input:UpdateStockLocationInput,expectedVersion){ const changed=await rows(db.update(warehouseLocations).set(norm(input as any)).where(and(eq(warehouseLocations.id,id),eq(warehouseLocations.updatedAt,expectedVersion))).returning()); if(!changed.length) { if(!await this.findById(id)) throw new StockLocationNotFoundError(id); throw new StaleInventoryVersionError(id); } return location(changed[0]); } };
 return { products:productRepo, inventory:inventoryRepo, stockMovements:movementRepo, stockLocations:locationRepo };
}
