export type CurrencyCode = "EUR";
export type ProductId = string; export type StockLocationId = string; export type StockMovementId = string; export type SKU = string; export type Version = string; export type ISODateTime = string;
export type ProductStatus = "draft"|"published"|"sold"|"archived"|string;
export interface ProductRecord { readonly id:ProductId; readonly sku:SKU; readonly title:string; readonly slug:string; readonly type:string; readonly status:ProductStatus; readonly stockQuantity:number; readonly priceEur:number; readonly purchaseCost:number|null; readonly purchaseCurrency:CurrencyCode|null; readonly categoryId:string|null; readonly collectionId:string|null; readonly createdAt:ISODateTime; readonly updatedAt:Version; readonly marketplace: Readonly<{ ebayTitle?:string|null; etsyTitle?:string|null; wooProductName?:string|null }>; }
export interface CreateProductInput { readonly id:ProductId; readonly sku:SKU; readonly title:string; readonly slug:string; readonly type:string; readonly status:ProductStatus; readonly priceEur:number; readonly stockQuantity?:number; readonly categoryId?:string|null; readonly collectionId?:string|null; readonly purchaseCost?:number|null; readonly purchaseCurrency?:CurrencyCode|null; readonly createdAt:ISODateTime; readonly updatedAt:ISODateTime; }
export type UpdateProductInput = Partial<Omit<CreateProductInput,"id"|"createdAt">> & { readonly updatedAt:ISODateTime };
export interface InventoryState { readonly productId:ProductId; readonly locationId:StockLocationId|null; readonly quantity:number; readonly updatedAt:Version; }
export interface StockMovementRecord { readonly id:StockMovementId; readonly productId:ProductId; readonly type:string; readonly quantityDelta:number; readonly stockBefore:number; readonly stockAfter:number; readonly orderId:string|null; readonly orderItemId:string|null; readonly note:string|null; readonly idempotencyKey:string|null; readonly createdAt:ISODateTime; readonly updatedAt:ISODateTime; }
export interface AppendStockMovementInput extends StockMovementRecord {}
export interface StockLocationRecord { readonly id:StockLocationId; readonly warehouseId:string; readonly code:string; readonly name:string; readonly status:string; readonly locationType:string; readonly sortOrder:number; readonly createdAt:ISODateTime; readonly updatedAt:Version; }
export interface CreateStockLocationInput extends StockLocationRecord { readonly parentLocationId?:string|null; readonly erpReferenceId?:string|null; }
export type UpdateStockLocationInput = Partial<Pick<CreateStockLocationInput,"code"|"name"|"status"|"locationType"|"sortOrder">> & { readonly updatedAt:ISODateTime };
