import { randomUUID } from "node:crypto";
import { OrderStatus, PaymentStatus } from "@noctella/shared";
import type { UnitOfWork } from "../../services/unitOfWork";
import { BadRequestError, ConflictError, NotFoundError } from "../../services/errors";
import { finalizeInternalOrderInTransaction, resolveNoctellaWebOrder, TerminalCheckoutPriceChangedError, TerminalStockUnavailableError, type PaidOrderOutboxPort } from "../order/useCases";
import type { StripeCheckoutPort, VerifiedStripeCheckoutEvent } from "../../payments/stripe";
import { stripeCheckoutIntentSchema } from "../../validation/payment";
import { z } from "zod";
import type { TransactionPaymentEventRepository, TransactionPaymentRepository } from "../../repositories/payment/types";

const providerRequestSchema=z.object({customerEmail:z.string().email(),successUrl:z.string().url(),cancelUrl:z.string().url(),lines:z.array(z.object({title:z.string().min(1),unitAmount:z.number().int().positive(),quantity:z.literal(1)}).strict()).min(1)}).strict();
const checkoutSnapshotSchema=stripeCheckoutIntentSchema.extend({providerRequest:providerRequestSchema}).strict();
export type CheckoutSnapshotV1=z.infer<typeof checkoutSnapshotSchema>;
export type StripeCheckoutIntentV1=z.infer<typeof stripeCheckoutIntentSchema>;
export function parseCheckoutSnapshot(raw:string):CheckoutSnapshotV1 { try { return checkoutSnapshotSchema.parse(JSON.parse(raw)); } catch { throw new BadRequestError("Invalid checkout snapshot"); } }
function canonical(value:unknown):string { if(Array.isArray(value))return`[${value.map(canonical).join(",")}]`;if(value&&typeof value==="object")return`{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a<b?-1:a>b?1:0).map(([key,item])=>`${JSON.stringify(key)}:${canonical(item)}`).join(",")}}`;return JSON.stringify(value); }
function intentFromSnapshot(snapshot:CheckoutSnapshotV1):StripeCheckoutIntentV1 { const {providerRequest:_,...intent}=snapshot;return stripeCheckoutIntentSchema.parse(intent); }

export interface PaymentOperationsDetail { paymentId:string; provider:string; status:string; amount:number; currency:string; expectedAmountCents:number|null; providerReference:string|null; providerTransactionReference:string|null; orderId:string|null; createdAt:string; updatedAt:string; events:Array<{id:string;providerEventId:string;eventType:string;status:string;resultClassification:string|null;errorCode:string|null;createdAt:string;updatedAt:string}> }
export function getPaymentOperationsDetailUseCase(repositories:{payments:TransactionPaymentRepository;paymentEvents:TransactionPaymentEventRepository}) { return { async execute(paymentId:string):Promise<PaymentOperationsDetail> { const payment=await repositories.payments.findById(paymentId);if(!payment)throw new NotFoundError("Payment not found");const events=await repositories.paymentEvents.listByPaymentId(paymentId);return{paymentId:payment.id,provider:payment.provider,status:payment.status,amount:payment.amount,currency:payment.currency,expectedAmountCents:payment.expectedAmountCents,providerReference:payment.providerReference,providerTransactionReference:payment.providerTransactionReference,orderId:payment.orderId,createdAt:payment.createdAt,updatedAt:payment.updatedAt,events:events.map(item=>({id:item.id,providerEventId:item.providerEventId,eventType:item.eventType,status:item.status,resultClassification:item.resultClassification,errorCode:item.errorCode,createdAt:item.createdAt,updatedAt:item.updatedAt}))}; } }; }

export function initializeStripeCheckoutUseCase(uow:UnitOfWork,stripe:StripeCheckoutPort,urls:{success:string;cancel:string}) { return { async execute(input:StripeCheckoutIntentV1) { const intent=stripeCheckoutIntentSchema.parse(input);const now=new Date().toISOString(); const key=`payment:stripe:${intent.orderDraftId}`; const prepared=await uow.run(({repositories})=>{ const existing=repositories.payments.findByIdempotencyKey(key) as any; if(existing){if(!existing.checkoutSnapshot)throw new ConflictError("Payment initialization intent changed");const stored=parseCheckoutSnapshot(existing.checkoutSnapshot);if(canonical(intentFromSnapshot(stored))!==canonical(intent))throw new ConflictError("Payment initialization intent changed");return{payment:existing,providerRequest:stored.providerRequest};}const products=repositories.order.orderItems.write.validateProductReferences(intent.items.map(item=>item.productId)) as unknown as any[]; const resolved=resolveNoctellaWebOrder(intent.items,products);const id=randomUUID();const successUrl=`${urls.success}${urls.success.includes("?")?"&":"?"}paymentId=${encodeURIComponent(id)}`,cancelUrl=`${urls.cancel}${urls.cancel.includes("?")?"&":"?"}paymentId=${encodeURIComponent(id)}`;const providerRequest={customerEmail:intent.guestEmail,successUrl,cancelUrl,lines:resolved.lines.map(line=>({title:line.title,unitAmount:Math.round((line.unitPrice+Number.EPSILON)*100),quantity:1 as const}))};const stored=checkoutSnapshotSchema.parse({...intent,providerRequest});const json=canonical(stored); const payment={id,orderId:null,provider:"stripe",providerReference:null,providerTransactionReference:null,status:"pending",amount:resolved.subtotal,expectedAmountCents:resolved.subtotalCents,currency:"EUR",idempotencyKey:key,checkoutSnapshot:json,createdAt:now,updatedAt:now}; repositories.payments.createPendingCheckout(payment); return {payment,providerRequest}; }); const session=await stripe.createCheckoutSession({paymentId:prepared.payment.id,idempotencyKey:`stripe-checkout:${prepared.payment.id}`,successUrl:prepared.providerRequest.successUrl,cancelUrl:prepared.providerRequest.cancelUrl,customerEmail:prepared.providerRequest.customerEmail,lines:prepared.providerRequest.lines}); await uow.run(({repositories})=>{ const current=repositories.payments.findById(prepared.payment.id) as any; if(!current) throw new NotFoundError("Payment session not found"); repositories.payments.setProviderReference(current.id,session.sessionId); }); return {paymentId:prepared.payment.id,checkoutUrl:session.checkoutUrl}; } }; }

export function completeStripeWebhookUseCase(uow:UnitOfWork,outbox:PaidOrderOutboxPort,event:VerifiedStripeCheckoutEvent) { return uow.run(({repositories})=>{ if(event.eventType!=="checkout.session.completed") return {kind:"irrelevant" as const,affectedProductIds:[]}; const duplicate=repositories.paymentEvents.find("stripe",event.eventId) as any; if(duplicate) return {kind:"duplicate" as const,affectedProductIds:[]}; const now=new Date().toISOString(); const reject=(paymentId:string|null,classification:string,code:string)=>{repositories.paymentEvents.claim({id:randomUUID(),provider:"stripe",providerEventId:event.eventId,eventType:event.eventType,paymentId,status:"processing",resultClassification:null,errorCode:null,createdAt:now,updatedAt:now});repositories.paymentEvents.complete("stripe",event.eventId,paymentId,"completed",classification,code,now);return{kind:"rejected" as const,affectedProductIds:[]};}; if(!event.metadataPaymentId||event.metadataPaymentId!==event.clientReferenceId) return reject(null,"payment_identity_mismatch","PAYMENT_IDENTITY_MISMATCH"); const payment=repositories.payments.findById(event.metadataPaymentId) as any; if(!payment) return reject(null,"unknown_payment","UNKNOWN_PAYMENT"); repositories.paymentEvents.claim({id:randomUUID(),provider:"stripe",providerEventId:event.eventId,eventType:event.eventType,paymentId:payment.id,status:"processing",resultClassification:null,errorCode:null,createdAt:now,updatedAt:now}); if(payment.provider!=="stripe"){repositories.paymentEvents.complete("stripe",event.eventId,payment.id,"completed","provider_mismatch","PROVIDER_MISMATCH",now);return{kind:"rejected" as const,affectedProductIds:[]};} if(payment.providerReference&&payment.providerReference!==event.sessionId){repositories.paymentEvents.complete("stripe",event.eventId,payment.id,"completed","session_identity_mismatch","SESSION_IDENTITY_MISMATCH",now);return{kind:"rejected" as const,affectedProductIds:[]};} if(!payment.providerReference) repositories.payments.setProviderReference(payment.id,event.sessionId); if(payment.status==="manual_refund_required"){ repositories.paymentEvents.complete("stripe",event.eventId,payment.id,"manual_refund_required","already_manual_refund_required",null,now); return {kind:"manual_refund_required" as const,affectedProductIds:[]}; } if(event.paymentStatus!=="paid"){ repositories.paymentEvents.complete("stripe",event.eventId,payment.id,"completed","not_paid",null,now); return {kind:"not_paid" as const,affectedProductIds:[]}; }
    const manual=(classification:string,code:string)=>{ repositories.payments.markManualRefundRequired(payment.id,event.paymentIntentId,now); repositories.paymentEvents.complete("stripe",event.eventId,payment.id,"manual_refund_required",classification,code,now); return {kind:"manual_refund_required" as const,affectedProductIds:[]}; };
    if(event.currency!=="eur") return manual("currency_mismatch","CURRENCY_MISMATCH");
    if(!Number.isSafeInteger(event.amountTotal)||event.amountTotal!==payment.expectedAmountCents) return manual("amount_mismatch","AMOUNT_MISMATCH");
    if(!event.paymentIntentId) return manual("payment_intent_missing","PAYMENT_INTENT_MISSING");
    if(payment.providerTransactionReference&&payment.providerTransactionReference!==event.paymentIntentId) throw new ConflictError("Stripe PaymentIntent identity mismatch");
    let snapshot:CheckoutSnapshotV1; try { if(!payment.checkoutSnapshot) throw new BadRequestError("Invalid checkout snapshot"); snapshot=parseCheckoutSnapshot(payment.checkoutSnapshot); } catch(error) { if(error instanceof BadRequestError) return manual("snapshot_invalid","SNAPSHOT_INVALID"); throw error; }
    const orderId=randomUUID(); try { const result=finalizeInternalOrderInTransaction({orderDraftId:snapshot.orderDraftId,idempotencyKey:snapshot.orderDraftId,channel:"Internal",guestEmail:snapshot.guestEmail,status:OrderStatus.Processing,paymentStatus:PaymentStatus.Paid,paymentProvider:"stripe",paymentReference:event.sessionId,currency:"EUR",billingAddress:snapshot.billingAddress,shippingAddress:snapshot.shippingAddress,subtotalAmount:payment.expectedAmountCents/100,totalAmount:payment.expectedAmountCents/100,notes:snapshot.notes,items:snapshot.items},{repositories,clock:{now:()=>new Date(now)},idGenerator:{id:()=>randomUUID()},inventoryDriver:"sqlite",outbox,pricingContext:"noctella_web",paidSession:{amount:payment.expectedAmountCents/100,currency:"EUR"},orderId,idempotencyKey:snapshot.orderDraftId}); if(result instanceof Promise) throw new Error("SQLITE_ASYNC_TRANSACTION_CALLBACK_REJECTED"); repositories.payments.markPaidAndLinkOrder(payment.id,result.order.id,event.paymentIntentId,now); repositories.paymentEvents.complete("stripe",event.eventId,payment.id,"completed","fulfilled",null,now); return {kind:"fulfilled" as const,order:result.order,affectedProductIds:result.affectedProductIds}; } catch(error) { if(error instanceof TerminalStockUnavailableError) return manual("insufficient_stock","INSUFFICIENT_STOCK"); if(error instanceof TerminalCheckoutPriceChangedError) return manual("checkout_price_changed","CHECKOUT_PRICE_CHANGED"); if(error instanceof BadRequestError||error instanceof NotFoundError) return manual("fulfillment_unavailable","FULFILLMENT_UNAVAILABLE"); throw error; }
  }); }
