import { describe,expect,it,vi } from "vitest";
import { paymentStatusMessage,readPaymentStatusOnce,redirectToHostedCheckout,startPaymentStatusPolling } from "../src/lib/stripeCheckoutFlow";

describe("Sprint 127 hosted Stripe Storefront flow",()=>{
  it("redirects only to the API-provided hosted Checkout URL",()=>{const target={assign:vi.fn()};redirectToHostedCheckout("https://checkout.stripe.test/session",target as any);expect(target.assign).toHaveBeenCalledWith("https://checkout.stripe.test/session");});
  it("polls read-only status while pending without order or verify mutation",async()=>{const getStatus=vi.fn().mockResolvedValueOnce({status:"pending"}).mockResolvedValueOnce({status:"paid",order:{id:"order-1",orderNumber:"NOC-1"}}),states:any[]=[],scheduled:Array<()=>void>=[];startPaymentStatusPolling("payment-1",getStatus,state=>states.push(state),callback=>scheduled.push(callback));await vi.waitFor(()=>expect(states).toHaveLength(1));expect(scheduled).toHaveLength(1);scheduled[0]();await vi.waitFor(()=>expect(states).toHaveLength(2));expect(getStatus).toHaveBeenCalledTimes(2);expect(getStatus).toHaveBeenCalledWith("payment-1");});
  it("cancels pending polling on cleanup before another request starts",async()=>{vi.useFakeTimers();const getStatus=vi.fn().mockResolvedValue({status:"pending"}),states:any[]=[];const cleanup=startPaymentStatusPolling("payment-1",getStatus,state=>states.push(state));await vi.advanceTimersByTimeAsync(0);expect(getStatus).toHaveBeenCalledOnce();cleanup();await vi.advanceTimersByTimeAsync(1500);expect(getStatus).toHaveBeenCalledOnce();vi.useRealTimers();});
  it("renders safe paid and manual-review messages without provider identifiers",()=>{const paid=paymentStatusMessage({status:"paid",order:{id:"order-1",orderNumber:"NOC-1"}}),manual=paymentStatusMessage({status:"manual_refund_required"});expect(paid.message).toContain("NOC-1");expect(manual.message).toContain("contact support");expect(`${paid.message}${manual.message}`).not.toMatch(/cs_|pi_|PaymentIntent|internal/i);});
  it("keeps cancel status lookup read only and performs one GET abstraction call",async()=>{const getStatus=vi.fn().mockResolvedValue({status:"pending"});expect(await readPaymentStatusOnce("payment-1",getStatus)).toEqual({status:"pending"});expect(getStatus).toHaveBeenCalledOnce();});
});
