import { readFileSync, mkdtempSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os"; import path from "node:path";
const root=path.resolve(__dirname,"..");
type R={status:"PASS"|"FAIL"; issues:string[]};
const forbiddenContract=[/DbClient/,/schema\.|db\/schema|\.\.\/db\/schema/,/drizzle-orm/,/\bsql`|\bSQL\b/,/transaction\s*\(/,/commit\s*\(/,/rollback\s*\(/,/services?\//,/routes?\//,/controllers?\//,/provider|SDK|fetch\s*\(|axios|process\.env|OPENAI|Anthropic/i,/\b(raw|query|execute|runSql)\s*\(/,/ebayTitle:\s*string;/,/etsyTitle:\s*string;/,/wooProductName:\s*string;/,/updateMovement|deleteMovement|update\s*\([^)]*StockMovement|delete\s*\([^)]*StockMovement/];
const forbiddenImpl=[/\.transaction\s*\(/,/commit\s*\(/,/rollback\s*\(/,/services?\//,/queue|enqueue|event publication|publish\(/,/provider|SDK|fetch\s*\(|axios|OPENAI|Anthropic/i,/throw\s+new\s+Error\([^)]*SQL|connection|constraint/i];
export function auditInventoryRepositorySource(src:string,kind:"contract"|"implementation"="contract"):R{ const list=kind==="contract"?forbiddenContract:forbiddenImpl; const issues=list.filter(r=>r.test(src)).map(r=>`forbidden:${r}`); return {status:issues.length?"FAIL":"PASS",issues}; }
export function runInventoryRepositoryAudit(base=root):R{ const files=["repositories/inventory/types.ts","repositories/inventory/productRepository.ts","repositories/inventory/inventoryRepository.ts","repositories/inventory/stockMovementRepository.ts","repositories/inventory/stockLocationRepository.ts","repositories/inventory/errors.ts"]; const impl=["repositories/inventory/drizzleCore.ts","repositories/inventory/sqlite/index.ts","repositories/inventory/postgres/index.ts","repositories/inventory/factory.ts"]; const issues:string[]=[]; for(const f of files){ const r=auditInventoryRepositorySource(readFileSync(path.join(base,f),"utf8"),"contract"); issues.push(...r.issues.map(i=>`${f}:${i}`)); } for(const f of impl){ const r=auditInventoryRepositorySource(readFileSync(path.join(base,f),"utf8"),"implementation"); issues.push(...r.issues.map(i=>`${f}:${i}`)); } return {status:issues.length?"FAIL":"PASS",issues}; }
export function inventoryRepositoryAuditFixtures(){ const dir=mkdtempSync(path.join(tmpdir(),"inv-repo-audit-")); const fixtures={ dbClient:"type X = DbClient", schema:"import { products } from '../db/schema'", sql:"const x = sql`select 1`", tx:"db.transaction(()=>{})", service:"import '../services/products'", provider:"fetch('x')", generic:"interface R { raw(): void }", marketplace:"interface X { ebayTitle: string; }", movementMutation:"interface R { updateMovement(): void; deleteMovement(): void }" }; for(const [k,v] of Object.entries(fixtures)) writeFileSync(path.join(dir,`${k}.ts`),v); return {dir,cleanup:()=>rmSync(dir,{recursive:true,force:true}),fixtures}; }
if (require.main === module) { const r=runInventoryRepositoryAudit(); if(r.status!=="PASS"){ console.error(r.issues.join("\n")); process.exit(1); } console.log("Inventory repository audit PASS"); }
