import { readFileSync, existsSync } from "node:fs"; import path from "node:path";
const root=path.resolve(__dirname,"..");
const contractFiles=["repositories/sales/types.ts","repositories/sales/errors.ts","repositories/sales/factory.ts"];
const productionFiles=[...contractFiles,"repositories/sales/sqlite/index.ts","repositories/sales/postgres/index.ts",];
const forbiddenContracts:[string,RegExp][]=[["SQL",/sql`|select\s+\*|insert\s+into|update\s+\w+\s+set|delete\s+from/i],["schema",/db\/schema|schema\./i],["Drizzle",/drizzle-orm/i],["DbClient",/DbClient/i],["HTTP",/Request|Response|Express/i],["provider SDK",/from ["'][^"']*(stripe|paypal|ebay|etsy|woocommerce|sdk)|require\(["'][^"']*(stripe|paypal|ebay|etsy|woocommerce|sdk)/i],["Inventory repository",/repositories\/inventory|InventoryRepository/i],["Refund service",/refundService/i],["transaction",/transaction\(|begin|commit|rollback/i],["Date.now",/Date\.now/],["randomUUID",/randomUUID/],["EventEmitter",/EventEmitter/],["queue",/queue|worker|webhook|Kafka|RabbitMQ|SNS/i],["BaseRepository",/BaseRepository/],["generic patch",/Record<string|Record<\s*string|patch:\s*Record/i],["profit calculation",/profit\s*=|calculateProfit/i],["stock update",/stockQuantity|quantityDelta/i],["stock movement creation",/insert\(stockMovements\)|stockMovements\)/]];
const forbiddenImpl=[[/\.transaction\(|\bbegin\b|\bcommit\b|\brollback\b/i,"transaction ownership"],[/Date\.now|randomUUID|EventEmitter|Kafka|RabbitMQ|SNS|queue|worker|webhook/i,"side effect"],[/calculateProfit|profit\s*=|stockQuantity\s*=|insert\(stockMovements\)/i,"business mutation"]];
export function auditSalesRepositorySource(files:Record<string,string>){const issues:string[]=[]; for(const [f,src] of Object.entries(files)){const isContract=/repositories\/sales\/(types|errors|factory)\.ts$/.test(f); const rules=isContract?forbiddenContracts:forbiddenImpl.map(([r,n])=>[n,r] as [string,RegExp]); for(const [name,re] of rules) if(re.test(src)) issues.push(`${f}: ${name}`);} return{status:issues.length?"FAIL":"PASS",issues} as const}
export function salesRepositoryAuditFixtures(){return{clean:"export interface SaleRepository{findById(id:string):Sale|null}",sql:"sql`select * from sales`",schema:'import { orders } from "../db/schema"',drizzle:'import { eq } from "drizzle-orm"',db:'type X=DbClient',http:'import { Request } from "express"',sdk:'import ebay from "ebay-sdk"',inventory:'import { InventoryRepository } from "../inventory"',transaction:'db.transaction(()=>{}) commit rollback',dateNow:'Date.now()',uuid:'randomUUID()',event:'new EventEmitter()',queue:'queue.add(worker)',webhook:'webhook()',generic:'class BaseRepository{}',patch:'patch: Record<string, unknown>',profit:'const profit = gross - cost',stock:'stockQuantity = 0',movement:'insert(stockMovements)'}}
export function runSalesRepositoryAudit(){const files=Object.fromEntries(productionFiles.filter(f=>existsSync(path.join(root,f))).map(f=>[f,readFileSync(path.join(root,f),"utf8")])); return auditSalesRepositorySource(files)}
if(require.main===module){const r=runSalesRepositoryAudit(); if(r.status!=="PASS"){console.error(r.issues.join("\n")); process.exit(1)} console.log("Sales repository audit PASS")}
