import { and, desc, eq, sql } from "drizzle-orm";
import { ProductStatus, type StockMovement, StockMovementType } from "@noctella/shared";
import * as sqliteSchema from "../../db/schema.sqlite";
import * as postgresSchema from "../../db/schema.postgres";
import type { StockMovementCreateInput, StockMovementRepositoryBundle, StockMovementListQuery } from "./types";
function normDate(v:unknown){ return v instanceof Date ? v.toISOString() : v; }
function toMovement(row: Record<string, unknown>): StockMovement { return { id: String(row.id), productId: String(row.productId), type: row.type as StockMovementType, quantityDelta: Number(row.quantityDelta), stockBefore: Number(row.stockBefore), stockAfter: Number(row.stockAfter), orderId: row.orderId ? String(row.orderId) : undefined, orderItemId: row.orderItemId ? String(row.orderItemId) : undefined, note: row.note ? String(row.note) : undefined, createdByAdminUserId: row.createdByAdminUserId ? String(row.createdByAdminUserId) : undefined, idempotencyKey: row.idempotencyKey ? String(row.idempotencyKey) : undefined, createdAt: String(normDate(row.createdAt)), updatedAt: String(normDate(row.updatedAt)) }; }
function rowsOf<T>(query: { all?: () => T[] } | T[]): T[] { return Array.isArray(query) ? query : query.all ? query.all() : []; }
function runReturning<T>(query: { all?: () => T[]; run?: () => void } | T[]): T[] { if (Array.isArray(query)) return query; if (query.all) return query.all(); query.run?.(); return []; }
function last<T>(a:T[]){ return a[a.length - 1]; }
export function createDrizzleStockMovementRepositories(db:unknown, schema: typeof sqliteSchema | typeof postgresSchema, dialect: "sqlite" | "postgres"): StockMovementRepositoryBundle {
  const client = db as { select: (...args: unknown[]) => unknown; insert: (...args: unknown[]) => unknown; update: (...args: unknown[]) => { set: (v: unknown) => { where: (w: unknown) => { run?: () => void; all?: () => unknown[] } } } };
  const { products, stockMovements } = schema;
  const read = {
    productExists(productId:string){ const rows=rowsOf<Record<string, unknown>>(((client.select as (s:unknown)=>{from:(t:unknown)=>{where:(w:unknown)=>{limit:(n:number)=>unknown}}})({id:products.id}).from(products).where(eq(products.id, productId)).limit(1)) as { all?: () => Record<string, unknown>[] }); return rows.length>0; },
    getProductBaseStock(productId:string){ const rows=rowsOf<Record<string, unknown>>(((client.select as (s:unknown)=>{from:(t:unknown)=>{where:(w:unknown)=>{limit:(n:number)=>unknown}}})({stockQuantity:products.stockQuantity}).from(products).where(eq(products.id, productId)).limit(1)) as { all?: () => Record<string, unknown>[] }); return rows[0]?.stockQuantity as number | undefined; },
    getBalance(productId:string){ const base=this.getProductBaseStock(productId); if (base === undefined) return undefined; const rows=rowsOf<Record<string, unknown>>(((client.select as ()=>{from:(t:unknown)=>{where:(w:unknown)=>{orderBy:(o:unknown)=>unknown}}})().from(stockMovements).where(eq(stockMovements.productId, productId)).orderBy(stockMovements.createdAt)) as { all?: () => Record<string, unknown>[] }); void rows; return { productId, quantity: base }; },
    getHistory(query:StockMovementListQuery){ const filters=[]; if(query.productId) filters.push(eq(stockMovements.productId, query.productId)); if(query.type) filters.push(eq(stockMovements.type, query.type)); const where=filters.length ? and(...filters) : undefined; const countRows=rowsOf<Record<string, unknown>>(((client.select as (s:unknown)=>{from:(t:unknown)=>{where:(w:unknown)=>unknown}})({ count: sql<number>`count(*)` }).from(stockMovements).where(where)) as { all?: () => Record<string, unknown>[] }); const rows=rowsOf<Record<string, unknown>>(((client.select as ()=>{from:(t:unknown)=>{where:(w:unknown)=>{orderBy:(o:unknown)=>{limit:(n:number)=>{offset:(n:number)=>unknown}}}}})().from(stockMovements).where(where).orderBy(desc(stockMovements.createdAt)).limit(query.pageSize).offset((query.page-1)*query.pageSize)) as { all?: () => Record<string, unknown>[] }); return { items: rows.map(toMovement), total: Number(countRows[0]?.count ?? 0), page: query.page, pageSize: query.pageSize }; },
    findByIdempotencyKey(key:string){ const rows=rowsOf<Record<string, unknown>>(((client.select as ()=>{from:(t:unknown)=>{where:(w:unknown)=>{limit:(n:number)=>unknown}}})().from(stockMovements).where(eq(stockMovements.idempotencyKey, key)).limit(1)) as { all?: () => Record<string, unknown>[] }); return rows[0] ? toMovement(rows[0]) : undefined; },
  };
  const write = { create(input:StockMovementCreateInput){ const now=input.updatedAt; const row={...input, orderId: input.orderId ?? null, orderItemId: input.orderItemId ?? null, note: input.note ?? null, createdByAdminUserId: input.createdByAdminUserId ?? null, idempotencyKey: input.idempotencyKey ?? null}; const rows=runReturning<Record<string, unknown>>(((client.insert as (t:unknown)=>{values:(v:unknown)=>{returning:()=>unknown; run?:()=>void}})(stockMovements).values(row).returning()) as { all?: () => Record<string, unknown>[]; run?: () => void }); const statusPatch=input.updateProductStatusOnZeroSale && input.type === StockMovementType.Sale && input.stockAfter === 0 ? { status: ProductStatus.Sold } : {}; const productUpdate=client.update(products).set({ stockQuantity: input.stockAfter, updatedAt: now, ...statusPatch }).where(eq(products.id, input.productId)); if (productUpdate.run) productUpdate.run(); return toMovement(rows[0] ?? row); } };
  void dialect;
  return { stockMovements: { read, write } } as unknown as StockMovementRepositoryBundle;
}
